aws/aws-sam-cli

version.go
```
$ go build -o sam -ldflags "-X main.version=0.1.0"
$ ./sam --version
sam version 0.1.0
```
=> Fixing debug log print when checking package version. Fixes #11

start.go
This uses the json encoding package json.Number type to transparently
work with both a number and/or a string. If it's a number, the json
encoding will convert it to a string.
See:
http://igorsobreira.com/2015/04/11/decoding-json-numbers-into-strings-in-go.html
Fixes #38.
=> If the 'body' returned by a Lambda function is a number, don't choke.

README.md
=> Fix typo in HOWTO under the Getting Started section

validate_test.go, vendor/github.com/awslabs/goformation/unmarshal.go, vendor/vendor.json
Test suite:
```
aws-sam-local$ go test
Running Suite: AwsSamLocal Suite
================================
Random Seed: 1502647868
Will run 30 of 30 specs
••••••••••••••••••••••••••••••
Ran 30 of 30 Specs in 0.000 seconds
SUCCESS! -- 30 Passed | 0 Failed | 0 Pending | 0 Skipped PASS
ok      github.com/awslabs/aws-sam-local        3.051s
```
Execution of `start-api`:
```
2017/08/13 20:13:16 Connected to Docker 1.30
2017/08/13 20:13:16 Successfully parsed ../goformation/test-resources/api-backend.yaml (version 2010-09-09)
2017/08/13 20:13:16 Fetching lambci/lambda:nodejs image for nodejs runtime...
nodejs: Pulling from lambci/lambda
Digest: sha256:a868b2344ef5c6037fc2834e1d0abc014f494ec446b0cd224d13ec6836f30d52
Status: Image is up to date for lambci/lambda:nodejs
2017/08/13 20:13:18 Fetching …
```
=> New goformation version removing unnecessary tag reading. Fixes #30

README.md, invoke.go, main.go, runtime.go, start.go
When using the Remote Docker, there is a problem that the function code can not be found.
Modified to allow the host path to the volume to be specified, assuming that the specific path of the development machine is mounted on the Docker Host. (Ex: Docker Toolbox)
```
sam local invoke "TestFunc" -v /c/Users/shlee/projects/test-project
```
=> Support for changing Docker Volume Basedir

event.go
Headers' in API event source should be 'headers'. 
Fixes #64.
=> API event source 'Headers' should be 'headers'

invoke.go, main.go, runtime.go, start.go
Add a flag to instruct SAM to avoid downloading images unless needed (i.e runtime image doesn't exist locally) -- dramatically improves runtime
=> Provide a flag to skip pulling images (Issue #67)

main.go
-p is already used for --port with `sam local start-api`.
Fixes #99.
=> Fixed redeclared CLI flag

README.md, invoke.go, main.go, runtime.go, start.go
In our set-up, we locally start our docker containers in a network.
To allow the lambda functions started up by sam-local to access these docker containers, we needed to put the created lambda docker containers in the same network.
We've made a small change to sam-local so that you can (optionally) set an environment variable and enter the name or id of the docker network you want to add the containers to.
We thought this might be useful to be added to the real sam-local, hence this pull request.
=> Add docker containers to existing docker network

env.go, env_test.go, invoke.go, main.go, router/api.go, router/function.go, router/function_test.go, router/mount.go, router/mount_test.go, router/router.go, router/router_suite_test.go, router/router_test.go, runtime.go, runtime_test.go, samples/java/template.yml, start.go, test/environment-overrides.json
This change takes a lot of the logic out of start.go for HTTP handling, and moves it to a new, separate 'router' package.
It also moves all of the environment handling out into a separate file (env.go and env_test.go), to make that a lot cleaner and remove duplication. These changes makes for a much smaller start.go, with far less logic.
The new HTTP router implementation looks like this:
```go
// initiate a new router
r := router.NewServerlessRouter()
// Add a AWS::Serverless::Function to it
r.AddFunction(someServerlessFunction)
// Add a AWS::Serverless::Api to it
r.AddAPI(someServerlessApi)
// Add a static files dir
r.AddStaticDir("public/", "/")
// Pass it to Go's HTTP pkg for serving
http.ListenAndServe("0.0.0.0:3000", r.Router()))
```
As the router impementation isn't a …
=> New HTTP router implementation for 'sam local start-api'

README.md, runtime.go
Keeping up with Apple's naming isn't quite as bad as with AWS's, but here's a small housekeeping PR just the same.
=> Renamed OS X to macOS

env.go
On a machine with no AWS credentials configured, each execution takes an additional 20 seconds to complete. This time is spent waiting for the connection to 169.254.169.254 to time out.
I believe this is the cause of issue https://github.com/awslabs/aws-sam-local/issues/134
If aws-sam-local is rarely run on an ec2 instance, it may be better to disable the EC2RoleProvider by default.
=> Add warning when no credentials found. 

convert.go, convert_test.go, invoke.go
This allows customers with CloudFormation templates that contain classic Lambda functions to test them via SAM local
=> Allow execution of AWS::Lambda::Function via the invoke subcommand

event.go, event_test.go
As shown by this failing test sam-local returns an empty map if no path parameters are defined on either the request or the route. Sadly this is not the behaviour of API gateway. There it is null which causes untyped scripting languages to work fine locally but crash on AWS.
Even though the [mux docs state differently](https://github.com/gorilla/mux/blob/7625a85c14e615274a4ee4bc8654f72310a563e4/mux.go#L379) `mux.Vars()` doesn't return nil but an empty map if no path parameters are present. This PR sets the PathParameters explicitly to nill if the map returned by `mux.Vars()` is empty.
Closes #173
PS: I'm not much of a gopher so feel free to call me out if I did something stupid.
**Edit:**
Ah! TIL: Go has the concept of nill maps which are read only empty maps. Therefore the mux docs are …
=> fix(event): set PathParameters explicitly to nill if non

deploy.go, package.go
Because the err returned by `cmd.Wait()` wasn't checked `sam package` and `sam
deploy` would always return exit code 0 even if the aws cli cmd had a non-zero
exit code.
This commit checks the error and calls `log.Fatal()`. While this prints the
original exit code to stderr (at least on macOS) this does not propagate the
original error code but exits with 1. This is because there seems to be no easy
os independent way of getting the exit code. Anyway this should do it for all
sane use cases.
Closes #178
=> fix(deploy, package): propagate non-zero exit codes

event.go, event_test.go
Using [aws-serverless-java-container](https://github.com/awslabs/aws-serverless-java-container) to run a Spring application in a Lambda function I was continuously getting errors. 
1. Checkout and build the [Spring example](https://github.com/awslabs/aws-serverless-java-container/tree/master/samples/spring/pet-store).
2. run with `sam local start-api -t sam.yaml` (latest release and latest develop build)
3. run `curl http://localhost:3000/pets` and get `{"message":"Gateway timeout"}`
It is caused by a Java NullPointerException at `spring-web-4.3.9.RELEASE-sources.jar!/org/springframework/web/util/UrlPathHelper.java:245` originating from `org.springframework.web.util.UrlPathHelper#getPathWithinApplication` because `com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequest#g …
=> api event is missing the stage property

samples/python-with-packages/Makefile
* Default BUCKET to <<bucket>> instead of "fridev-lambda"
* Only set AWS_PROFILE S3_PREFIX STACK_NAME if not in user environment
* Deal with empty $(VENV_DIR)/lib64/python$(PY_VERSION)/site-packages
* Do not include *.pyc (*.so native Linux binaries are preserved)
=> Add generic Environment and OS improvements to samples/python-with-packages/Makefile

router/api.go, router/api_test.go, router/router.go, router/router_test.go, start.go, test/templates/api-missing-method.yaml
Addressing issue reported in awslabs/aws-sam-local#225 and sapessi/serverless-sam#14
* Added error checking to the start method for empty mounts
* Added colors to terminal messages
* Added default empty handler for unmapped HTTP mounts + unit tests
* Minor formatting issues
=> Fixed issue reported in awslabs/aws-sam-local#225. 

runtime.go
Fix issue where a template with no AWS::Serverless:Function.Timeout set causes AWS_LAMBDA_FUNCTION_TIMEOUT=0 to be sent to the Lambda runtime. Instead it should default to the SAM specification default (3 seconds). Also included the same default behaviour for the memory size as this was missing too.
=> Function timeout and memory size fixes (use SAM specification defaults)

README.md
The CLI from time to time provides a nag saying there is a newer version of SAM Local available. It then sends you here to find out more information but doesn't provide a command example. This PR fixes that.
=> update README to include upgrade command for npm installs

README.md
[Release notes for 0.2.3](https://github.com/awslabs/aws-sam-local/releases/tag/v0.2.3) included this line:
> Support for AWS::Serverless::Api resources, including defining your API with inline swagger
This means that the "Inline Swagger support within SAM templates" item under "Project Status" is done, right? Or is there more to it?
=> Update README to mark inline Swagger as supported

runtime.go
Adds Python3.6 to debug overrides section of `runtime.go`.
=> Allow debugger args to be passed to Python3.6 functions

runtime.go
When DEBUGGER_ARGS is not provided, the value from getenv is an empty string. `.split` on empty string, does not return an empty slice, but a slice with the empty string itself. This translated to an extra space in the final arguments sent to Docker container, hence the blow up.
=> Handle the case of empty debug arguments. Fixes #314

runtime.go
Not sure when these changed, but these are the latest values used on Lambda
=> Update debug flags to match latest on live Lambda

router/event.go, router/event_test.go
This helps address https://github.com/awslabs/aws-serverless-java-container/issues/138
Added three headers to the request event. These headers are also present in API Gateway's proxy event:
* `Host` (sent by the client or forced by the library based on the request object)
* `X-Forwarded-Proto`
* `X-Forwarded-Port`
=> Added Forward headers similar to API Gateway's

README.md, runtime.go
Pertains to [this comment](https://github.com/awslabs/aws-sam-local/pull/285#issuecomment-376993161) made on [this PR](https://github.com/awslabs/aws-sam-local/pull/285).
Changes the run command for Node.js version 6.10 to use the legacy debugger (as it previously did) instead of the inspector debugger. Includes directions in the README for when to use legacy and when to use inspector in your launch configuration in VSCode.
=> Fix node debugger protocol

samcli/commands/init/__init__.py
Quick fix for a typo in github name when displaying ``sam init --help`` for an advanced custom template
=> Fix typo in github repo name under sam init --help

README.rst
When attempting to manually install I noticed that the link for cloning the repo was incorrect, just a quick fix for it for future users.
=> Fixed broken link in manual installation instructions

README.rst, samcli/local/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/README.md, samcli/local/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/Solution.sln, samcli/local/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/build.cake, samcli/local/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/build.ps1, samcli/local/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/build.sh
This PR enhance the .NET example in the `sam init` examples:
* Adds the solution file
* Adds Cake, the DSL to build .NET solution
* Updates the README
=> Enhance the .NET example

samcli/local/apigw/service.py, tests/functional/function_code.py, tests/functional/local/apigw/test_service.py, tests/unit/local/apigw/test_service.py
In testing with a local served files, I noted that Content-Type headers were being compared in a case-sensitive way.  Which means that for an express application which is serving headers up in lowercase, sam local was adding a second 'Content-Type: application/json header.
=> Allow for case insensitve header names

samcli/commands/validate/lib/sam_template_validator.py, tests/functional/commands/validate/lib/test_sam_template_validator.py, tests/unit/commands/validate/lib/test_sam_template_validator.py
#417 
For the `sam validate` command, only add the DefinitionUri before running the SAM Translator to an `AWS::Serverless::Api` Resource if the DefintionBody is not given.
*Tested locally*
* ran `pytest -vv tests/functional/commands/validate/lib/test_sam_template_validator.py`
=> fix: Do not add DefinitionUri when DefinitionBody Property is given

samcli/commands/local/lib/swagger/reader.py, tests/unit/commands/local/lib/swagger/test_reader.py
Signed-off-by: Marcel Casado <mcasado@tendrilinc.com>
https://github.com/awslabs/aws-sam-cli/issues/438
Uploading swagger files from s3 is broken since we use boto3 method that expected a string and not a file object. Changed to use the right boto3 method that takes the file object. Modified test and added unit test
=> Fix download a swagger file from given S3 location

samcli/local/apigw/service.py, tests/functional/local/apigw/test_service.py, tests/integration/local/start_api/test_start_api.py, tests/unit/local/apigw/test_service.py
Fixes the bug reported in #404
*Issue #, if available:* #404
APIGW only supports one value for a query string key. 0.3.0 assumed this was a list. This PR aligns the Event that is sent to Lambda on a request with how APIGW handles Query Strings.
=> fix: Value of QueryString in the API event should only be a string

README.rst
None
Fixes the github clone URL in the Readme. Copy and pasting the current command yields:
```
fatal: repository 'git@github.com/awslabs/aws-sam-cli.git' does not exist
```
After this change you receive:
```
Cloning into 'aws-sam-cli'...
```
=> Fixes github clone url in README.rst

requirements/base.txt, tests/functional/local/apigw/test_service.py
Functional tests for the local APIGW we intermittently failing due to
connection issues. This is due to the variable time periods the local
APIGW needs to get setup. Adding a sleep statement to the setup methods,
allows time for the setup to finish. Pervisouly, this was only in one tests
setup method.
Upgrade need in order to fix #400 (this does not fix that issue, that will come in a later PR)
See commit details above
=> chore: Update Flask version to 1.0.2

samcli/local/apigw/service.py, tests/functional/local/apigw/test_service.py, tests/unit/local/apigw/test_service.py
Flask will automagically add a OPTIONS to a route if OPTIONS is not provided
in the list of HTTP Verbs on a url rule. Since we add a new url rule for each
path + HTTP Verb, Flask was adding OPTIONS to every path. This causes some
paths to not execute the Local Lambda code when calling a path with an OPTIONS
verb. We turn off this behavior by turning off the feature through provide_automatic_options.
*Issue #, if available:* 
#400
See above commit message
=> fix: Options requests not invoking Local Lambda

README.rst
`sam -version` -> "Error: no such option: -v"
`sam --version` -> "SAM CLI, version 0.3.0"
=> Fix readme typo in `sam -version`

samcli/local/apigw/service.py, tests/integration/local/start_api/test_start_api.py, tests/integration/testdata/start_api/main.py, tests/integration/testdata/start_api/template.yaml
Flask thinks we are running in a production environment and displays
warning banners beause of it. We set an environment variable before
starting the service to tell Flask we are running within a 'main'
function.
This commit also adds a tests for having two Lambda functions defined under
a given path but have different methods associated with them.
=> fix: Tell Flask we are running the service in main

samcli/__init__.py, setup.py
This is in preparation for a new release (0.4.0). The release will include support for Python3.6 which is the reason there are some additional changes to the setup.py
=> chore: Version bump and update setup.py to include Python3.6

README.rst
The original link points to Docker Toolbox which is deprecated according to Docker website (https://docs.docker.com/toolbox/toolbox_install_windows/)
=> Update Docker on Windows installation link

samcli/commands/validate/lib/sam_template_validator.py
This PR outputs the translated template (as YAML) when calling `sam validate --debug`
Figured this might be a useful stopgap until there's an official CLI command for outputting the translation
=> Add translated template output to `validate --debug`

docs/running_and_debugging_serverless_applications_locally.rst
The Docker container is stopped after every request when running locally however the docs indicate it will be re-used when running an interpreted language.
This PR removes the paragraph for clarity. Feel free to close if I've missed an option that makes this work!
=> Remove docs about re-using Docker container

samcli/local/apigw/path_converter.py, tests/functional/local/apigw/test_service.py, tests/unit/local/apigw/test_path_converter.py
Addressed the bug from #457 where SAM CLI only accepted proxy paths with '{proxy+}'. This PR will allow 'proxy' to be any arbitrary name.
I ran the functional tests locally in both Py2 and Py3 (all passed in both).
=> fix: Allow Proxy Paths to have arbitrary names

samcli/local/apigw/local_apigw_service.py, samcli/local/lambda_service/lambda_error_responses.py, samcli/local/lambda_service/local_lambda_invoke_service.py, samcli/local/services/base_local_service.py, tests/functional/function_code.py, tests/functional/local/lambda_service/test_local_lambda_invoke.py, tests/unit/local/apigw/test_local_apigw_service.py, tests/unit/local/lambda_service/test_lambda_error_responses.py, tests/unit/local/lambda_service/test_local_lambda_invoke_service.py, tests/unit/local/services/test_base_local_service.py
Details:
* Handling for when lambda returns an error
* Handled payload could not be parsed as JSON
* Abstracted if the lambda output is an error from the container into LambdaOutputParser
* Added handling for X-Amz-Log-Type
* Added handling for X-Amz-Invocation-Type
* Moved all Request validate to flask.before_request call
* Added handling for Query parameters (not supported)
* Added handling for unsupported_media_type
* Added handling for ServiceError
* Added handling for generic 404 Error handling
* Fix up tests to make them runable
This is to handle the Error cases that can occur in the Local Lambda Service. This is meant to mimic the actually service with some caveats that are specific to local:
* The generic 404 has the same response if the Lambda Function …
=> feat(LocalLambdaService): Error handling for local lambda

samcli/local/services/base_local_service.py, tests/unit/local/services/test_base_local_service.py
*Issue #531*
*Description of changes: fix corner case that only one '\n' in response*
=> fix: invalid response with new line symbol

samcli/local/lambda_service/local_lambda_invoke_service.py, tests/functional/local/lambda_service/test_local_lambda_invoke.py, tests/integration/local/invoke/test_integrations_cli.py, tests/integration/local/start_lambda/start_lambda_api_integ_base.py, tests/integration/local/start_lambda/test_start_lambda.py, tests/integration/testdata/invoke/main.py, tests/integration/testdata/invoke/template.yml, tests/unit/local/lambda_service/test_local_lambda_invoke_service.py
Add integration tests for `sam local start-lambda` command.
=> feat(LocalLambdaService): Integ test for start-lambda command

samcli/__init__.py
=> Preparing for release - v0.5.0

samcli/commands/local/lib/local_lambda_service.py
When running 'sam local start-lambda' it logged "templatethrough" rather than "template through"
=> Fixed spacing typo

README.rst
Link at the bottom of the readme wasn't rendering ok
=> [minor] Fix @mhart link in readme (was a markdown link)

README.rst
*Description of changes:* Typo in readme:
Removed Cloudtrail entry and added SNS. Cloudtrail doesn't seem to be a valid sample event?
SAM CLI, version 0.5.0
=> Fix readme: removed cloudtrail, added SNS to match

README.rst
I haven't updated the Apache-2.0 link because it doesn't seem to work with the new repo name (yet?).
*Issue #576
*Description of changes:* Just updated the links :)
=> Update repo name references

README.rst, requirements/base.txt, requirements/dev.txt, samcli/commands/local/cli_common/invoke_context.py, samcli/commands/local/cli_common/options.py, samcli/commands/local/cli_common/user_exceptions.py, samcli/commands/local/invoke/cli.py, samcli/commands/local/lib/debug_context.py, samcli/commands/local/lib/local_lambda.py, samcli/commands/local/start_api/cli.py, samcli/commands/local/start_lambda/cli.py, samcli/local/docker/container.py, samcli/local/docker/lambda_container.py, samcli/local/lambdafn/runtime.py, tests/functional/commands/local/lib/test_local_api_service.py, tests/functional/commands/local/lib/test_local_lambda.py, tests/functional/local/docker/test_lambda_container.py, tests/unit/commands/local/cli_common/test_invoke_context.py, tests/unit/commands/local/invoke/test_cli.py, tests/unit/commands/local/lib/test_debug_context.py, tests/unit/commands/local/lib/test_local_lambda.py, tests/unit/commands/local/start_api/test_cli.py, tests/unit/commands/local/start_lambda/test_cli.py, tests/unit/local/docker/test_container.py, tests/unit/local/docker/test_lambda_container.py, tests/unit/local/lambdafn/test_runtime.py
Golang Debugging was initally implemented in #495, but reverted in #526
due to functional and integration tests failures. This commit reverts #526
and adds in the testing gaps. The specific differences are:
* _get_debug_context method was replaces with the __bool__/__nonzero (py2)
* Added additional unit tests for lambda_container to cover added methods
* Updated Functional tests
* Added debug_context support in start-lambda
#281
=> feat(debugging): Support debugging Golang functions.

README.rst
*Issue #, if available:* 34
*Description of changes:* Change "Kinesis" to "Kinesis Streams" in the README
=> "Amazon Kinesis" disambiguation #34

DEVELOPMENT_GUIDE.rst
*Issue #, if available:* #597
Instructions in the output of pyenv are incorrect, so adding a note to guide any Windows Users. 
=> adding instructions for how to add pyenv to your PATH for Windows

README.rst
Adding instructions for Windows users to successfully install sam
=> docs :Creating instructions for Windows users to install sam

DEVELOPMENT_GUIDE.rst
Since pyenv doesn't support Windows, I added a note directing Windows users to use pipenv instead.
=> docs: Adding a note directing Windows users to use pipenv

samcli/local/lambdafn/env_vars.py, tests/unit/local/lambdafn/test_env_vars.py
https://github.com/awslabs/aws-sam-cli/issues/517
Fix stringifying  λ environment variables that are passed when using Python2.
=> Fix stringifying λ environment variables when using Python2

docs/deploying_serverless_applications.rst
It looks like the packaging command does not require the `file` word between --template-file and the file name
=> Remove an extra word in the sam packaging command

samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/hello_world/tests/unit/test_handler.js
On init of NodeJs project, tests were immediately failing because it should have been calling to app.lambdaHandler.
Default function for lambdaHandler was changed but this change was not made in the test initialization.
=> Fix casing in NodeJS test initializtion

docs/installation.rst
Adds instructions to explain how to update SAM CLI on AWS Cloud9 environments where it is older.
=> added upgrade instructions for AWS Cloud9

docs/deploying_serverless_applications.rst
Small change to the packaging and deployment docs to make the packaged output template name consistent across the packaging and deployment example commands.
=> docs: Consistent packaged template naming

samcli/local/docker/container.py, samcli/local/docker/utils.py, tests/unit/local/docker/test_container.py, tests/unit/local/docker/test_utils.py
- On supplying path for docker in windows environments, change path to unix style.
- This allows sam-cli to work with docker toolkit.
- https://github.com/awslabs/aws-sam-cli/issues/461
- change windows style paths to unix style paths, to allow operability of the sam cli under windows 8.
- Did testing on windows environment with docker toolbox and docker for windows.
=> fix(path): change windows style path to unix

docs/usage.rst
The section on debugging Go wasn't highlighting code snippets. This change fixes that.
- Tiny documentation changes to ensure code is rendering properly.
=> Update usage.rst to render code inline in Debugging Go section

samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/hello_world/tests/unit/test_handler.js
Nodejs8.10 lambda doesn't take in a callback so tests pass no
matter what. Should be testing results captured from await call.
Nodejs 8.10 runtime unit tests are passing but not properly testing anything since the lamdba uses async/await instead of callbacks.
=> Properly test results with generated Nodejs8.10 runtime unit tests.

requirements/base.txt
Fix Installation of aws-sam-cli using python3.7 when trying to do a vanilla install without using any previously built binaries.
enum34 Issue: https://bitbucket.org/stoneleaf/enum34/issues/21/setuppy-should-no-op-for-python-34
Command to use under a python 3.7 virtualenv
```
pip install -v --no-binary :all: --ignore-installed .
```
=> fix: conditionally install enum34 based on python version

samcli/local/init/__init__.py, samcli/local/init/templates/cookiecutter-aws-sam-hello-dotnet/cookiecutter.json, samcli/local/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/README.md, samcli/local/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/src/HelloWorld/HelloWorld.csproj, samcli/local/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/src/HelloWorld/aws-lambda-tools-defaults.json, samcli/local/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/template.yaml, samcli/local/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/test/HelloWorld.Test/HelloWorld.Tests.csproj
*Issue #, if available:* https://github.com/awslabs/aws-sam-cli/issues/609
* Adds support for dotnetcore 2.1 
* Defaults to dotnetcore 2.1 when `dotnet` is selected
* Addresses a regression noted in https://github.com/awslabs/aws-sam-cli/issues/673
=> Add dotnetcore 2.1 support for init command

requirements/base.txt, samcli/commands/local/lib/generated_sample_events/events.py
- pystache does not explicitly state it supports py36
- last release was in 2014
- using chevron instead
- tested creation of sample events, and they worked.
=> fix: remove dependency on pystache

samcli/commands/local/invoke/cli.py, samcli/commands/local/lib/exceptions.py, samcli/commands/local/lib/local_lambda.py, samcli/commands/local/start_api/cli.py, samcli/commands/local/start_lambda/cli.py, tests/unit/commands/local/invoke/test_cli.py, tests/unit/commands/local/lib/test_local_lambda.py, tests/unit/commands/local/start_api/test_cli.py, tests/unit/commands/local/start_lambda/test_cli.py
*Issue #, if available:* #626 
Introduces an exception to be thrown when an environment variable file is invalid. 
SAM still swallows regular malformed env files, but will throw an error if the json structure doesn't match as expected.
=> fix: raise error for invalid environment variables file

.travis.yml, DEVELOPMENT_GUIDE.rst, setup.py, tox.ini
* Referencing https://github.com/travis-ci/travis-ci/issues/9815
* listed as a current workaround until travis CI comes up with official support for 3.7
=> feat: travis CI support for Python 3.7

docs/usage.rst
https://github.com/awslabs/aws-sam-cli/issues/555
stopOnEntry flag allows breaking directly into user code, instead of the runtime bootstrap file.
=> fix: correct launch.json for node js debugging through vs code

samcli/commands/local/lib/generated_sample_events/events/apigateway/AwsProxy.json, tests/integration/local/start_lambda/test_start_lambda.py
*Issue #, if available:* N/A
*Description of changes:* Documentation states that the isBase64Encoded key is a bool value (see [https://amzn.to/2QAWECb](https://amzn.to/2QAWECb)). The aws-proxy generated sample event defines it as a string. This is causing type casting issues in languages like Go.
Also, fixed integration test assertion for "test_lambda_function_raised_error"
=> Updated isBase64Encoded value to bool as defined in documentation

samcli/cli/main.py, samcli/commands/local/lib/debug_context.py, tests/unit/commands/local/lib/test_debug_context.py
* N/A ( I can create one and reference it)
* Allow for stdout and stderr streams to be unbuffered by default.
=> fix: allow for stdout and stderr streams to be unbufferred directly.

samcli/local/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/README.md, samcli/local/init/templates/cookiecutter-aws-sam-hello-golang/{{cookiecutter.project_name}}/README.md, samcli/local/init/templates/cookiecutter-aws-sam-hello-java/{{cookiecutter.project_name}}/README.md, samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/README.md, samcli/local/init/templates/cookiecutter-aws-sam-hello-python/{{cookiecutter.project_name}}/README.md
Corrects AWS permissions from PowerUser to Administrator.
SAM creates an implicit IAM Role as part of `AWS::Serverless::Function` resource and therefore needs Administrator access as an initial requirement or else this will fail.
Thanks to @sliedig for spotting this at last minute
=> Init templates: Correct permissions for AWS CLI under requirements

DEVELOPMENT_GUIDE.rst
=> docs: add instructions for using local version of SAM Transformer

samcli/commands/local/invoke/cli.py, samcli/local/docker/manager.py, tests/unit/commands/local/invoke/test_cli.py, tests/unit/local/docker/test_manager.py
#529 and #451
When working completely offline, SAM CLI fails when trying to download the docker image. Instead of failing right away, we will check to see if we have an older image that we could use instead. If we do not have an image locally, we fail gracefully with a message describing we could not download the image.
=> fix: Attempt to recover/invoke function when docker connectivity is poor

samcli/commands/build/build_context.py, samcli/commands/build/command.py, samcli/commands/deploy/__init__.py, samcli/commands/package/__init__.py, samcli/lib/samlib/cloudformation_command.py, samcli/lib/utils/osutils.py, samcli/local/init/templates/cookiecutter-aws-sam-hello-python/{{cookiecutter.project_name}}/README.md, tests/unit/commands/test_deploy.py, tests/unit/commands/test_package.py, tests/unit/lib/samlib/test_cloudformation_command.py
- `sam init` Python example README changes to include `sam build`
- `sam package` command now just defaults to a built template. So you can do `sam build && sam package --s3-bucket foo` to build and then package. Don't need to manually wire the intermediate template files through.
=> Documentation updates + "sam package" defaults to built template

requirements/base.txt, samcli/cli/main.py, samcli/commands/build/command.py, tests/integration/buildcmd/test_build_cmd.py, tests/integration/testdata/buildcmd/Python/main.py, tests/integration/testdata/buildcmd/Python/requirements.txt
This command currently prints version information in JSON format.
In future we will expand this to print everything from versions of
dependencies, list of commands available, capabilities exposed by
the commands, etc. Hopefully eventually this will provide a nice
list of machine readable instructions for other tools to integrate
with SAM CLI
=> Adding a `sam --info` command

requirements/dev.txt
Unit tests started to fail with unexpected error: `AttributeError: module 'astroid' has no attribute 'YES'`
Pinned `astroid` package version in >=1.5.8,<2.1.0 range
=> Fix astroid version

samcli/__init__.py, samcli/cli/options.py, tests/integration/local/invoke/test_integrations_cli.py
Because of the default value, this value will end up overriding whatever user had set in their environment using AWS_REGION or AWS_DEFAULT_REGION.
*Checklist:*
=> fix: Don't set default value for --region

samcli/local/layers/layer_downloader.py, tests/integration/local/invoke/runtimes/test_with_runtime_zips.py, tests/integration/local/invoke/test_integrations_cli.py, tests/unit/local/layers/test_download_layers.py
=> fix: Create Layer Cache during building image

designs/resource_metadata_overriding.md, designs/template_generation_through_frameworks.md, samcli/commands/local/lib/sam_base_provider.py, samcli/lib/samlib/resource_metadata_normalizer.py, tests/integration/local/invoke/test_integrations_cli.py, tests/integration/testdata/invoke/different_code_location/main.py, tests/integration/testdata/invoke/template.yml, tests/unit/commands/local/lib/test_sam_base_provider.py, tests/unit/lib/samlib/test_resource_metadata_normalizer.py
💻 [**Rendered Design Doc is here**](https://github.com/jfuss/aws-sam-cli/blob/experimental/cdk/designs/template_generation_through_frameworks.md)
🗓 **RFC Open for feedback until**: 1/10/2018
* Issue *
#893
This design is meant to capture how we can directly support templates that are embedded with Metadata CDK appended into the template. This will allow customers to synthesize templates written in CDK and locally debug/invoke their functions through SAM CLI. While understanding CDK Metadata is the only thing in scope for this design, it is left open to allow further support and expansion (most likely through another command) that can generate the AWS CloudFormation templates directly within SAM CLI.
*Checklist:* …
=> feat(invoke): reading Metadata adding to Resources in a template

samcli/local/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/README.md, samcli/local/init/templates/cookiecutter-aws-sam-hello-golang/{{cookiecutter.project_name}}/README.md, samcli/local/init/templates/cookiecutter-aws-sam-hello-java/{{cookiecutter.project_name}}/README.md
Other than Python, all the cookiecutter README.md files for the other
languages contained a typo in the sam package command.
See also: https://stackoverflow.com/q/54074428/3787051
*Checklist:*
- [N/A] Write Design Document ([Do I need to write a design document?](https://github.com/awslabs/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.rst#design-document))
- [N/A] Write unit tests
- [N/A] Write/update functional tests
- [N/A] Write/update integration tests
- [N/A] `make pr` passes
=> Fix sam package command in cookiecutter docs

README.md
Remove the max age off the badge images so the default gets used
😄 
*Checklist:*
=> Remove maxage off badges

samcli/lib/utils/tar.py, samcli/local/docker/lambda_image.py, tests/unit/lib/utils/test_tar.py, tests/unit/local/docker/test_lambda_image.py
https://github.com/awslabs/aws-sam-cli/issues/863
Stopped using compression when creating tarball of docker context for building `samcli/lambda` docker image containing local Lambda layers. With compression, the stream-and-build procedure takes roughly 27 seconds for a sample 215 MB file tree of Python dependencies (compressing to 51 MB). Without compression, the same procedure takes less than 4 seconds.
*Checklist:*
=> Speed up local layer builds by skipping unnecessary compression of docker context

samcli/commands/deploy/__init__.py, samcli/commands/package/__init__.py, tests/unit/commands/test_deploy.py, tests/unit/commands/test_package.py
=> chore: add required options for package and deploy

setup.cfg, setup.py
#889
Previously we were adding the complete license into the `license` key in `setup()`. This cause a corruption of the `METADATA` file that exist within the packaged `whl` or `tar` file.  PyPi uses this file to render the homepage for the project and pip uses this for validation locally (should it install into X python version for example).
*Checklist:*
=> fix: update license key in setup() to expected value by PyPi

samcli/local/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/template.yaml, samcli/local/init/templates/cookiecutter-aws-sam-hello-golang/{{cookiecutter.project_name}}/template.yaml, samcli/local/init/templates/cookiecutter-aws-sam-hello-java/{{cookiecutter.project_name}}/template.yaml, samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/template.yaml, samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs6/{{cookiecutter.project_name}}/template.yaml, samcli/local/init/templates/cookiecutter-aws-sam-hello-python/{{cookiecutter.project_name}}/template.yaml, samcli/local/init/templates/cookiecutter-aws-sam-hello-ruby/{{cookiecutter.project_name}}/template.yaml
*Issue #, if available:* N/A
The template indent spacing was inconsistent (sometimes 4 spaces,
sometimes 2). This makes them consistently use 2 spaces. 2 spaces was
chosen, because it's a defacto standard for yaml and also the AWS
Serverless Application Repository has a "Copy as SAM Resource" button,
which copies yaml to your clipboard using 2 spaces.
*Checklist:*
=> fix(init): Make template spacing consistent

samcli/commands/build/command.py, samcli/lib/build/app_builder.py, samcli/lib/build/workflow_config.py, tests/integration/buildcmd/build_integ_base.py, tests/integration/buildcmd/test_build_cmd.py, tests/unit/commands/buildcmd/test_command.py, tests/unit/lib/build_module/test_app_builder.py, tests/unit/lib/build_module/test_workflow_config.py
=> refactor(build): Move workflow config information into its own file

.pylintrc, samcli/__main__.py, samcli/cli/main.py
- `python -m samcli.cli.main` invokes sam cli
=> feat: allow sam to be invoked as a module

tests/integration/local/invoke/test_integrations_cli.py
=> tests(integ): adding integ test for aws config and profile env vars

CONTRIBUTING.md, DEVELOPMENT_GUIDE.md
I was trying to get to the development guide, then I found the link didn't exist.
=> docs: fix links to .rst files

tests/integration/local/invoke/test_integrations_cli.py, tests/integration/testdata/invoke/sam-template.yaml
#992
Added tests for the following SAM Env Vars:
* SAM_LAYER_CACHE_BASEDIR
* SAM_SKIP_PULL_IMAGE
* SAM_TEMPLATE_FILE
* SAM_DOCKER_NETWORK
Ones not included:
* SAM_DEBUG
* SAM_DEBUG_PORT
* DEBUGGER_ARGS
* SAM_DOCKER_VOLUME_BASEDIR
* SAM_FORCE_IMAGE_BUILD
I am happy to add tests for the ones I did not include, but I did not have a good way to test them.
*Checklist:*
=> test(integ): Add tests for SAM_* Environment Variables

samcli/__main__.py, samcli/cli/command.py
- irrespective of the module name that invokes the CLI, the command that
is seen on the help/description text, should always say "sam"
Example
```
(aws_sam_cli_WS) srirammv@localrainbow:20:20:34:~/aws_sam_cli_WS/aws-sam-cli$python -m samcli
Usage: sam [OPTIONS] COMMAND [ARGS]...
AWS Serverless Application Model (SAM) CLI
The AWS Serverless Application Model extends AWS CloudFormation to provide
a simplified way of defining the Amazon API Gateway APIs, AWS Lambda
functions, and Amazon DynamoDB tables needed by your serverless
application. You can find more in-depth guide about the SAM specification
here: https://github.com/awslabs/serverless-application-model.
Options:
--debug    Turn on debug logging to print debug message generated by SAM
CLI.
--version  Show the version and exit.
--info …
```
=> fix: always ensure the base command is set to "sam"

setup.py
N/A
Python wheels, `.whl` files, produced through `python setup.py bdist_wheel` do not read or understand `MANIFEST.in` files. Since we use this file to remove tests modules from the dists, tests end up in the `.whl` files that get uploaded to PyPi. This PR updates the `exclude` parameter in `find_packages` to exclude all `test.*` modules, following [setuptools documentation](https://setuptools.readthedocs.io/en/latest/setuptools.html#using-find-packages).
*Checklist:*
=> fix: Remove tests from .whl file (bdist_wheel)

samcli/local/docker/lambda_build_container.py, tests/unit/local/docker/test_lambda_build_container.py
=> fix(build): use container directories in executable_search_paths when building in container

tests/integration/local/invoke/test_integrations_cli.py
- while testing for custom profiles, make sure environment variables are
not already set, as it looks like preset environment variables get
precendence over setting via profiles.
=> fix: ensure clean environment variables before test

requirements/base.txt, samcli/commands/validate/lib/sam_template_validator.py
Bump version of `aws-sam-translator`.
This PR also removes a monkey patch we created to suppress some root level logging the `aws-sam-translator` was doing. With the release of 1.10.0, there is no longer a `logging`module in the samtranslator.parser.parser module. When running `make pr`, pylint was complaining about this as well (see below)
```
************* Module samcli.commands.validate.lib.sam_template_validator
E: 81,39: Module 'samtranslator.parser.parser' has no 'logging' member (no-member)
```
*Checklist:*
=> Chore: Bump aws-sam-translator

requirements/base.txt, samcli/lib/build/workflow_config.py, samcli/local/common/runtime_template.py, samcli/local/init/templates/cookiecutter-aws-sam-hello-java-maven/{{cookiecutter.project_name}}/README.md, samcli/local/init/templates/cookiecutter-aws-sam-hello-java-maven/{{cookiecutter.project_name}}/template.yaml, tests/integration/buildcmd/test_build_cmd.py, tests/integration/testdata/buildcmd/Java/maven/pom.xml, tests/integration/testdata/buildcmd/Java/maven/src/main/java/aws/example/Hello.java, tests/unit/lib/build_module/test_workflow_config.py
=> feat(build): Support building Java8 functions through Maven

samcli/local/common/runtime_template.py
I modify invalid golang template path.
The golang template path is
`aws-sam-cli/samcli/local/init/templates/cookiecutter-aws-sam-hello-golang/`
But, invalid path is set in `samcli/local/common/runtime_template.py` file.
*Checklist:*
=> fix: golang template path

samcli/local/init/templates/cookiecutter-aws-sam-hello-java-gradle/{{cookiecutter.project_name}}/HelloWorldFunction/build.gradle
This issue is reported in AWS Toolkit JetBrains, but the root cause is the Gradle template
https://github.com/aws/aws-toolkit-jetbrains/issues/854
Remove the redundant `sourceSets` configuration and replace the deprecated methods. 
*Checklist:*
=> Fix incorrect Gradle project configuration.

samcli/local/docker/container.py, tests/unit/local/docker/test_container.py
ISSUE: Performance for Docker runs using `sam local start-api` on Mac is horrible. I benchmarked requiring a large Ruby application at ~45seconds.
FIX: Resolve Docker on Mac performance issues by allowing the project folder to be mounted as both "read only" (current behavior) and "delegated". The docs for Docker mention that a comma-separated list is an allowed value. Hence I maintained the `ro` mode and simply added `delegated` to the list. Doc: https://docs.docker.com/v17.09/engine/admin/volumes/volumes/
Please see this article for a description of the new option added. https://docs.docker.com/docker-for-mac/osxfs-caching/. If tests pass, I assume this option being added is a noop for non Mac platforms.
=> Add Docker Delegated Consistency to Volume

samcli/lib/build/workflow_config.py, tests/integration/buildcmd/test_build_cmd.py, tests/integration/testdata/buildcmd/Java/gradle-kotlin/build.gradle.kts, tests/integration/testdata/buildcmd/Java/gradle-kotlin/src/main/java/aws/example/Hello.java, tests/unit/lib/build_module/test_workflow_config.py
* Issue #1097
* Allows to use `build.gradle.kts` instead of `build.gradle`
=> Adding specific configuration for gradle projects using kotlin build script

samcli/local/init/templates/cookiecutter-aws-sam-hello-ruby/{{cookiecutter.project_name}}/hello_world/app.rb
Nothing.
Fix context doc URL of Ruby runtime.
*Checklist:*
=> Fix context doc URL of Ruby runtime 

README.md, snap/local/launchers/launcher.sh, snap/snapcraft.yaml, snapcraft.yaml
*Issue #, if available:* N/A
*Description of changes:* Add support for snapcraft package
*Checklist:*
=> Add snapcraft config and link to snap package in README

.gitignore, samcli/commands/build/command.py, samcli/lib/build/app_builder.py, samcli/lib/build/workflow_config.py, tests/integration/buildcmd/test_build_cmd.py, tests/unit/lib/build_module/test_app_builder.py
"sam build" for Dotnet does not really need to support building within a container because majority of the dotnet modules don't have native bindings and can compile on any platform and run successfully on Lambda.
PR is marked WIP because the exact error message and UX is still not signed off.
*Checklist:*
=> feat: Error on --use-container for dotnet builds

samcli/local/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/template.yaml
N/A
`sam init --runtime dotnetcore` produced a template without a Runtime, making the template invalid. This change removes an else if case in the template generation to allow always producing the latest dotnetcore runtime. The cli (click) will validate the options before cookiecutter runs, so we don't need strict match checks expect for the none latest cases (in this case for dotnetcore2.0).
*Checklist:*
=> fix(init): Add runtime to template when dotnetcore runtime is asked for

samcli/__init__.py
=> chore(version): set 0.14.3.dev1 version

MANIFEST.in, Makefile, requirements/base.txt, requirements/dev.txt, requirements/prod.txt, requirements/tools.txt, setup.py
During development, we can't easily use development versions of other dependencies such as AWS Lambda Builders.
In this change, I have separated out dev requirements from prod requirements. For Production, the dependencies are version pinned and pulled from PyPi. For dev requirements, the dependencies are pulled directly from Github source. 
I had to remote the `extras_requires` in setup.py because it did not support installing from Github. Instead I modified the Makefile to pip install these dependencies separately. This is acceptable for development builds.
For production, I concatenate `base.txt` with `prod.txt` and use it as the final list of requirements.
*Testing:*
Following commands worked as expected
- `SAM_CLI_DEV=1 pip install …
=> Depend on development version of lambda-builders for dev builds

samcli/commands/build/build_context.py, tests/unit/commands/buildcmd/test_build_context.py
#1101 
See https://github.com/awslabs/aws-sam-cli/issues/1101#issuecomment-481317178 for more details.
*Checklist:*
=> fix(build): Resolve path after .aws-sam is created

docs/usage.md
I changed the [delve](https://github.com/go-delve/delve) URL written in docs.md.
Thank you!
*Checklist:*
=> fix go-delve URL

designs/sam_build_cmd.md, samcli/commands/build/build_context.py, samcli/commands/build/command.py, samcli/lib/build/app_builder.py, tests/integration/buildcmd/build_integ_base.py, tests/integration/buildcmd/test_build_cmd.py, tests/integration/testdata/buildcmd/many-functions-template.yaml, tests/unit/commands/buildcmd/test_build_context.py, tests/unit/commands/buildcmd/test_command.py, tests/unit/lib/build_module/test_app_builder.py
N/A
This enables a customer to build a single function similar to how they would invoke a single function. To build a single function, you can pass the LogicalID to the command `sam build <MyLogicalId>`. If the LogicalID is omitted, the command will behave exactly how it does not and build the whole template.
This change enables a customer (or IDE) to quickly build a single function for faster test cycles. This could result in a deployment to of source code instead of built code, if the customer only builds one of the n number of functions in the template and then does a package and deploy. With this change, customers will need to still use `sam build` without the logicalId before package and deploying. This could create more customer confusion in the short term. …
=> feat(build): Build a single function

DEVELOPMENT_GUIDE.md, samcli/local/lambdafn/zip.py, tests/unit/local/lambdafn/test_zip.py
*Issue #, if available:* #917 
*Description of changes:*  This enables the layer downloader to us AWS_CA_BUNDLE environment variable if it exists.  It defaults to SSL verify True if it doesn't.
*Checklist:*
=> Layer Downloader now looks for AWS_CA_BUNDLE if it exists

README.md, samcli/commands/build/command.py, samcli/commands/init/__init__.py, samcli/commands/local/invoke/cli.py, samcli/commands/local/start_api/cli.py, samcli/commands/local/start_lambda/cli.py, samcli/lib/build/workflow_config.py, samcli/local/common/runtime_template.py, samcli/local/docker/lambda_container.py, samcli/local/docker/lambda_debug_entrypoint.py, samcli/local/docker/lambda_image.py, samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs/README.md, samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs/cookiecutter.json, samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/README.md, samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/hello-world/package.json, samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/template.yaml, tests/integration/buildcmd/test_build_cmd.py, tests/unit/commands/local/invoke/test_cli.py, tests/unit/commands/local/start_api/test_cli.py, tests/unit/commands/local/start_lambda/test_cli.py, tests/unit/local/docker/test_lambda_container.py
- local invoke, test and debug nodejs10.x lambda runtimes.
*Checklist:*
=> feat(nodejs10.x): support new nodejs10.x runtime

samcli/commands/local/lib/sam_function_provider.py, tests/integration/buildcmd/test_build_cmd.py, tests/unit/commands/local/lib/test_sam_function_provider.py
DockerLambda only supports one version of a container. Recently this was updated to AmazonLinux1803
but (at the time of writing) the Lambda Service is still using AmazonLinux1703. Given that, SAM CLI
will now fail if the arn:aws:lambda:::awslayer:AmazonLinux1703 Layer Arn is provided. If
arn:aws:lambda:::awslayer:AmazonLinux1803 Layer Arn is provided, we simply ignore it when reading
the Layer Definition on a Function. This scenerios happen in both build and invoke related commands.
N/A
See git commit above.
*Checklist:*
=> fix(invoke/build): Allow AmazonLinux1803 Layer and fail when AmazonLinux1703 Layer is provided

samcli/local/apigw/local_apigw_service.py, samcli/local/lambda_service/local_lambda_invoke_service.py, samcli/local/services/base_local_service.py, tests/integration/local/start_api/test_start_api.py, tests/integration/testdata/start_api/main.py, tests/integration/testdata/start_api/template.yaml, tests/unit/local/apigw/test_local_apigw_service.py, tests/unit/local/services/test_base_local_service.py
#830 
This is a rework of #842 by @martysweet, which seems to have stalled. This PR uses Flask's built-in method of providing multiple header values, which makes it act like API GW. In particular, multi-value headers are folded into a comma-separated list *unless* it's `Set-Cookie` which is a special-case.
There's two parts to this PR. First drops `CaseInsensitiveDict` as it doesn't seem to be necessary. The `Headers` class in Flask is already case-insensitive and swapping in `Headers` in the test case for `CaseInsensitiveDict` passed the tests. There are some minor differences:
* `Headers` isn't JSON serializable by default
* `Headers` won't pass equality comparison with a dict
* `Headers` raises `werkzeug.exceptions.BadRequestKeyError` …
=> Local support for response multiValueHeaders

samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/README.md, samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs6/{{cookiecutter.project_name}}/README.md
This is a purely documentation change. The rest of these README.md files refer to the directory as `hello-world` rather than `hello_world`, and I can confirm the generated folder is named `hello-world`. Simply pulling the documentation into line with reality.
This only is for Node.js templates, other languages appear to use `hello_world`.
*Checklist:*
=> docs: Fix name of source directory in README.md

samcli/commands/deploy/__init__.py
=> Remove duplicate `sam deploy` in command help text

samcli/commands/local/cli_common/invoke_context.py, samcli/commands/local/invoke/cli.py, samcli/commands/local/lib/local_lambda.py, samcli/commands/local/start_api/cli.py, samcli/commands/local/start_lambda/cli.py, samcli/local/layers/layer_downloader.py, tests/integration/local/start_lambda/test_start_lambda.py, tests/unit/commands/local/cli_common/test_invoke_context.py, tests/unit/commands/local/invoke/test_cli.py, tests/unit/commands/local/lib/test_local_lambda.py, tests/unit/commands/local/start_api/test_cli.py, tests/unit/commands/local/start_lambda/test_cli.py
=> fix: Move boto3 client creation to a computed property

requirements/base.txt, tests/functional/local/apigw/test_local_apigw_service.py
*Issue #, if available:* n/a
- Bump requests from 2.20.0 to 2.22.0
- Update `make_service_response` for readability and dynamic inclusion of requests' version number
Upgrading requests to 2.22 lifts the upper bound of urllib3 to <1.26.  urllib3 1.25 includes fixes for the following vulnerabilities [CVE-2019-9740](https://nvd.nist.gov/vuln/detail/CVE-2019-9740) and [CVE-2019-112369](https://nvd.nist.gov/vuln/detail/CVE-2019-11236) which were also backported to the 1.24 series (included in release 1.24.3).
urllib3 1.25.2+ includes also other improvements like certificate validation, TLSv1.3 support, Brotli support, ….  See https://github.com/urllib3/urllib3/blob/1.25.3/CHANGES.rst
By submitting this pull request, I confirm that my contribution is made under the …
=> fix: upgrade requests to 2.22.0

designs/_template.md, requirements/base.txt, samcli/__init__.py, samcli/commands/deploy/__init__.py, samcli/commands/local/cli_common/invoke_context.py, samcli/commands/local/invoke/cli.py, samcli/commands/local/lib/local_lambda.py, samcli/commands/local/start_api/cli.py, samcli/commands/local/start_lambda/cli.py, samcli/local/apigw/local_apigw_service.py, samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/README.md, samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs6/{{cookiecutter.project_name}}/README.md, samcli/local/lambda_service/local_lambda_invoke_service.py, samcli/local/layers/layer_downloader.py, samcli/local/services/base_local_service.py, tests/functional/local/apigw/test_local_apigw_service.py, tests/integration/local/start_api/test_start_api.py, tests/integration/local/start_lambda/test_start_lambda.py, tests/integration/testdata/start_api/main.py, tests/integration/testdata/start_api/template.yaml, tests/unit/commands/local/cli_common/test_invoke_context.py, tests/unit/commands/local/invoke/test_cli.py, tests/unit/commands/local/lib/test_local_lambda.py, tests/unit/commands/local/start_api/test_cli.py, tests/unit/commands/local/start_lambda/test_cli.py, tests/unit/local/apigw/test_local_apigw_service.py, tests/unit/local/services/test_base_local_service.py
=> chore: v0.17.0

appveyor.yml
Still pending validation by actually running in AppVeyor
*Checklist:*
=> AppVeyor to run unit tests & linters

requirements/base.txt
To support Docker Proxy Config (https://github.com/awslabs/aws-sam-cli/pull/1196)
*Checklist:*
=> chore: Docker SDK minimum version should be 3.7.0

samcli/local/docker/container.py, samcli/local/docker/utils.py, tests/unit/local/docker/test_container.py
#913 
This updates the docker create command to configure the proxy settings inside the docker container using global docker configuration file.  This will allow users who sit behind a proxy and have configured their proxy settings in docker to pass through their proxy for things such as dependency installation (Pip, etc.).
*Checklist:*
=> Docker proxy config

samcli/commands/_utils/template.py
Add packaging of local files support for "AWS::AppSync::FunctionConfiguration" resource (AWS AppSync Function) mapping templates:
RequestMappingTemplateS3Location
ResponseMappingTemplateS3Location
https://github.com/awslabs/aws-sam-cli/issues/897
Added new AppSync FunctionConfiguration resource and 2 properties to be supported to configuration file along other supported properties.
*Checklist:*
=> AWS::AppSync::FunctionConfiguration mapping templates packaging support

tests/integration/publish/publish_app_integ_base.py
- Integration tests pass on windows and mac.
=> fix: encoding on files read for publish integ tests

samcli/lib/telemetry/telemetry.py, tests/integration/telemetry/integ_base.py, tests/integration/telemetry/test_telemetry_contract.py, tests/unit/lib/telemetry/test_telemetry.py
- Increase read timeout to 100ms. Backend needs a bit more time than 1ms to reliably receive & process data
- Don't crash if offline
- Integration tests to validate offline behavior & opt-in/opt-out behavior
*Checklist:*
=> fix: More robust connections to telemetry backend

DEVELOPMENT_GUIDE.md
=> doc: Adding testing guidelines

samcli/lib/samlib/cloudformation_command.py, tests/unit/lib/samlib/test_cloudformation_command.py
- Less confusing error msg for not from aws world people
*Checklist:*
=> Less confusing error msg for not from aws world people

samcli/commands/init/__init__.py, samcli/local/common/runtime_template.py, samcli/local/init/__init__.py
- `sam init -r node -d npm` now yeilds a sam template with `nodejs10.x` as
runtime instead of `nodejs`
https://github.com/awslabs/aws-sam-cli/issues/1251
=> fix: default to nodejs10.x on init

samcli/local/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/src/HelloWorld/Function.cs, samcli/local/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/test/HelloWorld.Test/FunctionTest.cs
Cleaning up the project template created from `sam init` to be more .NET idiomatic
*Checklist:*
=> Update the .NET Core project template

tests/unit/commands/local/lib/swagger/test_reader.py, tests/unit/commands/local/lib/test_sam_api_provider.py, tests/unit/lib/build_module/test_app_builder.py, tests/unit/lib/telemetry/test_metrics.py, tests/unit/lib/utils/test_codeuri.py, tests/unit/local/docker/test_lambda_build_container.py, tests/unit/local/lambdafn/test_zip.py, tests/unit/local/layers/test_download_layers.py
first pass at getting unit tests to pass on windows (with Appveyor)
=> fix: fix unit tests so that they pass on windows

samcli/cli/command.py, tests/integration/deprecation/test_deprecation_warning.py
- if AWS SAM CLI is installed under python2.7 environment, there is a
warning which says that AWS SAM CLI will no longer be installable
under python2.7 from October 1st 2019.
* https://github.com/awslabs/aws-sam-cli/issues/1273
*Checklist:*
=> warning: deprecation warning message - Python 2.7

samcli/local/docker/lambda_build_container.py, tests/unit/local/docker/test_lambda_build_container.py
=> Fetch amazon/lambda-build-nodejs10.x build image

samcli/cli/global_config.py, tests/unit/cli/test_global_config.py
*Issue #, if available:* Resolves #1313
*Description of changes:* Handle OSError when creating the config directory.
*Checklist:* make pr passing
=> Add OSError Handler to GlobalConfig

samcli/cli/command.py, samcli/commands/init/__init__.py
- fix init so that it displays short help content
- display commands in lifecycle order
```
~/aws_sam_cli_WS/aws-sam-cli❯ sam --help                                                                                              
Usage: sam [OPTIONS] COMMAND [ARGS]...
AWS Serverless Application Model (SAM) CLI
The AWS Serverless Application Model extends AWS CloudFormation to provide
a simplified way of defining the Amazon API Gateway APIs, AWS Lambda
functions, and Amazon DynamoDB tables needed by your serverless
application. You can find more in-depth guide about the SAM specification
here: https://github.com/awslabs/serverless-application-model.
Options:
--debug    Turn on debug logging to print debug message generated by SAM
CLI.
--version  Show the version and exit.
--info
--help …
```
=> fix: sam commands in lifecycle app order in help command

samcli/commands/build/command.py
For compatibility with Windows. relpath() fails when the specified path is on a different drive.
*Issue #, if available:* #1336
*Description of changes:* use abspath() instead of relpath(), so cli command succeeds even when running on windows where sam and build_dir/template are located on different drive.
*Checklist:*
=> Try relpath first, if failed use the user specified path

samcli/yamlhelper.py, tests/unit/test_yamlhelper.py
#1354
Ported over the changes that have made it into the AWS CLI YamlHelper so we should have parity with SAM and the AWS CLI.
*Checklist:*
https://github.com/awslabs/aws-sam-cli/issues/1354
=> updates to yamlhelper and related tests

samcli/commands/build/build_context.py, samcli/commands/build/command.py, samcli/commands/build/exceptions.py, tests/unit/commands/buildcmd/test_build_context.py
=> fix(build): Disallow --build-dir to resolve to cwd

Makefile, samcli/lib/intrinsic_resolver/intrinsic_property_resolver.py, tests/smoke/templates/sar/getatt-custom-resource.yaml, tests/smoke/templates/sar/vpc-import-value.yaml, tests/unit/lib/intrinsic_resolver/test_intrinsic_resolver.py
#1386 #1408 #1407 
I described the issue here: https://github.com/awslabs/aws-sam-cli/issues/1386#issuecomment-530966456
Previously, when we encountered an intrinsic we could not resolve, the exception was thrown up to the resource level and we set the original resource into the modified (in memory) template we use for the commands. Instead, this change will only set that property back into the dictionary allowing any intrinsics we can resolve to remain resolved.
*Checklist:*
=> fix(intrinsics): Attempt to resolve all intrinsics but leave untouched in failure

tests/integration/buildcmd/build_integ_base.py, tests/integration/deprecation/test_deprecation_warning.py, tests/integration/local/start_lambda/start_lambda_api_integ_base.py, tests/integration/local/start_lambda/test_start_lambda.py
=> chore: black format tests

tests/integration/buildcmd/test_build_cmd.py, tests/integration/testdata/buildcmd/Ruby/Gemfile
The `httparty` gem has native extensions, and can fail to build on Windows, which is causing integ test failures. Changed to a new gem which should be much more platform-agnostic to build.
*Checklist:*
=> Fix Ruby Integ Test

samcli/cli/command.py
https://github.com/awslabs/aws-sam-cli/issues/1273
Change message from warning to deprecation notice.
*Checklist:*
=> fix: py2 warning message to be deprecated instead

requirements/isolated.txt, samcli/commands/build/command.py, samcli/commands/init/__init__.py, samcli/commands/local/invoke/cli.py, samcli/commands/local/start_api/cli.py, samcli/commands/local/start_lambda/cli.py, samcli/commands/logs/command.py, samcli/commands/publish/command.py, samcli/commands/validate/validate.py, tests/unit/commands/buildcmd/test_command.py, tests/unit/commands/init/test_cli.py, tests/unit/commands/local/invoke/test_cli.py, tests/unit/commands/local/start_api/test_cli.py, tests/unit/commands/local/start_lambda/test_cli.py, tests/unit/commands/logs/test_command.py, tests/unit/commands/publish/test_command.py, tests/unit/commands/validate/test_cli.py
N/A
`sam --help` is a very slow operation. Testing on my machine took about ~1.25s. Comparing this the `sam build --help`, help text was displayed in ~.7s. The main reason for this is due to how python loads modules and click. In order for click to know the help text of each command, click calls `list_commands` and then `get_command` for each command in the list. Our `get_command` implementation will then import the command module and return the `cli` method. This means a `sam --help` will end up loading the entire `samcli` module (or very close to it), while `sam build --help` will only load the 'build' related modules. 
This PR moves, most, of the command module loading from the global package/module scope (file), to specific methods. …
=> feat(perf): Improve load time of help text

appveyor.yml, requirements/dev.txt, tests/integration/local/invoke/runtimes/test_with_runtime_zips.py, tests/integration/local/invoke/test_integrations_cli.py, tests/integration/local/start_api/test_start_api.py, tests/integration/local/start_lambda/test_start_lambda.py, tests/integration/testdata/invoke/layers/layer-template.yml, tests/integration/testdata/invoke/template.yml, tests/integration/testdata/start_api/cdk-sample-output.yaml, tests/integration/testdata/start_api/methods-resources-api-template.yaml, tests/integration/testdata/start_api/serverless-sample-output.yaml, tests/integration/testdata/start_api/swagger-rest-api-template.yaml, tests/integration/testdata/start_api/swagger-template.yaml, tests/integration/testdata/start_api/template.yaml
- cause the builds to fail on appveyor rather than halting the test
forever, resulting in a lengthy build timeout.
- had to play around with requirements to be able to adopt `pytest-timeout`, also do we need `tox`?
*Checklist:*
=> fix: add timeouts on docker local-invoke, start-api and start-lambda integration tests

requirements/dev.txt, samcli/lib/intrinsic_resolver/intrinsic_property_resolver.py, tests/integration/local/start_api/test_start_api.py, tests/integration/testdata/start_api/swagger.yaml, tests/integration/testdata/start_api/template-with-included-swagger.yaml, tests/unit/lib/intrinsic_resolver/test_intrinsic_resolver.py
#1418 and possibly all of #1427 (haven't tested with that yet)
`Fn::Transform` with `AWS::Include` allows for inlining data that is found in a separate file. The current implementation only took the value from the `Parameter.Location`, which is breaks `start-api`. This PR will take the value of `Parameter.Location` and try to load the local file and return that as the value of the `Fn::Transform`. If the file is not a valid local file, the `Fn::Transform` is left alone (say if the value is an s3 Uri). Our other code paths already handle these cases, so no special logic is needed, but we can expand this in the future to do all the right things.
*Checklist:*
By submitting this pull request, I confirm that my contribution is made under the …
=> fix: Inline data that was defined with AWS::Include

samcli/commands/local/lib/generated_sample_events/events/cloudwatch/ScheduledEvent.json
n/a
The account id in the generated event was empty. Before:
```
{
"id": "cdc73f9d-aea9-11e3-9d5a-835b769c0d9c",
"detail-type": "Scheduled Event",
"source": "aws.events",
"account": "",
"time": "1970-01-01T00:00:00Z",
"region": "us-east-1",
"resources": [
"arn:aws:events:us-east-1:123456789012:rule/ExampleRule"
],
"detail": {}
}
```
After:
```
{
"id": "cdc73f9d-aea9-11e3-9d5a-835b769c0d9c",
"detail-type": "Scheduled Event",
"source": "aws.events",
"account": "123456789012",
"time": "1970-01-01T00:00:00Z",
"region": "us-east-1",
"resources": [
"arn:aws:events:us-east-1:123456789012:rule/ExampleRule"
],
"detail": {}
}
```
*Checklist:*
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> Fixes empty account id in CloudWatch Scheduled Event

samcli/commands/local/lib/generated_sample_events/event-mapping.json, samcli/commands/local/lib/generated_sample_events/events/sagemaker/AnnotationConsolidation.json, samcli/commands/local/lib/generated_sample_events/events/sagemaker/PreHumanTask.json
Adds events for Lambda functions for SageMaker Ground Truth for these Lambda functions in the [CreateLabelingJob operation](https://docs.aws.amazon.com/sagemaker/latest/dg/API_CreateLabelingJob.html):
1. PreHumanTask
2. AnnotationConsolidation
*Checklist:*
- [n/a] Write Design Document ([Do I need to write a design document?](https://github.com/awslabs/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.rst#design-document))
- [n/a] Write unit tests
- [n/a] Write/update functional tests
- [n/a] Write/update integration tests
- [n/a] Write documentation
=> Adds SageMaker Ground Truth Lambda events

samcli/commands/init/__init__.py
=> Add HELP_TEXT for init command

requirements/base.txt, samcli/commands/init/__init__.py, samcli/commands/init/init_generator.py, samcli/commands/init/init_templates.py, samcli/commands/init/interactive_init_flow.py, samcli/local/common/runtime_template.py, tests/unit/commands/init/test_cli.py, tests/unit/commands/init/test_templates.py
=> Init User Flow Rework

requirements/base.txt, samcli/commands/local/lib/sam_function_provider.py, samcli/local/lambdafn/config.py, tests/unit/commands/local/lib/test_sam_function_provider.py, tests/unit/local/lambdafn/test_config.py
=> fix: Move validation of timeout is an int further down the stack

samcli/local/lambdafn/config.py
=> chore: Simplify how timeouts are casted to an int

designs/sam-app-config.md, designs/sam-config.md, docs/sam-config-docs.md
- a configuration that provides parameter pass throughs for
sam cli commands
=> design: samconfig

appveyor-windows-build-java-container.yml, appveyor-windows-build-java-inprocess.yml, appveyor-windows-build-ruby.yml, tests/integration/buildcmd/test_build_cmd.py
Split java and ruby builds into two functions, one for in process and one for container.
When running java builds on Windows Server 2019, the in process builds where hanging,
reason is known. Splitting the tests allows us to run the container builds on
Windows Server 2019, which is required due to needing docker that spins up a linux
instance. We can then run in-process builds in Visual Studio images, which works for java.
This commit will also update the ruby builds on windows but instead of running both in process
and container builds, we will only run container builds. When running ruby in-process builds
on Visual Studio images, we still see failures (which is assumed to be the same as when they
are run on Windows Server 2019 which is an ssl issue). This will at least allow us to …
=> chore: fix java build and ruby appveyor builds

requirements/base.txt, requirements/isolated.txt, samcli/cli/cli_config_file.py, samcli/cli/types.py, samcli/commands/_utils/options.py, samcli/commands/build/command.py, samcli/commands/deploy/command.py, samcli/commands/init/__init__.py, samcli/commands/local/generate_event/event_generation.py, samcli/commands/local/invoke/cli.py, samcli/commands/local/start_api/cli.py, samcli/commands/local/start_lambda/cli.py, samcli/commands/logs/command.py, samcli/commands/package/__init__.py, samcli/commands/package/command.py, samcli/commands/publish/command.py, samcli/commands/validate/validate.py, tests/unit/cli/test_cli_config_file.py, tests/unit/cli/test_types.py, tests/unit/commands/_utils/test_options.py, tests/unit/commands/local/generate_event/test_event_generation.py
- add passthroughs to the CLI command line interface via a configuration
file
- local defaults are set at: `samconfig.toml` at project root.
- This commit contains code copied and modified from https://github.com/phha/click_config_file/blob/master/click_config_file.py under MIT license
- Design doc PR is separate: https://github.com/awslabs/aws-sam-cli/pull/1503
=> feat: configuration file for sam cli commands

.pylintrc, samcli/cli/types.py, samcli/commands/_utils/options.py, samcli/commands/deploy/command.py, samcli/commands/package/command.py, samcli/commands/package/exceptions.py, samcli/commands/package/package_context.py, samcli/lib/package/artifact_exporter.py, samcli/lib/package/s3_uploader.py, tests/unit/commands/deploy/test_command.py, tests/unit/lib/package/test_s3_uploader.py
- if the template is left unspecified, built artifacts are chosen and s3 bucket is optionally needed to deploy in one command.
- existing workflows to package and deploy do not break.
=> Package and deploy in one command

samcli/commands/_utils/table_print.py, samcli/lib/deploy/deployer.py, samcli/lib/deploy/utils.py
Tried using `Colored` within samcli/lib/utils/colors. was messing up formatting.
Need to migrate table_print.py to using Colored.
=> Colors for deploy

samcli/commands/package/exceptions.py, samcli/lib/package/s3_uploader.py, tests/unit/lib/package/test_s3_uploader.py
=> fix: deploy error on not supplying s3 bucket

samcli/cli/main.py, samcli/lib/utils/sam_logging.py, tests/unit/lib/utils/test_sam_logging.py
=> fix: override botocore logging to a NullHandler

requirements/base.txt, requirements/isolated.txt, samcli/cli/cli_config_file.py, samcli/cli/context.py, samcli/commands/_utils/options.py, samcli/commands/_utils/template.py, samcli/commands/deploy/command.py, samcli/commands/deploy/deploy_context.py, samcli/commands/deploy/exceptions.py, samcli/commands/local/generate_event/event_generation.py, samcli/lib/bootstrap/bootstrap.py, samcli/lib/config/samconfig.py, samcli/lib/deploy/deployer.py, tests/unit/cli/test_cli_config_file.py, tests/unit/commands/_utils/test_options.py, tests/unit/commands/_utils/test_template.py, tests/unit/commands/deploy/test_command.py, tests/unit/commands/deploy/test_deploy_context.py, tests/unit/lib/config/test_samconfig.py
`sam deploy -i` now provides an interactive guided deployment experience. 
Remaining:
**Screenshot**
=> feat: Guided interactive deployment

samcli/lib/deploy/deployer.py
=> fix: stack outputs on deploy

samcli/commands/deploy/command.py, tests/unit/commands/deploy/test_command.py
=> fix: always showcase deploy args

samcli/commands/deploy/command.py, samcli/lib/bootstrap/bootstrap.py, tests/unit/commands/deploy/test_command.py
Dont save noecho params to config file via guided deploy
=> fix: parameter override prompts during guided deploy

samcli/commands/deploy/deploy_context.py, samcli/commands/package/exceptions.py, tests/unit/lib/package/test_s3_uploader.py
=> fix: usability fixes on deploy error with no s3 bucket

samcli/commands/exceptions.py, samcli/lib/bootstrap/bootstrap.py, tests/unit/lib/bootstrap/test_bootstrap.py
=> Add Exception Handling for Client Misconfiguration

samcli/commands/deploy/exceptions.py, samcli/lib/deploy/deployer.py, tests/unit/lib/deploy/test_deployer.py
- deployment s3 bucket is specific to the region it was created in.
cfn/lambda requires code to be packaged within the same region as
where the stack is to be deployed. When such a case is encountered
prompt to use `sam deploy --guided`
*Checklist:*
=> fix: helpful error message when deploy happens across regions

samcli/local/docker/container.py, tests/unit/local/docker/test_container.py
When attaching to a docker container, specify logs=True in order to
receive the output the container has generated prior to it being
attached.
Related to #1551
PR #1552 switched to using Docker API for attaching to containers. However, it is invoked with `logs=False` so that only the output generated by the container after attaching is collected. This means that some initial output may get lost.
Specify `logs=True` when attaching to a container to ensure the complete output is collected.
*Checklist:*
=> fix: collect prior output from attached containers

samcli/commands/deploy/command.py, samcli/commands/deploy/deploy_context.py, samcli/lib/package/s3_uploader.py, tests/integration/deploy/deploy_integ_base.py, tests/integration/deploy/test_deploy_command.py, tests/regression/deploy/test_deploy_regression.py
- integration tests for `sam deploy` and `sam deploy --guided`
- fix for regression tests
- `stack-name` is required
- additional error cases for when a s3 bucket is needed to be looked up
during `sam deploy`
- move parameter prompts logic to its own function
*Checklist:*
=> tests: integration tests for `sam deploy`

samcli/commands/_utils/options.py, samcli/commands/deploy/command.py, samcli/lib/bootstrap/bootstrap.py, samcli/lib/deploy/deployer.py, samcli/lib/package/s3_uploader.py, tests/integration/deploy/test_deploy_command.py, tests/unit/cli/test_cli_config_file.py, tests/unit/commands/_utils/test_options.py, tests/unit/commands/deploy/test_command.py, tests/unit/lib/bootstrap/test_bootstrap.py, tests/unit/lib/deploy/test_deployer.py
- providing non standard capabilities gives an appropriate error message
- add s3 prefix to be the stack name during guided deploy
*Checklist:*
=> bugfixes: `stack-name` is required on deploy

samcli/cli/cli_config_file.py, samcli/commands/exceptions.py, samcli/lib/config/exceptions.py, samcli/lib/config/samconfig.py, samcli/lib/config/version.py, tests/unit/cli/test_cli_config_file.py, tests/unit/commands/deploy/test_command.py, tests/unit/lib/samconfig/test_samconfig.py
- support version key, any float is okay.
- if a config file is present and the version key is missing, we do not
process it.
- if a config file is missing, thats fine. this check does not get in
the way.
- validation logic to determine if a SAM CLI version is compatible can
be written later.
*Checklist:*
=> fix: add version to `samconfig.toml` file

tests/integration/deploy/test_deploy_command.py, tests/regression/deploy/test_deploy_regression.py
- add sleeps in between deploy integration and regression tests.
*Checklist:*
=> integ tests: throttling with cloudformation

samcli/commands/bootstrap/exceptions.py, samcli/commands/deploy/command.py
=> fix: samconfig.toml links in `sam deploy --guided`

appveyor-windows.yml, appveyor.yml, tests/integration/buildcmd/test_build_cmd.py, tests/integration/local/invoke/test_integrations_cli.py
=> Move to using communicate with a timeout for integ tests

tests/integration/deploy/test_deploy_command.py, tests/integration/init/test_init_command.py, tests/integration/local/generate_event/test_cli_integ.py, tests/integration/local/invoke/runtimes/test_with_runtime_zips.py, tests/integration/local/invoke/test_integrations_cli.py, tests/integration/package/test_package_command.py, tests/integration/publish/test_command_integ.py, tests/integration/telemetry/test_installed_metric.py, tests/integration/telemetry/test_prompt.py, tests/integration/telemetry/test_telemetry_contract.py, tests/regression/deploy/regression_deploy_base.py, tests/regression/deploy/test_deploy_regression.py, tests/regression/package/regression_package_base.py, tests/regression/package/test_package_regression.py
=> refactor: move all process.wait to process.communicate

samcli/commands/deploy/command.py, samcli/commands/init/init_generator.py, samcli/lib/utils/osutils.py, samcli/lib/utils/temp_file_utils.py, samcli/local/init/__init__.py, samcli/local/init/arbitrary_project.py, samcli/local/init/exceptions.py, tests/integration/init/test_init_command.py, tests/unit/lib/utils/test_file_utils.py, tests/unit/local/init/test_arbitrary_project.py, tests/unit/local/init/test_init.py
=> feat: Initialize a project from non-cookiecutter github repo or zip file

samcli/commands/_utils/options.py
I found typo : `–guided` option.
`--guided` is correct.
- https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-deploy.html
```sh
$ sam --version
SAM CLI, version 0.33.1
$ sam deploy
Usage: sam deploy [OPTIONS]
Try "sam deploy --help" for help.
Error: Missing option '--stack-name', 'sam deploy –guided' can be used to provide and save needed parameters for future deploys.
```
*Checklist:*
I understand it 👍
>By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
Thanks.
=> Fixed typo of "sam deploy" option

samcli/lib/deploy/deployer.py, tests/unit/lib/deploy/test_deployer.py
#1610 
- Do not exit after exhausting retries.
*Checklist:*
=> fix: do not exit after throttling retries have been exhausted

samcli/commands/deploy/command.py
*Description of changes:* Typos (especially line breaks) on the sam deploy documentation.
*Checklist:*
=> fixing typos on sam deploy documentation

samcli/commands/deploy/command.py, samcli/local/services/base_local_service.py, tests/unit/local/services/test_base_local_service.py
*Issue 1458:*
*Description of changes:* During `sam local start-api` we expect container to return response. We then parse this response with some caveat explained [here](https://github.com/awslabs/aws-sam-cli/blob/develop/samcli/local/services/base_local_service.py#L151-L155) and expect a particular set of keys. Due to recent changes in lambda one of the key was removed from the response. The key removed was `stackTrace`, we rely on this key to add `FunctionError` in our response to client. Since the key was removed we need to handle the scenario so that we don't loose the information of function error.
*Checklist:*
=> Fix for stackTrace not returned in new Lambda containers.

appveyor-windows-build-python.yml, appveyor-windows-build-ruby.yml
N/A
Ruby and Python installed through choco needs 1.3.3 or choco installs fail.
*Checklist:*
=> fix(ci): force chocolatey-core.extension 1.3.3

samcli/commands/local/lib/provider.py, samcli/commands/local/lib/sam_api_provider.py, tests/unit/commands/local/lib/test_sam_api_provider.py
WIP - Fix for: https://github.com/awslabs/aws-sam-cli/issues/1645
**Description of changes:**
- Updated code to parse the AllowCredentials out of the API resource.
**Notes**
- I don't have time to go through and add/update any further unit tests or integration tests. I just wanted to throw this out here as a starting point.
=> Set the CORS "Access-Control-Allow-Credentials" for local running

samcli/local/docker/lambda_debug_settings.py, tests/unit/lib/bootstrap/test_bootstrap.py
To support debugging for Nodejs10.x and Nodejs12.x, SAM CLI overrides
the entrypoint to the container. In newer runtimes (that are based
on the provided runtime), we overrided the bootstrap file which can
have side-effects. In the case of Nodejs, the bootstrap file adds
the NODE_PATH env var. Since we override this, NODE_PATH does not
get setup on the system and causes modules to not load (in some
cases, #1246). With #1634 (Java11 Debug support), we added a
capability to attach Env Vars into the container for debug mode
invokes. We will use this to apply the NODE_PATH onto the container
for debug.
I attempted to move all the args we pass into NODE_OPTIONS, which would
make Nodejs work like Java11 for debug. That is, allow us not to override
the entrypoint and still be able to apply the …
=> fix(debug): Add NODE_PATH env var when debugging Node10/12

tests/integration/init/schemas/test_init_with_schemas_command.py
These tests probably could use a refactor so that we can look up input values by ID rather than a positional number.
=> Use Correct Runtime "Positions" For Integ Tests

tests/integration/testdata/package/aws-serverless-inline.yaml
=> Removes API Event from Inline Test

appveyor.yml, requirements/base.txt, samcli/settings/__init__.py, setup.py, tests/unit/local/apigw/test_local_apigw_service.py, tests/unit/local/lambda_service/test_local_lambda_invoke_service.py
=> chore: Run make pr on Python3.8

samcli/commands/deploy/command.py, samcli/commands/deploy/deploy_context.py, samcli/commands/deploy/guided_config.py, samcli/commands/deploy/guided_context.py, samcli/commands/deploy/utils.py, samcli/commands/package/package_context.py, samcli/lib/utils/botoconfig.py, tests/unit/commands/deploy/test_command.py, tests/unit/commands/samconfig/test_samconfig.py
* This change is necessary to address overall tech debt introduced by lumping all functions into one `command.py` file which handled both interactive and non-interactive modes when  `sam deploy` was used.
* Fix for https://github.com/awslabs/aws-sam-cli/issues/1652
* Previously user agent used to be passed via `AWS_EXECUTION_ENV`, Moving away from AWS CLI regressed that functionality.
* Interactive prompts and their lifecycles during the guided deploy phase are moved to its own class, and the results of the prompts are then used to start the package-deploy process with all the parameters that were gathered. This removes tight coupling and allows for guided prompts to be changed independently.
* Dealing with configuration files …
=> refactor: `sam deploy`

samcli/commands/init/init_templates.py, samcli/lib/utils/osutils.py
* sam init clones from a git repository called aws-sam-cli-app-templates, but when attempting to reclone, removal of the old directory becomes problematic due to the read-only nature of the `.git` files that get downloaded and results in a traceback.
* If a given file is not able to be deleted due to permission issues, write permissions are added to the file in question and deleted.
* None, the previous side-effects of leaving behind .git objects will be addressed.
=> fix: change permissions and remove files on rmtree

designs/botocore_sessions.md, samcli/cli/context.py, samcli/commands/deploy/deploy_context.py, samcli/commands/package/package_context.py, samcli/lib/bootstrap/bootstrap.py, tests/unit/lib/bootstrap/test_bootstrap.py
* This change is necessary to address MFA usecases when caching of credentials is essential. There have been multiple reports in github issues: [1682](https://github.com/awslabs/aws-sam-cli/issues/1682), [1623](https://github.com/awslabs/aws-sam-cli/issues/1623)
* Use botocore's native json file cache manager.
* Sessions are managed at the cli context level and not anywhere else.
TODO?
* Need to check entire codebase for session management.
Depends on:
* https://github.com/awslabs/aws-sam-cli/pull/1681
=> fix: botocore sessions across samcli

samcli/commands/package/package_context.py
Appveyor gates are failing on linting.
Ran against black on ubuntu docker machine to reproduce the issue, turns out be an extra comma. This is however not caught locally running against black on mac os x.
None
*Checklist:*
=> fix: linting

samcli/commands/deploy/command.py
Ugly break points when reading the --help
Added some missing trailing spaces
None
*Checklist:*
=> deploy command help improvements

designs/botocore_sessions.md, samcli/cli/context.py, samcli/commands/deploy/deploy_context.py, samcli/commands/package/package_context.py, samcli/lib/bootstrap/bootstrap.py, tests/unit/cli/test_context.py, tests/unit/lib/bootstrap/test_bootstrap.py, tests/unit/lib/build_module/test_app_builder.py
https://github.com/awslabs/aws-sam-cli/issues/1682
SAM CLI does not cache MFA based credentials and asks for them each time as the credentials are not cached.
MFA based credentials are cached at ~/.aws/boto/cache
* Only one prompt for MFA based authentication, and if the MFA code is successful, only one prompt till the credentials that were retrieved expire.
=> fix: cache MFA based credentials

samcli/lib/package/artifact_exporter.py, tests/unit/lib/package/test_artifact_exporter.py
*Issue #, if available:* #1706
The `sam package` command does not read any global values over the course of packaging - traditionally, only build and deploy functionality would use any values. Issue #1706 points to an uncommon use case that exposes that some global values do need to be considered, at minimum so that package won't break deploy.
Creates an `apply_global_values` method that fetches global values we use (currently just the one) and applies them if/when they are applicable.
None
*Checklist:*
- [N/A] Write Design Document ([Do I need to write a design document?](https://github.com/awslabs/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.rst#design-document))
By submitting this …
=> fix: Handle global value for Function CodeUri in Package

requirements/base.txt, requirements/isolated.txt
=> chore: version bump on aws-lambda-builders to 0.7.0

samcli/commands/deploy/deploy_context.py, samcli/commands/package/package_context.py, samcli/lib/utils/botoconfig.py
* The change allows for adding sam cli version and installation id if
telemetry is on during aws services calls.
* None
*Checklist:*
=> feat: boto user agent string for package and deploy

samcli/commands/_utils/options.py
* deploy command has a `--template-file` option but does not say that
the template specified to it needs to contain built artifacts.
* The help text makes it explicit that the template specified to the
`--template-file` option in `sam deploy` needs to contain built
artifacts for the resources specified in the template, if applicable.
* None
*Checklist:*
=> fix: deploy help text for `--template-file` option.

appveyor-windows-build-dotnet.yml, appveyor-windows-build-go.yml, appveyor-windows-build-java-container.yml, appveyor-windows-build-java-ruby-inprocess.yml, appveyor-windows-build-nodejs.yml, appveyor-windows-build-python.yml, appveyor-windows-build-ruby.yml, appveyor-windows.yml
* With release v0.41.0 - MSIs have version 3.7.6 as their base version.
Appveyor testing needs to reflect that.
* Appveyor test frameworks are now using python 3.7.6. The environment
variables are set according to: https://www.appveyor.com/docs/windows-images-software/
* None
*Checklist:*
=> fix: appveyor windows job - python version

samcli/lib/bootstrap/bootstrap.py
Solves #1696, where creating the managed stack in any partition but aws
will fail.
#1696
Managed stack SAM CLI creates is not deploy-able in partitions outside of 'aws'. 
Parameterizes the Partition in the manage stack
None
*Checklist:*
=> fix(deploy): Allow all Partitions for S3 Policy on managed stack

samcli/lib/intrinsic_resolver/intrinsics_symbol_table.py, tests/integration/local/invoke/test_integrations_cli.py, tests/integration/testdata/invoke/template.yml, tests/unit/lib/intrinsic_resolver/test_intrinsics_symbol_table.py
#1476
When a Parameter is an empty string, we select the name of the Parameter instead of the value during intrinsic resolving. This is unexpected to customers when they want the value to be an empty string.
Fixes and allows Empty Strings for Parameters to be resolved correctly.
I don't believe so.
*Checklist:*
=> fix: Handle the case for Parameters being empty strings

samcli/commands/_utils/table_print.py, samcli/lib/deploy/deployer.py
* easier to grok the outputs from the deployed stack
* (Key, Description, Value) are new line separated to provide a clean
interface.
* Change stack outputs colors to green as they indicate a successfully
deployed stack.
*Preview*
https://github.com/awslabs/aws-sam-cli/issues/1659
* Hard to copy/paste outputs
* All output value start from a minimal offset so that they have enough width to showcase without breaks.
* A potentially super long output value could still flow over to the next line.
*Checklist:*
=> ux: improve deploy outputs text

tests/integration/init/schemas/schemas_test_data_setup.py, tests/unit/lib/schemas/test_schemas_api_caller.py
*Issue* : Fixes #1777 
Fixes deprecation warnings in Python 3.7+
Uses raw strings for the fix.
*Checklist:*
=> Fix deprecation warnings due to invalid escape sequences.

samcli/cli/cli_config_file.py, tests/unit/cli/test_cli_config_file.py
* This change is necessary because there was code that allowed for using
non default config prefixes, even though an attempt was made to hide
them.
* Irrespective of the configuration prefix passed in to the hidden
option, a default config prefix is always chosen.
* Users who had subscribed and started using an unsupported option will
be affected.
*Checklist:*
=> fix: config env cannot be other than default

samcli/lib/deploy/deployer.py, tests/unit/lib/deploy/test_deployer.py
* bug from previous PR which always looked for outputs in deployed
templates.
* Explicitly check for outputs, before attempting to display them.
* Added extra tests to verify so that it does not cause regressions in
the future.
* None.
*Checklist:*
=> fix: display no outputs if outputs are not defined.

samcli/lib/deploy/deployer.py, tests/unit/lib/deploy/test_deployer.py
This PR improves `sam deploy` inefficient log fetching. Current implementation fetches events repeatidly until deploy finished. And it fetches "all" log events for every fetches. It includes already shown events and old events before the current deployment starts.
So, when we update a stack in many times, sam-cli event showing becomes quite slow. And it takes a little bit longer time after actual stack deployment finished.
The PR implementation skip older events and prevent to fetch all, old events.
I guess almost nothing. Maybe the number of API calls increases because it does not fetch all old events.
*Checklist:*
By submitting this pull request, I confirm that my contribution is …
=> Efficient deploy log fetching

tests/integration/deploy/test_deploy_command.py, tests/integration/init/schemas/test_init_with_schemas_command.py, tests/integration/local/invoke/test_integrations_cli.py, tests/integration/package/test_package_command.py, tests/integration/publish/test_command_integ.py, tests/regression/deploy/test_deploy_regression.py, tests/regression/package/test_package_regression.py, tests/testing_utils.py
Working on creating Canary to run all integration tests in secure environment. This code change disable skipping test if tests are triggered by Canary.
Canary Trigger will setup an environment variable which will be monitored by tests. If detected then this will disable skipping tests.
None
*Checklist:*
=> test: run by canary

designs/md5_checksums_package_deploy.md, requirements/base.txt, requirements/isolated.txt, samcli/lib/package/artifact_exporter.py, samcli/lib/package/s3_uploader.py, samcli/lib/utils/hash.py, tests/integration/deploy/deploy_integ_base.py, tests/integration/deploy/test_deploy_command.py, tests/integration/testdata/package/main.py, tests/unit/lib/package/test_artifact_exporter.py, tests/unit/lib/package/test_s3_uploader.py, tests/unit/lib/utils/test_hash.py
* sam deploy of the same built artifacts can result in new uploads to s3
during the package step.
* Hash of the directory is constructed rather than on the packaged zip
file.
* Potentially None
*Checklist:*
=> fix: packaging of built artifacts

tests/integration/testdata/package/aws-serverless-function.yaml
* python3.6 runtime was not present in the default test environment.
* change runtime to be `python3.7`
* None
*Checklist:*
=> fix: `aws-serverless-function` template to have python3.7 runtime

tests/regression/package/test_package_regression.py
In a recent change #1789, we updated how we hash local code for package to allow only packaging resources that have changed. We have regression tests that validate package and deploy are the same as AWS CLI. With the change, we are purposefully deviating from AWS CLI's implementation to provide a better experience and therefore need to update our regression tests. We are removing only the package regression tests that are failing due to our known difference in hashing.
N/A
Regressions tests are failing on master for a change that will cause a 'regression' between us and AWS CLI.
Removes the test that are known to be caused by the change.
None
The follow …
=> fix(test): Remove package regression tests

samcli/lib/build/workflow_config.py, samcli/lib/init/templates/cookiecutter-aws-sam-hello-ruby/{{cookiecutter.project_name}}/template.yaml, samcli/local/common/runtime_template.py, samcli/local/docker/lambda_image.py, tests/integration/buildcmd/test_build_cmd.py
* To support ruby2.7 runtime in AWS SAM CLI.
* `sam init`, `sam build` , `sam local` are all supported for ruby2.7
* None
*Checklist:*
=> feat: ruby2.7 support in AWS SAM CLI

samcli/commands/init/init_templates.py
We are creating folder with permission in Hex format, however we should be using octal format.
*Checklist:*
=> fix: config_dir creation permission. Hex permissions were used instead of octal.

appveyor.yml, tests/integration/package/package_integ_base.py, tests/integration/publish/publish_app_integ_base.py, tests/regression/package/regression_package_base.py, tests/testing_utils.py
Our integration tests use S3 bucket to run several tests. Given that S3 objects are eventually consistent and we are using same bucket for lot of integration tests, we want to have multiple buckets to reduce transient failures. This change will allow referring correct bucket based on the python version for which test is running.
This spreads total number of objects across several buckets and improving sync time to reduce time it takes by S3 to be consistent.
NA
*Checklist:*
=> feat: adding separate bucket based on python version for integration tests.

tests/integration/init/schemas/schemas_test_data_setup.py
Event bridge integration tests do no respect session token to run secure tests. This code change fixes that.
Using session token if present.
*Checklist:*
=> fix: bug around using temporary credentials in event bridge integration test.

tests/integration/deploy/test_deploy_command.py
Our Deploy integration tests sometimes fail without any log message or CFN stack id. This change is extracting some code out around command execution and adding some logging which will be displayed when tests fail.
*Checklist:*
=> refactor: deploy integration tests to use same level of logging.

tests/integration/deploy/test_deploy_command.py
While refactoring I added `tag` field to put it in log, but removed it later as it wasn't useful. This PR is to finish that remove as it remained at few places.
*Checklist:*
=> fix: bug introduced in deploy integ test refactoring.

requirements/base.txt
In version 0.9.4 of jmespath in Python3.8, there was SyntaxErrors getting reported to the console. In version of jmespath 0.9.5, this was fixed. 
Upgrades the jmespath dependency to one that does not have SyntaxErrors in Python3.8
None.
*Checklist:*
=> chore: Upgrade jmespath to remove SyntaxError logs

requirements/base.txt
=> chore: Upgrade aws-lambda-builders to 0.8.0

pytest.ini, tests/integration/deploy/test_deploy_command.py, tests/integration/package/package_integ_base.py, tests/integration/publish/publish_app_integ_base.py
We often see NoSuchKey error when running integration tests when trying to use object uploaded to S3. For our integration tests we rarely change our objects.
This change will stop object deletion at the end of integration test, so that we have higher chance of successful integration test.
None
*Checklist:*
=> fix: removing object deletion and using same stack name for integration tests to avoid NoSuchKey errors.

appveyor-windows.yml
We have recently moved to using separate bucket for individual test run. This change is needed to make windows run compatible with that change.
*Checklist:*
=> fix: adding separate bucket env var to windows appveyor file.

tests/integration/buildcmd/test_build_cmd.py, tests/integration/deploy/test_deploy_command.py, tests/testing_utils.py
Refactoring buildcmd integ test to use same method which deploy uses and have better logging around failure and process run.
*Checklist:*
=> fix: buildcmd to use same level of logging as deploy integration tests.

samcli/local/apigw/local_apigw_service.py, tests/unit/local/apigw/test_local_apigw_service.py
Putting this in draft and will update with more details on Monday but wanted to send this out today to have appveyor run all the tests.
TLDR: In start-api, we would output 
```
LOG.error(
"Function returned an invalid response (must include one of: body, headers, multiValueHeaders or "
"statusCode in the response object). Response received: %s",
lambda_response,)
```
in cases that made it very difficult to debug my Api Gateway and function locally. For example, we would log the above when the mime type was incorrect. It took me putting SAM CLI into debug to figure out that was the cause of the "internal service error" on the Api.
#1770 and #1530 Seem to have the same symptom I saw. I think they are related but it is hard to tell given the issues. 
*Why is this …
=> fix(start-api): raise concrete exceptions during parsing of lambda output

samcli/commands/deploy/guided_context.py, tests/integration/deploy/test_deploy_command.py, tests/unit/commands/deploy/test_deploy_context.py, tests/unit/commands/deploy/test_guided_config.py, tests/unit/commands/deploy/test_guided_context.py
* Previously, the string was passed along which leads to a validation
failure.
* The default is now a list.
* None.
https://github.com/awslabs/aws-sam-cli/issues/1848
*Checklist:*
=> fix: default capabilities on guided mode to be a list

tests/integration/buildcmd/build_integ_base.py, tests/integration/buildcmd/test_build_cmd.py, tests/integration/deploy/test_deploy_command.py, tests/testing_utils.py
This change will print better logs, stderr and stdout around the command that fails when running `test_with_go` integration tests.
*Checklist:*
=> fix: adding better logging to build_integ_test base's run of Popen command

tests/integration/deploy/test_deploy_command.py
rebasing PR on github dashboard missed one method rename. Fixing it.
*Checklist:*
=> fix: renaming _run_command_with_input to run_command_with_input.

tests/integration/buildcmd/test_build_cmd.py, tests/integration/local/invoke/test_integrations_cli.py
Our current order of flaky and parameterized_expand annotation do not working for flaky annotation. This PR is changing order so that both annotations work.
In order to test this change I added a dummy test method with force failure and 2 parameters for expansion. [Here](https://paste.ubuntu.com/p/W2258k7gPm/) is output of test with our current order (flaky before parameter). [Here](https://paste.ubuntu.com/p/Rhvm3pk7dS/) is the output of test with new order (parameter before flaky).
In first run we only see two test runs one for each parameter, in second run we see 6 test runs one for each parameter rerun 3 times.
*Checklist:*
By submitting this pull …
=> fix: changing order of parameterized expand and flaky annotation.

samcli/lib/providers/sam_api_provider.py, tests/integration/local/start_api/test_start_api.py, tests/integration/testdata/start_api/template-with-unresolved-intrinsic-in-cors.yaml, tests/unit/commands/local/lib/test_sam_api_provider.py
#1432
This change allows for the Lambda behind an API to be reachable when SAM CLI fails to resolve an intrinsic function in the API Cors definition.
When reading the CORS configuration, we check to see if the value is a string that starts with `!` (indicating it is an intrinsics, !Ref for example) or anything but a string. This will then log a message to tell customers we are ignoring this property due to the intrinsic being unresolved.
No
*Checklist:*
=> fix: Log warning if there is unresolved intrinsics in cors

appveyor-windows-build-dotnet.yml, appveyor-windows-build-go.yml, appveyor-windows-build-java-container.yml, appveyor-windows-build-java-ruby-inprocess.yml, appveyor-windows-build-nodejs.yml, appveyor-windows-build-python.yml, appveyor-windows-build-ruby.yml, appveyor-windows.yml, appveyor.yml
Sometimes our Appveyor build jobs fail with exit status 1. This fix is recommended by Appveyor team in email and [here](https://help.appveyor.com/discussions/problems/25166-byoc-100-cpu-usage-in-bash-shellsh-and-random-exited-with-code-1).
*Checklist:*
=> fix: adding APPVEYOR_CONSOLE_DISABLE_PTY environment variable to fix random appveyor job failure.

samcli/local/services/base_local_service.py, tests/unit/local/services/test_base_local_service.py
*Issue #1404 *
When a Java thrown exception has a cause, the `start-lambda` runtime does not mark it as a failure. When it does not have a cause, it does.
Supports 4 property dicts as sent by Java.
Unknown?
*Checklist:*
=> Support 4 property errors for Java lambdas

samcli/commands/_utils/template.py, samcli/lib/build/app_builder.py, tests/integration/buildcmd/test_build_cmd.py, tests/integration/testdata/buildcmd/template.yaml, tests/unit/commands/_utils/test_template.py
#1839
Previous to this change, if there was a full s3 url (https://s3.amazon....) as a value of a property that could be a local file, we treated it as a local file and updated the template to `../../https://s3.amazon...`. This creates an invalid template for build causing customers needing to maunally edit the built template.
We now check if the value of the property starts with `http` or `https`.
No
*Checklist:*
=> fix(build): Do not treat urls as local paths

samcli/commands/deploy/command.py, tests/integration/deploy/test_deploy_command.py, tests/integration/package/package_integ_base.py
It is impossible to switch changeset confirmation off
=> add missing --no-confirm-changeset option

tests/integration/deploy/test_deploy_command.py
=> fix: usage of old method name '_run_command'

tests/integration/deploy/test_deploy_command.py
Missed a spot in previous fix commit. run_command is moved out of the class, hence self.run_command is failing.
And this time I tested in dev canary https://ci.appveyor.com/project/AWSSAMCLI/aws-sam-cli-canary-linux-dev
*Checklist:*
=> fix: usage for run_command method.

samcli/lib/providers/sam_function_provider.py, tests/integration/testdata/start_api/template.yaml, tests/unit/commands/local/lib/test_sam_function_provider.py
#1885 
When using start-api, FunctionName gets prioritized over the LogicalId. This was caused by a recent change of supporting invoking with a FunctionName instead of a LogicalId, which is not expected. 
We now first search for the LogicalId and if we don't find anything, we try the function name. This keeps local invoke working for both and for things like start-lambda and start-api, we can still reference by the logical id.
Not that I know of.
*Checklist:*
=> fix(start-api): Allow invoking when a function has a FunctionName

samcli/commands/local/lib/local_lambda.py, tests/integration/local/invoke/test_integrations_cli.py, tests/integration/local/start_lambda/start_lambda_api_integ_base.py, tests/integration/local/start_lambda/test_start_lambda.py, tests/integration/testdata/invoke/template.yml, tests/integration/testdata/invoke/vars.json
#1888
Due to some changes in #1215, we started to expect the Env Var file to be keyed off of the function name instead of the LogicalId. This only happened when you had defined a `FunctionName` in your template. When it the FunctionName wasn't defined, we define it to be the LogicalId. I added more integration tests to cover these cases. I did fine a bug in our integration tests as well, that would have caught the issue initially. In our `sam local invoke` integration tests, we test that we can override a functions Env Vars through the `--env-vars` flag. However, what was defined in the template and what was in the override were the same string. So our tests was just always passing without actually validating the key was the one …
=> fix: Use LogicalId for Env Vars fetching within the Env Var file

appveyor-windows-build-dotnet.yml, samcli/lib/build/workflow_config.py, samcli/lib/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/src/HelloWorld/HelloWorld.csproj, samcli/lib/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/template.yaml, samcli/lib/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/test/HelloWorld.Test/HelloWorld.Tests.csproj, samcli/local/common/runtime_template.py, samcli/local/docker/lambda_image.py, tests/integration/buildcmd/test_build_cmd.py, tests/integration/testdata/buildcmd/Dotnetcore3.1/HelloWorld.csproj, tests/integration/testdata/buildcmd/Dotnetcore3.1/Program.cs, tests/integration/testdata/buildcmd/Dotnetcore3.1/aws-lambda-tools-defaults.json
* Add support for init, build, local invoke on dotnetcore3.1 runtimes.
=> feat: dotnetcore3.1 support

samcli/commands/build/command.py, samcli/lib/build/app_builder.py, tests/unit/commands/buildcmd/test_command.py, tests/unit/lib/build_module/test_app_builder.py
* Telemetry does not capture correct level of detail today.
* Show the deeper cause of Exception and emit to Telemetry.
* None
*Checklist:*
=> fix: split BuildError - showcase deeper exception

samcli/cli/cli_config_file.py
* Make it abundantly clear that a config file is being looked for during
cli invocation.
* Removes obfuscation of the config file and the options with which SAM
CLI is being invoked with.
* There will always be a blurb printed to the console on "Samconfig",
irrespective of the command being used.
*Checklist:*
=> fix: logging for samconfig

samcli/local/lambdafn/zip.py, tests/integration/local/invoke/test_integrations_cli.py, tests/integration/local/start_lambda/test_start_lambda.py, tests/integration/testdata/invoke/main.py, tests/integration/testdata/invoke/template.yml, tests/unit/local/lambdafn/test_zip.py
This reverts commit 360d90aa560e0b2bb926ad037729ae160ebf17f6.
This commit originally reverted #1140 due to os.symlink not being
available on windows in Python2.7 stdlib, details here: https://github.com/awslabs/aws-sam-cli/pull/1315#issuecomment-518939441. We recently removed Python2.7 support in #1416, so this commit
is a revert of the revert, with some additional black formating to make `make pr`
pass.
*Checklist:*
=> Revert "Revert "fix: Respect zipped symlinks (#1140)""

tests/integration/local/invoke/test_integrations_cli.py
Similar to #1014 
On windows, we do not set the permissions correctly when unzipping the layers. Which is different than what the PR that added this test was solving.
Skips test on windows.
Doesn't tests symlinks on windows.
N/A
*Checklist:*
=> test(integ): Skip Git layer Symlink test due to binary permission issue

samcli/commands/init/__init__.py, samcli/lib/build/app_builder.py, samcli/lib/providers/sam_function_provider.py
#1934
This is to add warnings for customers using build, invoke|start-api|start-lambda, and init commands with runtimes that are no longer supported by AWS Lambda.
This is the first phase, so we can safely remove these depreciated runtimes in a future release.
None, just prints warnings when a customer uses a depreciated runtime.
N/A
*Checklist:*
=> feat: Print warning about using depreciated runtimes

samcli/commands/deploy/auth_utils.py, samcli/commands/deploy/deploy_context.py, samcli/commands/deploy/guided_context.py, samcli/lib/providers/provider.py, samcli/lib/providers/sam_function_provider.py, tests/integration/deploy/test_deploy_command.py, tests/unit/commands/deploy/test_auth_utils.py, tests/unit/commands/deploy/test_command.py, tests/unit/commands/deploy/test_deploy_context.py, tests/unit/commands/deploy/test_guided_context.py, tests/unit/commands/local/lib/test_local_lambda.py, tests/unit/commands/local/lib/test_sam_function_provider.py
* If Auth is determined to be not present with a degree of possibility,
a prompt is shown to ask the user if they are explicitly okay with such
a configuration.
* Showcase to the user that there may be a potential issue with how the
template resources have been configured.
* Extra prompt on guided mode.
*Checklist:*
=> fix: showcase prompts and messages on deploying - auth

samcli/commands/deploy/deploy_context.py, samcli/commands/deploy/guided_context.py, samcli/lib/providers/sam_base_provider.py, samcli/lib/samlib/wrapper.py, tests/integration/local/invoke/test_integrations_cli.py, tests/integration/local/start_lambda/test_start_lambda.py, tests/integration/testdata/invoke/layers/layer-bad-template.yaml, tests/integration/testdata/invoke/layers/layer-template.yml, tests/integration/testdata/invoke/main.py, tests/integration/testdata/invoke/template-pseudo-params.yaml, tests/integration/testdata/invoke/template.yml, tests/unit/commands/local/lib/test_sam_base_provider.py
* Some plugins require that intrinsics are resolved and parameter
information be present.
* Passing parameters that have parameters and pseudo parameters resolved
fixes the issue.
* Also tested with local invoke and deploy
* None at this point.
* https://github.com/awslabs/aws-sam-cli/issues/1958
* https://github.com/awslabs/aws-sam-cli/issues/1956
*Checklist:*
By submitting this pull request, I confirm that my contribution is made under the terms …
=> fix: allow parameters to be passed through to `SamTranslatorWrapper`

tests/integration/local/invoke/test_integrations_cli.py
For some reason this test started failing, it doesn't fail on local or when run in isolation. Marking this test as flaky.
*Checklist:*
=> Marking failing test as flaky.

requirements/base.txt, requirements/reproducible-linux.txt
* Need the latest aws lambda builders to support build for `provided`
runtimes.
*If so, did you run `make update-reproducible-reqs`
* Yes
*Checklist:*
=> chore: version bump to 0.9.0 - aws lambda builders

Makefile
n/a
We need to produce the reproducible-linux.txt file from the same python version otherwise things will conflict. We standardized on python3.7 to match our MSI and brew bottles.
n/a
n/a
*Checklist:*
=> chore: Force producing reproducible-linux.txt from python3.7 env

appveyor.yml
Recent change in AppVeyor https://www.appveyor.com/updates/ broke our docker layer tests. This is a quick work around to block our release. We need to do proper fix.
*Checklist:*
=> Using Previous image of AppVeyor to fix docker layer issue.

.pylintrc, Makefile, samcli/commands/build/build_context.py, samcli/commands/build/command.py, samcli/commands/build/exceptions.py, samcli/lib/build/app_builder.py, samcli/lib/build/workflow_config.py, samcli/lib/providers/provider.py, samcli/lib/providers/sam_base_provider.py, samcli/lib/providers/sam_function_provider.py, samcli/lib/providers/sam_layer_provider.py, samcli/local/lambdafn/exceptions.py, tests/integration/buildcmd/build_integ_base.py, tests/integration/buildcmd/test_build_cmd.py, tests/integration/testdata/buildcmd/PyLayer/layer.py, tests/integration/testdata/buildcmd/PyLayer/requirements.txt, tests/integration/testdata/buildcmd/PythonWithLayer/main.py, tests/integration/testdata/buildcmd/PythonWithLayer/requirements.txt, tests/integration/testdata/buildcmd/layers-functions-template.yaml, tests/unit/commands/buildcmd/test_build_context.py, tests/unit/commands/buildcmd/test_command.py, tests/unit/commands/local/lib/test_provider.py, tests/unit/commands/local/lib/test_sam_function_provider.py, tests/unit/commands/local/lib/test_sam_layer_provider.py, tests/unit/lib/build_module/test_app_builder.py
Adding ability to build layers. If a user want to build a layer then simply add following:
```
Metadata:
BuildMethod: <runtime>
```
to the layer in the template. This will pick the build method for that runtime (as it does for Lambda Function). After that Layer can be build by one of the following two commands:
`sam build`
`sam build LayerLogicalId`
*Checklist:*
=> Build for Layers

samcli/commands/deploy/auth_utils.py, tests/unit/commands/deploy/test_auth_utils.py
* Instrinsics in defintion body are not resolved when checking for
security scheme, making it hard to do checks. So only do the checks if
the instrinsics in the paths are already resolved.
* If defintion body now has instrinsics, it does not crash the sam cli
process.
*Checklist:*
=> bug: security prompt - instrinsics in definition body

samcli/local/apigw/local_apigw_service.py, tests/unit/local/apigw/test_local_apigw_service.py
#2037
Developing on a local server that caches static file is error-prone and confusing, the best is not caching static assets. 
Configuring Flask not to emit caching header
When running `sam local start-api` and requesting a static file caching headers won't be emitted anymore.
no
*Checklist:*
- [ x ] Write unit tests
- [ x ] `make pr` passes
=> bug: Static flask server won't cache response anymore

samcli/lib/deploy/deployer.py, samcli/lib/utils/botoconfig.py
We do hit throttling limit when polling cloudformation for describe stack. AwsCli recently made a change to update their polling frequency, this change is to add same values to sam-cli.
*Checklist:*
=> fix: Updating CFN polling frequency as per aws-cli change.

samcli/__init__.py
Resolve conflict between https://www.python.org/dev/peps/pep-0440/#pre-releases and https://packaging.python.org/guides/distributing-packages-using-setuptools/#pre-release-versioning by changing approach.
=> Version bump

samcli/local/rapid/build.sh
N/A
The build script to build the init.go binary is 9.1Mb. If we remove the debug symbols we can reduce this to 6.6Mb. 
adds -s and -w linker flags. 
-s: Omit the symbol table and debug information.
-w: Omit the DWARF symbol table.
None that I know of.
N/A
*Checklist:*
=> refactor: Build init.go with -s and -w flags to removed debug info

samcli/local/docker/lambda_container.py, samcli/local/docker/lambda_image.py, tests/unit/local/docker/test_lambda_container.py, tests/unit/local/docker/test_lambda_image.py
This is an alternative solution to #2098 
We need RAPID inside the container at runtime. The options are mounting or created an image on they fly. Mounting requires the path to be sharable to docker and if it not, the invoke will fail which is a regressions in rc1.
Instead of mounting or allowing customers to give the path to an alternative rapid, we will just build the image locally that has rapid baked into it. This will ensure we can set permissions on this binary (if needed). This should get around the initially issue found in #2095 where we could not mount the rapid binary due to share settings of docker. The implementation creates a tar and sends that to the docker build (through the sdk). If …
=> refactor: Bake Rapid into image on the fly

build-image-src/Dockerfile-java11, build-image-src/Dockerfile-nodejs10x, build-image-src/Dockerfile-nodejs12x, build-image-src/Dockerfile-python38, build-image-src/Dockerfile-ruby27
Discovered a regression where on Ruby 2.7, the `nokogiri` dependency
would build without errors, but would not run on local testing or on AWS
Lambda itself.
On further investigation, it appears that `nokogiri` can compile with or
without `liblzma` present, but if it is present in the build
enviornment (pre-change) and it is not present on the invoke
environment (true in AL2 runtimes), you will experience runtime failures
attempting to require `nokogiri`.
I have been able to verify that with these changes, `nokogiri` builds
correctly for Ruby 2.7 and runs both locally and on AWS Lambda.
=> Remove liblzma and libxslt from AL2 build images

appveyor-windows-build-python.yml, requirements/base.txt, requirements/reproducible-linux.txt, samcli/__init__.py
n/a
Use the latest lambda builders and update SAM CLI's version to 1.0.0
yes
yes
*Checklist:*
=> chore: Bump aws-lambda-builders and SAM CLI to 1.0.0

samcli/local/docker/lambda_debug_settings.py
=> fix: Update Python3.8 debug entrypoint

README.md
=> chore: readme update with screenshot

requirements/base.txt, requirements/reproducible-linux.txt
Docker Python SDK updated to version 4.3.0. Breaks support for docker API version 1.37.
~=4.0 installs latest docker sdk version of 4.x
Changed ~=4.0 to ~=4.2.0 which installs latest version within 4.2
Docker will not update to latest breaking changes. Manual update to requirements.txt is required.
Yes
Yes
*Checklist:*
=> Fix: Use Docker Python SDK Version 4.2.x Instead of 4.x

samcli/commands/deploy/guided_context.py, tests/unit/commands/deploy/test_command.py
=> fix: remove redundant `print_deploy_args` call

samcli/local/docker/lambda_debug_settings.py, tests/unit/local/docker/test_lambda_container.py
Was missing from original release.
=> Add Debug Support for java8.al2 Runtime

tests/integration/package/test_package_command.py
=> fix: relaxing warning message check due to windows.

samcli/lib/warnings/sam_cli_warning.py, tests/unit/lib/warnings/test_sam_cli_warnings.py
#2206 
We recently published a change with bug where we assume all resources in CFN will have `Type`. This is failing when we are trying to validate warning messages from template. This change will fix that assumption.
*Checklist:*
=> fix: bug when validation resource with no type.

samcli/lib/deploy/deployer.py, tests/unit/lib/deploy/test_deployer.py
Issue #1844
To satisfy customer requirement for to see if replacement happened when deploying
Added a column to show if replacement happened (reading from boto3 client response)
Not known so far
No
*Checklist:*
=> feat: Added a column in print changeset to show if replacement happened

samcli/lib/generated_sample_events/event-mapping.json, samcli/lib/generated_sample_events/events.py, samcli/lib/generated_sample_events/events/sqs/Sqs.json, samcli/lib/utils/hash.py, tests/unit/commands/local/generate_event/test_event_generation.py, tests/unit/lib/utils/test_hash.py
#758 
Customer wants to be able to customize message body when generating an SQS event
To support customized `body` in the SQS was straightforward, but customizing `body` would also trigger an update in `md5OfBody`. (see [here](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_Message.html))
I introduced an additional `children` attribute in `event-mapping.json` to describe such relation, and made corresponding update in `events.py` to consume the `children` attribute. I also added supported for calculating the md5 digest of `body`.
No, the change is mostly contained with the `Events` class in …
=> feat: Add support for customized message body in generated SQS message

README.md
https://github.com/aws/serverless-application-model/issues/1692
Previous Slack invite link was broken.
Updated README with new invite link.
*Checklist:*
=> Fix: Slack #samdev Invite Link

tests/integration/deploy/test_deploy_command.py, tests/integration/local/invoke/test_integrations_do_cli.py
1. UI changes from #2176 introduce extra command line prompts, which fails guided tests in test_deploy_command.py. 
2. The lines console output changes run by run, for example: 
```
Loading function
[32mSTART RequestId: 4b4bf033-f0e5-15ff-5852-f4d216476c0e Version: $LATEST[0m
value1 = value1
value2 = value2
value3 = value3
Docker Lambda is writing to stderr
"Hello world"
[32mEND RequestId: 4b4bf033-f0e5-15ff-5852-f4d216476c0e[0m
[32mREPORT RequestId: 4b4bf033-f0e5-15ff-5852-f4d216476c0e	Init Duration: 128.38 ms	Duration: 3.01 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 26 MB	[0m
```
and
```
Loading function
[32mSTART RequestId: 33e1c9c8-b775-134b-3ef1-9fee0345e9b6 Version: …
```
=> fix: flaky test and ingegration tests

samcli/cli/cli_config_file.py, samcli/commands/deploy/guided_config.py
Update command line `--help` information to match AWS document.
*Checklist:*
=> Update command line document for new config file options

samcli/local/docker/lambda_debug_settings.py, tests/unit/local/docker/test_lambda_container.py
Debugging config for dotnet3.1
Debugging support for dotnet3.1
No
*Checklist:*
=> Debugging support for dotnet3.1

samcli/__init__.py
Preview preview-rapid init was not marked executable
=> Make preview init executable

samcli/lib/build/build_graph.py, tests/unit/lib/build_module/test_build_graph.py
#2293
Projects that uses mapping for function name, fails to build.
To update generation of build graph. Instead of using functionname, it should use name property of the function resource
*Checklist:*
=> fix: use name instead of functionname when creating build graph

samcli/lib/build/app_builder.py, tests/integration/buildcmd/build_integ_base.py, tests/integration/buildcmd/test_build_cmd.py, tests/integration/testdata/buildcmd/Gemfile, tests/integration/testdata/buildcmd/RubyWithRootGemfile/app.rb, tests/unit/lib/build_module/test_app_builder.py
#2292
Building some of the ruby projects into temp folder is not working because of shared Gemfile in the root folder
Instead of building into temp folder, it is building into one of the functions for same build definition
*Checklist:*
=> fix: for de-dup builds, build into one of the function folder instead of temporary folder

.pre-commit-config.yaml, DEVELOPMENT_GUIDE.md, Makefile, appveyor.yml, requirements/dev.txt, samcli/cli/cli_config_file.py, samcli/commands/deploy/guided_context.py, samcli/commands/logs/command.py, samcli/commands/publish/command.py, samcli/commands/validate/validate.py, samcli/local/docker/lambda_debug_settings.py, tests/integration/buildcmd/build_integ_base.py, tests/integration/package/test_package_command.py, tests/unit/commands/deploy/test_guided_context.py, tests/unit/commands/local/generate_event/test_event_generation.py, tests/unit/lib/samconfig/test_samconfig.py, tests/unit/lib/utils/test_hash.py
to make black version consistent with appveyor and dev guide. Even better, by only specifying black version in one place , we can reduce our maintenance cost. 
- make black installation managed
- only specify black version in one place
- avoid installing black in pre-commit (reuse existing black installed by `make init`)
- simplify dev guide
*Checklist:*
=> chore: Fix inconsistent black version in precommit

samcli/lib/providers/sam_api_provider.py, tests/integration/local/start_api/test_start_api.py, tests/integration/testdata/start_api/swagger-template-http-api.yaml
=> fix: apply PayloadFormationVersion in httpapi event

samcli/cli/cli_config_file.py, tests/integration/deploy/deploy_integ_base.py, tests/integration/deploy/test_deploy_command.py, tests/integration/testdata/package/samconfig-invalid-syntax.toml, tests/unit/cli/test_cli_config_file.py
*Issue #, if available:* #2311 
- Prevent issues in the config from being ignored.
- Improve UX by stating the root cause as early as possible.
Fail immediately if a non-`KeyError` exception is thrown when processing the config.
For example, with the following `samconfig.toml`:
```toml
version = 0.1
[default.deploy.parameters]
stack_name = _sam-app"
```
Instead of cryptic error messages as in #2311, `sam deploy` and `sam deploy --guided` will now show the following output:
```bash
Error: Error reading configuration: Unexpected character: '_' at line 3 col 13
```
A few notes regarding the PR:
- Keeping the `KeyError` handling as-is for now as it's not directly relevant to the issue and there might be marginal benefit to it (e.g. allow specifying a custom `config_env` without the …
=> fix: fail on invalid config

samcli/local/apigw/local_apigw_service.py, tests/integration/local/start_api/test_start_api.py, tests/integration/testdata/start_api/main.py, tests/integration/testdata/start_api/template-http-api.yaml, tests/unit/local/apigw/test_local_apigw_service.py
It's great to see that #1942 and #2326 are now merged into develop so we can run HttpApi locally!
Another great thing is to let the API Gateway infer Lambda function responses as described in https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.v2.
Since it doesn't work when running "sam local start-api", this pr tries to fix it.
It adds functionality to make API Gateway infer Lambda function response for HttpApi with PayloadFormatVersion 2.0.
None
No
*Checklist:* …
=> Fix: Make API Gateway infer Lambda function response for HttpApi with PayloadFormatVersion 2.0

.pylintrc, requirements/base.txt, requirements/reproducible-linux.txt, samcli/commands/local/lib/swagger/integration_uri.py, samcli/commands/local/lib/swagger/reader.py, samcli/lib/intrinsic_resolver/intrinsic_property_resolver.py, samcli/lib/intrinsic_resolver/intrinsics_symbol_table.py, samcli/lib/intrinsic_resolver/invalid_intrinsic_validation.py, samcli/lib/providers/api_collector.py, samcli/lib/providers/cfn_api_provider.py, samcli/lib/providers/cfn_base_api_provider.py
A followup mentioned in https://github.com/aws/aws-sam-cli/pull/2304#discussion_r508755968
Use https://six.readthedocs.io/ as a reference to remove `six` usage and keep only the Python 3 part.
None
*Checklist:*
=> Remove six usage

samcli/local/apigw/local_apigw_service.py, tests/integration/local/start_api/test_start_api.py, tests/integration/testdata/start_api/cfn-quick-created-http-api-with-default-route.yaml, tests/unit/local/apigw/test_local_apigw_service.py
*Issue #, if available:* https://github.com/aws/aws-sam-cli/issues/2345
*Why is this change necessary?* to fix the Http APi event route key
*How does it address the issue?* it fixes the used route format"{path}:{method}", and use the correct format "{method} {path}"
*What side effects does this change have?* no side effects
no
*Checklist:*
=> fix HttpApi event V2 route key

requirements/base.txt, requirements/reproducible-linux.txt, tests/functional/commands/validate/lib/models/amq.yaml, tests/functional/commands/validate/lib/models/api_with_basic_custom_domain.yaml, tests/functional/commands/validate/lib/models/api_with_basic_custom_domain_http.yaml, tests/functional/commands/validate/lib/models/api_with_basic_custom_domain_intrinsics.yaml, tests/functional/commands/validate/lib/models/api_with_basic_custom_domain_intrinsics_http.yaml, tests/functional/commands/validate/lib/models/http_api_lambda_auth.yaml, tests/functional/commands/validate/lib/models/http_api_lambda_auth_full.yaml, tests/functional/commands/validate/lib/models/layers_with_intrinsics.yaml, tests/functional/commands/validate/lib/models/state_machine_with_xray.yaml
Update sam-translator version to 1.29.0
To support MQ and MTLS changes in sam-translator
Yes
*Checklist:*
=> feat: update sam-translator version to 1.29.0

samcli/commands/build/command.py, tests/integration/deploy/test_deploy_command.py
This change will stop removing the default stack for aws-sam-cli which is aws-sam-cli-managed-default stack.
Since CFN termination protection is enabled, this is causing failures in Canaries
By not removing the default AWS SAM CLI stack
*Checklist:*
=> fix: Fix canary failures and update help text for build command

appveyor.yml
When AppVeyor updates their python env, like from 3.7.7 to 3.7.9, 3.7.7 won't be available, and builds will fail due to the error:
```
/opt/appveyor/build-agent/bash-shell.sh: line 51: /home/appveyor/venv3.7.7/bin/activate: No such file or directory
```
According to AppVeyor doc, we don't have to specify patch version: https://www.appveyor.com/docs/linux-images-software/#python
Remove patch version so it can handle patch version python upgrade on AppVeyor side.
nothing
=> chore: Remove python patch version in AppVeyor to be more robust

tests/integration/buildcmd/test_build_cmd.py, tests/integration/local/invoke/invoke_integ_base.py, tests/integration/local/invoke/runtimes/test_with_runtime_zips.py, tests/integration/local/start_api/start_api_integ_base.py, tests/integration/local/start_lambda/start_lambda_api_integ_base.py, tests/testing_utils.py
Follow up #2395, disable local invoke that requires docker images.
Without disabling them, these tests are likely to fail: https://ci.appveyor.com/project/AWSSAMCLI/aws-sam-cli/builds/36418448/job/o43404pa7i1awh3r
=> ci: Disable local invoke in integ test on AppVeyor except for Canary

appveyor.yml
```
Log in docker hub as awssamclitestdockeruser
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /home/appveyor/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
```
```
$ if [[ -n $BY_CANARY ]] && [[ -n $DOCKER_USER ]] && [[ -n $DOCKER_PASS ]];
then echo Logging in Docker Hub; echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin;
fi
Logging in Docker Hub
Login Succeeded
```
=> ci: Login docker hub using stdin password input

samcli/lib/package/artifact_exporter.py, tests/integration/package/test_package_command_zip.py, tests/integration/testdata/package/aws-include-transform.yaml
- default to s3 based uploader
- added integration test for Fn::Transform which was missing before.
https://github.com/aws/aws-sam-cli/issues/2432
* AWS Include defaults to s3 as the export mechanism. there was a bug in not supplying the correct uploader.
* Specified AWS Include macro now packages to s3
* Its a regression fix
=> fix(package): regression with "Fn::Transform"

samcli/local/docker/manager.py, tests/unit/local/docker/test_manager.py
https://github.com/aws/aws-sam-cli/issues/2446
If build images are not downloaded before, running build command in parallel might cause docker to start pulling same image more than once.
By adding a thread lock for different images. That means each image should only be pulled once during a parallel operation. Different images (ex: nodejs, python) can be pulled at the same time.
Adding a lock per image pull might add small performance decrease (around hundreds of milliseconds).
=> fix: use a lock when pulling different images

samcli/commands/package/package_context.py, tests/unit/commands/package/test_package_context.py
https://github.com/aws/aws-sam-cli/issues/2433
If user doesn't have any default region setting (env variable or in ~/.aws folder) guided deploy command will fail.
This change sets region from guided deploy parameters
None
=> fix: create signer client with region definition

requirements/base.txt, requirements/reproducible-linux.txt, samcli/commands/exceptions.py, samcli/commands/local/cli_common/invoke_context.py, samcli/commands/local/cli_common/options.py, samcli/commands/local/lib/debug_context.py, samcli/commands/local/lib/local_lambda.py, samcli/commands/local/start_api/cli.py, samcli/commands/local/start_lambda/cli.py, samcli/lib/utils/async_utils.py, samcli/lib/utils/file_observer.py, samcli/local/docker/container.py, samcli/local/docker/manager.py, samcli/local/lambdafn/config.py, samcli/local/lambdafn/runtime.py, tests/integration/local/start_api/start_api_integ_base.py, tests/integration/local/start_api/test_start_api.py, tests/integration/local/start_lambda/start_lambda_api_integ_base.py, tests/integration/local/start_lambda/test_start_lambda.py, tests/integration/testdata/start_api/template-warm-containers.yaml, tests/unit/commands/local/cli_common/test_invoke_context.py, tests/unit/commands/local/lib/test_local_lambda.py, tests/unit/commands/local/start_api/test_cli.py, tests/unit/commands/local/start_lambda/test_cli.py, tests/unit/commands/samconfig/test_samconfig.py, tests/unit/lib/utils/test_file_observer.py, tests/unit/local/docker/test_container.py, tests/unit/local/docker/test_manager.py, tests/unit/local/lambdafn/test_config.py, tests/unit/local/lambdafn/test_runtime.py
This change added the warm containers options to enhance the Lambda Function local testing performance.
we added the container-mode option that determine if SAM CLI will handle the containers life cycle in warm mode, or normal mode.
N/A
=> feat: warm containers

samcli/local/docker/lambda_debug_settings.py
#2384 
Add AWS_EXECUTION_ENV to debug env variable list.
=> fix: add AWS_EXECUTION_ENV to debug env variables for json runtimes

samcli/commands/local/cli_common/invoke_context.py, samcli/local/docker/container.py, samcli/local/lambdafn/runtime.py, tests/integration/local/start_api/test_start_api.py, tests/unit/local/docker/test_container.py, tests/unit/local/lambdafn/test_runtime.py
https://github.com/aws/aws-sam-cli/issues/188
to allow of local testing with large input request
After the use of rapid-rie server, no need to send the input event as part of the container environment variables.
N/A
=> fix: accepting large input requests

samcli/commands/_utils/resources.py
There is a small typo in samcli/commands/_utils/resources.py.
Should read `utility` rather than `utlity`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, utlity -> utility

requirements/base.txt
boto3 has been stable among minor version upgrades,
we can make the version requirement loose as we do in
https://github.com/aws/serverless-application-model/pull/1812
=> Loose the boto3 version requirement

requirements/base.txt, requirements/reproducible-linux.txt
Updating aws-lambda-builders version
To release various bugfixes in builders library
=> chore: bump aws-lambda-builders version to 1.2.0

samcli/commands/package/package_context.py, samcli/lib/deploy/deployer.py, samcli/lib/package/artifact_exporter.py, samcli/lib/package/code_signer.py, samcli/lib/package/packageable_resources.py, samcli/lib/package/s3_uploader.py, samcli/lib/package/uploaders.py, samcli/lib/package/utils.py, tests/integration/package/test_package_command_image.py, tests/integration/testdata/package/aws-serverless-application-image.yaml, tests/unit/lib/package/test_artifact_exporter.py
1. Current `Template`'s `uploader` has three possible types, which is not very easy to comprehend
- `S3Uploader`
- `ECRUploader`
- `Dict[str, Union[S3Uploader, ECRUploader]]`
2. When uploaders are passed along the invocation path, they can be lost:
1. `Template` (originally `{"s3": self.s3_uploader, "ecr": self.ecr_uploader}`
2. `Resource` (either has `s3_uploader` or `ecr_uploader`) because of this piece of code
https://github.com/aws/aws-sam-cli/blob/0e4e99b37d031ba4caca128f3c3b333da519f770/samcli/lib/package/artifact_exporter.py#L228-L234
3. `Template` (created by `CloudFormationStackResource.do_export`), now `Template` can only has `s3_uploader` or `ecr_uploader`, not both.
https://github.com/aws/aws-sam-cli/blob/0e4e99b37d031ba4caca128f3c3b333da519f770/samcli/lib/package/artifact_expo …
=> fix: Cannot package Image functions in nested stack

.pylintrc, samcli/cli/context.py, samcli/cli/global_config.py, samcli/commands/_utils/table_print.py, samcli/commands/deploy/deploy_context.py, samcli/commands/deploy/guided_config.py, samcli/commands/deploy/guided_context.py, samcli/commands/init/init_templates.py, samcli/commands/local/generate_event/event_generation.py, samcli/commands/package/package_context.py, samcli/lib/build/app_builder.py, samcli/lib/build/build_strategy.py, samcli/lib/config/samconfig.py, samcli/lib/deploy/deployer.py, samcli/lib/generated_sample_events/events.py, samcli/lib/intrinsic_resolver/intrinsic_property_resolver.py, samcli/lib/providers/cfn_api_provider.py, samcli/lib/providers/cfn_base_api_provider.py, samcli/lib/providers/sam_api_provider.py, samcli/lib/samlib/wrapper.py, samcli/lib/telemetry/metric.py, samcli/lib/utils/hash.py, samcli/lib/warnings/sam_cli_warning.py, samcli/local/apigw/local_apigw_service.py, samcli/local/docker/manager.py, samcli/local/layers/layer_downloader.py, tests/unit/lib/build_module/test_build_strategy.py
…static
There are many instance methods do not need to be instance methods since `self` is not being used. Making it static increases readability. 
Making them static. One exception, for `BuildStrategy`, the class is meant to be an abstract class, so I made its two instance methods abstract instead of static. 
no, 
> A static method can be called either on the class (such as C.f()) or on an instance (such as C().f()). https://docs.python.org/3/library/functions.html#staticmethod
We don't need to change how we invoke them.
=> chore: Make methods that do not need to be instance methods static

samcli/lib/utils/file_observer.py, samcli/lib/utils/hash.py, samcli/local/lambdafn/runtime.py, tests/integration/local/start_api/start_api_integ_base.py, tests/integration/local/start_api/test_start_api.py, tests/integration/local/start_lambda/start_lambda_api_integ_base.py, tests/integration/local/start_lambda/test_start_lambda.py, tests/integration/testdata/start_api/image_package_type/Dockerfile, tests/integration/testdata/start_api/image_package_type/main.py, tests/integration/testdata/start_api/image_package_type/template.yaml, tests/unit/lib/utils/test_file_observer.py, tests/unit/local/lambdafn/test_runtime.py
https://github.com/aws/aws-sam-cli/issues/2507
to make sam cli able to reload the image package type lambda functions if it got changed.
SAM will listen the docker events to observe if there is any change to the lambda function image.
N/A
=> (Fix) observe the docker images for lambda functions with Image package type

samcli/lib/package/utils.py
https://github.com/aws/aws-sam-cli/issues/2511
Artifact ZIP file has 0% compression.
Specifies the compression level and type.
`zf.writestr` does not use the compression type given in the ZipFile constructor.
=> fix: No Default Compress Type for Windows

tests/integration/package/test_package_command_image.py
Fix the integration test failure:
```
tests/integration/package/test_package_command_image.py:141: in test_package_template_with_image_function_in_nested_application
self.assertIn("Pushed", process_stderr)
E   AssertionError: 'Pushed' not found in '\x1b[1A\x1b[G\x1b[0KThe push refers to repository [*****]\n\n\x1b[1A\x1b[G\x1b[0K\rc04d1437198b: Preparing \x1b[0B\x1b[G\x1b[1A\x1b[G\n\x1b[1A\x1b[G\x1b[0K\rc04d1437198b: Layer already exists \x1b[1B\x1b[G\n\x1b[1A\x1b[G\x1b[0Kalpine-7731472c3f2a-latest: digest: sha256:d0710affa17fad5f466a70159cc458227bd25d4afb39514ef662ead3e6c99515 size: 528\n\n\rUploading to b44d7f8e83d3e55edef4a6ad7675ae4e.template  472 / 472.0  (100.00%)'
```
When that integration test runs, the image was already uploaded once. In this test we only need to verify the image …
=> ci: Fix an integration test failure caused by resource already exists

tests/integration/deploy/test_deploy_command.py
Adding code signer integration tests for Canary
=> ci: Add Code Signer Integration Tests

requirements/dev.txt
mypy adds some new rules in 0.800 and it broke current PR check.
I checked the rules and it looks like it requires some effort to fix it or suppress the type error (in the bundled `sam init` template files.) So the current solution is to freeze mypy's version so its future new versions won't break our PR checks.
No
=> ci: Freeze mypy version in dev.txt

tests/integration/package/test_package_command_image.py
A followup to #2542. Turned out the `stderr` is not reliable and it replies on docker client outputting the expected message. Here I changed the assertion to verify uploaded template file instead.
This behavior is decided by our sam-cli only, we don't need to worry about docker client version or docker client changing behavior in the future breaking our tests.
=> ci: Check template content when test nested image function package

samcli/lib/package/s3_uploader.py
`mypy_boto3_s3` is in `dev.txt`, we should not import this.
=> ci: Remove type stubs import from dev.txt

samcli/commands/local/cli_common/invoke_context.py, tests/unit/commands/local/cli_common/test_invoke_context.py
Fix local invoke with custom region. Somehow it was not caught in the canary run yesterday https://ci.appveyor.com/project/AWSSAMCLI/aws-sam-cli-canary-linux/builds/37696048/job/5vth4t3503scpn9a
Caused by a typo in #2594, `_parameter_overrides` should be `parameter_overrides`.
This also further refactors how property `parameter_overrides` works. Doing mutation in property getter is not a good practice. When I looked at the code I did not realize `parameter_overrides` could mutate `_parameter_overrides` and is different from `_parameter_overrides`. The mutation has been moved to the constructor.
N/A
=> fix: Custom region is not passed properly in local invoke

samcli/lib/providers/sam_stack_provider.py, tests/unit/commands/local/lib/test_stack_provider.py
This is a follow up of #2594, to support nested stack.
If root template is not `./template.yaml` or in current working directory, local nested templates cannot be resolved properly.
Does a path derivation depending on whether nested template location is absolute path or not. If it is not, it is joined with parent's template directory.
N/A, nested stack support is not available and this PR has no customer impact.
=> fix: Nested stack cannot be extracted if root template is not in working dir

samcli/lib/providers/provider.py, samcli/lib/providers/sam_function_provider.py, tests/unit/commands/local/lib/test_sam_function_provider.py
This is a follow up of #2594, 2nd PR to support nested stack.
*These two commits are taken out from https://github.com/aahung/aws-sam-cli/tree/nested-stack-2
two functions with the same name can appear in two different nested stacks, which causing one overriding the other. 
Before the dict's key is function name, which is not unique in a multi-stack setting. Now the key is a unique key "full_path" consisting of stack_path and function name.
N/A, nested stack support is not available and this PR has no customer impact.
=> fix: SamFunctionProvider could miss functions with same name but in different stacks

samcli/lib/build/build_strategy.py, tests/integration/buildcmd/test_build_cmd.py, tests/integration/testdata/buildcmd/PythonImage/main.py, tests/integration/testdata/buildcmd/dedup-functions-image-template.yaml, tests/unit/lib/build_module/test_build_strategy.py
=> fix: If image functions have same metadata, only 1st one is in the result

samcli/lib/build/build_strategy.py, samcli/lib/providers/provider.py, samcli/lib/providers/sam_function_provider.py, samcli/lib/providers/sam_stack_provider.py, tests/integration/buildcmd/test_build_cmd.py, tests/integration/testdata/buildcmd/PythonImage/main.py, tests/integration/testdata/buildcmd/dedup-functions-image-template.yaml, tests/unit/commands/local/lib/test_sam_function_provider.py, tests/unit/commands/local/lib/test_stack_provider.py, tests/unit/lib/build_module/test_build_strategy.py
This reverts commit 60eb2f880e03f0f77d71bbe9ccdc7b14d4f31507.
Return back nested stack changes that we reverted before releasing V. 1.18.2
=> Revert "Revert nested stack changes before 1.18.2 release (#2641)"

appveyor-windows-build-go.yml
* Go integration tests
* Go 1.16 introduced a breaking change with go build no longer being allowed to change/create go.mod and go.sum files by default.
* Initial Assessment was that setting go env will not fix this, but that been set incorrectly without an "=" sign.
* Set a go env variable to allow for changes.
* None, allows for build tests to start passing again.
=> fix: Go 1.16 set GOFLAGS to allow change of go.mod and go.sum

MANIFEST.in
https://github.com/aws/aws-sam-cli/issues/2660
pre-dev.txt requirement file was missing from the MANIFEST.in which causes PyPi tarball source to fail installation.
=> fix: Added pre-dev.txt to MANIFEST.in

.pylintrc, samcli/cli/cli_config_file.py, samcli/cli/global_config.py, samcli/commands/_utils/options.py, samcli/commands/local/generate_event/event_generation.py, samcli/commands/logs/logs_context.py, samcli/lib/build/app_builder.py, samcli/lib/config/samconfig.py, samcli/lib/deploy/deployer.py, samcli/lib/init/__init__.py, samcli/lib/intrinsic_resolver/intrinsic_property_resolver.py, samcli/lib/intrinsic_resolver/intrinsics_symbol_table.py, samcli/lib/logs/event.py, samcli/lib/logs/fetcher.py, samcli/lib/logs/formatter.py, samcli/lib/providers/api_collector.py, samcli/lib/providers/api_provider.py, samcli/lib/providers/cfn_api_provider.py, samcli/lib/providers/cfn_base_api_provider.py, samcli/lib/providers/sam_api_provider.py, samcli/lib/schemas/schemas_code_manager.py, samcli/lib/utils/version_checker.py, samcli/local/apigw/local_apigw_service.py, samcli/local/docker/container.py, samcli/local/docker/lambda_container.py, samcli/local/events/api_event.py, samcli/local/lambdafn/env_vars.py, samcli/local/lambdafn/zip.py
Some docstrings are outdated and confusing. For example, the arguments of a function do not appear in the docstring, or have the incorrect types.
This PR fixes them all and enable lint check so it won't happen next time.
No side effects.
=> chore: Fix mismatch docstrings and enable lint check

tests/unit/local/apigw/test_local_apigw_service.py, tests/unit/local/docker/test_lambda_container.py, tests/unit/local/events/test_api_event.py, tests/unit/local/lambdafn/test_runtime.py
pytest keeps complaining
```
DeprecationWarning: Please use assertEqual instead.
self.assertEquals(route_key, "$default")
```
> For historical reasons, some of the TestCase methods had one or more aliases that are now deprecated. The following table lists the correct names along with their deprecated aliases:
Method Name   | Deprecated alias | Deprecated alias
--------------+------------------+-----------------
assertEqual() | failUnlessEqual  | assertEquals
...
http://docs.python.org/3.3/library/unittest.html#deprecated-aliases
Replace deprecated self.assertEquals() with assertEqual()
=> chore: Replace deprecated self.assertEquals() with assertEqual()

appveyor.yml
https://ci.appveyor.com/project/AWSSAMCLI/aws-sam-cli-canary-linux/builds/38069583/job/by3koa2559sqtxrc
python 3.8 could not be installed due to apt cache outdated.
run apt update before installing anything.
=> ci: Do apt update before installing

build-image-src/Dockerfile-python27
The URL to Python 2.7 `get-pip.py` has changed:
```
% curl https://bootstrap.pypa.io/2.7/get-pip.py | python /dev/stdin
Hi there!
The URL you are using to fetch this script has changed, and this one will no
longer work. Please use get-pip.py from the following URL instead:
https://bootstrap.pypa.io/pip/2.7/get-pip.py
Sorry if this change causes any inconvenience for you!
We don't have a good mechanism to make more gradual changes here, and this
renaming is a part of an effort to make it easier to us to update these
scripts, when there's a pip release. It's also essential for improving how we
handle the `get-pip.py` scripts, when pip drops support for a Python minor
version.
There are no more renames/URL changes planned, and we don't expect that a need
would arise to do this again in the …
```
=> fix: Python 2.7 build image get-pip.py URL

samcli/commands/build/build_context.py, samcli/commands/deploy/deploy_context.py, samcli/commands/deploy/guided_context.py, samcli/commands/local/cli_common/invoke_context.py, samcli/lib/providers/exceptions.py, samcli/lib/providers/sam_stack_provider.py, tests/unit/commands/buildcmd/test_build_context.py, tests/unit/commands/deploy/test_command.py, tests/unit/commands/deploy/test_deploy_context.py, tests/unit/commands/deploy/test_guided_context.py, tests/unit/commands/local/cli_common/test_invoke_context.py, tests/unit/commands/local/lib/test_stack_provider.py
#2689
Error message `Nested application 'Application' has specified S3 location for Location which is unsupported. Skipping resources inside this nested application.` is printed when deploying, which is misleading. 
Add `ignore_code_extraction_warnings` to stack provider like the one in function provider.
No 
=> fix: Only outputing remote stack warning during building

samcli/lib/providers/sam_stack_provider.py, tests/integration/buildcmd/test_build_cmd.py, tests/integration/testdata/buildcmd/deep-nested/child-stack-x-template-symlink.yaml, tests/integration/testdata/buildcmd/deep-nested/template-with-symlink.yaml, tests/integration/testdata/buildcmd/deep-nested/template.yaml, tests/unit/commands/local/lib/test_stack_provider.py
reported by @kornicameister in #2690  
When child templates are symbolic link, the resources' paths in them cannot be resolved.
for example, stack_file_path = 'folder/t.yaml' -> '../folder2/t.yaml' and the path = 'src' the correct normalized path being returned should be '../folder2/t.yaml' but if we don't resolve the symlink first, it would return 'folder/src.'
resolve the symlink in `normalize_resource_path()`
=> fix: Build fails when child templates are symbolic links

samcli/commands/_utils/resources.py, samcli/commands/_utils/template.py, tests/integration/package/test_package_command_image.py, tests/integration/testdata/package/aws-lambda-function-image-and-api.yaml, tests/unit/commands/_utils/test_template.py
https://github.com/aws/aws-sam-cli/issues/2450
* only make `--s3-bucket` or `--image-repository` mandatory if there are
resources present in the template that have locations that need to be
packaged to different AWS destinations such as S3 or ECR.
* look for specific packageable resource locations based on their types to determine if `--s3-bucket` or `--image-repository` is required.
* for templates that have zero dependence on S3 or ECR, sam package will no longer require either `--s3-bucket` or `--image-repository`
```
template.yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
python3.8
Sample SAM Template for image
Globals:
Function:
Timeout: 3
Resources:
RailsHttpApi:
Type: AWS::Serverless::HttpApi
Properties:
StageName: PROD
~/..../ sam …
```
=> fix: --s3-bucket or --image-repository requirement

tests/unit/commands/init/test_cli.py
N/A
New templates added in https://github.com/aws/aws-sam-cli-app-templates/pull/86 will require one more user input instead of defaulting to the first and only template.
This hangs test_init_cli_no_package_type unit test.
=> fix: Added Template User Input to Unit Test for Python Image Init Templates

samcli/lib/providers/provider.py, samcli/lib/providers/sam_function_provider.py, tests/integration/buildcmd/build_integ_base.py, tests/integration/buildcmd/test_build_cmd.py, tests/integration/testdata/buildcmd/nested-with-intrinsic-functions/child-pass-down.yaml, tests/integration/testdata/buildcmd/nested-with-intrinsic-functions/child-pass-up.yaml, tests/integration/testdata/buildcmd/nested-with-intrinsic-functions/template-pass-down.yaml, tests/integration/testdata/buildcmd/nested-with-intrinsic-functions/template-pass-up.yaml, tests/unit/commands/local/lib/test_provider.py
fix #2724
sam-cli does not support resolving intrinsic functions in parameters/outputs, which results in incorrect layer reference when the layer is passed from some other stacks using intrinsic functions.
Before we have a great support of intrinsic functions, customers should still be able to build their stacks. Incorrect resolution of layers should only affect `local *`.
Delay the validation process and only raise exception when certain layer properties are used.
I added two integration tests to cover both using parameters (pass down) and outputs (pass up). 
*pass up: template-pass-up.yaml, pass down: template-pass-down.yaml
- pass up before: 
- `sam build` works, 
- `sam local invoke` works
- pass up now: 
- `sam build` works, 
- `sam local invoke`: ~`Error: {'Fn::GetAtt': ['ChildApp', …
=> fix: sam build fails when layer logicalID shared across stacks

samcli/commands/build/build_context.py, samcli/commands/build/command.py, samcli/commands/build/exceptions.py, samcli/lib/build/app_builder.py, samcli/local/docker/lambda_build_container.py, samcli/local/docker/manager.py, tests/integration/buildcmd/build_integ_base.py, tests/unit/commands/buildcmd/test_command.py, tests/unit/commands/samconfig/test_samconfig.py, tests/unit/lib/build_module/test_app_builder.py, tests/unit/local/docker/test_lambda_build_container.py
Integration tests will be added in another PR.
=> feat(Public ECR): Added --build-image Options

samcli/lib/telemetry/cicd.py, samcli/lib/telemetry/metric.py, tests/integration/telemetry/test_installed_metric.py, tests/unit/lib/telemetry/test_cicd.py, tests/unit/lib/telemetry/test_metric.py
=> feat: Add CICD platform to metrics

samcli/commands/local/cli_common/invoke_context.py, samcli/commands/local/cli_common/options.py, samcli/commands/local/invoke/cli.py, samcli/commands/local/lib/local_lambda.py, samcli/commands/local/start_api/cli.py, samcli/commands/local/start_lambda/cli.py, samcli/local/docker/container.py, samcli/local/docker/lambda_container.py, samcli/local/lambdafn/runtime.py, tests/unit/commands/local/cli_common/test_invoke_context.py, tests/unit/commands/local/invoke/test_cli.py, tests/unit/commands/local/lib/test_local_lambda.py, tests/unit/commands/local/start_api/test_cli.py, tests/unit/commands/local/start_lambda/test_cli.py, tests/unit/commands/samconfig/test_samconfig.py, tests/unit/local/docker/test_container.py, tests/unit/local/lambdafn/test_runtime.py
This reverts commit e653fe214255357aa6eb025dc060b2672d9e8e51.
=> Revert "feat: add option --container-host to commands local start-api, local start-lambda and local invoke (#2700)"

samcli/lib/telemetry/cicd.py, tests/unit/lib/telemetry/test_cicd.py
According to the doc https://www.jenkins.io/doc/book/pipeline/jenkinsfile/#working-with-your-jenkinsfile
`JENKINS_URL` is only available if Jenkins URL set in "System Configuration." So here we use `BUILD_TAG` to identify Jenkins instead to ensure no false negatives
=> chore: Use BUILD_TAG instead of JENKINS_URL to identify Jenkins env

samcli/__init__.py, tests/integration/testdata/buildcmd/Java/gradle-kotlin/build.gradle.kts, tests/integration/testdata/buildcmd/Java/gradle/build.gradle, tests/integration/testdata/buildcmd/Java/gradlew/build.gradle
Gradle java build failures.
`compile` was deprecated from Gradle
Replace `compile` to `implementation` in build.gradle
=> fix: Java Gradle 7 Build Test Data Issue

samcli/commands/local/cli_common/invoke_context.py, samcli/commands/local/cli_common/options.py, samcli/commands/local/invoke/cli.py, samcli/commands/local/lib/local_lambda.py, samcli/commands/local/start_api/cli.py, samcli/commands/local/start_lambda/cli.py, samcli/local/docker/container.py, samcli/local/docker/lambda_container.py, samcli/local/lambdafn/runtime.py, tests/unit/commands/local/cli_common/test_invoke_context.py, tests/unit/commands/local/invoke/test_cli.py, tests/unit/commands/local/lib/test_local_lambda.py, tests/unit/commands/local/start_api/test_cli.py, tests/unit/commands/local/start_lambda/test_cli.py, tests/unit/commands/samconfig/test_samconfig.py, tests/unit/local/docker/test_container.py, tests/unit/local/lambdafn/test_runtime.py
#2492 #2436
We found there is an issue of warm container with #2700 before release and remote Docker host is not support in that PR. So we decided to revert that change.
This PR includes following changes:
- #2700 which was reverted last week
- fix warm container issue when using `--container-host` option
- add remote Docker support by using a new option `--container-host-interface`. Customers can specify what interface they want to bind ports to with this option.
For Docker API call, we was binding ports to `127.0.0.1` which makes it can not be accessed from remote. With the new change, customers can bind ports to a specific host. In this way, using remote Docker host will be available.
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache …
=> feat: add option --container-host and --container-host-interface to sam local commands

mypy.ini, samcli/commands/init/__init__.py, samcli/commands/init/init_templates.py, samcli/lib/utils/git_repo.py, tests/unit/commands/init/test_cli.py, tests/unit/commands/init/test_templates.py, tests/unit/lib/utils/test_git_repo.py
#1713 
This refactors allows the reuse of `git clone` functionality in both `sam init` and `sam pipeline init` 
It extracts the `git clone`logic to its own class
N/A
=> refactor: Extract git-clone functionality out of InitTemplates class

.gitignore
No issue
After .Net Core 3.1 test data was added directories with temporary generated files where not added to .gitignore. As a result, in an environment with installed .Net Core and VSCode with OmniSharp server, those temporary files are generated on IDE startup.
Adding above mentioned directories to .gitignore
None
=> ignoring temp dirs used by dotnet

samcli/commands/exceptions.py, samcli/commands/pipeline/init/cli.py, samcli/commands/pipeline/init/interactive_init_flow.py, samcli/commands/pipeline/init/pipeline_templates_manifest.py, samcli/commands/pipeline/pipeline.py, samcli/lib/cookiecutter/interactive_flow_creator.py, samcli/lib/utils/git_repo.py, samcli/yamlhelper.py, tests/unit/commands/pipeline/init/test_cli.py, tests/unit/commands/pipeline/init/test_initeractive_init_flow.py, tests/unit/commands/pipeline/init/test_pipeline_templates_manifest.py
#1713 
part of sam-pipelines feature
by implementing new command`sam pipeline init` that generates the pipeline configuration files
N/A - new feature that doesn't affect existing code
=> sam pipeline init command

DEVELOPMENT_GUIDE.md
PREVIEW: https://github.com/aahung/aws-sam-cli/blob/dev-guide-overhaul/DEVELOPMENT_GUIDE.md
=> chore: Overhaul the development guide

samcli/commands/_utils/options.py, tests/integration/testdata/validate/default_json/template.json, tests/integration/testdata/validate/default_yaml/template.yaml, tests/integration/testdata/validate/multiple_files/template.json, tests/integration/testdata/validate/multiple_files/template.yaml, tests/integration/testdata/validate/with_build/.aws-sam/build/template.yaml, tests/integration/testdata/validate/with_build/template.json, tests/integration/validate/test_validate_command.py, tests/unit/commands/_utils/test_options.py
#2355
Allows users to validate template.json (in json instead of yaml format) without specifying `--template` argument with a path to the file. Improves user experience
Adding `template.json` to the list of default file names when looking up a template file.
None
=> Validate default template.json

samcli/lib/package/artifact_exporter.py, samcli/lib/package/packageable_resources.py, samcli/lib/package/utils.py, tests/unit/lib/package/test_artifact_exporter.py, tests/unit/lib/package/test_utils.py
#2779
The `CloudFormationStackResource` only check a URL against a limited s3 url format (to decide what artifact not to upload), causing package/deploy to fail.
Add a new `is_s3_url()` function to check all kinds of s3 urls and skip the upload when detecting so.
N/A
=> fix: package/deploy failure when Location/TemplateURL is virtual host S3 URL

samcli/local/lambdafn/runtime.py, tests/integration/local/invoke/test_integrations_cli.py, tests/integration/testdata/invoke/layers/local-zip-layer-template.yml, tests/unit/local/lambdafn/test_runtime.py
#947
Support passing a local archive file in "AWS::Serverless::LayerVersion" in local invoke
We already handle when function's codeuri points to a zip file, this PR extend that to `ContentUri` of LayerVersion
N/A
=> feat: Supports uncompression local layer zips in sam local

requirements/base.txt, requirements/reproducible-linux.txt, tests/integration/buildcmd/test_build_cmd.py, tests/integration/testdata/buildcmd/PythonPEP600/main.py, tests/integration/testdata/buildcmd/PythonPEP600/requirements.txt
=> chore: Update aws_lambda_builders to 1.4.0

tests/unit/lib/build_module/test_build_graph.py
NONE
There are no unit tests for LayerBuildDefinition in the build_graph unit test file, and eventhough its behaviour and implementation is quite similar to FunctionBuildDefinition, since they are separate clases and lists, we should also have it covered in the unit testing workflow.
It adds some missing asserts and a new test_case for LayerBuildDefinition.
None I am aware of.
=> Adds missing unit tests for LayerBuildDefinition in build_graph

samcli/commands/pipeline/bootstrap/cli.py, samcli/commands/pipeline/bootstrap/guided_context.py, samcli/commands/pipeline/init/interactive_init_flow.py, samcli/lib/pipeline/bootstrap/environment.py, samcli/lib/pipeline/bootstrap/environment_resources.yaml, samcli/lib/pipeline/bootstrap/resource.py, tests/unit/commands/pipeline/bootstrap/test_cli.py, tests/unit/commands/pipeline/bootstrap/test_guided_context.py, tests/unit/lib/pipeline/bootstrap/test_environment.py, tests/unit/lib/pipeline/bootstrap/test_resource.py
#1713 
Applying UX review action item
By renaming the pipeline bootstrap command argument `ecr-repo` to `image-repository` and change the code accordingly
N/A
=> Sam pipelines ux rename ecr repo to image repository

samcli/commands/pipeline/init/interactive_init_flow.py, samcli/lib/cookiecutter/template.py, tests/unit/commands/pipeline/init/test_initeractive_init_flow.py, tests/unit/lib/cookiecutter/test_template.py
Need to replace `APP_PIPELINE_TEMPLATES_REPO_URL` to run it.
```
APP_PIPELINE_TEMPLATES_REPO_URL = "https://github.com/aahung/aws-sam-cli-pipeline-init-templates-1.git"
```
=> feat: Support creating pipeline files directly into . without hooks

designs/sam-config.md, samcli/cli/cli_config_file.py, samcli/cli/main.py, samcli/cli/options.py, samcli/commands/_utils/options.py, tests/integration/buildcmd/build_integ_base.py, tests/integration/buildcmd/test_build_cmd.py, tests/integration/init/test_init_command.py
This reverts commit 2a13a69822660538c478118125eef50d0164995a.
Reverting to be able to release the new SAM CLI version.
This commit broke the local invoke integration tests.
I think we also need to review the update to the `click.echo` outputs, we may want to revert back to `LOG.debug` as this doesn't seem like a very meaningful information to display outside of the `--debug` parameter.
=> Revert "samconfig debug level logging fixed; documentation updated (#2891)"

tests/integration/validate/test_validate_command.py
Fixes the TestValidate::test_default_template_file_choice  tests for Windows.
The previous code was checking for a path starting with a `/` which is only for Unix/MacOS.
This fix doesn't check the beginning of the message anymore (unnecessary)
=> fix: Windows default template validation integration test

samcli/cli/types.py, tests/integration/deploy/test_deploy_command.py, tests/integration/testdata/package/samconfig-tags-list.toml, tests/integration/testdata/package/samconfig-tags-string.toml, tests/unit/cli/test_types.py, tests/unit/lib/build_module/test_build_graph.py
#2559 
Adds convenience for users to input tags as a string or a list in samconfig.toml file.
Allows user to write tags as a list or a string in samconfig.toml file.
None found
=> Enabled ability to provide tags as list in samconfig.toml file

requirements/dev.txt
a bug in 1.17.91, the fix https://github.com/vemel/mypy_boto3_builder/pull/82 has not yet been released. 
Pin to the latest version without the buggy
> [botocore-stubs] all exceptions kwargs are annotated properly
None, it is only used in CI
=> ci: Pin boto3-stubs to 1.17.90 due to a bug in 1.17.91

tests/integration/deploy/test_deploy_command.py
#2559
Fix the canary/integration tests that were failing
=> fix: Fixed deploy canary/integration tests for tags methods

samcli/lib/pipeline/bootstrap/environment_resources.yaml, tests/integration/pipeline/test_bootstrap_command.py
#1713 
Improves the S3 bucket security by:
1. Denys non ssl requests
2. Enable Server access logging
N/A
=> Sam pipelines s3 security

samcli/lib/pipeline/bootstrap/environment_resources.yaml, tests/integration/pipeline/test_bootstrap_command.py
#1713 
Fix a typo that caused the ArtifactsLoggingBucketPolicy policy to be assigned to the Artifacts Bucket instead of ArtifactsLogging Bucket
Corrects the typo in the "Bucket" CFN property
Ensuring the ArtifactsLoggingBucketPolicy denies non ssl requests
=> Ensure the ArtifactsLoggingBucket denies non ssl requests

samcli/lib/package/s3_uploader.py
https://github.com/aws/aws-sam-cli/issues/2665
If same package is tried to be packaged and/or deployed, same file exists message is printed as `debug` where it makes harder to be visible.
By changing the `debug` into `info`
N/A
=> feat: Increase awareness of same file warning during package

samcli/commands/pipeline/bootstrap/cli.py, samcli/commands/pipeline/bootstrap/guided_context.py, samcli/commands/pipeline/init/cli.py, samcli/commands/pipeline/init/interactive_init_flow.py, samcli/commands/pipeline/init/pipeline_templates_manifest.py, samcli/lib/pipeline/bootstrap/environment.py, tests/unit/commands/pipeline/init/test_initeractive_init_flow.py
#1713 
Minor UX improvements
N/A
=> Sam pipelines ux round 3

samcli/lib/pipeline/bootstrap/environment.py, tests/unit/lib/pipeline/bootstrap/test_environment.py
This change is maintaining consistency with AWS environment variable names.
=> Adding AWS_ prefix to displayed out.

samcli/commands/deploy/guided_context.py, samcli/lib/package/ecr_utils.py, samcli/lib/providers/sam_base_provider.py, samcli/lib/providers/sam_function_provider.py, tests/unit/commands/local/lib/test_sam_function_provider.py
#2934 
- Support deployment of `PackageType: Image` lambda functions of which the underlying Docker image is built/deployed externally to SAM.
- Checks whether or not the `ImageUri` property of a `AWS::Serverless::Function`, or `Code.ImageUri` property of a `AWS::Lambda::Function` is a valid ECR URL, based on the resource `PackageType`. If so, skips the local image build and prompts the user with a proper warning, similarly to `Zip` packaged lambdas.
```
Function:
Type: AWS::Serverless::Function
Properties:
PackageType: Image
ImageUri: 123456789012.dkr.ecr.eu-west-1.amazonaws.com/function:latest
```
```
% sam build
The resource AWS::Serverless::Function 'Function' has specified ECR registry image for ImageUri. It will not be built and SAM CLI does not support invoking it locally.
```
TBD …
=> fix: Skip build of Docker image if ImageUri is a valid ECR URL (#2934)

samcli/commands/package/validations.py, samcli/lib/iac/interface.py, samcli/lib/package/packageable_resources.py
=> Cdk support package and deploy fix

samcli/commands/pipeline/bootstrap/cli.py
```diff
Pipeline execution role.
CloudFormation execution role.
Artifacts bucket.
Should we proceed with the creation? [y/N]: y
Looking for resources needed for deployment: Not found.
Creating the required resources...
Successfully created!
We have created the following resources:
arn:aws:iam::***
arn:aws:iam::***
arn:aws:s3:::***
You provided the following resources. Please make sure it has the required permissions as shown at https://github.com/aws/aws-sam-cli/blob/develop/samcli/lib/pipeline/bootstrap/environment_resources.yaml
arn:aws:iam::***
+ The ARNs of created resources have been written to .aws-sam/pipeline/pipelineconfig.toml.
+ It will be used next time you run `sam pipeline bootstrap` or `sam pipeline init` commands in this directory.
```
By submitting this pull request, I …
=> Inform write to pipelineconfig.toml at the end of bootstrap

samcli/commands/pipeline/init/interactive_init_flow.py, samcli/lib/cookiecutter/question.py, tests/unit/commands/pipeline/init/test_initeractive_init_flow.py
**Template diff:**
```diff
diff --git a/GitHub-Actions/two-environment-pipeline-template/questions.json b/GitHub-Actions/two-environment-pipeline-template/questions.json
index 6133a8c..bc25eaf 100644
--- a/GitHub-Actions/two-environment-pipeline-template/questions.json
+++ b/GitHub-Actions/two-environment-pipeline-template/questions.json
@@ -15,6 +15,12 @@
"key": "sam_template",
"question": "What is the template file path?",
"default": "template.yaml"
+  }, {
+    "key": "message_list_environment_names_testing",
+    "question": {
+      "keyPath": ["environment_names_message"]
+    },
+    "kind": "info"
}, {
"key": "message_testing_environment_name",
"question": "We use the environment name to automatically retrieve the bootstrapped resources created when you ran `sam pipeline …
```
=> List detected env names in pipeline init when prompt to input the env name

samcli/commands/pipeline/bootstrap/cli.py, samcli/commands/pipeline/bootstrap/guided_context.py, samcli/commands/pipeline/external_links.py, samcli/lib/pipeline/bootstrap/environment.py, samcli/lib/pipeline/bootstrap/resource.py, samcli/lib/utils/colors.py, tests/unit/commands/pipeline/bootstrap/test_guided_context.py, tests/unit/lib/pipeline/bootstrap/test_environment.py, tests/unit/lib/pipeline/bootstrap/test_resource.py
=> Ux bootstrap revamp 20210706

samcli/lib/pipeline/bootstrap/environment.py, samcli/lib/pipeline/bootstrap/environment_resources.yaml, tests/unit/lib/pipeline/bootstrap/test_environment.py
Adding condition so that Cloudformation execution role can only be assumed by CFN from one account.
=> Adding account condition for CFN execution role.

samcli/commands/pipeline/bootstrap/cli.py, samcli/commands/pipeline/bootstrap/guided_context.py, samcli/commands/pipeline/init/cli.py, samcli/commands/pipeline/init/interactive_init_flow.py, samcli/lib/bootstrap/bootstrap.py, samcli/lib/cookiecutter/interactive_flow.py, samcli/lib/cookiecutter/question.py, samcli/lib/utils/profile.py, tests/unit/commands/pipeline/bootstrap/test_guided_context.py, tests/unit/commands/pipeline/init/test_cli.py, tests/unit/commands/pipeline/init/test_initeractive_init_flow.py, tests/unit/lib/bootstrap/test_bootstrap.py, tests/unit/lib/cookiecutter/test_question.py
=> pipeline UX revamp 20210707

samcli/commands/pipeline/bootstrap/guided_context.py, tests/unit/commands/pipeline/bootstrap/test_guided_context.py
=> chore: Account source list only uses numbers

samcli/commands/pipeline/bootstrap/cli.py, samcli/commands/pipeline/bootstrap/guided_context.py, samcli/commands/pipeline/init/cli.py, samcli/commands/pipeline/init/interactive_init_flow.py, samcli/lib/pipeline/bootstrap/stage.py
=> Fixing various cosmetics UX issues with pipeline workflow.

samcli/commands/init/__init__.py
=> fix: interactive creating CDK project won't direct to the correct resource

samcli/commands/pipeline/init/interactive_init_flow.py
```
Checking for existing stages...
[!] None detected in this account.
To set up stage(s), please quit the process using Ctrl+C and use one of the following commands:
sam pipeline init --bootstrap		To be guided through the stage and config file creation process.
sam pipeline bootstrap				To specify details for an individual stage.
To reference stage resources bootstrapped in a different account, press enter to proceed []:
```
=> Updating message when bootstrap stages are missing.

tests/integration/pipeline/base.py, tests/integration/pipeline/test_bootstrap_command.py
Fixing integration tests for pipeline bootstrap command.
=> Fixing bootstrap integ tests.

tests/integration/pipeline/base.py, tests/integration/pipeline/test_bootstrap_command.py
=> Fix bootstrap test region

samcli/lib/pipeline/bootstrap/stage.py, tests/integration/pipeline/base.py, tests/integration/pipeline/test_init_command.py, tests/integration/testdata/pipeline/custom_template/metadata.json, tests/unit/lib/pipeline/bootstrap/test_environment.py
=> Add more pipeline init integ test

tests/integration/pipeline/test_bootstrap_command.py
=> Config file bug

tests/integration/pipeline/test_init_command.py
=> Fix pipeline init integ test because of pipelineconfig file exists

samcli/lib/pipeline/bootstrap/stage_resources.yaml
To support AWS CodePipeline init template
=> Allow roles with Tag aws-sam-pipeline-codebuild-service-role to assume PipelineExecutionRole

requirements/base.txt, requirements/reproducible-linux.txt
=> chore: bump aws-lambda-builder version to 1.5.0

samcli/commands/pipeline/bootstrap/cli.py, samcli/commands/pipeline/init/cli.py, samcli/commands/pipeline/init/interactive_init_flow.py, tests/integration/testdata/pipeline/expected_jenkinsfile
=> chore: Refine pipeline help text and update unit test

installer/pyinstaller/hook-samcli.py, samcli/__init__.py
=> Add pipeline to pyinstaller

samcli/lib/utils/git_repo.py, tests/unit/commands/init/test_cli.py, tests/unit/commands/init/test_templates.py, tests/unit/lib/utils/test_git_repo.py
**To make `make pr` great again**
Speed up the `make pr` (specifically `make test`) and reduce its time by 65%
```
2346 passed, 12 skipped, 20 warnings in 103.91s (0:01:43)
to
2346 passed, 12 skipped, 20 warnings in 35.22s
```
Avoid making `git clone` on the same URL over and over again.
N/A
=> ci: Speed up unit test by caching the git clone

samcli/commands/delete/delete_context.py, samcli/lib/delete/cf_utils.py, samcli/lib/package/ecr_uploader.py, samcli/lib/package/packageable_resources.py, samcli/lib/package/s3_uploader.py, tests/integration/delete/delete_integ_base.py, tests/integration/delete/test_delete_command.py, tests/integration/testdata/delete/aws-ecr-repository.yaml, tests/integration/testdata/delete/aws-serverless-function-retain.yaml, tests/unit/commands/delete/test_delete_context.py, tests/unit/lib/delete/test_cf_utils.py
Bugs fixed and new changes:
- No stack-name present when no-prompts is provided
- No region present when no-prompts is provided
- Retaining everything when a stack has termination protection enabled
- ecr_uploader.delete_artifact tries to delete an image from a repository that is already deleted (In the case of deleting ECR Companion Stack)
- Double checking if s3_bucket and key are strings in packageable_resources
- More integration tests for guided and non-guided delete
=> Sam delete bug fixes

tests/integration/buildcmd/test_build_cmd.py
=> fix: integration test case related to recent fix on ruby

tests/integration/deploy/test_deploy_command.py, tests/integration/package/test_package_command_image.py, tests/integration/testdata/package/aws-lambda-function-image-and-api.yaml, tests/integration/testdata/package/aws-lambda-function-image.yaml, tests/integration/testdata/package/aws-serverless-function-image.yaml, tests/integration/testdata/package/deep-nested-image/ChildStackX/ChildStackY/template.yaml, tests/integration/testdata/package/deep-nested-image/ChildStackX/template.yaml, tests/integration/testdata/package/deep-nested-image/template.yaml
Our Canaries keep failing with Dockerhub limits. We are hitting this because some of our tests are downloading and using images from Dockerhub. This PR forces us to use images that are on Public ECR.
=> fix(integ): Use images that are in public ecr

tests/integration/deploy/test_deploy_command.py, tests/integration/package/test_package_command_image.py, tests/integration/testdata/package/aws-lambda-function-image-and-api.yaml, tests/integration/testdata/package/aws-lambda-function-image.yaml, tests/integration/testdata/package/aws-serverless-function-image.yaml, tests/integration/testdata/package/deep-nested-image/ChildStackX/ChildStackY/template.yaml, tests/integration/testdata/package/deep-nested-image/ChildStackX/template.yaml, tests/integration/testdata/package/deep-nested-image/template.yaml
=> fix(integ): Fix Invalid image tag errors

samcli/commands/delete/delete_context.py, tests/unit/commands/delete/test_delete_context.py
Small PR to merge SAM Delete and Auto ECR.
=> refactor(Delete): Refactor SAM Delete to Use Auto ECR

samcli/lib/bootstrap/bootstrap.py
#3243
`sam deploy` fails if the bootstrap CFn stack is not created yet.
The reason is that the creation of `SamCliSourceBucketBucketPolicy` fails.
The Events tab of CFn console tells "The specified bucket is not valid. (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketName)".
`!Ref` can only be used in YAML.
All `"!Ref foo"` are changed to `{"Ref": "foo"}`.
=> fix: `sam deploy` fails because bootstap stack is not created 

requirements/base.txt, requirements/reproducible-linux.txt
https://github.com/aws/aws-lambda-builders/issues/229
https://github.com/aws/aws-lambda-builders/issues/253
https://github.com/aws/aws-lambda-builders/issues/114
* Update AWS Lambda Builders to Latest which is v1.7.0
* Allows building pep517 based python packages. 
* None
=> chore: update aws-lambda-builders to 1.7.0

samcli/lib/observability/xray_traces/xray_event_puller.py, tests/unit/lib/observability/xray_traces/test_xray_event_puller.py
When pulling XRay traces, it sometimes returns partial results where the trace recording is not completed, and their times have been reported wrong (zeros or negative values).
This change will fix this issue by not pulling certain XRay trace if it is still marked as partial
=> fix: don't pull partial xray traces

tests/integration/buildcmd/build_integ_base.py, tests/integration/buildcmd/test_build_cmd.py, tests/testing_utils.py
Added `SKIP_DOCKER_BUILD` instead of commenting out build tests.
=> fix: Temp disabling build images integration tests, skipping ARM64 invoking for Go1.x (not supported yet)

samcli/commands/pipeline/bootstrap/cli.py, samcli/commands/pipeline/bootstrap/guided_context.py, samcli/commands/pipeline/init/interactive_init_flow.py, samcli/lib/config/samconfig.py, samcli/lib/pipeline/bootstrap/stage.py, tests/integration/pipeline/base.py, tests/integration/pipeline/test_bootstrap_command.py, tests/integration/pipeline/test_init_command.py, tests/unit/commands/pipeline/bootstrap/test_cli.py, tests/unit/commands/pipeline/bootstrap/test_guided_context.py, tests/unit/commands/pipeline/init/test_initeractive_init_flow.py, tests/unit/lib/pipeline/bootstrap/test_environment.py, tests/unit/lib/samconfig/test_samconfig.py
Change some uses of stage name to configuration name - clarifying you cannot actually name the stage
=> Change some uses of stage name to configuration name

installer/pyinstaller/Instruction.md, installer/pyinstaller/build-linux.sh
Reverts aws/aws-sam-cli#3393
https://github.com/aws/aws-sam-cli/issues/3416
Tested on Ubuntu 20.04. Compared ldd with previous script, no diff was found.
ldd output on `quay.io/pypa/manylinux2014_x86_64:2021-01-24-91ce2b8`:
```
.build/output/pyinstaller-output/dist/array.cpython-37m-x86_64-linux-gnu.so:
linux-vdso.so.1 =>  ()
libpython3.7m.so.1.0 => /usr/local/lib/libpython3.7m.so.1.0 ()
libpthread.so.0 => /lib64/libpthread.so.0 ()
libc.so.6 => /lib64/libc.so.6 ()
libcrypt.so.2 => /usr/local/lib/libcrypt.so.2 ()
libdl.so.2 => /lib64/libdl.so.2 ()
libutil.so.1 => /lib64/libutil.so.1 ()
libm.so.6 => /lib64/libm.so.6 ()
/lib64/ld-linux-x86-64.so.2 ()
.build/output/pyinstaller-output/dist/_asyncio.cpython-37m-x86_64-linux-gnu.so:
linux-vdso.so.1 =>  ()
libpython3.7m.so.1.0 => …
```
=> Revert "Revert "Fix #3334""

requirements/base.txt
https://github.com/aws/aws-sam-cli/issues/3417
Bump boto3 version to be minimal 1.18.32 as DisableRollback is add in this version.
=> fix: Bumped Minimal boto3 Version to 1.18.32

installer/pyinstaller/build-linux.sh
```
Removing CI Scripts
removed ‘./output/aws-sam-cli-src/appveyor-windows-build-dotnet.yml’
removed ‘./output/aws-sam-cli-src/appveyor-windows-build-go.yml’
removed ‘./output/aws-sam-cli-src/appveyor-windows-build-java-container.yml’
removed ‘./output/aws-sam-cli-src/appveyor-windows-build-java-ruby-inprocess.yml’
removed ‘./output/aws-sam-cli-src/appveyor-windows-build-nodejs.yml’
removed ‘./output/aws-sam-cli-src/appveyor-windows-build-python.yml’
removed ‘./output/aws-sam-cli-src/appveyor-windows-build-ruby.yml’
removed ‘./output/aws-sam-cli-src/appveyor-windows.yml’
removed ‘./output/aws-sam-cli-src/appveyor.yml’
Installing Python
``` …
=> fix: Remove CI Scripts from PyInstaller Package

.github/workflows/README.md, .github/workflows/pr-labeler.yml, requirements/dev.txt, samcli/commands/init/interactive_event_bridge_flow.py, samcli/commands/pipeline/init/pipeline_templates_manifest.py, samcli/lib/cookiecutter/question.py, samcli/lib/pipeline/bootstrap/resource.py
n/a
By default `pull_request_target` github actions run on `opened`, `synchronize`, or `reopened`. This causes updates to the PR to be improperly tagged when a maintainer updates the PR from `HEAD` of `develop`. Instead, we will only run the PR github actions on open for the auto labeler.
No
=> Only add labels on open of PRs

tests/integration/deploy/test_deploy_command.py, tests/integration/testdata/sync/infra/after/Ruby/function/Gemfile, tests/integration/testdata/sync/infra/after/Ruby/layer/Gemfile, tests/integration/testdata/sync/infra/before/Ruby/function/Gemfile, tests/integration/testdata/sync/infra/before/Ruby/layer/Gemfile, tests/integration/testdata/sync/infra/template-ruby-after.yaml, tests/integration/testdata/sync/infra/template-ruby-before.yaml
=> fix: Correction of integration tests for canary environments

samcli/commands/_utils/template.py, tests/integration/buildcmd/build_integ_base.py, tests/integration/buildcmd/test_build_cmd.py, tests/unit/commands/_utils/test_template.py
=> (fix) stop resolving relative paths for Function image URI

samcli/commands/local/lib/swagger/parser.py, tests/integration/local/start_api/test_start_api.py, tests/integration/testdata/start_api/swagger-template.yaml, tests/unit/commands/local/lib/swagger/test_parser.py
accept `AWS_PROXY` as integration type
=> fix: accept AWS_PROXY as integration type

samcli/commands/validate/validate.py, tests/integration/validate/test_validate_command.py
add unsupported command to asm validate in case of CDK synthesized templates
=> feat: add unsupported command to asm validate in case of CDK synthesized templates

samcli/lib/build/app_builder.py, tests/integration/buildcmd/test_build_cmd.py, tests/integration/testdata/buildcmd/layers-functions-template.yaml, tests/unit/lib/build_module/test_app_builder.py
use the correct content property for Lambda Layer Version
=> fix: use the correct content property for Lambda Layer Version

samcli/lib/build/app_builder.py, samcli/lib/build/build_graph.py, samcli/lib/utils/file_observer.py, samcli/local/lambdafn/runtime.py, tests/unit/lib/build_module/test_app_builder.py, tests/unit/lib/build_module/test_build_graph.py
=> fix: copy normalized metadata to built resources only

samcli/lib/bootstrap/nested_stack/nested_stack_builder.py, samcli/lib/bootstrap/nested_stack/nested_stack_manager.py, tests/integration/deploy/test_deploy_command.py, tests/integration/package/test_package_command_zip.py, tests/integration/testdata/package/aws-cloudformation-stack-child.yaml, tests/integration/testdata/package/aws-cloudformation-stack-regression.yaml, tests/integration/testdata/package/aws-serverlessrepo-application_regression.yaml, tests/integration/testdata/sync/infra/after/Ruby/function/Gemfile, tests/integration/testdata/sync/infra/after/Ruby/layer/Gemfile, tests/integration/testdata/sync/infra/before/Ruby/function/Gemfile, tests/integration/testdata/sync/infra/before/Ruby/layer/Gemfile, tests/integration/testdata/sync/infra/template-ruby-after.yaml, tests/integration/testdata/sync/infra/template-ruby-before.yaml, tests/integration/validate/test_validate_command.py, tests/regression/package/regression_package_base.py, tests/regression/package/test_package_regression.py, tests/unit/lib/bootstrap/nested_stack/test_nested_stack_builder.py
=> test: Develop fix regression test cases

tests/integration/sync/test_sync_command.py
=> fix: Adjustments for integration test failures

samcli/commands/init/init_templates.py, samcli/lib/init/local_manifest.json, samcli/local/common/runtime_template.py, tests/unit/commands/init/test_cli.py
https://github.com/aws/aws-sam-cli/issues/3576
Customers are currently experience issues when they can't clone
Allow customers without internet or who can't clone the git repo access internal template without breaking
None
=> Fix: Use Internal CLI templates

samcli/lib/sync/flows/generic_api_sync_flow.py, samcli/lib/sync/flows/stepfunctions_sync_flow.py, tests/unit/lib/sync/flows/test_http_api_sync_flow.py, tests/unit/lib/sync/flows/test_rest_api_sync_flow.py, tests/unit/lib/sync/flows/test_stepfunctions_sync_flow.py
N.A.
Without this change any definition files will not be found correctly if base_dir option is not respected for customers who have code directory somewhere else
It adds the base_dir into the full path of the definition files
N.A.
=> Fix: Make resource syncs respect base dir option

appveyor-iac-integration-ubuntu.yml, appveyor-ubuntu.yml, appveyor.yml
N/A
Our CI is broken due to trying to install pip for Python 3.6 which reached its EOL.
```
If ($env:INSTALL_PY_36_PIP) {python3.6 get-pip.py --user}
ERROR: This script does not work on Python 3.6 The minimum supported Python version is 3.7. Please use https://bootstrap.pypa.io/pip/3.6/get-pip.py instead.
```
Download a separate 3.6 script and install it instead.
N/A
=> fix: Updated get-pip.py for Python3.6

README.md, samcli/commands/_utils/click_mutex.py, samcli/commands/init/__init__.py, samcli/commands/local/cli_common/click_mutex.py, samcli/commands/sync/command.py, tests/integration/init/test_init_command.py, tests/unit/commands/_utils/test_click_mutex.py
N/A
For sam sync, both --watch and --code can be specified at the same time, but this is not a valid workflow.
In such case --code is ignored and a normal --watch is started.
Refactored click_mutex.py to be reusable outside of sam init.
Format of the sam init errors are changed but the content is the same.
=> fix: Add Validation for Incompatible watch and code Options

tests/integration/testdata/buildcmd/Provided/Makefile-container
Fix provided Makefile build tests by downloading compatible `get-pip.py` file
=> fix: provided makefile py36 tests

appveyor-windows-build-dotnet.yml, appveyor-windows-build-go.yml, appveyor-windows-build-java-container.yml, appveyor-windows-build-java-ruby-inprocess.yml, appveyor-windows-build-nodejs.yml, appveyor-windows-build-python.yml, appveyor-windows-build-ruby.yml, appveyor-windows.yml, appveyor.yml
Update all `pytest` commands to use `ps:` prefix to resolve issues with windows tests.
=> chore: use ps prefix for windows integration tests to run pytest commands

build_dir/MyFunctionbf3066d1DepLayer/AWS_SAM_CLI_README, samcli/lib/build/build_graph.py, tests/unit/lib/build_module/test_build_graph.py
SAM-CLI calls Lambda Builders only once for each CodeURI. This works for existing runtimes since everything in the CodeURI gets built. For esbuild, independent handlers within the same CodeURI are built separately, meaning that all of the handlers within a CodeURI need to be added as entry points.
=> feat: Allow Independent Build Definitions Based on Build Method

requirements/base.txt, requirements/reproducible-linux.txt
=> chore: bump aws-lambda-builders to 1.11.0 version

samcli/lib/build/app_builder.py, samcli/lib/build/build_graph.py, tests/unit/lib/build_module/test_build_graph.py, tests/unit/lib/build_module/test_build_strategy.py
Update the build definition comparison to handle esbuild needing a separate build for each handler.
=> feat: Update build graph to include handler for esbuild comparison
