aws/aws-sam-cli

distribution/npm/npm-release.sh
http://npmjs.com/package/aws-sam-local looks bare without a README.
=> Updating NPM publish script to add README.md to the package

test/templates/output_section.yaml, validate_test.go, vendor/github.com/awslabs/goformation/unmarshal.go
Test passes
```
➜  aws-sam-local git:(JoinIssue) go test
Running Suite: AwsSamLocal Suite
================================
Random Seed: 1502591448
Will run 30 of 30 specs
••••••••••••••••••••••••••••••
Ran 30 of 30 Specs in 0.001 seconds
SUCCESS! -- 30 Passed | 0 Failed | 0 Pending | 0 Skipped PASS
```
=> !Join fails validation because of missing colon in regex. Fixes #25

README.md
I did not have this and did not get any error message
=> Docker file sharing need to be enabled for project directory. (DOC)

runtime_test.go
Adding tests - mainly for my own understanding but thought it might be useful in the future.
=> Adding tests for getEnvironmentVariables

runtime.go
Thanks for #75 , I could use aws-sam-local with jersey java project. However, when I apply aws-sam-local to my application, error as following was occurred.
``` shell
2017/08/21 13:03:36 ERROR: Failed to decompress archive: open /private/var/folders/j5/89qxx8y14cq1hmnz15j0vswm4n16zq/T/aws-sam-local-1503288213879995074/com/amazonaws/services/kms/model/DisableKeyRequest.class: too many open files
```
This error maybe occurred because of defer queue explosion. So I add anonymous function to in the loop to prevent to this, execute defer operation at each loop.
=> Prevent `too many open files` error at the time of file opening loop

README.md
=> Added npm permissions info.

generate-event.go
=> Replace all httpMethod attributes in the generated api event

invoke.go, start.go
Fixes issue #124 
Passed tests with `go test`
=> Fixes issue 124: No log file is written with log-file

runtime.go
=> Add Go 1.x support

runtime.go
Thanks heaps to @romanlum for kicking this off and putting in a huge effort for https://github.com/lambci/docker-lambda/pull/68
=> Add .NET Core 2.0 support

README.md
Document the use of `--profile` as an argument in `start-api`
=> Update README.md --profile use documentation

README.md, runtime.go
=> Add support for the Node.js 8.10 Runtime

README.rst
I remove the text that links to samples folders.
=> docs: remove broken links to sample code.

CONTRIBUTING.md
Added some additional things Contributors should be checking before submitting a PR to the repo
=> docs: Add more details on Contributing through PR

samcli/local/init/templates/cookiecutter-aws-sam-hello-python/{{cookiecutter.project_name}}/README.md
=> docs: Corrected typo in init's Python example README

README.rst
Changes made in this PR:
*  Formatting issues under Package and Deploy section
*  Emphasis on ``sam init`` under Usage
*  Rename Upgrading from... to Upgrading and inverted instruction order
*  Add explicit command on update preferred shell configuration under Installation
*  Updates menu and removes redundant info on install/troubleshooting
*  Separate `Pyenv` and other advanced installation to another section
*  Adds Path adjustment procedure along with installation
*  `sam` formatting issue
*  Removes redundant Py2.7 verification (pre-req + validation + verification)
*  Emphasize OSes and adds link to Docker file sharing options
*  Emphasis on py3 support pre-req
By submitting this pull request, I confirm that my contribution is made …
=> feat: README clean up on installation, menu and formatting

DESIGN.rst
* N/A
* Just a correction of indentation on DESIGN.rst
=> fix: change indentation on DESIGN.rst

README.rst, samcli/local/docker/lambda_container.py
This is now supported on docker-lambda
=> Add dotnetcore2.1 container support

README.rst
=> docs: Adding readme for "sam logs" and "sam local start-lambda" command

README.rst
*Issue:* #583
I've added missing dependencies (`botocore`), update constants references, added a default region, and improved indentation for readability.
ping @jfuss @sanathkr
=> Sample code should run properly without changes

samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/hello_world/app.js, samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/template.yaml
I've only renamed the handler (because camel case!).
ping @sanathkr
=> Minor improvements for Node.js init template

samcli/local/init/templates/cookiecutter-aws-sam-hello-java/{{cookiecutter.project_name}}/pom.xml, tests/integration/testdata/invoke/runtimes/java8/pom.xml
aws-lambda-java-core 1.1.0 -> 1.2.0
=> aws-lambda-java-core 1.1.0 -> 1.2.0

README.rst
Signed-off-by: Campion Fellin <campio@amazon.com>
*Issue #, if available:* #432 
*Description of changes:* Add `awscli` to list of dependencies.
=> Update README prerequisites to include awscli

README.rst
*Description of changes:* Remove an unnecessary/incorrect comma
=> Update README.rst for grammar fix

samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/hello_world/package.json
https://github.com/awslabs/aws-sam-cli/issues/585
=> Fix Broken link Issue 585

docs/installation.rst
=> Fixed typo

docs/installation.rst
*Description of changes:* just fixed a typo in the docs
=> change sam -version to sam --version

samcli/__init__.py
=> chore(0.6.0): SAM CLI Version bump

samcli/commands/init/__init__.py
=> Removed dual line

docs/usage.rst
=> fix generate-sample-event-payloads link

requirements/base.txt
Upgrading to the newly released 1.7.0 version of SAM
=> chore: update requirements to use new version of aws-sam-translator

DEVELOPMENT_GUIDE.rst
*Issue #, if available:* NA
*Description of changes:* Minor change to Dev Guide samcli36 -> samcli37
=> Updated virtualenv alias name for 3.7 in dev guide.

docs/usage.rst
*Issue #, if available:* https://github.com/awslabs/aws-sam-cli/issues/54 https://github.com/awslabs/aws-sam-cli/issues/172 
**Special Thanks** to [Sriram](https://twitter.com/TheSrirama) for discovering that
=> Explain how to debug Python functions using VS Code

samcli/__init__.py
=> chore(0.6.1): SAM CLI Version bump

docs/installation.rst
=> lowercase needed for docker

.travis.yml, samcli/local/apigw/local_apigw_service.py, tests/unit/local/apigw/test_local_apigw_service.py
=> chore: Enable Travis to run integ tests

samcli/__init__.py
=> chore(version_bump): bump to 0.6.2

samcli/__init__.py
=> Bumping version to 0.7.0 in preparation for release

samcli/commands/deploy/__init__.py, samcli/commands/package/__init__.py, samcli/lib/samlib/cloudformation_command.py, tests/unit/lib/samlib/test_cloudformation_command.py
#782 
Check for AWS CLI installation, and if not found, fail with a proper error message.
*Checklist:*
=> AWS CLI on windows can be called aws.cmd or aws.exe

samcli/__init__.py, samcli/cli/options.py, tests/integration/local/invoke/test_integrations_cli.py
=> chore: v0.8.1 Release

README.rst
=> list ruby as supported runtime

tests/functional/commands/local/lib/test_local_api_service.py, tests/functional/commands/local/lib/test_local_lambda.py, tests/functional/local/apigw/test_local_apigw_service.py, tests/functional/local/docker/test_lambda_container.py, tests/functional/local/lambda_service/test_local_lambda_invoke.py, tests/functional/local/lambdafn/test_runtime.py
=> fix: Update functional tests to work

samcli/__init__.py
=> chore(version): bump version to 0.10.0

README.md
seems like leftovers from #891
looked but didn't see any.
fixed links to doc pages from .rst to .md
*Checklist:*
=> fix links to .md files

samcli/commands/local/lib/local_lambda.py, tests/unit/commands/local/lib/test_local_lambda.py
=> refactor(logging): Add additional information when function not found

tests/integration/publish/publish_app_integ_base.py
=> fix(publish): fix failing integ tests due to .rst to .md file changes

tests/integration/testdata/publish/metadata_create_app.json, tests/integration/testdata/publish/metadata_create_app_version.json, tests/integration/testdata/publish/metadata_update_app.json, tests/integration/testdata/publish/template_create_app.yaml, tests/integration/testdata/publish/template_create_app_version.yaml, tests/integration/testdata/publish/template_not_packaged.yaml, tests/integration/testdata/publish/template_update_app.yaml
=> fix(publish): fix integ test metadata and templates

samcli/local/init/templates/cookiecutter-aws-sam-hello-python/README.md
=> Fix Python Cookiecutter README

requirements/base.txt
=> chore: Bump aws-sam-transform to 1.9.1

samcli/__init__.py
=> chore(release): Bump version to 0.12.0

samcli/__init__.py
=> chore: bump version to 0.13.0

requirements/base.txt
=> chore: Bump aws-lambda-builers to 0.2.1

samcli/__init__.py
=> chore: Version bump SAM CLI to 0.14.0

samcli/__init__.py
=> chore: Version bump SAM CLI to 0.14.1

samcli/__init__.py
=> chore: Version bump SAM CLI to 0.14.1 (#1082)

samcli/__init__.py
=> chore: bump version to 0.14.2

samcli/__init__.py, samcli/local/init/templates/cookiecutter-aws-sam-hello-java-gradle/{{cookiecutter.project_name}}/HelloWorldFunction/build.gradle
=> Release: v0.14.2

README.md
=> fixed Contributors

samcli/local/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/src/HelloWorld/HelloWorld.csproj
=> fix(dotnet): init dependencies to latest

samcli/__init__.py
Just a merge to get dotnet_build_support upto date with latest from develop
=> chore(version): set 0.14.3.dev1 version (#1112)

samcli/__init__.py
=> chore(version): set 0.15.0

requirements/base.txt
0.3.0 will be released soon.. Staging the version bump here
*Checklist:*
=> Bumping to Lambda Builders 0.3.0

tests/functional/init/test_generate_project.py
=> fix(func-tests): add dependency manager param

samcli/local/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/src/HelloWorld/HelloWorld.csproj, samcli/local/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/src/HelloWorld/aws-lambda-tools-defaults.json, samcli/local/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/test/HelloWorld.Test/HelloWorld.Tests.csproj
=> fix(init): Default all configuration to dotnetcore2.1 for dotnetcore

samcli/__init__.py
=> chore(version): version bump to 0.16.0

samcli/__init__.py
=> Bumping to v0.16.1

designs/_template.md
=> Add testing plan (QA) questions to design document

samcli/__init__.py
=> chore: bump version to 0.17.0

.travis.yml
=> chore(python3.8): Add Python3.8 to Travis builds

samcli/__init__.py
Bump version to 0.18.0
*Checklist:*
=> chore: bump version to 0.18.0

samcli/commands/local/lib/api_collector.py, samcli/commands/local/lib/api_provider.py, samcli/commands/local/lib/cfn_api_provider.py, samcli/commands/local/lib/cfn_base_api_provider.py, samcli/commands/local/lib/local_api_service.py, samcli/commands/local/lib/provider.py, samcli/commands/local/lib/sam_api_provider.py, samcli/commands/local/lib/sam_base_provider.py, tests/integration/local/start_api/test_start_api.py, tests/integration/testdata/start_api/swagger-rest-api-template.yaml, tests/unit/commands/local/lib/test_api_provider.py, tests/unit/commands/local/lib/test_cfn_api_provider.py, tests/unit/commands/local/lib/test_local_api_service.py, tests/unit/commands/local/lib/test_sam_api_provider.py
=> Re-Revert "feat(start-api): CloudFormation AWS::ApiGateway::RestApi support (#1238)"

samcli/__init__.py, samcli/cli/main.py
=> chore: Bumping to v0.19.0 and updating Telemetry Opt-Out URL

samcli/cli/main.py
=> fix: Update telemetry prompt wording

samcli/lib/samlib/cloudformation_command.py, tests/unit/lib/samlib/test_cloudformation_command.py
=> feat: Set execution environment when calling AWS CLI

requirements/base.txt
=> Upgrade dependencies

samcli/commands/local/lib/api_collector.py, samcli/commands/local/lib/api_provider.py, samcli/commands/local/lib/cfn_api_provider.py, samcli/commands/local/lib/cfn_base_api_provider.py, samcli/commands/local/lib/local_api_service.py, samcli/commands/local/lib/provider.py, samcli/commands/local/lib/sam_api_provider.py, samcli/commands/local/lib/sam_base_provider.py, samcli/commands/local/lib/swagger/parser.py, samcli/commands/local/lib/swagger/reader.py, samcli/local/apigw/local_apigw_service.py, tests/functional/commands/local/lib/test_local_api_service.py, tests/integration/local/start_api/test_start_api.py, tests/integration/testdata/start_api/swagger-rest-api-template.yaml, tests/unit/commands/local/lib/swagger/test_parser.py, tests/unit/commands/local/lib/swagger/test_reader.py, tests/unit/commands/local/lib/test_api_provider.py, tests/unit/commands/local/lib/test_cfn_api_provider.py, tests/unit/commands/local/lib/test_local_api_service.py, tests/unit/commands/local/lib/test_sam_api_provider.py, tests/unit/local/apigw/test_local_apigw_service.py
=> feat(start-api): Support for RestApi and Stage of CloudFormation resources

samcli/__init__.py
=> chore: Version bump for 0.20.0 release

samcli/__init__.py
=> chore: Update version to 0.20.1

samcli/commands/local/lib/generated_sample_events/events/apigateway/AwsProxy.json, samcli/commands/local/lib/generated_sample_events/events/ses/SesEmailReceiving.json
Everything switched to triple mustache in #824 except for these two
occurrences.
*Issue #, if available:* N/A
*Description of changes:* See above
*Checklist:*
=> fix(generate-event): Remove two remaining cases of double mustache

Makefile
=> chore: Run black --check on make pr

requirements/base.txt, requirements/isolated.txt, samcli/__init__.py
=> chore: Bumping SAM Translator version

requirements/isolated.txt
bump in dateparser libray to 0.7.2
*Checklist:*
=> fix: isolated requirements

requirements/dev.txt
=> fix: pin pytest-forked to 1.0.2

requirements/base.txt, requirements/isolated.txt
=> chore: version bump on aws-lambda-builders to 0.5.0

samcli/__init__.py
=> chore: bump version to 0.23.0

samcli/commands/local/lib/generated_sample_events/events/cloudfront/CloudFrontServeObjectOnViewerDevice.json
Fix typo in CloudFrontServeObjectOnViewerDevice test event
N/A
Fix typo in CloudFrontServeObjectOnViewerDevice test event, dektop -> desktop
*Checklist:*
=> Fix typo in CloudFrontServeObjectOnViewer event

samcli/__init__.py
=> chore: bump version to 0.30.0

README.md
#1497 
Fixed slack channel link
I referred: https://github.com/awslabs/serverless-application-model/pull/1177
*Checklist:*
- ~Write Design Document ([Do I need to write a design document?](https://github.com/awslabs/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.rst#design-document))~
- ~Write unit tests~
- ~Write/update functional tests~
- ~Write/update integration tests~
=> fix: slack channel link

samcli/commands/init/interactive_init_flow.py
=> Remove non-interactive command explainer

samcli/__init__.py
=> chore: Bump version to 0.31.0

Makefile, tests/regression/package/regression_package_base.py
=> fix: compare dictionaries instead of json strings for regression test

samcli/__init__.py
=> chore: Bump version to 0.31.1

samcli/cli/cli_config_file.py, samcli/commands/_utils/table_print.py, samcli/commands/build/command.py, samcli/commands/deploy/command.py, samcli/commands/deploy/deploy_context.py, samcli/commands/deploy/exceptions.py, samcli/lib/config/samconfig.py, samcli/lib/deploy/deployer.py, tests/unit/commands/deploy/test_command.py, tests/unit/lib/deploy/test_deployer.py
- change sam build output text
*Checklist:*
=> fix: usability fixes on deploy --guided

samcli/lib/config/samconfig.py, tests/unit/lib/config/test_samconfig.py
=> fix: only create config file on write

samcli/__init__.py
=> chore: Version bump to 0.32.0

samcli/commands/deploy/command.py, samcli/lib/bootstrap/bootstrap.py
=> Reduce guided output

samcli/lib/bootstrap/bootstrap.py
=> feat: s3 bucket versioning - managed stack

samcli/__init__.py
=> chore: release v0.33.0

tests/integration/publish/publish_app_integ_base.py
=> fix: move the sleep before applying bucket policy

tests/unit/lib/utils/test_file_utils.py
=> tests: close tempfile before attempting to delete

samcli/commands/deploy/deploy_context.py
=> fix: showcase changeset arn on deploy

samcli/__init__.py
=> chore: Version bump to 0.33.1

samcli/__init__.py, samcli/commands/deploy/deploy_context.py
=> 0.33.1 release

samcli/local/init/arbitrary_project.py, tests/unit/local/init/test_arbitrary_project.py
=> Ignore .git when init from arbitrary github repo

requirements/base.txt, tests/functional/commands/validate/lib/models/function_with_event_source_mapping.yaml, tests/functional/commands/validate/lib/test_sam_template_validator.py
updated the sam version to v1.16.0
pytest tests/functional/commands/validate/lib/test_sam_template_validator.py passes
*Checklist:*
=> Update aws-sam-translator Dependency

samcli/commands/deploy/command.py
=> fix: Add --no-fail-on-empty-changeset back

samcli/local/init/arbitrary_project.py, samcli/local/init/exceptions.py, tests/integration/init/test_init_command.py, tests/unit/local/init/test_arbitrary_project.py
=> Pretty error msg when init location is invalid

requirements/base.txt, samcli/__init__.py, samcli/commands/_utils/options.py, samcli/commands/deploy/command.py, samcli/commands/init/init_generator.py, samcli/lib/utils/osutils.py, samcli/lib/utils/temp_file_utils.py, samcli/local/init/__init__.py, samcli/local/init/arbitrary_project.py, samcli/local/init/exceptions.py, tests/functional/commands/validate/lib/models/function_with_event_source_mapping.yaml, tests/functional/commands/validate/lib/test_sam_template_validator.py, tests/integration/init/test_init_command.py, tests/unit/lib/utils/test_file_utils.py, tests/unit/local/init/test_arbitrary_project.py, tests/unit/local/init/test_init.py
=> Release v0.34.0

tests/integration/deploy/deploy_integ_base.py, tests/integration/deploy/test_deploy_command.py
=> chore: Integ tests for fail-on-empty-changeset flag

tests/unit/cli/test_types.py
#1602 
- Added a series of tests to illustrate what is supported and what is not.
*Checklist:*
=> Param overrides unit tests

samcli/commands/deploy/command.py, samcli/local/services/base_local_service.py, tests/unit/local/services/test_base_local_service.py
Reverts awslabs/aws-sam-cli#1620
=> Revert "Fix for stackTrace not returned in new Lambda containers."

samcli/__init__.py
=> chore: Version bump to v0.35.0

requirements/base.txt, samcli/commands/exceptions.py, samcli/commands/init/__init__.py, samcli/commands/init/init_templates.py, samcli/commands/init/interactive_event_bridge_flow.py, samcli/commands/init/interactive_init_flow.py, samcli/commands/local/cli_common/user_exceptions.py, samcli/lib/schemas/cli_paginator.py, samcli/lib/schemas/schemas_api_caller.py, samcli/lib/schemas/schemas_aws_config.py, samcli/lib/schemas/schemas_cli_message_generator.py, samcli/lib/schemas/schemas_code_manager.py, samcli/lib/schemas/schemas_constants.py, samcli/lib/schemas/schemas_directory_hierarchy_builder.py, samcli/local/common/runtime_template.py, tests/integration/init/schemas/schemas_test_data_setup.py, tests/integration/init/schemas/test_init_with_schemas_command.py, tests/integration/init/test_init_command.py, tests/unit/commands/init/test_cli.py, tests/unit/commands/init/test_interactive_event_bridge_flow.py, tests/unit/lib/samlib/test_schemas_directory_hierarchy_builder.py, tests/unit/lib/schemas/test_cli_paginator.py, tests/unit/lib/schemas/test_schemas_api_caller.py, tests/unit/lib/schemas/test_schemas_aws_config.py, tests/unit/lib/schemas/test_schemas_cli_message_generator.py, tests/unit/lib/schemas/test_schemas_code_manager.py
=> feat(init): Support for EventBridge Schemas

requirements/base.txt, tests/functional/commands/validate/lib/models/cloudwatchevent.yaml
bumped up sam translator version to v1.17.0
pytest tests/functional/commands/validate/lib/test_sam_template_validator.py was successful
*Checklist:*
=> chore: bump up sam tranlator version (sam v1.17.0)

samcli/__init__.py
=> chore: version bump to 0.36.0

requirements/base.txt, tests/functional/commands/validate/lib/models/function_with_deployment_preference.yaml
Bump up the sam translator version to v1.18.0
pytest succeeded 
*Checklist:*
=> chore: updated functional tests for provisioned concurrency support

requirements/base.txt, samcli/__init__.py, tests/functional/commands/validate/lib/models/function_with_deployment_preference.yaml
=> Release 0.36.0 (#1632)

samcli/__init__.py
=> chore: version bump to 0.37.0

samcli/__init__.py
=> chore: Version bump to 0.38.0

samcli/commands/local/lib/provider.py, samcli/commands/local/lib/sam_api_provider.py, tests/unit/commands/local/lib/test_sam_api_provider.py
Reverts awslabs/aws-sam-cli#1648
=> Revert "Set the CORS "Access-Control-Allow-Credentials" for local running"

samcli/commands/_utils/template.py, samcli/commands/build/build_context.py, samcli/commands/build/command.py, samcli/commands/exceptions.py, samcli/commands/init/__init__.py, samcli/commands/init/init_generator.py, samcli/commands/init/init_templates.py, samcli/commands/local/cli_common/invoke_context.py, samcli/commands/local/invoke/cli.py, samcli/commands/local/start_api/cli.py, samcli/commands/local/start_lambda/cli.py, samcli/commands/logs/logs_context.py, samcli/commands/publish/command.py, samcli/commands/validate/validate.py, samcli/lib/telemetry/metrics.py, tests/unit/commands/_utils/test_template.py, tests/unit/commands/init/test_cli.py, tests/unit/commands/publish/test_command.py, tests/unit/lib/telemetry/test_metrics.py
N/A
Updates how we handle UserExceptions so that when telemetry is on, we can see the more specific errors than just "UserException".
*Checklist:*
=> feat: Update handling of UserExceptions that are raised

requirements/base.txt, tests/functional/commands/validate/lib/models/http_api_existing_openapi.yaml, tests/functional/commands/validate/lib/models/http_api_existing_openapi_conditions.yaml, tests/functional/commands/validate/lib/test_sam_template_validator.py
*Checklist:*
- [ n/a] Write Design Document ([Do I need to write a design document?](https://github.com/awslabs/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.rst#design-document))
- [ n/a] Write unit tests
- [ n/a] Write/update integration tests
- [n/a] Write documentation
=> chore: update functional test templates for sam v1.19.1

samcli/__init__.py
=> chore: Version bump to 0.39.0

designs/sam-config.md
* Implementation based on the samconfig design changed course based on
well reasoned discussions, but was not reflected back onto the design
doc.
* Design reflects more of present day implementation of `samconfig.toml`
* None
TODO
* Add more detail on multiple configuration files and its future.
*Checklist:*
=> fix: samconfig design accuracy

samcli/__init__.py
* To release a new version of sam cli.
* increases the version of sam cli.
* None
*Checklist:*
=> chore: bump version to 0.40.0

samcli/__init__.py
* For releasing a new version of AWS SAM CLI
* None
*Checklist:*
=> chore: version bump to 0.41.0

README.md
None.
Keep README clean.
Removed unfortunate dash in README Markdown.
None.
*Checklist:*
=> Remove unfortunate dash

samcli/__init__.py
=> chore: Version Bump to 0.42.0

samcli/__init__.py
=> chore: version bump to 0.43.0

tests/integration/init/schemas/test_init_with_schemas_command.py
=> Init integration fixes - event bridge tests

samcli/__init__.py, samcli/lib/build/workflow_config.py, samcli/lib/init/templates/cookiecutter-aws-sam-hello-ruby/{{cookiecutter.project_name}}/template.yaml, samcli/local/common/runtime_template.py, samcli/local/docker/lambda_image.py, tests/integration/buildcmd/test_build_cmd.py, tests/integration/init/schemas/test_init_with_schemas_command.py
=> release v0.43.0

appveyor.yml
=> fix(ci): Go version to 1.13 and update patch python versions

samcli/__init__.py
=> chore: bump version to 0.44.0

samcli/__init__.py
=> chore: Version bump to 0.45.0

requirements/base.txt, tests/functional/commands/validate/lib/models/all_policy_templates.yaml, tests/functional/commands/validate/lib/models/api_with_basic_custom_domain_http.yaml, tests/functional/commands/validate/lib/models/api_with_basic_custom_domain_intrinsics_http.yaml, tests/functional/commands/validate/lib/models/api_with_custom_domain_route53_hosted_zone_name_http.yaml, tests/functional/commands/validate/lib/models/api_with_custom_domain_route53_http.yaml, tests/functional/commands/validate/lib/models/api_with_usageplans.yaml, tests/functional/commands/validate/lib/models/http_api_def_uri.yaml, tests/functional/commands/validate/lib/models/http_api_existing_openapi.yaml, tests/functional/commands/validate/lib/models/http_api_existing_openapi_conditions.yaml, tests/functional/commands/validate/lib/models/http_api_explicit_stage.yaml, tests/functional/commands/validate/lib/models/http_api_with_cors.yaml, tests/functional/commands/validate/lib/models/implicit_http_api.yaml, tests/functional/commands/validate/lib/models/implicit_http_api_auth_and_simple_case.yaml, tests/functional/commands/validate/lib/models/implicit_http_api_with_many_conditions.yaml, tests/functional/commands/validate/lib/test_sam_template_validator.py
Bump up sam translator version
*Checklist:*
=> chore: bump translator version and add tests

appveyor-windows.yml, pytest.ini, requirements/base.txt, samcli/__init__.py, samcli/commands/deploy/guided_context.py, samcli/local/apigw/local_apigw_service.py, tests/functional/commands/validate/lib/models/all_policy_templates.yaml, tests/functional/commands/validate/lib/models/api_with_basic_custom_domain_http.yaml, tests/functional/commands/validate/lib/models/api_with_basic_custom_domain_intrinsics_http.yaml, tests/functional/commands/validate/lib/models/api_with_custom_domain_route53_hosted_zone_name_http.yaml, tests/functional/commands/validate/lib/models/api_with_custom_domain_route53_http.yaml, tests/functional/commands/validate/lib/models/api_with_usageplans.yaml, tests/functional/commands/validate/lib/models/http_api_def_uri.yaml, tests/functional/commands/validate/lib/models/http_api_existing_openapi.yaml, tests/functional/commands/validate/lib/models/http_api_existing_openapi_conditions.yaml, tests/functional/commands/validate/lib/models/http_api_explicit_stage.yaml, tests/functional/commands/validate/lib/models/http_api_with_cors.yaml, tests/functional/commands/validate/lib/models/implicit_http_api.yaml, tests/functional/commands/validate/lib/models/implicit_http_api_auth_and_simple_case.yaml, tests/functional/commands/validate/lib/models/implicit_http_api_with_many_conditions.yaml, tests/functional/commands/validate/lib/test_sam_template_validator.py, tests/integration/buildcmd/test_build_cmd.py, tests/integration/deploy/test_deploy_command.py, tests/integration/package/package_integ_base.py, tests/integration/publish/publish_app_integ_base.py, tests/testing_utils.py, tests/unit/commands/deploy/test_deploy_context.py, tests/unit/commands/deploy/test_guided_config.py, tests/unit/commands/deploy/test_guided_context.py, tests/unit/local/apigw/test_local_apigw_service.py
=> chore: Release 0.45.0

samcli/__init__.py
Version bump for monday's release.
*Checklist:*
=> chore: Version bump to 0.46.0

samcli/__init__.py
* For releasing a new version of SAM CLI.
=> chore: bump version to 0.47.0

samcli/__init__.py
* For releasing a new version of SAM CLI
*Checklist:*
=> chore: version bump 0.46.2

samcli/__init__.py
* required for a new release of SAM CLI.
=> chore: version bump to 0.47.0

samcli/cli/cli_config_file.py
Reverts awslabs/aws-sam-cli#1889
Reverting as Sriram says PR is not complete.
=> Revert "fix: logging for samconfig"

samcli/__init__.py
=> chore: version to 0.48.0

samcli/__init__.py
=> chore: version to 0.49.0

appveyor.yml
=> Python 377

samcli/__init__.py
=> chore: version bump to 0.50.0

samcli/lib/build/app_builder.py, samcli/lib/build/workflow_config.py, samcli/lib/providers/provider.py, samcli/lib/providers/sam_function_provider.py, samcli/lib/providers/sam_layer_provider.py, tests/integration/buildcmd/test_build_cmd.py, tests/integration/testdata/buildcmd/PyLayerMake/Makefile, tests/integration/testdata/buildcmd/PyLayerMake/layer.py, tests/integration/testdata/buildcmd/PyLayerMake/requirements.txt, tests/integration/testdata/buildcmd/layers-functions-template.yaml, tests/unit/commands/local/lib/test_provider.py, tests/unit/commands/local/lib/test_sam_layer_provider.py
=> feat: adding makefile workflow for layers build.

samcli/__init__.py
=> chore: version v0.51.0

samcli/commands/local/generate_event/cli.py
*Issue #1999*
-
Correct the inline help
None
=> Fixed #1999 - Inline help issue in "sam local generate-event"

samcli/lib/build/app_builder.py, tests/unit/lib/build_module/test_app_builder.py
*Issue #2005 , if available:*
Ran integration test on local and it works.
*Checklist:*
=> Fixing bug for build for layers in container.

requirements/base.txt, requirements/reproducible-linux.txt, tests/functional/commands/validate/lib/models/function_with_file_system_config.yaml, tests/functional/commands/validate/lib/test_sam_template_validator.py
Still need to update reproducible-linux dependency file once 1.25.0 is live.
=> Adding SAM 1.25.0 Functional Test

samcli/__init__.py
=> chore: bump version to 0.53.0

appveyor.yml
AppVeyor released fix here https://www.appveyor.com/updates/2020/05/24/ so we don't need this workaround anymore.
*Checklist:*
=> Removing hack for docker issue as it is fixed by AppVeyor.

build-image-src/ATTRIBUTION.txt, build-image-src/Dockerfile-java11, build-image-src/Dockerfile-java8, build-image-src/Dockerfile-nodejs10x, build-image-src/Dockerfile-nodejs12x, build-image-src/Dockerfile-provided, build-image-src/Dockerfile-python27, build-image-src/Dockerfile-python36, build-image-src/Dockerfile-python37, build-image-src/Dockerfile-python38, build-image-src/Dockerfile-ruby25, build-image-src/Dockerfile-ruby27
=> Add Source for Docker Build Images

samcli/__init__.py
=> chore: Bump AWS SAM CLI Version

samcli/__init__.py
=> chore: Bump version to RC2

samcli/local/docker/lambda_image.py, tests/unit/local/docker/test_lambda_image.py
Helps anything that might depend on STDOUT output...
=> Build output dots

tests/integration/init/schemas/test_init_with_schemas_command.py
=> Update Init Integ Tests

samcli/local/docker/manager.py, tests/unit/local/docker/test_manager.py
=> Stop showing 'Failed to download ...' when using local rapid docker images

samcli/commands/deploy/command.py, samcli/commands/deploy/exceptions.py, tests/unit/commands/deploy/test_command.py
Fixing some integration test failures
Removed unnecessary checks in deploy logic
*Checklist:*
=> Fixed integration tests for resolve-s3 feature

samcli/cli/context.py, samcli/commands/_utils/options.py, samcli/commands/package/command.py, samcli/lib/telemetry/metrics.py, samcli/lib/warnings/sam_cli_warning.py, tests/integration/package/test_package_command.py, tests/integration/testdata/package/aws-serverless-function-codedeploy-warning.yaml, tests/unit/commands/_utils/test_options.py, tests/unit/lib/telemetry/test_metrics.py, tests/unit/lib/warnings/test_sam_cli_warnings.py, tests/unit/lib/warnings/test_warnings.py
=> fix: template warning

requirements/base.txt, requirements/reproducible-linux.txt, samcli/__init__.py
=> chore: bump lambda-builder version v1.1.0 and sam-cli version v1.2.0.

requirements/base.txt, requirements/reproducible-linux.txt, samcli/__init__.py
=> Chore: Bumped aws-sam-translator to version 1.27.0 and aws-sam-cli to version 1.3.0

build-image-src/Dockerfile-provided
This is only a change to the build image definition.
=> Add SAM_CLI_VERSION build arg to provided image

samcli/__init__.py
=> chore: bump SAM CLI version to 1.3.1

samcli/__init__.py
=> chore: bump SAM CLI version to 1.3.2

samcli/__init__.py
=> chore: bump version to 1.4.0

samcli/__init__.py
=> chore: bump version to 1.5.0

samcli/__init__.py
=> chore: bump version to 1.6.0

DEVELOPMENT_GUIDE.md
Fix a typo (`intruction` -> `instruction`)
*Checklist:*
=> chore: Update DEVELOPMENT_GUIDE.md (typo)

samcli/__init__.py
=> chore: bump version

samcli/__init__.py
=> chore: bump version to 1.9.0

.github/workflows/pr_title.yml
We'll be auto-generating release notes; ensures PR titles are somewhat consistent.
Run regex check on every PR title.
*Checklist:*
=> ci: check PR title

samcli/__init__.py
=> chore: bump version to 1.10.0

.github/PULL_REQUEST_TEMPLATE.md
Improve legibility of PR summaries.
Clearly separated sections; working URLs; actionable items in checklist.
None.
=> docs: improve PR template

samcli/lib/generated_sample_events/events.py
#2381
Suppress the warning according to [Temporarily Suppressing Warnings](https://docs.python.org/3/library/warnings.html#temporarily-suppressing-warnings)
no side effect
=> chore: Suppress SyntaxWarning caused by chevron on Windows

tests/integration/buildcmd/test_build_cmd.py
docker hub has stricter request limit now
by not running integration tests requiring docker when PR is filed
**this also fixed a typo: "use_continer"**
=> ci: Skip integration tests requiring docker on CI except for canary

samcli/__init__.py
To bump up samcli version to 1.11.0
=> chore: bump version to 1.11.0

samcli/lib/package/artifact_exporter.py, tests/integration/deploy/test_deploy_command.py, tests/unit/lib/package/test_artifact_exporter.py
Removing Code Signer integration tests until feature gating is completely removed.
=> fix: remove code signer integration tests until feature gating is removed

tests/integration/local/invoke/test_integrations_do_cli.py
- Look for outputs within each element of the list.
=> fix(local-invoke): integration tests

samcli/__init__.py
=> chore(version): change version to be 1.13.1

.pylintrc
=> chore: Remove biased language

samcli/__init__.py
=> chore(version): patch version bump to 1.13.2

samcli/commands/local/cli_common/options.py
Update the new options (warm-containers && debug-function) help description 
=> chore: update the warm-containers & debug-function options help wording

appveyor-windows.yml
=> Added Docker Hub Login for Windows

appveyor-windows.yml
=> Fix/windows docker login Env

tests/integration/deploy/test_deploy_command.py, tests/integration/local/start_api/start_api_integ_base.py
=> fix: canary tests

tests/integration/local/start_lambda/start_lambda_api_integ_base.py
=> fix: replace signaling with kill process

requirements/base.txt, requirements/reproducible-linux.txt, samcli/__init__.py, tests/functional/commands/validate/lib/models/function_with_event_source_mapping.yaml
Bump sam-translator version to v1.33
=> chore: bump sam-translator version to v1.33 & bump cli version to v1.15

samcli/lib/init/templates/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/hello-world/package.json
=> Update axios Version

requirements/base.txt, requirements/reproducible-linux.txt, samcli/__init__.py, tests/functional/commands/validate/lib/models/eventbridgerule_with_dlq.yaml, tests/functional/commands/validate/lib/models/eventbridgerule_with_retry_policy.yaml, tests/functional/commands/validate/lib/models/function_event_conditions.yaml, tests/functional/commands/validate/lib/models/function_with_amq.yaml, tests/functional/commands/validate/lib/models/function_with_amq_kms.yaml, tests/functional/commands/validate/lib/models/function_with_event_source_mapping.yaml, tests/functional/commands/validate/lib/models/http_api_description.yaml, tests/functional/commands/validate/lib/models/state_machine_with_eb_dlq.yaml, tests/functional/commands/validate/lib/models/state_machine_with_eb_dlq_generated.yaml, tests/functional/commands/validate/lib/models/state_machine_with_eb_retry_policy.yaml, tests/functional/commands/validate/lib/models/state_machine_with_schedule_dlq_retry_policy.yaml
=> chore: bump version to 1.16.0

.github/ISSUE_TEMPLATE/Bug_report.md, .github/ISSUE_TEMPLATE/Feature_request.md
Added:
- AWS region 
- Steps from external tools
=> chore: Updated issue bug report template

build-image-src/Dockerfile-nodejs14x
See #2561
Applies same changes as https://github.com/aws/aws-sam-cli/pull/2561 to the new `nodejs14.x` build image.
None.
=> chore: improve nodejs14.x build image

samcli/commands/deploy/guided_context.py, tests/unit/commands/deploy/test_guided_context.py
=> fix: s3-bucket are ignored with sam deploy --guided

installer/pyinstaller/hook-samcli.py
=> fix: include aws_lambda_builders package

requirements/base.txt, requirements/reproducible-linux.txt, samcli/__init__.py
=> chore: bump aws-lambda-builders version to 1.3.0 & sam cli to 1.19.0

samcli/__init__.py
=> chore: bump SAM CLI version to 1.19.1

tests/integration/buildcmd/build_integ_base.py
#2144 
This is a fix to the new integration tests shipped. One of the last commits caused integration test failures in https://github.com/aws/aws-sam-cli/pull/2592
Integration test get_command_list() gets the correct changes to support integration tests
None
=> [Fix] Container env vars integration test failure fix

samcli/__init__.py
N.A.
Version bump for SAMCLI release
N.A.
None.
=> chore: bump version to 1.20.0

mypy.ini, samcli/commands/local/lib/swagger/integration_uri.py, samcli/lib/build/app_builder.py, samcli/lib/build/build_graph.py, samcli/lib/build/build_strategy.py, samcli/lib/providers/api_collector.py, samcli/lib/providers/api_provider.py, samcli/lib/providers/cfn_api_provider.py, samcli/lib/providers/cfn_base_api_provider.py, samcli/lib/providers/exceptions.py, samcli/lib/providers/provider.py, samcli/lib/providers/sam_api_provider.py, samcli/lib/providers/sam_base_provider.py, samcli/lib/providers/sam_function_provider.py, samcli/lib/providers/sam_layer_provider.py, samcli/lib/providers/sam_stack_provider.py, samcli/local/apigw/local_apigw_service.py
Add type hint to all files in module "samcli.lib.providers"
No behavior change. 
=> chore: Add typehint to samcli.lib.providers.*

samcli/local/docker/lambda_build_container.py, samcli/local/docker/manager.py, tests/unit/local/docker/test_lambda_build_container.py, tests/unit/local/docker/test_manager.py
=> feat(Public ECR): Changed Build Image Registry to Public ECR

samcli/commands/build/build_context.py, samcli/lib/providers/sam_function_provider.py, samcli/lib/providers/sam_layer_provider.py, tests/integration/buildcmd/test_build_cmd.py, tests/integration/testdata/buildcmd/base-dir-image/template/child/template.yaml, tests/integration/testdata/buildcmd/base-dir-image/template/template.yaml, tests/integration/testdata/buildcmd/base-dir/ChildStackX/ChildStackY/FunctionA/main_a_2.py, tests/integration/testdata/buildcmd/base-dir/ChildStackX/ChildStackY/MyLayerVersion/my_layer/simple_python.py, tests/integration/testdata/buildcmd/base-dir/ChildStackX/ChildStackY/template.yaml, tests/integration/testdata/buildcmd/base-dir/ChildStackX/FunctionB/main_b.py, tests/integration/testdata/buildcmd/base-dir/ChildStackX/template.yaml, tests/integration/testdata/buildcmd/base-dir/FunctionA/main_a.py, tests/integration/testdata/buildcmd/base-dir/template/template.yaml, tests/unit/commands/buildcmd/test_build_context.py, tests/unit/commands/local/lib/test_sam_function_provider.py
=> fix: --base-dir is disregarded in sam build

samcli/__init__.py
N.A.
Version bump for release
N.A.
None
=> chore: bump version to 1.21.1

tests/integration/buildcmd/build_integ_base.py, tests/integration/buildcmd/test_build_cmd.py
=> feat(Public ECR): Updated Test Image Name and Added Latest Tag Check

requirements/reproducible-linux.txt
=> chore: update reproducible-linux.txt

samcli/__init__.py
N.A.
Version bump for release
N.A.
None
=> Version bump to 1.22.0

samcli/__init__.py
=> chore: bump version to 1.23.0

installer/pyinstaller/build-linux.sh
=> chore: add command line options to pyinstaller build script

.vim/coc-settings.json, requirements/base.txt, requirements/reproducible-linux.txt
Ran into [Watchdog issue#689](https://github.com/gorakhargosh/watchdog/issues/689) while running `make init` on mac. As per recommendation in issue bumping watchdog version to their latest release.
=> Watchdog error

tests/unit/lib/build_module/test_build_graph.py
=> fix: Build graph tests using assertTrue instead of assertEqual + added assertions

requirements/base.txt, requirements/reproducible-linux.txt, tests/functional/commands/validate/lib/models/all_policy_templates.yaml, tests/functional/commands/validate/lib/models/api_with_swagger_authorizer_none.yaml, tests/functional/commands/validate/lib/models/api_with_usageplans_shared_attributes_three.yaml, tests/functional/commands/validate/lib/models/api_with_usageplans_shared_attributes_two.yaml, tests/functional/commands/validate/lib/models/function_with_deployment_preference_alarms_intrinsic_if.yaml, tests/functional/commands/validate/lib/models/implicit_api_deletion_policy_precedence.yaml, tests/functional/commands/validate/lib/models/layer_deletion_policy_precedence.yaml, tests/functional/commands/validate/lib/models/state_machine_with_xray_policies.yaml, tests/functional/commands/validate/lib/models/state_machine_with_xray_role.yaml, tests/functional/commands/validate/lib/models/version_deletion_policy_precedence.yaml
=> chore: update to aws-sam-translator 1.36.0

samcli/__init__.py
Version bump for 1.24.0 release
=> chore: bump version to 1.24.0

installer/pyinstaller/hook-samcli.py
=> fix: Add configparser to hiddenimports to resolve dependency issue from botocore in PyInstaller

samcli/__init__.py
=> chore: bump version to 1.24.1

tests/integration/deploy/test_deploy_command.py
Fixing linux canary issue which can be seen here; https://ci.appveyor.com/project/AWSSAMCLI/aws-sam-cli-canary-linux/build/job/ke7k929ej64sxni0
=> chore: fix canary issue

samcli/commands/deploy/guided_context.py, samcli/commands/pipeline/bootstrap/cli.py, samcli/commands/pipeline/bootstrap/guided_context.py, samcli/lib/utils/defaults.py, tests/unit/commands/deploy/test_guided_context.py, tests/unit/commands/pipeline/bootstrap/test_guided_context.py
=> Add region to pipeline bootstrap interactive flow

samcli/lib/bootstrap/bootstrap.py
N.A.
To improve our managed stack policy for s3 bucket to be more secure
Adds a condition to limits the s3 action to be only allowed from the source account
Not expecting any
=> Add condition to managed bucket policy

appveyor.yml
=> Update appveyor.yml to do docker login on both dockerhub and Public ECR

appveyor.yml
=> Update appveyor.yml to improve Public ECR performance

samcli/__init__.py
N.A.
Version bump for scheduled release
=> chore: bump version to 1.25.0

appveyor.yml
=> fix: reduce python testing matrix

appveyor.yml
=> temp: disable testing against python 3.8, and enabled 3.7

samcli/commands/pipeline/bootstrap/guided_context.py, samcli/lib/bootstrap/bootstrap.py, tests/unit/commands/pipeline/bootstrap/test_guided_context.py, tests/unit/lib/bootstrap/test_bootstrap.py
=> Adding account id to bootstrap message.

samcli/lib/bootstrap/bootstrap.py, samcli/lib/pipeline/bootstrap/environment.py, samcli/lib/pipeline/bootstrap/environment_resources.yaml, tests/unit/lib/pipeline/bootstrap/test_environment.py
=> Cfn creds fix

samcli/commands/pipeline/bootstrap/cli.py, samcli/commands/pipeline/init/interactive_init_flow.py, tests/unit/commands/pipeline/bootstrap/test_cli.py
=> Fix toml file incorrect read/write in init --bootstrap

samcli/lib/pipeline/bootstrap/environment_resources.yaml
=> Temporarily removing account fix.

samcli/lib/cookiecutter/question.py, tests/integration/pipeline/test_init_command.py, tests/unit/lib/cookiecutter/test_question.py
=> Auto skip questions if stage detected

samcli/commands/pipeline/init/interactive_init_flow.py, tests/unit/commands/pipeline/init/test_initeractive_init_flow.py
Follow up: https://github.com/aws/aws-sam-cli-pipeline-init-templates/pull/29
=> Stage name index selection

samcli/commands/pipeline/bootstrap/cli.py, samcli/commands/pipeline/external_links.py
=> pipeline: Add doc link

tests/functional/commands/validate/lib/models/api_with_ip_range_blacklist.yaml, tests/functional/commands/validate/lib/models/api_with_ip_range_whitelist.yaml
=> Adding accidentally removed tests back.

tests/integration/testdata/pipeline/expected_jenkinsfile
=> ci: Update expected Jenkins file in pipeline integ test

tests/integration/pipeline/base.py
=> Clearing pipeline integ test buckets with versioned objects.

tests/integration/pipeline/base.py
=> Fixing bug in bucket cleanup.

tests/integration/pipeline/base.py
=> Deleting bucket

samcli/__init__.py
=> chore: bump SAM CLI version to 1.27.0

MANIFEST.in, samcli/__init__.py
=> Including stage resource yaml in pip.

samcli/commands/_utils/iac_validations.py, samcli/commands/deploy/guided_context.py, samcli/lib/iac/interface.py, tests/integration/deploy/deploy_integ_base.py, tests/integration/deploy/test_deploy_command_cdk.py, tests/integration/testdata/package/cdk/python/aws-lambda-function/app.py, tests/integration/testdata/package/cdk/python/aws-lambda-function/aws_lambda_function/aws_lambda_function_stack.py, tests/integration/testdata/package/cdk/python/aws-lambda-layer/app.py, tests/testing_utils.py, tests/unit/commands/deploy/test_command.py, tests/unit/commands/deploy/test_guided_context.py
=> Cdk support dev integ test deploy

tests/cdk_testing_utils.py, tests/integration/deploy/test_deploy_command_cdk.py, tests/integration/package/package_integ_base.py, tests/integration/package/test_package_command_cdk_image.py, tests/integration/package/test_package_command_cdk_zip.py
=> Cdk support dev cdk python test utils

samcli/lib/intrinsic_resolver/intrinsic_property_resolver.py, samcli/lib/providers/sam_function_provider.py, tests/integration/buildcmd/test_cdk_build_cmd.py, tests/integration/testdata/buildcmd/CDK/cdk-example-multiple-stacks-01/docker_lambda_code/app.js, tests/integration/testdata/buildcmd/CDK/cdk-example-multiple-stacks-01/hello_cdk_nested_stacks/hello_cdk_nested_stacks_stack.py, tests/unit/lib/intrinsic_resolver/test_intrinsic_resolver.py
=> fix: Error when trying to build CDK project with image assets.

appveyor-windows.yml
=> Add ECR credentials for windows test

appveyor-windows.yml
=> Install aws cli in the windows test jobs

requirements/base.txt, requirements/reproducible-linux.txt, tests/integration/buildcmd/test_build_cmd.py
=> chore: Update dateparser to 1.0, update TestBuildCommand_PythonFunctions_Images test requirement

samcli/__init__.py
=> chore: bump version to 1.29.0

samcli/__init__.py, tests/integration/package/package_integ_base.py
=> Fix the signing integration test cases by creating the S3 Buckets with versioning enabled

tests/integration/deploy/test_deploy_command.py
=> fix: Deploy Integration Test Stack Name

tests/integration/testdata/invoke/cdk/python/aws-lambda-function/cdk.json
=> fix: invoke cdk integration test fail in windows

.coveragerc, mypy.ini, samcli/lib/iac/cdk/cdk_iac.py, samcli/lib/iac/cdk/exceptions.py, samcli/lib/iac/cfn/cfn_iac.py, samcli/lib/iac/exceptions.py, samcli/lib/iac/iac_factory.py, samcli/lib/iac/plugins_interfaces.py, tests/unit/lib/iac/test_iac_factory.py
- Renamed `class Project` to `class SamCliProject` to match design doc.
- Added `class ProjectFindRule` and `class Context`
- `class IaCPlugin` -> `class IaCPluginInterface` and made changes according to doc
- Added `class IaCPluginDefinition`
Changes start on line 796
=> feat: Update IaC Interface to Match New Design

samcli/lib/bootstrap/companion_stack/companion_stack_manager.py, samcli/lib/delete/cfn_utils.py, tests/integration/delete/test_delete_command.py
=> fix: SAM Delete CFN Rate Limit

samcli/__init__.py
=> chore: Version Bump to 1.31.0

samcli/lib/iac/cfn/cfn_iac.py, samcli/lib/iac/plugins_interfaces.py, tests/unit/lib/iac/cfn/test_cfn_iac_implementation.py, tests/unit/lib/iac/cfn/test_data/nested_stack.yaml, tests/unit/lib/iac/cfn/test_data/stack.yaml, tests/unit/lib/iac/test_iac_factory.py
- Clone current CFN implementation for reading a project
- Fix some typing issues
- Intrinsics and schema validation through `get_resolved_cfn_template`
=> feat: CFN read project implementation

samcli/commands/_utils/template.py, samcli/commands/local/cli_common/invoke_context.py, samcli/lib/providers/sam_stack_provider.py, tests/integration/local/invoke/invoke_integ_base.py, tests/integration/local/invoke/test_integrations_cli.py, tests/unit/commands/local/cli_common/test_invoke_context.py, tests/unit/commands/local/lib/test_stack_provider.py
This reverts commit 0d7f92eed4c82151f36e53c67190f1269dde0842.
=> Revert "Add root_template_dir to nested stack (#3237)"

samcli/__init__.py
=> chore: bump version to 1.32.0

samcli/lib/intrinsic_resolver/intrinsic_property_resolver.py, tests/integration/local/invoke/invoke_integ_base.py, tests/integration/local/invoke/test_integrations_cli_cdk.py, tests/integration/local/start_api/start_api_integ_base.py, tests/integration/local/start_api/test_start_api_cdk.py, tests/integration/local/start_lambda/start_lambda_api_integ_base.py, tests/integration/local/start_lambda/test_start_lambda_cdk.py, tests/integration/testdata/invoke/cdk/python/aws-lambda-function/aws_lambda_function/aws_lambda_function_stack.py, tests/integration/testdata/invoke/cdk/python/aws-lambda-function/docker_lambda_code/Dockerfile, tests/integration/testdata/invoke/cdk/python/aws-lambda-function/docker_lambda_code/app.js, tests/integration/testdata/invoke/cdk/python/aws-lambda-function/docker_lambda_code/package.json, tests/integration/testdata/invoke/cdk/python/aws-lambda-function/lambda_code/app.py, tests/integration/testdata/start_api/cdk/python/aws-api-resource/.gitignore, tests/integration/testdata/start_api/cdk/python/aws-api-resource/app.py, tests/integration/testdata/start_api/cdk/python/aws-api-resource/aws_lambda_function/aws_lambda_function_stack.py, tests/integration/testdata/start_api/cdk/python/aws-api-resource/cdk.json, tests/integration/testdata/start_api/cdk/python/aws-api-resource/lambda_code/app.py, tests/integration/testdata/start_api/cdk/python/aws-lambda-function/.gitignore, tests/integration/testdata/start_api/cdk/python/aws-lambda-function/app.py, tests/integration/testdata/start_api/cdk/python/aws-lambda-function/aws_lambda_function/aws_lambda_function_stack.py, tests/integration/testdata/start_api/cdk/python/aws-lambda-function/cdk.json, tests/integration/testdata/start_api/cdk/python/aws-lambda-function/lambda_code/app.py
=> test: Add integrations for CDK projects local commands (local invoke, local start-lambda, local start-api)

samcli/lib/bootstrap/companion_stack/data_types.py, tests/unit/lib/bootstrap/companion_stack/test_data_types.py
=> Revert "fix: ECR URI for China regions"

requirements/base.txt, requirements/reproducible-linux.txt, samcli/__init__.py
Waiting for LB and SAM release to update reproducible hashes.
=> chore: Update Lambda Builders, SAM, and SAM CLI Versions

setup.py
=> patch sam accelerate cmd name

samcli/commands/local/lib/local_lambda.py, samcli/lib/utils/architecture.py, samcli/local/docker/lambda_image.py, tests/unit/commands/local/lib/test_local_lambda.py, tests/unit/lib/utils/test_architecture.py, tests/unit/local/docker/test_lambda_image.py
=> fix: emulation image tag

appveyor.yml, pytest.ini
=> fix: canary settings

samcli/commands/sync/command.py, samcli/lib/build/build_graph.py, samcli/lib/build/build_strategy.py, samcli/lib/utils/hash.py, tests/unit/lib/build_module/test_build_graph.py, tests/unit/lib/build_module/test_build_strategy.py, tests/unit/lib/utils/test_hash.py
=> chore: Changed hashing method for build definitions

samcli/commands/init/interactive_init_flow.py
Adds hint to show users how to use the new recently added create pipeline configuration
=> Add Pipeline Hint

appveyor.yml
=> fix: Updated Ubuntu Image to 20.04

requirements/base.txt, requirements/reproducible-linux.txt, tests/functional/commands/validate/lib/models/api_request_model_with_validator.yaml, tests/functional/commands/validate/lib/models/api_request_model_with_validator_openapi_3.yaml, tests/functional/commands/validate/lib/models/api_swagger_integration_with_ref_intrinsic_api_id.yaml, tests/functional/commands/validate/lib/models/api_swagger_integration_with_string_api_id.yaml, tests/functional/commands/validate/lib/models/api_with_any_method_in_swagger.yaml, tests/functional/commands/validate/lib/models/api_with_auth_all_minimum.yaml, tests/functional/commands/validate/lib/models/api_with_identity_intrinsic.yaml, tests/functional/commands/validate/lib/models/basic_layer.yaml, tests/functional/commands/validate/lib/models/cloudwatchevent_intrinsics.yaml, tests/functional/commands/validate/lib/models/cognito_userpool_with_event.yaml, tests/functional/commands/validate/lib/models/function_with_architectures.yaml, tests/functional/commands/validate/lib/models/function_with_auth_mechanism_for_self_managed_kafka.yaml, tests/functional/commands/validate/lib/models/function_with_intrinsic_architecture.yaml, tests/functional/commands/validate/lib/models/function_with_request_parameters.yaml, tests/functional/commands/validate/lib/models/function_with_self_managed_kafka.yaml, tests/functional/commands/validate/lib/models/function_with_vpc_permission_for_self_managed_kafka.yaml, tests/functional/commands/validate/lib/models/globals_for_function.yaml, tests/functional/commands/validate/lib/models/kinesis_intrinsics.yaml, tests/functional/commands/validate/lib/models/layers_with_intrinsics.yaml, tests/functional/commands/validate/lib/models/s3_intrinsics.yaml, tests/functional/commands/validate/lib/models/self_managed_kafka_with_intrinsics.yaml, tests/functional/commands/validate/lib/models/sns_intrinsics.yaml
=> chore: update to aws-sam-translator 1.40.0

appveyor.yml
This reverts commit 2f6b10804e2d36f122e69c7b75738c4f6f52c345.
=> Revert "fix: Updated Ubuntu Image to 20.04 (#3412)"

samcli/__init__.py
=> chore: bump version to 1.35

designs/resource_metadata_overriding.md
N/A
Minor typo
Minor typo
Date is correct
- [n/a ] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [n/a ] Write design document ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [n/a ] Write unit tests
- [ n/a] Write/update functional tests
- [ n/a] Write/update integration tests
- [ n/a] `make pr` passes
- [ n/a] `make update-reproducible-reqs` if dependencies were changed
- [ n/a] Write documentation
=> Timetravel seems unlikely

.github/labeler.yml, .github/workflows/pr-labeler.yml
N/A
Adds a Github Action to reduce the manual maintenance of PR labeling. 
Adds Github Action.
None
=> Chore: Add Auto PR labeler

samcli/lib/sync/flows/alias_version_sync_flow.py, samcli/lib/sync/flows/function_sync_flow.py, samcli/lib/sync/flows/http_api_sync_flow.py, samcli/lib/sync/flows/image_function_sync_flow.py, samcli/lib/sync/flows/layer_sync_flow.py, samcli/lib/sync/flows/rest_api_sync_flow.py, samcli/lib/sync/flows/stepfunctions_sync_flow.py, samcli/lib/sync/flows/zip_function_sync_flow.py, samcli/lib/sync/sync_flow.py, samcli/lib/utils/boto_utils.py, tests/unit/lib/sync/flows/test_alias_version_sync_flow.py, tests/unit/lib/sync/flows/test_function_sync_flow.py, tests/unit/lib/sync/flows/test_http_api_sync_flow.py, tests/unit/lib/sync/flows/test_image_function_sync_flow.py, tests/unit/lib/sync/flows/test_layer_sync_flow.py, tests/unit/lib/sync/flows/test_rest_api_sync_flow.py, tests/unit/lib/sync/flows/test_stepfunctions_sync_flow.py, tests/unit/lib/sync/flows/test_zip_function_sync_flow.py, tests/unit/lib/sync/test_sync_flow.py, tests/unit/lib/utils/test_boto_utils.py
=> fix: use common method for client generation in sync flows

samcli/commands/build/build_context.py, samcli/commands/init/interactive_init_flow.py, samcli/commands/local/invoke/cli.py, samcli/commands/local/start_api/cli.py, samcli/commands/local/start_lambda/cli.py, samcli/commands/logs/command.py
Add SAM Accelerate commands into next command you can use section
=> chore: add accelerate commands into next command you can use section

samcli/lib/observability/cw_logs/cw_log_group_provider.py, tests/unit/lib/observability/cw_logs/test_cw_log_group_provider.py
=> fix: validate sfn logging configuration

samcli/commands/build/build_context.py, samcli/commands/init/interactive_init_flow.py, samcli/commands/local/invoke/cli.py, samcli/commands/local/start_api/cli.py, samcli/commands/local/start_lambda/cli.py, samcli/commands/logs/command.py
=> Revert "chore: add accelerate commands into next command you can use section"

requirements/base.txt, requirements/reproducible-linux.txt
=> chore: bump aws-sam-translator version to 1.41.0

samcli/__init__.py
=> chore: bump version 1.36.0

requirements/base.txt, requirements/reproducible-linux.txt
=> Revert "chore: bump aws-sam-translator version to 1.41.0"

samcli/__init__.py
=> Revert "chore: bump version 1.36.0"

samcli/lib/sync/flows/http_api_sync_flow.py, samcli/lib/sync/flows/rest_api_sync_flow.py, samcli/lib/utils/resources.py, tests/unit/lib/sync/flows/test_http_api_sync_flow.py, tests/unit/lib/sync/flows/test_rest_api_sync_flow.py
=> fix: Correcting workflow for http and rest api code syncs

samcli/commands/_utils/experimental.py, samcli/commands/sync/command.py, tests/integration/telemetry/test_experimental_metric.py, tests/unit/commands/_utils/test_experimental.py, tests/unit/commands/logs/test_command.py, tests/unit/commands/sync/test_command.py, tests/unit/lib/observability/cw_logs/test_cw_log_group_provider.py
=> fix: Experimental Context for Sync

samcli/commands/build/build_context.py, samcli/commands/init/interactive_init_flow.py, samcli/commands/logs/command.py
Adding Accelerate commands for next commands to try
=> chore: add accelerate commands for next commands to try

requirements/base.txt, requirements/reproducible-linux.txt
=> chore: bump Transform version to 1.42.0

appveyor.yml
=> fix: Use docker --version Instead due to AppVeyor Issue

build_dir/MyFunctionbf3066d1DepLayer/AWS_SAM_CLI_README
=> fix: Remove build dir

appveyor-ubuntu.yml, appveyor-windows.yml, appveyor.yml
=> test: split testing in separate jobs

requirements/dev.txt, tests/testing_utils.py
N/A
Adding persistent process testing utilities for using in watch, logs, and traces integration tests.
No prod changes.
N/A
N/A
=> feat: Added Persistent Process Utils

appveyor-windows.yml, tests/iac_integration/cdk/test_sam_cdk_integration.py, tests/integration/local/start_api/start_api_integ_base.py, tests/integration/local/start_lambda/start_lambda_api_integ_base.py, tests/integration/sync/test_sync_infra.py, tests/testing_utils.py
Successful run: https://ci.appveyor.com/project/AWSSAMCLI/aws-sam-cli-canary-windows/build/job/t4o4kfd7p0mg7bb4
=> chore: fix windows canaries for "sam local" tests

samcli/__init__.py
=> chore: bump version to 1.38.0

appveyor-ubuntu.yml
=> chore: Update nodejs version in canary

samcli/__init__.py
=> chore: Version bump to 1.39.0

requirements/base.txt, requirements/reproducible-linux.txt
=> Update Lambda Builder version

.gitignore, appveyor-windows-build-dotnet.yml, samcli/commands/build/command.py, samcli/lib/build/workflow_config.py, samcli/lib/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/src/HelloWorld/HelloWorld.csproj, samcli/lib/init/templates/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/test/HelloWorld.Test/HelloWorld.Tests.csproj, samcli/lib/utils/architecture.py, samcli/local/common/runtime_template.py, samcli/local/docker/lambda_debug_settings.py, samcli/local/docker/lambda_image.py, tests/integration/buildcmd/test_build_cmd.py, tests/integration/testdata/buildcmd/Dotnet6/HelloWorld.csproj, tests/integration/testdata/buildcmd/Dotnet6/Program.cs, tests/integration/testdata/buildcmd/Dotnet6/aws-lambda-tools-defaults.json, tests/unit/local/docker/test_lambda_container.py, tests/unit/local/docker/test_lambda_debug_settings.py
=> Feat dotnet6 aboelha (#415)

samcli/__init__.py
=> chore: bump version to 1.40.0

samcli/__init__.py
=> chore: Version Bump for 1.40.1

samcli/lib/utils/file_observer.py, tests/integration/local/start_api/start_api_integ_base.py, tests/integration/local/start_api/test_start_api.py, tests/integration/testdata/start_api/main-layers.py, tests/integration/testdata/start_api/template-warm-containers-layers.yaml, tests/unit/lib/utils/test_file_observer.py
=> Revert "Revert "fix: Warm containers break on non-local layers""

samcli/lib/schemas/schemas_api_caller.py, samcli/local/common/runtime_template.py, tests/integration/init/schemas/test_init_with_schemas_command.py
=> Revert "feat: Add Go code generation option to Eventbridge Schemas workflow"

samcli/lib/build/app_builder.py, tests/unit/lib/build_module/test_app_builder.py
=> Revert "feat: Add flag for using npm ci in node builds"

samcli/__init__.py
=> chore: bump version to 1.41.0

samcli/lib/build/app_builder.py, tests/unit/lib/build_module/test_app_builder.py
=> Revert "Revert "feat: Add flag for using npm ci in node builds""

appveyor-windows-build-dotnet.yml, appveyor-windows-build-go.yml, appveyor-windows-build-java-container.yml, appveyor-windows-build-java-ruby-inprocess.yml, appveyor-windows-build-nodejs.yml, appveyor-windows-build-python.yml, appveyor-windows-build-ruby.yml, appveyor-windows.yml
N/A
Swap to Windows AppVeyor instances to use Visual Studio 2019 image after changes to CI worker type.
These images do not have D drive and docker folder sharing issue is already fixed in these images.
Updated D:\tmp and D:\source to C drive instead.
Canary runs:
Windows: https://ci.appveyor.com/project/AWSSAMCLI/aws-sam-cli-canary-windows-dev/builds/42995211
Linux: https://ci.appveyor.com/project/AWSSAMCLI/aws-sam-cli-canary-linux-dev/builds/42994974
Updated appveyor yaml image to Visual Studio 2019 and D drive to C drive.
N/A
=> feat: Updated Image to Visual Studio 2019

requirements/base.txt, requirements/reproducible-linux.txt, samcli/commands/validate/lib/sam_template_validator.py, samcli/yamlhelper.py
=> chore: Update translator version to 1.43.0

samcli/__init__.py
=> chore: bump version to 1.42.0

samcli/__init__.py
=> chore: bump version to 1.43.0

DEVELOPMENT_GUIDE.md, appveyor-windows-build-dotnet.yml, appveyor-windows-build-go.yml, appveyor-windows-build-java-container.yml, appveyor-windows-build-nodejs.yml, appveyor-windows-build-python.yml, appveyor-windows-build-ruby.yml, appveyor-windows.yml
- Remove python3.6 from the instructions or documentation
- Add recommendation when writing integration tests
=> chore: update development guide

samcli/commands/build/build_context.py, samcli/commands/local/lib/local_lambda.py, samcli/local/docker/container.py, tests/unit/local/docker/test_container.py
This reverts commit 416ee241a6fe5240a76c3fcb7d19f610225beaa3.
=> Revert "fix: container start waits for port (#3783)"

tests/integration/sync/test_sync_infra.py
N.A.
It fixes a few test cases expected values that were missed to be updated
It updates the expected values
N.A.
=> fix: Update expected values for sync integration tests

requirements/base.txt, requirements/reproducible-linux.txt, tests/functional/commands/validate/lib/models/function_with_function_url_config.yaml, tests/functional/commands/validate/lib/models/function_with_function_url_config_and_autopublishalias.yaml, tests/functional/commands/validate/lib/models/function_with_function_url_config_with_iam_authorization_type.yaml, tests/functional/commands/validate/lib/models/function_with_function_url_config_with_intrinsics.yaml, tests/functional/commands/validate/lib/models/function_with_function_url_config_without_cors_config.yaml
=> chore: update to aws-sam-translator 1.45.0

samcli/__init__.py
=> chore: bump version to 1.45.0

samcli/__init__.py
=> chore: bump version to 1.46.0

requirements/base.txt, requirements/reproducible-linux.txt
=> chore: Bump lambda builders version

samcli/__init__.py
=> chore: bump version to 1.47.0

samcli/commands/init/__init__.py, samcli/commands/init/init_generator.py, samcli/commands/init/interactive_init_flow.py, samcli/lib/init/__init__.py, samcli/lib/init/cli_template_modifier.py, samcli/lib/init/template_modifiers/cli_template_modifier.py, samcli/lib/init/template_modifiers/xray_tracing_template_modifier.py, tests/functional/commands/init/test_interactive_init_flow.py, tests/integration/init/test_init_command.py, tests/unit/commands/init/test_cli.py, tests/unit/commands/samconfig/test_samconfig.py, tests/unit/lib/init/test_cli_template_modifier.py
This pr provides support for Monitoring in SAM/SAMCLI 
=> feat: sam init support for x-ray tracing

tests/integration/init/schemas/schemas_test_data_setup.py
`sam init` integration tests are using schemas which is not available in registry. This PR addressing that issue by using schemas from AWS.
=> fix: sam init schema integration tests

samcli/__init__.py
=> chore: bump version to 1.48.0

samcli/__init__.py, samcli/local/docker/lambda_debug_settings.py, tests/unit/commands/init/test_cli.py
=> chore: Version bump to 1.49.0

requirements/base.txt, requirements/reproducible-linux.txt, samcli/views/concrete_views/rich_table.py, samcli/views/table_view.py, tests/unit/views/test_rich_table.py
Create an interface for CLI table views and implement it for the Rich terminal library.
We will need to find a better way to test this since the tests will be affected by screen size.
Allows us to create CLI tables more easily using various libraries.
=> feat: Add table view and rich table

samcli/__init__.py
=> chore: bump version to 1.51.0

samcli/cli/command.py, samcli/commands/list/cli_common/options.py, samcli/commands/list/list.py, samcli/commands/list/resources/cli.py, samcli/commands/list/stack_outputs/cli.py, samcli/commands/list/testable_resources/cli.py, tests/integration/list/list_integ_base.py, tests/integration/list/resources/resources_integ_base.py, tests/integration/list/resources/test_resources_command.py, tests/integration/list/stack_outputs/stack_outputs_integ_base.py, tests/integration/list/stack_outputs/test_stack_outputs_command.py, tests/integration/list/testable_resources/test_testable_resources_command.py, tests/integration/list/testable_resources/testable_resources_integ_base.py, tests/unit/commands/list/resources/test_cli.py, tests/unit/commands/list/resources/test_resources.py
Want a sam list command to be a single location where customers can observe the state and information related to their serverless application, both in the cloud and on their machine.
Provides the base commands of sam list and the integration tests for the help messages
=> feat: Adding base commands and help messages for sam list

samcli/commands/delete/command.py, samcli/commands/delete/delete_context.py, tests/integration/delete/delete_integ_base.py, tests/integration/delete/test_delete_command.py, tests/unit/commands/delete/test_command.py, tests/unit/commands/delete/test_delete_context.py
=> Revert "feat: Add --s3-bucket and --s3-prefix to sam delete"

build_dir/MyFunctionbf3066d1DepLayer/AWS_SAM_CLI_README, samcli/lib/telemetry/event.py, tests/unit/lib/telemetry/test_event.py
N/A
This change adds Events to the codebase, which will be used alongside the Telemetry class to keep record of which specific events occur during the runtime of a given command.
With the new data structure, Events and their available options can be created and used to represent the settings used during command runs.
Since the Event class and its test method are currently disjoint from the rest of the codebase, there are no immediate side effects to this addition.
=> Implement event data structure and relevant unit tests

samcli/local/apigw/local_apigw_service.py
No issue was open for this
It improves "debuggability".
I've lost quite some time before understanding that the data I was sending in a POST payload could not be properly decoded
(as part of #4017)
In case of a text decoding error, this PR ensures the error is logged.
None
=> Logging UnicodeDecodeError details in LocalApigwService._request_handler

samcli/commands/_utils/constants.py, samcli/commands/_utils/custom_options/hook_package_id_option.py, samcli/commands/_utils/options.py, samcli/commands/build/build_context.py, samcli/commands/local/invoke/cli.py, samcli/commands/local/start_lambda/cli.py, samcli/commands/sync/command.py, samcli/lib/hook/hook_wrapper.py, tests/unit/commands/_utils/custom_options/test_hook_package_id_option.py, tests/unit/commands/local/invoke/test_cli.py, tests/unit/commands/local/start_lambda/test_cli.py, tests/unit/commands/samconfig/test_samconfig.py, tests/unit/commands/sync/test_command.py, tests/unit/lib/hook/test_hook_wrapper.py
=> feat: add --hook-package-id option to sam local invoke, and sam local start-lambda commands

samcli/__init__.py
=> chore: bump version to 1.54.0

samcli/__init__.py
=> chore: bump version to 1.55.0

README.md, requirements/base.txt, requirements/reproducible-linux.txt, samcli/__init__.py, samcli/cli/cli_config_file.py, samcli/cli/types.py, samcli/commands/_utils/experimental.py, samcli/commands/build/build_context.py, tests/functional/commands/validate/lib/models/function_with_msk.yaml, tests/functional/commands/validate/lib/models/function_with_msk_with_intrinsics.yaml, tests/functional/commands/validate/lib/models/function_with_self_managed_kafka.yaml, tests/functional/commands/validate/lib/models/self_managed_kafka_with_intrinsics.yaml, tests/integration/buildcmd/build_integ_base.py, tests/integration/sync/test_sync_code.py, tests/integration/sync/test_sync_infra.py, tests/integration/sync/test_sync_watch.py, tests/unit/cli/test_cli_config_file.py, tests/unit/cli/test_types.py, tests/unit/commands/_utils/test_experimental.py, tests/unit/commands/buildcmd/test_build_context.py, tests/unit/commands/samconfig/test_samconfig.py
=> feat: Remove esbuild beta flag

samcli/hook_packages/terraform/hooks/prepare.py, tests/unit/hook_packages/terraform/test_prepare_hook.py
Collect the sam metadata resources found in the terraform project to be processed by the enrich method
=> feat: collect sam metadata resources to be processed by the enrich method

samcli/hook_packages/terraform/hooks/prepare.py, samcli/lib/hook/exceptions.py, tests/unit/hook_packages/terraform/test_prepare_hook.py
Add the sam metadata resource type property validations.
=> feat: do metadata resource type property validations

requirements/base.txt, requirements/reproducible-linux.txt
=> chore: bump lambda builders version to 1.19.0

samcli/hook_packages/terraform/hooks/prepare.py, tests/unit/hook_packages/terraform/test_prepare_hook.py
enrich the ZIP lambda functions with the data included in the sam metadata resource.
=> feat: enrich zip lambda functions

samcli/hook_packages/terraform/hooks/prepare.py, tests/unit/hook_packages/terraform/test_prepare_hook.py
enrich the Image lambda functions with the data included in the sam metadata resource.
=> feat: enrich image lambda functions

samcli/hook_packages/terraform/hooks/prepare.py, tests/unit/hook_packages/terraform/test_prepare_hook.py
=> chore: refactor enrich_zip_lambda_functions, and enrich_image_lambda_functions outside of enrich_mapped_resources

tests/integration/buildcmd/test_build_cmd.py
=> test: add integration test cases to cover Custom build with custom working directory

samcli/lib/sync/watch_manager.py
=> Fix typo in watch_manager.py

appveyor-ubuntu.yml, appveyor.yml
N/A
PR checks are not working due to go1.13 not available
switch to use go1.15
=> Update appveyor definition to use go1.15

README.md
N/A
Update the invite to match SAM's repos
Updates the Invite link
No
=> fix: Update Slack Invite link

samcli/__init__.py
=> chore: bump sam cli version to 1.56.1

README.md
=> fix: README.md - command names

samcli/__init__.py
=> Version bump to 1.58.0

samcli/__init__.py
=> chore: bump version to 1.59.0

samcli/hook_packages/terraform/hooks/prepare/resource_linking.py
Add _link_lambda_function_to_layer function stub to unblock other tasks
=> feat: add _link_lambda_function_to_layer function stub

samcli/hook_packages/terraform/hooks/prepare/exceptions.py, samcli/hook_packages/terraform/hooks/prepare/hook.py, samcli/hook_packages/terraform/hooks/prepare/resource_linking.py, samcli/hook_packages/terraform/lib/utils.py, tests/unit/hook_packages/terraform/hooks/prepare/test_hook.py, tests/unit/hook_packages/terraform/hooks/prepare/test_resource_linking.py, tests/unit/hook_packages/terraform/lib/test_utils.py
Implement the linking lambda layers to lambda functions.
=> feat: implement linking lambda layers to function

samcli/__init__.py
=> chore: bump version to 1.60.0

samcli/hook_packages/terraform/hooks/prepare/resource_linking.py, tests/integration/buildcmd/test_build_terraform_applications.py, tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_local_backend/artifacts/HelloWorldFunction/app.py, tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_local_backend/artifacts/HelloWorldFunction/requirements.txt, tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_local_backend/artifacts/layer1/lib.py, tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_local_backend/artifacts/layer1/requirements.txt, tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_local_backend/artifacts/layer2/lib.py, tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_local_backend/artifacts/layer2/requirements.txt, tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_local_backend/lambda_function/main.tf, tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_local_backend/lambda_layer/main.tf, tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_local_backend/main.tf, tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_local_backend/py_build.sh, tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_s3_backend/artifacts/HelloWorldFunction/app.py, tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_s3_backend/artifacts/HelloWorldFunction/requirements.txt, tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_s3_backend/artifacts/layer1/lib.py, tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_s3_backend/artifacts/layer1/requirements.txt, tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_s3_backend/artifacts/layer2/lib.py, tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_s3_backend/artifacts/layer2/requirements.txt, tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_s3_backend/lambda_function/main.tf, tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_s3_backend/lambda_layer/main.tf, tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_s3_backend/main.tf, tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_s3_backend/py_build.sh, tests/unit/hook_packages/terraform/hooks/prepare/test_resource_linking.py
=> test: Add integration test cases for building terraform projects with lambda layers support

samcli/__init__.py
=> chore: bump version to 1.61.0

samcli/lib/build/app_builder.py, samcli/local/docker/lambda_build_container.py, tests/integration/buildcmd/test_build_terraform_applications.py, tests/integration/testdata/buildcmd/terraform/build_image_docker/Dockerfile, tests/unit/local/docker/test_lambda_build_container.py
=> fix: building terraform projects in container

tests/integration/testdata/buildcmd/terraform/image_based_lambda_functions_local_backend/main.tf, tests/integration/testdata/buildcmd/terraform/image_based_lambda_functions_s3_backend/main.tf, tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_local_backend/main.tf, tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_local_backend_windows/main.tf, tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_s3_backend/main.tf, tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_s3_backend_windows/main.tf, tests/integration/testdata/invoke/terraform/image_lambda_function_local_image_uri/main.tf, tests/integration/testdata/invoke/terraform/simple_application_with_layers_no_building_logic/main.tf
=> test: use Serverless TF module from terraform registry

samcli/hook_packages/terraform/hooks/prepare/exceptions.py, tests/unit/hook_packages/terraform/hooks/prepare/test_resource_linking.py
Link know issues to their exceptions.
=> chore: Add issue links

MANIFEST.in, samcli/runtime_config.json, setup.py
=> chore: Merge develop to terraform

samcli/__init__.py
=> chore: bump version to 1.62.0

samcli/__init__.py
=> chore: merge from develop

samcli/__init__.py
=> chore: bump version to 1.63.0

samcli/__init__.py
=> chore: bump version 1.64.0

appveyor-windows-build-java-container.yml, samcli/__init__.py
=> chore: bump version to 1.65.0

samcli/__init__.py
=> chore: bump version to 1.66.0

samcli/__init__.py
I reverted back the previous version bump https://github.com/aws/aws-sam-cli/pull/4431, and updated the version to be `1.65.1`
=> chore: bump version to 1.65.1

samcli/commands/validate/validate.py, tests/integration/validate/test_validate_command.py
Update message to include usage of cfnlintrc config files and to avoid assumption of binary name
Removes binary name and includes suggestion for cfnlintrc file
Changed integration tests
=> Update lint help and output message

samcli/__init__.py
=> chore: bump version to 1.67.0

installer/pyinstaller/build-mac.sh
=> fix: move "set -eu" after setting all variables

samcli/__init__.py
=> chore: bump version to 1.68.0

samcli/__init__.py
=> chore: bump version to 1.70.0

.github/workflows/build.yml, .github/workflows/codeql.yml
Feature branches were not covered by the build and CodeQL Github Actions workflows.
Added `feat/*` to both workflow files.
=> feat: Added feature branches to build and codeql actions

samcli/__init__.py
=> chore: bump version to 1.72.0

samcli/__init__.py
=> chore: bump version to 1.73.0

samcli/cli/command.py, samcli/cli/context.py, samcli/cli/formatters.py, samcli/cli/main.py, samcli/cli/root/command_list.py, samcli/cli/row_modifiers.py, tests/unit/cli/test_command.py, tests/unit/cli/test_formatters.py, tests/unit/cli/test_row_modifiers.py
N/A
This gives the tool better UX to showcase the lifecycles of the process and how one should view the process and how to get started.
N/A
=> feat: implementation on the root command help text design

samcli/commands/build/build_context.py, samcli/lib/build/workflow_config.py, tests/integration/testdata/buildcmd/template_build_method_rust_binary.yaml, tests/integration/testdata/buildcmd/template_build_method_rust_single_function.yaml, tests/unit/lib/build_module/test_workflow_config.py
N/A
a clearer naming
Rename `rustcargolambda` Build Method to `rust-cargolambda`
No
=> Rename rustcargolambda build method to rust-cargolambda

tests/integration/list/stack_outputs/test_stack_outputs_command.py
https://github.com/aws/aws-sam-cli/security/code-scanning/5
Sanitizing URLs while in the integration tests.
N/A
=> codeql: fix warnings

samcli/__init__.py
=> chore: bump version to 1.76.0

tests/integration/init/schemas/test_init_with_schemas_command.py
N/A
`sam init` with schemas integration tests are breaking because the PR https://github.com/aws/aws-sam-cli-app-templates/pull/355 added `Hello World Example With Powertools` useCaseName for dotNet template which changed the order of options for the `sam init` question `Choose an AWS Quick Start application template`.
Before:
```
1 - Hello World Example
2 - Multi-step workflow
3 - Serverless API
4 - Scheduled task
5 - Standalone function
6 - Data processing
7 - Infrastructure event management
8 - Hello World Example With Powertools
9 - Serverless Connector Hello World Example
10 - Multi-step workflow with Connectors
11 - Lambda EFS example
12 - DynamoDB Example
13 - Machine Learning
```
After:
```
1 - Hello World Example
2 - Multi-step workflow
3 - Serverless API
4 - Scheduled task
5 - …
```
=> fix: Fix init schema integration tests

samcli/local/apigw/event_constructor.py, samcli/local/apigw/local_apigw_service.py, tests/unit/local/apigw/test_event_constructor.py, tests/unit/local/apigw/test_local_apigw_service.py
N/A
The `local_apigw_service.py` file is too large. 
Moved the event generation logic to it's own module.
None.
=> feat: Event construction refactor

tests/integration/buildcmd/test_build_cmd.py
N/A
The `buildcmd` Integration test broke due to missing import
Add the missing import
=> fix missing imports

samcli/commands/delete/delete_context.py, tests/unit/commands/delete/test_delete_context.py
=> Fix typo in delete_context.py

requirements/base.txt, requirements/reproducible-linux.txt, samcli/__init__.py, samcli/runtime_config.json, tests/functional/commands/validate/lib/models/cognito_user_pool_with_new_property_and_cognito_event.yaml, tests/functional/commands/validate/lib/models/connector_appsync_to_lambda.yaml, tests/functional/commands/validate/lib/models/function_with_function_url_config.yaml, tests/functional/commands/validate/lib/models/function_with_function_url_config_and_autopublishalias.yaml, tests/functional/commands/validate/lib/models/function_with_function_url_config_with_intrinsics.yaml, tests/functional/commands/validate/lib/models/function_with_mq.yaml, tests/functional/commands/validate/lib/models/separate_route53_recordset_group.yaml
=> chore: Bump SamTranslator version to 1.64.0

samcli/commands/deploy/core/command.py
N/A
**Before:**
**After:**
Gets the Alignment right based on the text options.
N/A
=> fix: set the indentation right for `sam deploy`

samcli/hook_packages/terraform/hooks/prepare/property_builder.py, samcli/hook_packages/terraform/hooks/prepare/translate.py, tests/unit/hook_packages/terraform/hooks/prepare/prepare_base.py, tests/unit/hook_packages/terraform/hooks/prepare/test_translate.py
N/A
Allow consuming Terraform `aws_api_gateway_resource` and converting it to a CFN `AWS::ApiGateway::Resource`
Creates the relevant resource mapper objects to handle the Terraform->CFN mapping.
N/A
=> feat: Read and translate APIGW Resource for Terraform

samcli/commands/_utils/options.py
With #3358, the `--no-progressbar` option also affects image uploads to ECR, in addition to artifacts uploads to S3.  
However, the help message only mentions artifacts uploads to S3.
I have updated the help message.
=> Update help message of --no-progressbar option

samcli/commands/_utils/click_mutex.py, samcli/commands/_utils/custom_options/replace_help_option.py, samcli/commands/init/command.py, samcli/commands/init/core/command.py, samcli/commands/init/core/formatters.py, samcli/commands/init/core/options.py, tests/unit/commands/init/core/test_command.py, tests/unit/commands/init/core/test_formatter.py, tests/unit/commands/init/core/test_options.py
N/A
* Clean up the help text for sam init, especially its the first command we ask to run after looking at the `sam --help` text.
* Split up examples section to showcase what each section is about, we should do this for other commands as well.
N/A
* Ran the unit and integration tests for the init suite.
=> sam init command help

samcli/__init__.py
=> chore: bump version to 1.80.0

samcli/runtime_config.json
=> feat: update app templates commit hash

samcli/__init__.py
=> chore: bump version to 1.81.0

requirements/base.txt, requirements/reproducible-linux.txt, tests/functional/commands/validate/lib/models/api_merge_definitions_with_any_method.yaml, tests/functional/commands/validate/lib/models/connector_with_non_id_source_and_destination.yaml, tests/functional/commands/validate/lib/models/schema_validation_4.yaml
To use the latest SAM Translator library
=> chore: Bump SamTranslator version to 1.65.0

samcli/__init__.py
=> chore: bump version to 1.82.0

requirements/base.txt, requirements/reproducible-linux.txt
Update to latest `aws-sam-translator`
* `aws-sam-translator` version 1.66.0 is now out.
=> feat: update `aws-sam-translator` to 1.66.0

installer/assets/THIRD-PARTY-LICENSES, requirements/base.txt, requirements/reproducible-linux.txt, samcli/lib/utils/sam_logging.py, tests/unit/lib/utils/test_sam_logging.py
better UX
After:
* Better UX overall and opens the pathway to better UX experiences powered by `rich`
```
sam local invoke
sam init
sam logs
sam traces
sam build
sam build --use-container
```
* N/A, only setting `rich` if its a tty otherwise we go back to a StreamHandler.
=> feat: logs powered by `rich`

tests/integration/local/invoke/test_invoke_terraform_applications.py, tests/integration/local/start_api/test_start_api.py, tests/integration/publish/publish_app_integ_base.py, tests/integration/testdata/sync/code/after/dotnet_function/src/HelloWorld/HelloWorld.csproj, tests/integration/testdata/sync/code/before/dotnet_function/src/HelloWorld/HelloWorld.csproj, tests/integration/testdata/sync/code/before/template-dotnet.yaml
Resolve some integration testing issues. I added comments to the PR for more details.
=> fix: fix some issues in integration testing

samcli/commands/sync/command.py, samcli/lib/build/app_builder.py, samcli/lib/deploy/deployer.py, samcli/lib/providers/sam_function_provider.py, samcli/lib/sync/sync_flow_executor.py, samcli/lib/sync/watch_manager.py, samcli/lib/utils/colors.py, tests/unit/lib/utils/test_colors.py
- maintain click backcompatability with interface.
- tests added
=> fix: switch to `rich` for color logging.

samcli/__init__.py
=> chore: version bump to 1.83.0

.github/workflows/automated-updates-to-sam-cli.yml
none
fixes GHA
Fixes spelling error
no
=> fix: spelling error in repo for updating SAM-T version GHA

samcli/hook_packages/terraform/hooks/prepare/translate.py, tests/unit/hook_packages/terraform/hooks/prepare/test_translate.py
* based on parent_id and root_resource_id
=> feat: Link APIGW Resources to APIGW REST APIs

samcli/__init__.py
=> chore: bump version to 1.84.0

samcli/__init__.py
=> chore: bump version to 1.85.0

tests/integration/testdata/buildcmd/aws-serverless-application-with-application-id-map.yaml
Use the SAR Application created in the Testing account instead of the one created in `077246666028` account.
=> chore: use the SAR Application created in testing accounts

samcli/__init__.py
=> chore: bump version to 1.86.0

samcli/__init__.py
=> chore: bump version to 1.87.0

samcli/__init__.py
=> chore: bump version to 1.88.0

samcli/__init__.py
=> chore: Version bump to 1.89.0

samcli/__init__.py
=> chore: bump version to 1.90.0

samcli/commands/pipeline/bootstrap/cli.py
N/A
Not necessary, but just a minor typo.
None.
=> chore: fix typo in help text of `pipeline bootstrap`

tests/end_to_end/testdata/esbuild-datadog-integration/template.yaml
N/A
Integration test times out during function invocation.
Increases the timeout to 15 seconds.
N/A
=> fix: Bump timeout

samcli/lib/providers/cfn_api_provider.py
Missing character in exception message.
Improve message text.
Add the missing character.
None.
=> fix(providers): correct typo

samcli/__init__.py
prepare for Python 3.11 release. 
=> chore: bump version to 1.92.0

samcli/__init__.py
=> chore: bump version to 1.93.0

README.md
N/A
To be more accurate 
Update brew tap badge in README.md
N/A
=> Update brew tap badge in README.md

samcli/__init__.py
=> chore: bump version to 1.94.0

appveyor-windows-binary.yml
=> Add Windows config

appveyor-windows-binary.yml
=> Binary canaries

samcli/__init__.py
=> chore: bump version to 1.95.0

samcli/lib/utils/subprocess_utils.py, samcli/local/apigw/local_apigw_service.py, tests/integration/buildcmd/test_build_terraform_applications_other_cases.py, tests/integration/testdata/buildcmd/terraform/broken_tf/main.tf
N/A
Fixes a bug and issue related to SAM CLI exception handling.
- Logs the authorizer exception message instead of just the exception name
- Fixes a bug where a formatted string attempts to be formatted again, throwing an exception
N/A
- [] Write/update unit tests
=> fix: Error messaging with Terraform and Authorizers

samcli/__init__.py
=> chore: Version bump to 1.97.0

appveyor-ubuntu.yml
=> chore: Change ubuntu canary thread count to 1

tests/integration/testdata/buildcmd/terraform/image_based_lambda_functions_local_backend/hello_world/Dockerfile, tests/integration/testdata/buildcmd/terraform/image_based_lambda_functions_s3_backend/hello_world/Dockerfile
=> fix: Pin Docker emulation image version of go1.x in build image

tests/integration/buildcmd/test_build_terraform_applications.py, tests/integration/testdata/buildcmd/terraform/image_based_lambda_functions_local_backend/hello_world/Dockerfile, tests/integration/testdata/buildcmd/terraform/image_based_lambda_functions_s3_backend/hello_world/Dockerfile
=> Fix test bad image

samcli/__init__.py
=> chore: bump version to 1.98.0

appveyor-ubuntu.yml, appveyor-windows.yml, tests/integration/buildcmd/build_integ_base.py, tests/integration/buildcmd/test_build_terraform_applications.py
=> test: Refactor Terraform build tests

samcli/__init__.py
=> chore: bump version to 1.99.0

samcli/commands/init/init_templates.py
without `.value`, it is comparing the wrong type (ie comparing an int against an enum)
compare init against an enum value
=> fix manifest status comparison

tests/integration/buildcmd/test_build_cmd.py
None.
The build and working directory was not being set correctly in this tests after the base class optimization, causing the symlinked template's resources to be resolved incorrectly.
Sets the base build directory and working directory to get the symlink to resolve correctly.
None.
=> fix(tests): Use correct build and cwd folder when building nested stacks

samcli/__init__.py
=> chore: version bump to 1.101

tests/integration/init/test_init_command.py
N/A
After adding the new runtime `provided al2023`, the order of prompts for the hello world template changed.
This PR fixes the integration test.
=> fix(test): Update the prompts to fix init integ test

tests/integration/buildcmd/test_build_cmd_arm64.py, tests/integration/buildcmd/test_build_cmd_rust.py, tests/integration/testdata/buildcmd/Provided/Makefile
=> test: Remove provided rust integ tests and change python3 to python

requirements/base.txt, requirements/reproducible-linux.txt, requirements/reproducible-mac.txt, requirements/reproducible-win.txt
=> feat: update cfn-lint to 0.83.4

samcli/__init__.py
=> chore: bump version to 1.104.0

appveyor-linux-binary.yml, appveyor-ubuntu.yml, appveyor-windows-binary.yml, appveyor-windows.yml, pytest.ini
Some integration tests are still missing retries, this PR adds a global retry configuration.
=> chore: Add retries and delay between retries globally

samcli/__init__.py
=> chore: version bump

samcli/__init__.py
=> chore: bump version to 1.106.0

samcli/__init__.py
=> chore: bump version to 1.107.0

samcli/__init__.py
=> chore: bump version to 1.108

samcli/__init__.py
=> chore: bump version to 1.109.0

samcli/__init__.py
=> chore: Version bump to 1.111.0

samcli/lib/deploy/deployer.py, tests/unit/lib/deploy/test_deployer.py
Displays the new event that is being surfaced by CFN
Displays the new status if it is prevent, behaves the same otherwise
=> feat: Display new CFN status during deploy

samcli/__init__.py
=> chore: bump sam cli version to 1.112.0

installer/pyinstaller/build-linux.sh, installer/pyinstaller/build-mac.sh
=> chore: Update OpenSSL version in installers

samcli/__init__.py
=> chore: version bump to v1.113.0

samcli/__init__.py
=> chore: version bump to v1.115

samcli/__init__.py
=> chore: version bump to 1.116.0

samcli/__init__.py
=> chore: bump version to 1.117.0

samcli/__init__.py
=> chore: Version bump to 1.118.0

samcli/commands/_utils/options.py, tests/integration/deploy/test_deploy_command.py
#6899 
Modified resolve_s3 option to allow override from samconfig 
=> fix: modified option resolve_s3 to allow override from samconfig

samcli/__init__.py
=> chore: bump version to 1.119.0

samcli/__init__.py
=> chore: bump version to 1.121.0

requirements/pyinstaller-build.txt, requirements/reproducible-linux.txt, requirements/reproducible-mac.txt, requirements/reproducible-win.txt
=> Revert "chore(deps): bump setuptools from 70.3.0 to 72.1.0 in /requirements"

samcli/__init__.py
=> chore: bump version to 1.122.0

samcli/lib/build/app_builder.py, samcli/lib/build/build_graph.py, samcli/lib/build/build_strategy.py, samcli/lib/providers/provider.py, tests/integration/buildcmd/build_integ_base.py
=> chore: update log

samcli/__init__.py
=> chore: Version bump to 1.123.0

samcli/lib/deploy/deployer.py, tests/unit/lib/deploy/test_deployer.py
The CFN event is now called detailed status.
New version of boto3 uses DetailedStatus name 
=> fix: the cfn event is called DetailedStatus

samcli/__init__.py
=> chore: bump version to 1.124.0

samcli/__init__.py
=> chore: bump version to 1.125.0

.github/workflows/validate_pyinstaller.yml
=> feat: update rie to v1.22

samcli/__init__.py
=> chore: bump version to 1.128.0

samcli/__init__.py
=> chore: bump version to 1.129.0

samcli/__init__.py
=> chore: version bump to 1.130.0

samcli/__init__.py
=> chore: bump version to 1.131.0

samcli/__init__.py
=> chore: bump version to 1.132.0

.github/dependabot.yml, CODEOWNERS
=> Add Lambda Tooling to Code Owners

appveyor-linux-binary.yml, appveyor-ubuntu.yml, appveyor-windows-al2023.yml, appveyor-windows.yml, setup.py
=> fix: run appVeyor build env on py311

tests/integration/local/start_api/test_start_api.py
Integration tests are failing when being run in Python 3.11 because of this.
=> test: Fix combination of flaky+parameterized

samcli/__init__.py
=> chore: bump version to 1.133.0

samcli/__init__.py
None 
Update dependencies
Update dependency versions
None. 
=> chore: bump version to 1.134.0

.github/workflows/pr-labeler.yml
Previous SAM team are no longer the maintainers of this repo
updates aliases
short-term since hard-coding aliases until we get a better solution
=> fix: Update maintainer aliases 

samcli/__init__.py
=> chore: bump version to 1.135.0

samcli/__init__.py
=> chore: bump version to 1.136.0

requirements/base.txt, requirements/reproducible-linux.txt, requirements/reproducible-mac.txt, requirements/reproducible-win.txt
To fix https://github.com/aws/aws-sam-cli/issues/7956
=> chore: update cfn-lint to 1.32.3

samcli/__init__.py
=> chore: bump version to 1.137.0

requirements/base.txt, requirements/reproducible-linux.txt, requirements/reproducible-mac.txt, requirements/reproducible-win.txt
Merge from aws/aws-sam-cli/develop
* chore: update aws-sam-translator to 1.97.0
=> Merge from aws/aws-sam-cli/develop

requirements/base.txt, requirements/reproducible-linux.txt, requirements/reproducible-mac.txt, requirements/reproducible-win.txt
=> chore(deps): bump cfn-lint from 1.32.3 to 1.34.1 in /requirements

samcli/__init__.py
New release of SAM CLI
Update version of SAM CLI 
=> chore: bump version to 1.138.0

README.md
=> chore: added a link to the Apache license badge

samcli/__init__.py
=> chore: bump version to 1.139.0

appveyor-windows-binary.yml
This is to fix canary failure running on Windows machines. 
We see canary failure due to missing path for DockerCli.exe
```
Restart-Service docker
& $Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchLinuxEngine
& : The term 'C:\Program Files\Docker\Docker\DockerCli.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path 
is correct and try again.
At line:1 char:3
+ & $Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchLinuxEngine
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (C:\Program File...r\DockerCli.exe:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
Command executed with …
```
=> fix: add check for docker client for switch mode on Windows machine

samcli/__init__.py
Release version 1.141.0
Release changes to public
=> chore: bump version to 1.141.0

samcli/__init__.py
=> chore: bump version to 1.142.0

appveyor-windows-al2023.yml
=> chore(test): Update appveyor-windows-al2023.yml

README.md
N/A
Fixes dead links on the README
references the correct link
N/A
=> fix(README): correct the dead link on open source contribution story
