appveyor-windows.yml

Appveyor defaults to 1.9 but we have sync tests that use Ruby 2.7.
This caused our integration tests that run within DeployIntegTesting
to fail.
DeployIntegTesting in `appveyor-windows.yml` fails due to 1.9 being the Ruby version.
Add Ruby 2.7 to the path which is what the sync tests use.
None

fix(ci): Move to Ruby 2.7 over 1.9

---

samcli/lib/sync/flows/generic_api_sync_flow.py

N/A
Definition file can be None which will error out when called with .joinpath(..,)
Added check for definition file.

fix: Skip APIs with No DefinitionUri

---

samcli/commands/init/__init__.py
samcli/commands/init/init_templates.py
samcli/commands/init/interactive_init_flow.py
samcli/lib/utils/git_repo.py
tests/unit/commands/init/test_cli.py

This pr addresses issues raised by customers with respect to new revamped SAM CLI Init interactive experience:
1. In this PR the wait time to get the manifest file from the cli template was reduced by 80%. Additional robust fault tolerance has been added to ensure that customers always get a vended app template.
2. CLl depends on the manifest file in the cli template repo to create the new, easy and quick interactive experience. This update in the PR ensures that the cli 
- Attempts to first get just the Manifest file directly from github
- If this fails, the CLI then resorts to cloning the cli template repo and using the cloned manifest
- if the cloning fails, a local manifest which acts as reference to all local app templates in SAM CLI is used.
This way ensures that customers always …

feat: sam init changes to improve getting manifest time and clone messaging

---

samcli/commands/init/__init__.py
samcli/commands/init/init_templates.py
samcli/commands/init/interactive_init_flow.py
samcli/local/common/runtime_template.py
tests/functional/commands/init/test_interactive_init_flow.py
tests/functional/testdata/init/unknown_runtime/manifest-v2.json
tests/functional/testdata/init/unknown_runtime/python3.8/cookiecutter-aws-sam-hello/cookiecutter.json
tests/functional/testdata/init/unknown_runtime/python3.8/cookiecutter-aws-sam-hello/setup.cfg
tests/functional/testdata/init/unknown_runtime/python3.8/cookiecutter-aws-sam-hello/{{cookiecutter.project_name}}/hello_world/app.py
tests/functional/testdata/init/unknown_runtime/python3.8/cookiecutter-aws-sam-hello/{{cookiecutter.project_name}}/hello_world/requirements.txt
tests/functional/testdata/init/unknown_runtime/python3.8/cookiecutter-aws-sam-hello/{{cookiecutter.project_name}}/template.yaml
tests/functional/testdata/init/unknown_runtime/random.runtime1/cookiecutter-aws-sam-hello/cookiecutter.json
tests/functional/testdata/init/unknown_runtime/random.runtime1/cookiecutter-aws-sam-hello/setup.cfg
tests/functional/testdata/init/unknown_runtime/random.runtime1/cookiecutter-aws-sam-hello/{{cookiecutter.project_name}}/hello_world/app.py
tests/functional/testdata/init/unknown_runtime/random.runtime1/cookiecutter-aws-sam-hello/{{cookiecutter.project_name}}/hello_world/requirements.txt
tests/functional/testdata/init/unknown_runtime/random.runtime1/cookiecutter-aws-sam-hello/{{cookiecutter.project_name}}/template.yaml
tests/functional/testdata/init/unknown_runtime/random.runtime2/cookiecutter-aws-sam-hello/cookiecutter.json
tests/functional/testdata/init/unknown_runtime/random.runtime2/cookiecutter-aws-sam-hello/setup.cfg
tests/functional/testdata/init/unknown_runtime/random.runtime2/cookiecutter-aws-sam-hello/{{cookiecutter.project_name}}/hello_world/app.py
tests/functional/testdata/init/unknown_runtime/random.runtime2/cookiecutter-aws-sam-hello/{{cookiecutter.project_name}}/hello_world/requirements.txt
tests/functional/testdata/init/unknown_runtime/random.runtime2/cookiecutter-aws-sam-hello/{{cookiecutter.project_name}}/template.yaml
tests/unit/commands/init/test_cli.py

This change fixes the bug when new runtimes in the app templates manifest break sam init.
Older versions of samcli fail when a new runtimes are added to cli template repo. Version affected are 1.37.0 to 1.40.0
It starts using `manifest-v2.json` in the app templates repo.

fix: Runtime sorting fix and use new manifest

---

samcli/lib/utils/file_observer.py
tests/integration/local/start_api/start_api_integ_base.py
tests/integration/local/start_api/test_start_api.py
tests/integration/testdata/start_api/main-layers.py
tests/integration/testdata/start_api/template-warm-containers-layers.yaml
tests/unit/lib/utils/test_file_observer.py

#3683
Running start-api with warm containers and a downloaded layer will throw an exception ```"Lambda functions containers initialization failed because of expected str, bytes or os.PathLike object, not NoneType"```
Check if layer codeuri exists before attempting to watch it

fix: Warm containers break on non-local layers

---

samcli/local/docker/lambda_debug_settings.py

N/A
Python3.6 emulation images now uses `/var/runtime/bootstrap.py` instead of `/var/runtime/awslambda/bootstrap.py`.
Although `/var/runtime/awslambda/bootstrap.py` is still a symlink to the new path, we want to update the path for the future.
Changes the path to `/var/runtime/bootstrap.py`.
None

fix: Update Python3.6 Debug Bootstrap Path

---

samcli/commands/init/interactive_init_flow.py
tests/functional/commands/init/test_interactive_init_flow.py
tests/functional/testdata/init/unknown_runtime/python3.8/cookiecutter-aws-sam-hello/{{cookiecutter.project_name}}/unique_test_file.txt
tests/unit/commands/init/test_cli.py

Help in gating runtimes SAMCLI is yet to supported to be accessed by customer.
Removes runtime from list of runtimes generated from the manifest file in CLI template repo
None

Gating Unsupported runtime

---

tests/integration/init/schemas/test_init_with_schemas_command.py

EB Go binding was introduced in PR #3657. However, it affected existing interactive init flow test cases as `go` became the first runtime option and everything else shifted downward by 1. This PR fixes these broken test cases.
Fix tests
Update the inputs
No

Fix broken integration tests due to new Go code binding in EB

---

requirements/base.txt
requirements/reproducible-linux.txt

#3789 
To match minimum boto3 version in SamTranslator. If a Linux customer has an older version of boto3 installed, they might see error `AttributeError: 'Session' object has no attribute 'get_partition_for_region'`. That requires a minimum of 1.19.5 for boto3.
bump boto3 minimum version
No

Bump minimum boto3 version to 1.19.5

---

samcli/local/docker/container.py

Colima seemed to need more than the current default 5s when doing `sam build --use-container`

fix: increase container start timeout

---

samcli/commands/init/init_templates.py
samcli/commands/init/interactive_init_flow.py
samcli/lib/init/__init__.py
samcli/local/common/runtime_template.py
tests/unit/commands/init/test_cli.py

Which issue(s) does this change fix?
This pr help us provide support for custom runtime in SAMCLI
Adding this support will enable us to custom runtimes
None
- [] Write design document if needed ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))

SAM INIT support for custom runtimes

---

.github/workflows/update_app_templates_hash.yml

N/A
We recently added a configuration file which keeps the latest commit hash from aws/aws-sam-cli-app-templates repositorty. This GH action is updating that hash value in configuration by running it every hour (or manually).
Test run in fork: https://github.com/mndeveci/aws-sam-cli/actions/runs/2223773270
Result PR in fork: https://github.com/mndeveci/aws-sam-cli/pull/3

chore: add gh action to update app templates hash

---

tests/unit/lib/utils/test_configuration.py

The test originally tested against the value set in `samcli/runtime_config.json`. However, since merging PR #3838, the value can change from time to time. This PR fixes the test and improves coverage.
mock `config.get` to return a fake value for testing. Also add test to test `samcli/runtime_config.json` is read properly.
No

Fix tests to not depend on changeable value

---

tests/integration/deploy/deploy_integ_base.py
tests/integration/init/schemas/test_init_with_schemas_command.py
tests/integration/init/test_init_command.py

N/A
To fix the failing integration tests.
Recent addition to `sam init` interactive workflow has affected some of the init integration tests. There was also misconfiguration from recent refactoring which affected one of the `sam deploy` integration tests.

fix: deploy and init integration tests

---

samcli/cli/global_config.py
tests/functional/commands/cli/test_global_config.py
tests/unit/cli/test_global_config.py

#3855
SAM CLI writes its `GlobalConfig` object when getting or setting its persistent configuration values. If a folder is configured which user doesn't have write access, getting or setting these values might fail, which will also affect the running command.
Move write into a try/except block so that failing while persisting a configuration won't affect running command.
N/A

fix: command should not fail when global config fails to write

---

appveyor-iac-integration-ubuntu.yml

fix: iac canaries

---

samcli/lib/observability/xray_traces/xray_event_mappers.py
samcli/lib/observability/xray_traces/xray_event_puller.py
samcli/lib/observability/xray_traces/xray_events.py
tests/unit/lib/observability/xray_traces/test_xray_event_puller.py

N.A.
Our previous fix on traces that introduced revision number to trace events, which is incompatible with traces command's trace_id option.
Made this revision change compatible with trace_id option.
Not known.

fix: Fixing the trace event class to support trace_id option

---

.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md
.github/ISSUE_TEMPLATE/anything_else.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/other.md
.github/workflows/pr-labeler.yml

Will help triage which new issues and PRs haven't been looked at by the team, as querying by no comments or no labels can sometimes be misleading.
New label `stage/needs-triage` automatically assigned on new issues and PRs.

feat: improve new PR and issue labeling for triaging

---

samcli/commands/logs/command.py
samcli/commands/logs/logs_context.py
samcli/lib/observability/xray_traces/xray_events.py
samcli/lib/utils/cloudformation.py
tests/integration/logs/test_logs_command.py
tests/integration/sync/test_sync_infra.py
tests/unit/commands/logs/test_logs_context.py
tests/unit/lib/utils/test_cloudformation.py

N/A
Adding Nested Stack support for `sam logs` command
As of now, `sam logs` only searches for `logicalId` -> `physicalId` mapping in the current stack. With this change, this search is expanded into nested stacks, and information returned as tree format.
Logs from nested stack resources can be pulled by prepending Nested Stack's logical id in the front (like `NestedStackLogicalId/ResourceLogicalId`)
With SAM Accelerate, customers were able to pull logs from all supported resources from the current stack, this feature is under Beta Flag at the moment. With this change, customers will be pulling logs from all supported resources across their nested stacks as well.
By submitting this pull request, I confirm that my contribution is …

feat: nested stack support for sam logs

---

requirements/base.txt
requirements/reproducible-linux.txt
samcli/commands/_utils/experimental.py
samcli/commands/build/build_context.py
tests/integration/buildcmd/build_integ_base.py
tests/integration/telemetry/test_experimental_metric.py
tests/unit/commands/_utils/test_experimental.py
tests/unit/commands/buildcmd/test_build_context.py

https://github.com/aws/aws-sam-cli/issues/3639
To use correct scope for building maven projects & copy correct files during layer build or Java runtimes.
Lambda Builders was using `compile` scope before for maven projects. With this change it will be using `runtime` scope which will only bundle dependencies that is needed during execution.
Also, it will be bundling `.jar` files for layer build since layer build doesn't support loading `.class` files.
Final package size might be affected since some dependencies will be dropped and some might be added to the final artifact. These changes were in Beta since Feb 2022. …

feat: make java build scope changes default

---

samcli/commands/_utils/options.py
tests/integration/buildcmd/test_build_cmd.py
tests/integration/testdata/buildcmd/samconfig_no_cached.toml
tests/unit/commands/samconfig/test_samconfig.py

#3828
To allow for samconfig.toml's cached = true setting to be overriden by a command line parameter 
adding a  "--no-cached" option to overrides the cached = true setting in samconfig.toml

Add explicit --no-cached option 

---

samcli/commands/build/build_context.py
samcli/lib/bootstrap/nested_stack/nested_stack_builder.py
samcli/lib/bootstrap/nested_stack/nested_stack_manager.py
tests/unit/commands/buildcmd/test_build_context.py
tests/unit/lib/bootstrap/nested_stack/test_nested_stack_builder.py
tests/unit/lib/bootstrap/nested_stack/test_nested_stack_manager.py

N/A
In order to support Auto Dependency Layer creation for Nested Stacks.
Previous implementation was only creating dependency layers for root stack. With this change, we are iterating over all stacks and create auto dependency layers for functions.
N/A

feat: ADL nested stack support

---

samcli/lib/sync/flows/function_sync_flow.py
samcli/lib/sync/flows/image_function_sync_flow.py
samcli/lib/sync/flows/layer_sync_flow.py
samcli/lib/sync/flows/zip_function_sync_flow.py
samcli/lib/sync/sync_flow.py
samcli/lib/sync/sync_flow_executor.py
samcli/lib/sync/watch_manager.py
samcli/lib/utils/lock_distributor.py
tests/integration/sync/test_sync_code.py
tests/unit/lib/sync/flows/test_image_function_sync_flow.py
tests/unit/lib/sync/flows/test_layer_sync_flow.py
tests/unit/lib/sync/flows/test_zip_function_sync_flow.py
tests/unit/lib/sync/test_sync_flow.py

N.A.
To prevent sync race condition on function flows.
Added a lockchain that both function config update and function code update need to grab.
Added a remote function status check to ensure function update was complete.
Not known.

fix: Add lockchain and status check to prevent sync flows race condition on function update

---

samcli/local/docker/lambda_debug_settings.py

See https://github.com/aws/aws-sam-cli/issues/3886
Node16 lambdas use an ES module entry point, not CJS.

fix: use correct entry file for node 16 debugging

---

.github/workflows/update_app_templates_hash.yml

Limit `Update aws/aws-sam-cli with latest commit hash from aws/aws-sam-cli-app-templates` GH Action to only run on `aws/aws-sam-cli`.

chore: run app templates hash updated job only on aws/aws-sam-cli

---

samcli/commands/_utils/table_print.py
samcli/lib/deploy/deployer.py
tests/unit/lib/deploy/test_deployer.py

Fixes #3910
Fixes #3911
When using the feature from #3500 and deploy with a large `SAM_CLI_POLL_DELAY` events for each poll iterations are in reverse order. And if another process update the stack while sleeping the loop won't stop and catch events from another process.
- Buffer events in a `deque` (push front) to print in chronological order
- Remove `DescribeStacks` request and rely on first `not_in_progress` event on the root stack to exit the loop
- In tests reverse mock events order to match `DescribeStackEvents` api reverse chronological order
- Test print order
- No more requests to `DescribeStack`
- Print refresh delay (`client_sleep`) in table header
By submitting this pull request, I confirm that my contribution is made …

Fix deploy with long poll delay events order and stop condition

---

tests/integration/logs/test_logs_command.py
tests/integration/sync/test_sync_code.py
tests/integration/testdata/logs/python-apigw-sfn/template.yaml

Sync watch and sync infra don't use fixture, so no change there.

chore: Add safe teardown for accelerate integration test

---

samcli/lib/build/app_builder.py
tests/integration/buildcmd/build_integ_base.py
tests/integration/buildcmd/test_build_cmd.py
tests/unit/lib/build_module/test_app_builder.py

The default behaviour of [docker image create API](https://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.ImageCollection.build) is to keep the intermediate containers created. So, when customer execute `sam build` for an Image type Lambda Function, the customer will find some created containers exist after `sam build` command finish. This PR is to clean these intermediate containers, and let the docker API delete these containers after the image built process finish.

feat: remove the created intermediate containers while building the lambda functions of Image Type

---

samcli/__init__.py
samcli/lib/utils/git_repo.py
tests/unit/lib/utils/test_git_repo.py

#3946 
App templates repo contains some very long paths in which Windows doesn't support them as it has a limitation of 260 chars. 
This change modifies the `git clone` command by appending `--config core.longpaths=true` if the system is Windows. The config is only applied for the cloned repo (i.e. the app templates repo) and won't affect user's system settings. 
No

Fix issue in cloning app templates repo in windows

---

samcli/commands/build/build_context.py
samcli/lib/providers/provider.py
samcli/lib/providers/sam_function_provider.py
samcli/lib/sync/flows/generic_api_sync_flow.py
samcli/lib/sync/flows/stepfunctions_sync_flow.py
samcli/lib/sync/sync_flow.py
tests/integration/sync/test_sync_code.py
tests/unit/commands/buildcmd/test_build_context.py
tests/unit/commands/local/lib/test_provider.py
tests/unit/lib/sync/flows/test_http_api_sync_flow.py
tests/unit/lib/sync/flows/test_rest_api_sync_flow.py
tests/unit/lib/sync/flows/test_stepfunctions_sync_flow.py
tests/unit/lib/sync/test_sync_flow.py

N.A.
Since currently we are implementing code sync support for nested stack, this will make Api and StepFunction resources within child stacks also syncable through sam sync --code.
It resolves the definition files from path relative to child template, to path relative to root template. For base_dir use cases, this will still be base_dir based.
Not known.

feat: Add in support for nested stack's code sync with Api's and StepFunctions

---

samcli/runtime_config.json
tests/integration/sync/sync_integ_base.py
tests/integration/sync/test_sync_code.py
tests/integration/sync/test_sync_infra.py
tests/integration/sync/test_sync_watch.py
tests/integration/testdata/sync/code/after/function/requirements.txt
tests/integration/testdata/sync/code/after/nodejs_function/app.js
tests/integration/testdata/sync/code/after/nodejs_function/package.json
tests/integration/testdata/sync/code/before/nodejs_function/app.js
tests/integration/testdata/sync/code/before/nodejs_function/package.json
tests/integration/testdata/sync/code/before/template-nodejs.yaml

Add integration tests for auto dependency layer.
- Adds checks to ensure ADL contains the expected dependencies
- Parameterizes existing accelerate integration tests to run both with ADL and without
- Add checks to existing tests to verify ADL contents
- Adds a Nodejs code test to verify that runtime with ADL

test: Add ADL tests for nested and non-nested stacks

---

samcli/lib/telemetry/project_metadata.py
tests/unit/lib/telemetry/test_project_metadata.py

N/A
Previously, the metadata attribute `projectName` would be retrieved as the name of the current folder the project is working in (in the event that a project is not also a git repository). This may present issues for projects that may take on identical names (i.e. multiple customers who use the default project name "sam-app"). In those situations, multiple different users would appear as one user. 
If we parse the entire current working directory instead of simply the folder name, we are able to differentiate between different projects of the same name. If two users were to have projects named "sam-app", they would appear identical before this change. With this change, the only way for the two to be identical is for them to have identical file paths to their working directory, which is …

Fix retrieval process for directory name

---

samcli/lib/telemetry/event.py
tests/unit/lib/telemetry/test_event.py

N/A
This implementation of tracking events will allow for any arbitrary event to be tracked and stored in a class variable that can be accessed across multiple files. It is necessary to allow for simplified collection of events that may occur during a SAM CLI session.
An `EventTracker` class has been added to encapsulate the logic of tracking events. It holds a private variable to store events, which are accumulated by scattering `EventTracker.track_event()` method calls throughout other code paths. When called, it appends those Events (if they are valid Events) to the private variable, which can later be accessed to send through Telemetry before the end of the session. The list of tracked events can also be cleared at the end of the session to prevent inaccuracies.
While this new class …

Implement tracker methods

---

tests/integration/buildcmd/build_integ_base.py
tests/integration/buildcmd/test_build_cmd.py
tests/integration/logs/test_logs_command.py
tests/integration/sync/test_sync_adl.py
tests/integration/testdata/sync/code/before/template-python-no-dependencies.yaml
tests/integration/testdata/sync/infra/template-python-after.yaml
tests/integration/testdata/sync/infra/template-python-before.yaml
tests/integration/testdata/sync/infra/template-ruby-after.yaml
tests/integration/testdata/sync/infra/template-ruby-before.yaml
tests/integration/testdata/sync/nested/before/child_stack/template.yaml
tests/integration/testdata/sync/nested/before/template.yaml
tests/integration/testdata/sync/nested_intrinsics/before/child_stack/child_layer/template.yaml

- Update regex to match the new build outputs
- Remove specific layer names from nested stack tests, which leads to random failures (same layer name should not be used in nested stacks)
- Add missing class fields for ADL tests
- Add missing method parameter for `sam logs` tests

chore: fix canary issues

---

samcli/commands/build/build_context.py

N/A
Debug log messaging from `sam build --debug` was confusing when Lambda Functions in CloudFormation template lack Docker metadata properties
Tweaks the wording. The original log message said "Skip Building %s function, as it does not contain either Dockerfile or DockerContext" which confused me, because my function _did_ contain a `DockerContext` property. It was unclear to me that this message was saying that a Function needs _both_ properties. The new wording feels like clearer English to me, but I can't really justify why...maybe because "is missing X or Y" is more affirmative than "does not contain X or Y".
None …

Clarify debug log message in build_context command

---

samcli/lib/build/app_builder.py
samcli/lib/build/build_strategy.py
tests/unit/lib/build_module/test_build_strategy.py

we should use cache build instead of incremental build when building inside container

bug: Use cache build instead of incremental when building in container

---

samcli/lib/observability/observability_info_puller.py
tests/unit/lib/observability/test_observability_info_puller.py

ctrl+c to sam log command with --include-traces option currently doesn't kill the traces' combine puller, with this fix now it should works correctly
overwrite the combine puller's `stop_tailing()` method to make sure it call `stop_tailing() `in all its children pullers.

bug: make sure all pullers in child combine puller also get stopped

---

samcli/commands/sync/command.py
samcli/lib/deploy/deployer.py
samcli/lib/sync/sync_flow_factory.py
tests/integration/sync/test_sync_code.py
tests/unit/commands/sync/test_command.py
tests/unit/lib/sync/test_sync_flow_factory.py

N.A.
When running sync --code, users can use --resource flag to run sync on specific resource types, for example --resource AWS::Serverless::Function means code sync on all serverless function resources. However if an invalid resource type is provided, the sync is skipped without letting the customer to be aware. This adds resource type validation and fail the command in that scenario.
By having a class that stores all supported resource types for sync code.
Not known

feat: Add --resource option input validation for sync --code

---

samcli/commands/local/cli_common/invoke_context.py
samcli/commands/local/cli_common/user_exceptions.py
tests/unit/commands/local/cli_common/test_invoke_context.py
tests/unit/commands/local/lib/test_local_lambda.py

`InvokeContextException` for `sam local` command is used for multiple different error cases. With this PR we are replacing each individual case with specific exception type.
To get more granular information about `InvokeContextException`'s.
By replacing `InvokeContextException` with specific ones.
N/A, some notes;
- `InvokeContextException` or parent class `UserException` have not caught anywhere in the codebase.
- The newly created exceptions are also extending from `UserException` which should cause SAM CLI to fail gracefully without logging the entire trace stack.

chore: replace InvokeContextException with granular ones

---

samcli/lib/build/build_strategy.py
tests/integration/buildcmd/test_build_cmd.py
tests/integration/testdata/buildcmd/Java/maven-with-layer/HelloWorldFunction/pom.xml
tests/integration/testdata/buildcmd/Java/maven-with-layer/HelloWorldFunction/src/main/java/helloworld/App.java
tests/integration/testdata/buildcmd/Java/maven-with-layer/HelloWorldLayer/pom.xml
tests/integration/testdata/buildcmd/Java/maven-with-layer/HelloWorldLayer/src/main/java/helloworldlayer/SimpleMath.java
tests/integration/testdata/buildcmd/template-java-maven-with-layers.yaml
tests/unit/lib/build_module/test_build_strategy.py

N/A
If a function depends on a layer which should be build before it, running `sam build --use-container` might fail randomly since layers and functions are built in parallel.
First builds layers in parallel and once it is completed it builds all functions in parallel.
N/A

fix: issues with parallel build when using compiled languages

---

tests/integration/sync/test_sync_adl.py

chore: skip TestSyncAdlWithWatchStartWithNoDependencies on windows

---

samcli/lib/telemetry/event.py

N/A
Previously, a race condition existed if two threads tried tracking events at the same time, as they would both try to be added to the list. This change works to fix that.
With the introduction of a thread lock, threads will need to wait for the read and write processes of the Event list to finish before performing their own operations.
Due to the nature of `threading.Lock()`, there should be no notable side effects in any other section of the code.

Add thread lock to EventTracker

---

samcli/lib/telemetry/event.py
tests/unit/lib/telemetry/test_event.py

N/A
With these added attributes, we can not only tell when Events occur, but also match Events to one command run via their `thread_id`, which is set to be the arbitrary ID of whatever thread is being used by the system.
The new attributes allow for queries to be run to match groups of Events by thread, which may be useful for SAM commands that employ multithreading.
Since the [thread_id](https://docs.python.org/3/library/threading.html#threading.get_ident) method picks an arbitrary integer to represent the thread ID, it takes no customer-specific data, and is safe for raw use as such. Otherwise, this would have the impact of adding two new fields to the `Event` data structure: `thread_id: int` and `timestamp: datetime`.
By …

Refactor Event data structure

---

tests/unit/lib/telemetry/test_event.py

N/A
As brought up in a [previous PR](https://github.com/aws/aws-sam-cli/pull/4019#discussion_r911300281), it may be a good idea to verify that the thread lock in `EventTracker` is functioning as intended. 
The `EventTracker._event_lock` is mocked in the unit test, which allows us to verify that its `__enter__` and `__exit__` methods are called, confirming that the lock is being used correctly.
This change only updates one unit test, and as such, has no noteworthy side effects.

Implement lock tests for EventTracker

---

README.md

README.md Updated typo fixes done.

---

samcli/lib/build/app_builder.py
samcli/lib/build/build_strategy.py
tests/unit/lib/build_module/test_app_builder.py
tests/unit/lib/build_module/test_build_strategy.py

After accelerate GA, we stopped gating the creating of a dependencies dir with a feature flag which means that now a dependencies dir is used for all builds where applicable. This means that the downstream lambda builders workflow performs an accelerate-specific workflow even when it shouldn't. 
Don't build with dependencies dir if cached is False.

fix: Don't use deps dir for non-cached builds

---

samcli/lib/telemetry/event.py
samcli/lib/telemetry/metric.py
tests/integration/telemetry/test_experimental_metric.py
tests/unit/lib/telemetry/test_event.py
tests/unit/lib/telemetry/test_metric.py

N/A
Previously, Event information could only be sent through Metric's `track_command` decorator. This change looks to decouple the functionality, allowing Events to be sent to the backend of Telemetry independently of the decorator.
With a new `send_events()` method, Events will be sent to the Telemetry backend whenever requested. This method is called in place of the existing format used in the `track_command` decorator. In addition, new functionality is given to the `track_event` method, and when there exceeds a certain number of tracked events, their information is sent automatically via Telemetry, and the existing Events are cleared from the list.
Now, `metricSpecificAttributes` for the `commandRun` metrics will no longer contain `events` as a field, as they will be sent under a …

Add send_events method to EventTracker

---

samcli/lib/telemetry/project_metadata.py
tests/unit/lib/telemetry/test_project_metadata.py

N/A
As discussed, the current SHA-1 hashing of project metadata info has proven not cryptographically secure enough, and thus should be upgraded to SHA-256.
Any and all prior uses of the `uuid.uuid5()` method, which uses SHA-1, have been replaced by `hashlib.sha256()` and its relevant encryption methods.
Rather than sending a string, the encryption methods will return bytes. This shouldn't have significant impact on existing structures and frameworks in the codebase.

Upgrade encryption algorithm from SHA-1 to SHA-256

---

samcli/commands/pipeline/bootstrap/cli.py
samcli/commands/pipeline/bootstrap/guided_context.py
samcli/commands/pipeline/bootstrap/oidc_config.py
samcli/commands/pipeline/bootstrap/pipeline_oidc_provider.py
samcli/commands/pipeline/init/interactive_init_flow.py
samcli/lib/cookiecutter/template.py
samcli/lib/pipeline/bootstrap/stage.py
tests/unit/commands/pipeline/bootstrap/test_cli.py
tests/unit/commands/pipeline/bootstrap/test_guided_context.py
tests/unit/commands/pipeline/bootstrap/test_oidc_config.py
tests/unit/commands/pipeline/init/test_initeractive_init_flow.py
tests/unit/lib/cookiecutter/test_template.py
tests/unit/lib/pipeline/bootstrap/test_environment.py

Supports Bitbucket OIDC during pipelines bootstrap
GitHub, GitLab, and Bitbucket all support OIDC but the assume role policy conditions they use differ for each of the providers. This change builds the correct policy for Bitbucket
Adding more click optoins/prompts so that the pipeline bootstrap command can build the correct values for the assume role policy

Support Bitbucket OIDC in pipeline bootstrap

---

samcli/lib/telemetry/event.py
tests/unit/lib/telemetry/test_event.py

N/A
The current `track_command` decorator tracks metrics after a command terminates, but the Events it collects must be tracked inline for the given command, and cannot currently tell us much about duration of execution. In addition, some commands like `sam sync` may run indefinitely, or for long enough periods of time that knowledge of their metrics won't be known until its execution is terminated.
A "long event" in this scenario defines a pair of two Events: one to track the start of a command, and one to track the end of it. Since `Event` objects are given timestamps upon creation, this can provide us with insights as to how long certain commands may take to run, or how long certain commands are run on average.
While this has no direct side effects, any future functions that implement …

Add long event tracker

---

samcli/commands/exceptions.py
samcli/lib/test_runner/invoke_testsuite.py
tests/unit/lib/test_runner/test_invoke_testsuite.py

Adds functionality to kick off a testsuite by running a Fargate task with a set of environment variables, using a [runTask](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html) query.
In order for customers to run their testsuites on Fargate, there needs to be functionality to make a runTask query to start a test-running task.
This change contains the code to make a test-running runTask query
N/A
The general image used in the Test Runner Task Definition is not yet public, so testing this is properly is not yet possible. Once remaining features are added, and the general image is public, thorough end to end testing can be done. Given that we are merging with a feature branch, I think waiting for further implementation and end to end tests is reasonable.
**PRs will …

FEAT: Test Runner - Kick Off Testsuite

---

samcli/lib/telemetry/event.py
tests/unit/lib/telemetry/test_event.py

N/A
Previously, when at capacity, Events would be sent inline. This could create slowdowns during execution if the Telemetry happens to be slow on a given day.
By sending these Events in a separate thread, we ensure that they are sent without disrupting the flow of execution of other commands and functions.
There are no notable side effects to this change, besides the use of an additional thread during execution.

Send events via thread when at capacity

---

samcli/commands/build/build_context.py
tests/unit/commands/buildcmd/test_build_context.py

Related to lambda builders change: https://github.com/aws/aws-lambda-builders/pull/375
Previously, both `Sourcemap: true` and `NODE_OPTIONS: --enable-source-maps` needed to be provided to enable source map usage. This is redundant since explicitly defining one would imply source map usage.
This change allows users to specify either `NODE_OPTIONS: --enable-source-maps` under environment variables or `Sourcemap: true` under esbuild build properties and have source maps enabled and added to their functions.
`NODE_OPTIONS` can be defined at either the Globals level or the Function level.
This change will modify the final template file in `sam build` by adding either `Sourcemap` or `NODE_OPTIONS` at the function level.
By submitting …

feat: Enable source maps if either Sourcemap: true or --enable-source-maps is provided

---

samcli/commands/build/build_context.py
samcli/lib/build/workflow_config.py
samcli/lib/build/workflows.py
samcli/lib/telemetry/event.py
tests/unit/lib/build_module/test_workflow_config.py
tests/unit/lib/telemetry/test_event.py

N/A
Events previously exist to capture the runtime of functions as they are built. However, up until now, we do not have a way to capture the information of workflow configs.
With a new `WorkflowUsed` Event, we will be able to capture and analyze data on which workflows customers are using most. This can reveal information such as the most common languages of workflows, most common dependency managers, and how many different workflow configs are used per build.
A new file, `workflows.py`, has been created to prevent a cyclic import, and allow for dynamic computing of Event values. Thus, for any new workflow to be added, it would need to be created there, and then be imported by `workflow_config.py`.
By submitting this pull request, …

Add workflow events

---

samcli/lib/telemetry/event.py

N/A
While reviewing my code, I noticed that the structure of the `send_events` method was poorly formatted for multi-threading, as the method holds the `event` lock for its entire duration, including when connecting to Telemetry to send the events. This can cause long waits, which we attempted to get rid of by sending events in a separate thread in the first place.
I rearranged the method, accessing the lock only for what is solely necessary. This means keeping the `telemetry.emit` method out of the lock, allowing it to properly execute in parallel if other Events are added to the tracker while sending.
This should cause notable increase in the speed of Events being tracked, especially on days that the Telemetry itself may be slower than usual.
**PRs will only be reviewed after checklist …

Fix send_events lock logic

---

samcli/lib/bootstrap/nested_stack/nested_stack_manager.py
tests/unit/lib/bootstrap/nested_stack/test_nested_stack_manager.py

N.A.
For ADL skipping copy when function has no dependencies, a layer root folder is needed to add layer readme
Calls the mkdir operation even if dependencies_dir is not a valid dir
Not known

fix: Create layer root folder before adding layer readme for ADL

---

samcli/commands/sync/command.py
samcli/lib/telemetry/event.py
tests/integration/telemetry/test_experimental_metric.py
tests/unit/lib/telemetry/test_event.py

N/A
There were a few things I wasn't happy with reflecting on some of my previous code, and they were too small to fit into PRs on their own. Thus, they've been delegated to *this* PR, which has many tiny adjustments and tweaks, outlined below in order of significance.
- `EventTracker.send_events` now executes on a thread! Previously, this logic was only implemented when the function was called at capacity. Now, it's the default!
- `EventTracker` now stores `session_id` locally. This fixes a bug I was only recently made aware of, where Events sent in a thread did not contain the session ID, thus preventing us from linking the data. With the new implementation, the session ID is appended to the Metric before it is sent out.
- The decorators on `sam sync` are rearranged (namely, …

Make minor tweaks before launch

---

samcli/cli/cli_config_file.py
tests/unit/cli/test_cli_config_file.py

Throw error and exit when --config-file does not exist
Fixes: https://github.com/aws/aws-sam-cli/issues/3899
Currently it throws an irrelevant error making it hard to debug.

Error out and exit when --config-file does not exist

---

samcli/cli/types.py
tests/unit/cli/test_types.py

With `multiple_values_per_key=True`:
`Key1=Value1 Key1=Value2` -> `{Key1: [Value1, Value2]}`
Without `multiple_values_per_key` specified (before this change):
`Key1=Value1 Key1=Value2` -> `{Key1: Value2}`
N/A
Currently, there is no way for a customer to specify "tag filters" consisting of keys with multiple values. This is useful for SAM CLI commands that make API calls such as [get-resources](https://docs.aws.amazon.com/cli/latest/reference/resourcegroupstaggingapi/get-resources.html#get-resources). If a customer would like to specify two resources with the same tag key but different values, this change makes that possible.
An optional flag is added to the `CfnTags` parameter class. If enabled, the resulting dictionary will map each key to a list of values instead of the latest entered …

Add option to CfnTag parameter to accept multiple values per key

---

tests/integration/testdata/buildcmd/Esbuild/Node/package.json
tests/integration/testdata/buildcmd/Esbuild/TypeScript/package.json
tests/integration/testdata/sync/code/before/esbuild_function/app.ts

To ensure integration tests keep working after switching over to using the production flag for esbuild npm install (https://github.com/aws/aws-lambda-builders/pull/379) we need to move the dependency to be a non-dev dependency for the binary to be found.

feat: Move esbuild binary to normal dependency

---

samcli/cli/types.py
samcli/commands/test_runner/init/cli.py
tests/unit/cli/test_types.py

N/A
The init command makes a [get-resources](https://docs.aws.amazon.com/cli/latest/reference/resourcegroupstaggingapi/get-resources.html) call with a tag filter, to get the ARNs of customer application resources with the specified tag.
It is possible that customers have resources tagged with the same key, but different values and would like to both to be discovered by the Test Runner (for IAM policy & Environment Variable generation).
Related: https://github.com/aws/aws-sam-cli/pull/4103
Makes use of the `multiple_values_per_key` option for the `CfnTags` type.
N/A

FEAT: Test Runner - Allow init --tags option to accept multiple values per key

---

samcli/commands/local/lib/local_lambda.py
tests/integration/local/invoke/test_integration_cli_images.py
tests/integration/local/invoke/test_integrations_cli.py
tests/integration/testdata/invoke/template.yml
tests/integration/testdata/invoke/template_image.yaml
tests/integration/testdata/invoke/vars.json
tests/unit/commands/local/lib/test_local_lambda.py

#1045 
Users cannot provide both global and function specific environment variables
in the env-vars json file for sam local.
This change allows users to use a mix of cloudformation and standard format for
environment variables
None found

feat: Allow mix of global and function specific env vars for sam local

---

samcli/lib/utils/tar.py
tests/unit/lib/utils/test_tar.py

N/A
In order to keep the code for generating tarballs in one place, we should support different creation modes, such as gzip compression.
Adds a `mode` option to the `create_tarball` function, with a default of `mode="w"`. This ensures any previous calls will function the same as before, but mode can be specified for alternative tarball creations.
None.

Add mode option to create_tarball, in order to support compression

---

samcli/commands/test_runner/init/cli.py
samcli/lib/test_runner/test_runner_template_generator.py
tests/unit/commands/test_runner/test_init_command.py
tests/unit/lib/test_runner/test_template_generator.py

N/A
This option improves UX by providing a shortcut to customers who are confident in the generated IAM permissions, and do not want to go through and "enable" them manually by un-commenting them.
A TODO: Having readily available public documentation describing which resources will have which IAM actions generated for them. This is vital knowledge for the customer to be aware of which actions they are granting by enabling `--allow-iam`.
Includes code to generate IAM actions that are not commented out in the Test Runner CloudFormation Template if the `--allow-iam` flag is present for the `init` command.
None …

FEAT: Test Runner - Add --allow-iam option to init command

---

samcli/hook_packages/terraform/hooks/prepare.py
tests/unit/hook_packages/terraform/test_prepare_hook.py

make sure that the output directory, and project root paths passed to the terraform prepare hook are absolute paths. Calculate the absolute paths if are not absolute.

feat: make sure that the output directory, and project root directory paths are absolute paths

---

samcli/commands/test_runner/run/cli.py
samcli/lib/test_runner/fargate_testsuite_runner.py
tests/unit/commands/test_runner/test_run_command.py
tests/unit/lib/test_runner/test_fargate_testsuite_runner.py

N/A
If tests fail, the command should return a non-zero exit code so that the customer can implement logic around test success or failure. Especially useful for automated workflows, CI/CD.
Additionally, test output can be coloured red in the event of failure :)
The `sam test-runner run` command will exit with the same code as the test run container.
None

FEAT: Test Runner - Command Exit Code Based On Test Results

---

samcli/commands/test_runner/init/cli.py
samcli/commands/test_runner/run/cli.py
samcli/lib/test_runner/fargate_testsuite_runner.py
tests/unit/lib/test_runner/test_fargate_testsuite_runner.py

Help message rewords, option renames, removed colours except for tables and test failures.
Also fixed typo in `test_no_fail_on_no_update`, where the error message was in the stack name instead of the message.
N/A
Improved customer UX
Changed help message wording and options to be more intuitive, reduced use of colour for more consistent experience.
None

UX Polishes

---

samcli/hook_packages/terraform/hooks/prepare.py
tests/unit/hook_packages/terraform/test_prepare_hook.py

Use the sam metadata resource_name property to retrieve the CFN resource to be enriched. We first try to use this value as the resource only postfix address, so we should concatenate it to the module address to get the full address. If we could not find a resource that match the previous address, so may be the resource name value is a full address, so we will try to use it without any concatenation. Finally if we did not find any resources, we will raise an error.

feat: get the cfn resource that match the sam metadata resource name property

---

.gitignore
samcli/cli/cli_config_file.py
tests/integration/package/test_package_command_image.py
tests/unit/cli/test_cli_config_file.py

* PR https://github.com/aws/aws-sam-cli/pull/4044 has caused a
regression.
* https://github.com/aws/aws-sam-cli/pull/4044 
* Re allow usage of relative paths for `--config-file`
* Only check for the path being a file after resolving it to be absolute.
* N/A

fix: allow relative paths for `--config-file`

---

tests/integration/buildcmd/build_integ_base.py
tests/integration/buildcmd/test_build_cmd.py
tests/integration/testdata/buildcmd/esbuild_templates/template_with_metadata_global_node_options.yaml
tests/integration/testdata/buildcmd/esbuild_templates/template_with_metadata_node_options.yaml

esbuild integration tests started failing after releasing the newest lambda builders which changes some of the default values. The tests were then unable to substitute the default parameters leading them to fail.
Parameters the templates used instead of the individual properties.

fix: Fix esbuild Properties Integration Tests

---

samcli/hook_packages/terraform/hooks/prepare.py
tests/unit/hook_packages/terraform/test_prepare_hook.py

SAM Metadata will contain specific properties for the lambda function source code or docker context. The value of this property can be either string, array, or encoded JSON object. Prepare hook will  try to decode the value of this property, and then check the output type. Based on each type, the hook will try to get the required path, and do some validations if metadata property is not as expected.
In case if this property value is an array, the hook will use only the first item as the required path, as SAM CLI currently only supports functions that refer to the source code directory, and does not support referring to an array of files.
in case if this property value is an encoded JSON object, the hook will use another property value to get the required path from this object.
The hook …

feat: extract the lambda function source code or docker context paths

---

samcli/lib/build/bundler.py
tests/integration/sync/test_sync_adl.py
tests/unit/lib/build_module/test_bundler.py

This change fixes URIs being resolved in the esbuild check, causing some URIs being resolved incorrectly
Adds `use_raw_codeuri=True` to parameters.

fix: Fixed URI path being resolved incorrectly and remove experimental call

---

samcli/hook_packages/terraform/hooks/prepare.py
tests/unit/hook_packages/terraform/test_prepare_hook.py

After the prepare hook finds the SAM Metadata and links it to a specific Lambda resource, we need to create a makefile with a target/recipe for each lambda resource to be built. 
Defines a stubbed function, and calls it after finding the sam metadata resources. 

feat: create stub function for generating custom makefile

---

installer/pyinstaller/hook-samcli.py
samcli/hook_packages/terraform/copy_terraform_built_artifacts.py
tests/integration/scripts/test_copy_terraform_built_artifacts.py

The current logic would make it so that if the terraform project root arg was not provided, extracted relative paths would be made relative to the current working directory (wherever the script was executed, so from the prepare hook's dir). 
Also, since hook packages should be independent/isolated, I moved the script into the terraform hook package. 
**NOTE:** not sure, however, where to move the integration test
The arg was made required.

fix: make terraform project root arg required, and move script into the terraform hook package dir

---

samcli/commands/build/command.py
tests/integration/buildcmd/build_integ_base.py
tests/integration/buildcmd/test_build_cmd.py
tests/testing_utils.py
tests/unit/commands/buildcmd/test_command.py

There is no sam build logic for terraform applications yet. This PR only ensures that we check to see if beta features are enabled when executing a command with build command with `--hook-package-id`
N/A
Only allow for `sam build` to continue if a hook package id is specified if executed within a beta context.

fix: check for `hook-package-id` only being allowed if a beta feature on `sam build`

---

samcli/lib/samlib/wrapper.py
samcli/runtime_config.json
tests/integration/buildcmd/test_build_cmd.py
tests/integration/deploy/test_deploy_command.py
tests/integration/testdata/buildcmd/language-extensions.yaml
tests/unit/lib/samlib/test_wrapper.py

#4172
SAM-CLI shouldn't error out when validating certain intrinsic properties if `Transform: AWS::LanguageExtensions` is in the template.
Temporarily patch the validation function to bypass certain validations.

fix: Patch sam-cli to support language extensions

---

samcli/local/apigw/local_apigw_service.py
tests/integration/local/start_api/test_start_api.py

#3515 
Customers are facing issues on postman due to HTTP/1.0 responses from sam local start-api.
New change allows the sam local start-api to respond using upgraded version HTTP/1.1
None found

feat: Enable sam local start-api to respond with HTTP/1.1 version

---

samcli/commands/local/cli_common/invoke_context.py
tests/unit/commands/local/cli_common/test_invoke_context.py

#2837
This changes fixes `--docker-volume-basedir` not being used to resolve a relative code URI in the template file. Previously, the code URI was automatically resolved to an absolute path, causing checks later on to ignore the directory passed by `--docker-volume-basedir` since the code URI had already been resolved.
If the command flag is passed, the invoke context will set `use_raw_codeuri=True` to the function providers, making sure that the code URI stays relative until the end.

fix: Fix `--docker-volume-basedir` being ignored for sam local

---

samcli/cli/command.py
tests/integration/root/root_integ_base.py
tests/integration/root/test_root_command.py
tests/unit/cli/test_command.py

- Only import cli commands for specific invocations of non-root
commands, eg: `sam build` not for `sam`
Speed up help for aws sam cli.
The `--help` page which is the first command that arguably a user would load for their first experience with aws sam cli. This command should be blazingly fast.
Only import modules if the child commands such as `sam build --help` etc are loaded, otherwise load a generic command with a name and a short help. 
N/A, This will probably break a bunch of tests that I will need to fix.

fix: speed up help by 2x on `sam` binary

---

samcli/cli/context.py
samcli/cli/main.py
samcli/commands/init/command.py
samcli/commands/init/init_flow_helpers.py
samcli/commands/init/interactive_init_flow.py
samcli/lib/build/deprecated_runtimes.py
tests/unit/cli/test_context.py
tests/unit/cli/test_main.py
tests/unit/lib/telemetry/test_metric.py

- This is faster than the earlier commit of https://github.com/aws/aws-sam-cli/pull/4205
- One more 2.6x improvement going to 144ms from 377ms for `sam --help` text, total improvement of 5.26x from last release.
- sam init help text 1.76x faster.
* slowness of the CLI
* better UX
* move expensive imports to be inside code blocks
* N/A

perf: push `--help` text to 150ms, 2.6x improvement - supercharge the cli.

---

samcli/hook_packages/terraform/hooks/prepare.py
tests/unit/hook_packages/terraform/test_prepare_hook.py

Verifies that python is installed and returns the name of the python command, to use for running python scripts.

feat: Implement _get_python_command_name

---

samcli/local/docker/container.py
tests/unit/local/docker/test_container.py

https://github.com/aws/aws-sam-cli/issues/4222
With v4.12.0 version of docker desktop on Windows, getting output streams of the container started to raise exception once the container is done with its work.
With this change, we are wrapping `_write_container_output` function to catch any unexpected errors from docker API so that these errors won't fail execution.
N/A

fix: wrap _write_container_output with try/except to gracefully handle any unexpected errors from docker api

---

samcli/commands/_utils/custom_options/hook_package_id_option.py
samcli/hook_packages/terraform/hooks/prepare.py
tests/integration/testdata/invoke/terraform/simple_application_no_building_logic/lambda/lambda2/main.tf
tests/integration/testdata/invoke/terraform/simple_application_no_building_logic/lambda/main.tf
tests/integration/testdata/invoke/terraform/simple_application_no_building_logic/main.tf
tests/integration/testdata/invoke/terraform/simple_application_no_building_logic/src/test.py
tests/unit/commands/_utils/custom_options/test_hook_package_id_option.py
tests/unit/hook_packages/terraform/test_prepare_hook.py

Generate the Makefile rule for building resources based on the SAM Metadata Terraform resource. 
The updated integration test example generates a Makefile that looks like this:
```
build-AwsLambdaFunctionS3Lambda54E19A65:
terraform apply -target null_resource.sam_metadata_aws_lambda_function_s3_lambda -auto-approve
terraform show -json | python3 .aws-sam-iacs/iacs_metadata/copy_terraform_built_artifacts.py --expression "|values|root_module|resources|[?address=="null_resource.sam_metadata_aws_lambda_function_s3_lambda"]|values|triggers|built_output_path" --directory "$(ARTIFACTS_DIR)" --terraform-project-root "/Users/mladan/ws/aws-sam-cli/tests/integration/testdata/invoke/terraform/simple_application_no_building_logic"
build-AwsLambdaLayerVersionLambdaLayer556B22D0:
terraform apply -target …
```

feat: Generate Makefile Rule

---

samcli/hook_packages/terraform/copy_terraform_built_artifacts.py
samcli/hook_packages/terraform/hooks/prepare/hook.py
tests/integration/scripts/test_copy_terraform_built_artifacts.py
tests/integration/scripts/testdata/build-output-path-dir.json
tests/integration/scripts/testdata/build-output-path-zip.json
tests/unit/hook_packages/terraform/hooks/prepare/test_hook.py

Remove the `terraform-project-root` parameter from the copy terraform built artifacts script, as it is not required. If the built artifact path is a relative path, it will be relative to the current project root directory, which is the copied project to the scratch directory, which is the MakeFile working directory. 

fix: remove the terraform project root parameter from built artifacts copy script.

---

samcli/hook_packages/terraform/hooks/prepare/hook.py

N/A
Path of `copy_terraform_built_artifact.py` needs to be adjusted after splitting `prepare.py` into multiple files.
The error message for handling `OSError` is not accurate for what the real error is.
- Update path variable
- Update error message when re-raising `PrepareHookException`

Fix copy script loc

---

samcli/hook_packages/terraform/hooks/prepare/exceptions.py
samcli/hook_packages/terraform/hooks/prepare/resource_linking.py
tests/unit/hook_packages/terraform/hooks/prepare/test_resource_linking.py

Iterate over a module's variables and resolve them to either their final constant value or a reference that we don't yet fully resolve (e.g. locals).
Adds recursive function for module variable resolution.

feat: Resolve Module Variables

---

samcli/hook_packages/terraform/hooks/prepare/resource_linking.py
tests/unit/hook_packages/terraform/hooks/prepare/test_resource_linking.py

Adding a function to resolve a terraform resource attribute value. 

feat: Add resource attribute resolving

---

appveyor-ubuntu.yml
appveyor-windows.yml

Separating build, deploy, package and sync integration tests into their own groups to speed up canary tests.
Testing here;
[Linux Run](https://ci.appveyor.com/project/AWSSAMCLI/aws-sam-cli-canary-linux-dev/builds/44954928)
[Windows Run](https://ci.appveyor.com/project/AWSSAMCLI/aws-sam-cli-canary-windows-dev/builds/44954934)

chore: separate CI jobs for deploy, package, delete and sync

---

samcli/hook_packages/terraform/hooks/prepare/resource_linking.py
tests/unit/hook_packages/terraform/hooks/prepare/test_resource_linking.py

Constructs a terraform module representation out of the terraform configuration.

feat: implement function to construct Modules out of the terraform configuration

---

samcli/cli/global_config.py
samcli/commands/sync/command.py
tests/unit/cli/test_global_config.py

N/A
As per user feedback, accepting the warning message at the beginning of `sam sync` starts to feel redundant
After user accepts the warning message, this change will be storing information of the current folder and stack and subsequent runs won't be asking this question to run `sam sync`.
N/A

feat: skip sync confirmation for subsequent runs

---

samcli/commands/sync/command.py
samcli/lib/sync/sync_flow_factory.py
samcli/lib/sync/watch_manager.py
tests/integration/sync/test_sync_watch.py
tests/integration/testdata/sync/code/before/template-python-code-only.yaml
tests/unit/commands/sync/test_command.py
tests/unit/lib/sync/test_watch_manager.py

This change was requested to speed up development pace when using `sam sync`. Users want to skip any Infra Sync (CFN deployment) when they know there are no template changes or they don't want to sync their template changes yet and want to do a quick code sync.
With this change, users now allowed to combine `--watch` flag and `--code` in `sam sync` command. When they are used in combination, `sam sync` will skip all Infra Sync (CFN deployment) actions to speed up development. Users have to run `sam sync` without `--code` flag to sync their template changes with their deployed stack.
With this new combination, template changes won't be synced with deployed stack. Users will be warned with a message to run the `sam sync` command without `--code` flag.
**PRs will only be reviewed after …

feat: use watch and code flags at the same time

---

tests/integration/sync/test_sync_watch.py

With latest changes, `sam sync` now skips confirmation message for subsequent runs of the same project. This addresses that change in our integration tests.

chore: fix sam sync integ tests after latest changes

---

samcli/hook_packages/terraform/hooks/prepare/hook.py
tests/unit/hook_packages/terraform/hooks/prepare/test_hook.py

We need the TF prepare hook to call our layer linking logic.
Add the connection logic from the hook to iterate through the resources in the TF modules and call the layer linking logic for each resource.

feat: Add logic for linking functions to layers

---

tests/integration/pipeline/test_bootstrap_command.py

Canary integration tests failed.
Two integration tests shares the same OIDC identity provider however only the first test to run will create it. But we don't have control which one will run first. And the other test with create image has been tested in other test cases. Hence remove it.

Remove conflict test case

---

tests/integration/pipeline/test_bootstrap_command.py

Fix the failed nightly canary. The test works fine on my account because the OIDC identity provider already exists hence no OIDC identity provider will be created. However, for the test account, it will create an OIDC identity provider.

Fix integration test

---

samcli/commands/delete/exceptions.py
samcli/lib/delete/cfn_utils.py
tests/unit/lib/delete/test_cfn_utils.py

* Add better error messaging when a stack fails to delete.
https://github.com/aws/aws-sam-cli/issues/3754
* Try a finite number of times and exit if unsuccessful.
* The waiter config now has a finite number of attempts baked in and when it fails it showcases the last stack status.
* N/A

fix: add `MaxAttempts` to `sam delete`

---

samcli/hook_packages/terraform/copy_terraform_built_artifacts.py

remove the dependency on six module, as it is not in the python core modules

fix: remove the dependency on six module

---

installer/assets/THIRD-PARTY-LICENSES
requirements/base.txt
requirements/reproducible-linux.txt
samcli/local/services/base_local_service.py
tests/iac_integration/cdk/test_sam_cdk_integration.py
tests/integration/local/common_utils.py
tests/integration/sync/test_sync_code.py

Related: https://github.com/aws/aws-sam-cli/pull/4326
With the latest version of flask and click libraries, some of the output of them has changed, which is affecting our integration tests. This PR is addressing them by correcting expected output from CLI.
This also downgrades Flask (and werkzeug) version lower than 2.1 since versions from 2.1 and later is creating issues when defining `<path:*>` endpoints.

fix: pin flask version, suppress flask output, fix integration tests

---

pytest.ini
tests/unit/lib/samlib/test_resource_metadata_normalizer.py
tests/unit/local/apigw/test_local_apigw_service.py
tests/unit/local/lambda_service/test_local_lambda_invoke_service.py

N/A
We should not be ignoring warnings that are outputted. Looking at the history, it seems like we turned off enforcing warnings in our Py2 removal (don't remember why). This PR re-enables pytest to fail if warnings are outputted and fixes the current failures.
Enabled warnings to fail the pytest build and fixes the current failures.
None, they are all for test.

chore: Enforce Pytest Warnings

---

appveyor-iac-integration-ubuntu.yml
appveyor-ubuntu.yml
appveyor.yml

[golang 1.15 is the oldest version that is supported in Appveyor images](https://www.appveyor.com/docs/linux-images-software/), which will probably be dropped in the near future. This PR is addressing that concern by upgrading its version to latest one (1.19).

chore: bump golang version in CI jobs

---

samcli/commands/build/build_context.py
samcli/commands/build/command.py
tests/unit/commands/buildcmd/test_build_context.py
tests/unit/commands/buildcmd/test_command.py

Changes the build success messages to not mention commands that won't work with current hook packages.
Checks for the hook package and changes which commands are mentioned in the message.
eg when using a hook package:
```
Build Succeeded
Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml
Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Start a local API: sam local start-api --hook-package-id terraform
[*] Emulate local Lambda functions: sam local start-lambda --hook-package-id terraform
```

fix: Updated build success message for hook packages

---

samcli/hook_packages/terraform/copy_terraform_built_artifacts.py
samcli/lib/hook/hook_wrapper.py

Help message looks like this:
```
--hook-package-id TEXT          The id of the hook package to be used to
extend the SAM CLI commands functionality.
As an example, you can use `terraform` to
extend SAM CLI commands functionality to
support terraform applications. Available
Hook Packages Ids ['terraform',
'__pycache__']
```
At the end you can see pycache listed as one of the available hook package ids. We should ensure it doesn't appear there.
Ignores `pycache`.

docs: ignore pycache when listing available hook package ids in help text

---

samcli/lib/delete/cfn_utils.py
tests/unit/lib/delete/test_cfn_utils.py

- Remove `MaxAttempts` and let it be set to default of 120 per https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudformation.html#waiters
https://github.com/aws/aws-sam-cli/issues/4361
- Removes the total number of attempts before change of state to be the default. This stems from a wrong understanding of what `MaxAttempts` meant during the previous implementation of the fix.
- Unsets `MaxAttempts` and restores default behavior.
- Fixes regression https://github.com/aws/aws-sam-cli/issues/4361 and should not have any other side effects.

fix: regresssion on `sam delete`

---

samcli/lib/samlib/resource_metadata_normalizer.py
tests/integration/buildcmd/test_build_cmd.py
tests/integration/testdata/buildcmd/PythonImage/Dockerfile.production
tests/unit/lib/samlib/test_resource_metadata_normalizer.py

Fixes #4355. Use `Path`/`PurePath`'s `name` property to extract a full Dockerfile file name. The current implementation uses `.stem` which omits the final suffix, is present.
Fixes #4355.
The `sam build` command does not properly locate Dockerfiles with extension(s) in their file names without this change.
By using the `.name` property on `Path`/`PurePath` as opposed to `.stem`, the entire file name is guaranteed to be included.
See https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.name and https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.stem.
None. File names with no extension (e.g., `Dockerfile`) will be parsed in the same way after this change.  …

Extract full file name from Dockerfile path

---

samcli/hook_packages/terraform/hooks/prepare/hook.py
tests/integration/buildcmd/test_build_terraform_applications.py
tests/unit/hook_packages/terraform/hooks/prepare/test_hook.py

Preparing a terraform project used to get stuck on the initializing part because it would wait for input (although this interactive part is not printed out on the cli).
This is what you would see if you ran `terraform init`:
The prepare step now errors out if input is required (and wasn't provided in the config). 

feat: error out if input is required on terraform init

---

samcli/commands/build/build_context.py
tests/unit/commands/buildcmd/test_build_context.py

Fixes one of the suggested commands to not include `-t/--template` when using `--hook-package-id`.
Adds another check for hook package ID.

fix: Ignore template option when using hook package

---

.github/workflows/pr-labeler.yml

Currently PR created by "aws-sam-cli-bot" are labelled as external pr, which is not accurate.
Add "aws-sam-cli-bot" as a maintainer in the PR label GH Action

Update aws-sam-cli-bot as user for internal pr labels

---

requirements/base.txt
requirements/reproducible-linux.txt

- run integ tests on this branch once brought in.
N/A
To bring in the streaming makefile builder changes and ensure integration tests continue to work as normal.
N/A
N/A

version: bring in latest lambda builders version

---

samcli/hook_packages/terraform/hooks/prepare/resource_linking.py
tests/unit/hook_packages/terraform/hooks/prepare/test_resource_linking.py

This change will let SAM CLI raise error for the following Terraform expressions:
```
layers = var.stage == "gamma" ? [aws_lambda_layer_version.layer1[0].arn] : "layer.arn"
```
```
layers = var.stage == "gamma" ? [aws_lambda_layer_version.layer1[0].arn] : "arn:aws:lambda:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:layer:${var.layer_name}:1"
```

feat: raise error for terraform expression that mix between constant values and references 

---

MANIFEST.in
setup.py

#4375 
SAM CLI installation copies the unnecessary "installer" directory, which might conflict with the Python "installer" library
Exclude "installer"

exclude installer dir in build

---

pytest.ini

To not raise `ResourceWarning` in pytest as errors, but still print them.
We should look into closing the resources properly. But we just don't raise it as error for now: 
```
ResourceWarning: unclosed <ssl.SSLSocket fd=1568, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.0.0.50', 50416), raddr=('54.239.29.24', 443)>
Exception ignored in: <ssl.SSLSocket fd=1668, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.0.0.50', 51558), raddr=('54.239.28.247', 443)>
ResourceWarning: unclosed <ssl.SSLSocket fd=1668, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.0.0.50', 51558), raddr=('54.239.28.247', 443)>
Exception ignored in: <ssl.SSLSocket fd=1408, family=AddressFamily.AF_INET, …
```

Ignore ResourceWarning in pytest

---

samcli/commands/_utils/options.py

Updates the help comment for `--skip-prepare-infra` to be more clear/read easier.

feat: Update skip prepare infra message

---

samcli/commands/local/lib/local_api_service.py

Hi team,
Running code locally with `sam local start-api` and see this message 
> You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
I assumed (similar to what was described here https://github.com/aws/aws-sam-cli/issues/901 and https://github.com/aws/aws-sam-cli/issues/1921) that my typescript code will be built as well but it is not the case.
Thought of clarifying this in the text of that note.
Please let me know if this makes sense.
Thank you
> By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 …

chore: Clarify note about code building on `sam local start-api`

---

samcli/__init__.py

Reverting back to version 1.65.0, as the 1.65.1 release got canceled

chore: revert version to 1.65.0

---

tests/integration/publish/test_command_integ.py

* flaky canary runs
* higher availability for nightly canary runs.
* re-run the test 3 times.
* potentially longer failure times.

fix: set `flaky` marker on sam publish tests

---

installer/pyinstaller/build-linux.sh

N/A
Pyinstaller version was bumped from 4.2 to 5.3 and build-linux.sh failed as the 
--onedir/--onefile options not allowed when spec file is provided.
Removing -D flags builds the pyinstaller executable with the provided spec file

fix: updated linux pyinstaller script

---

tests/integration/init/schemas/test_init_with_schemas_command.py

With new application templates added (go provided.al2), schema tests have been failing since the order of the expected runtimes have changes. This PR addresses that issue by updating the input for the tests.

fix: fix sam init schema tests

---

samcli/lib/providers/provider.py
samcli/lib/providers/sam_api_provider.py
tests/unit/commands/local/lib/test_api_provider.py

#4290 
When running `sam build`, SAM CLI provides a warning message about using `ServerlessRestApi` and/or `ServerlessHttpApi` as a resource in the template. But that logic first transforms the template and then run the validation, which prints the warning message even customers don't define these resources in their template.
Instead of looping through `Resources` from transformed template, we now loop through the resources without running SAM transform.
None

fix: implicit api warnings

---

samcli/commands/_utils/options.py
samcli/commands/init/interactive_init_flow.py
samcli/commands/local/start_api/cli.py
samcli/commands/local/start_lambda/cli.py
samcli/commands/logs/command.py
tests/unit/commands/_utils/test_options.py

we are targeting to add a section for sam local start-lambda and sam local start-api commands. When users run these commands, a message will be printed as shown below to suggest a few commands that they can use next.
```
Commands you can use next
=========================
[*] Validate SAM template: sam validate
[*] Test Function in the Cloud: sam sync --stack-name {{stack-name}} --watch
[*] Deploy: sam deploy --guided
=========================
```
Informative messages suggesting users some commands that can be used next improves user experience.
Added 

Added Next Command Suggestions

---

.github/workflows/close-stale-issues.yml

None
To reduce the load on maintainers, we will close stale issues. This keeps lingering issues to a minimum and gives maintainers better view of the repo state.
GHA will run daily, and look for stale issues. If a stale issue is found and does not have an exempt label, it will be marked "stale". Once the issue is in a stale state, it will be closed after a determined about of time (see config).
This will not closed except labels, issues with 1 or more reactions, and issues that have been recently commented on. 
This will close issues and mark them stale but should be done only after a maintainer responses first (and removes one of the exempt labels set by default). If there are issues, the issues can always be reopen, making this not something we are locked into and can get around.
**PRs …

chore: Update Closed Stale Issues Github Action

---

.github/workflows/close-stale-issues.yml

None
I want to test the workflow by manually invoking to ensure things are working as expected.
Moves the "close stale issues" Github Action to a `workflow_dispatch` which allows manually invoking. I will move this back to a schedule one I am happy with the results. 
None

chore: Move Close Stale issues to manual workflow for testing

---

installer/assets/THIRD-PARTY-LICENSES

We previously auto-updated certifi version, but the third party license file still needs an update.
So that the third party license that we distribute with the installation package is update to date
Updated the third party license file with the newest certifi version
N.A.

chore: Update third party license information on certifi version update

---

requirements/base.txt
tests/integration/validate/test_validate_command.py

- The validate integration tests are failing due to the expected non-lint output pattern not matching with what `sam validate` without `--lint` option will log to stdout
- Validate command will fail for using the --lint option if the pyyaml version is not >=5.4.1
- To fix the failing integration tests and resolve the console output mismatch
- To update pyyaml version in base.txt for compatible version requirement since to use --lint option, pyyaml > 5.4 is needed
- Note: since reproducible linux already has pyyaml as 5.4.1, no changes are introduced onto reproducible-linux.txt and THIRD-PARTY-LICENSES
- Updated the related integration test and verified the tests are passing locally
- Updated base.txt under requirements folder
N.A. …

fix:  Fix validate command integration tests console output missmatch and update pyyaml version requirement

---

samcli/lib/package/packageable_resources.py
samcli/lib/package/utils.py
tests/integration/sync/test_sync_adl.py
tests/integration/sync/test_sync_watch.py
tests/testing_utils.py
tests/unit/lib/package/test_artifact_exporter.py

N/A
With this PR https://github.com/aws/aws-sam-cli/pull/4462, we've changed some permissions of the files in ZIP package if the file is used for serverless function resources. But that is checking if logical id of the resource is type.
With this change, we are checking the resource type instead of resource logical id.
N/A

fix: use resource type instead of resource id for deciding zip method

---

installer/pyinstaller/hidden_imports.py
installer/pyinstaller/hook-samcli.py

- With the inclusion of `cfn-lint` as a dependency. There are data files, python files that need to be included for `cfn-lint`.
- One of the dependencies brought in by `cfn-lint` is `pbr`, this in turn has a dependency on `jschema-to-python`. The way around it is to explictly set `PBR_VERSION` as per https://docs.openstack.org/pbr/latest/user/packagers.html. However this solution is brittle and will leak dependency code into AWS SAM CLI codebase, the cleaner solution is to package `jschema-to-python` metadata only for pyinstaller instead.
N/A
* To get a working pyinstaller binary.
* Built and checked a working installer binary at: https://github.com/sriram-mv/aws-sam-cli/actions/runs/3706626011
* None
By submitting this pull …

fix: `pyinstaller` binaries

---

tests/integration/sync/test_sync_adl.py
tests/integration/validate/test_validate_command.py

Integration test failure on test_sync_adl.TestSyncAdlWithWatchStartWithNoDependencies testMethod=test_sync_watch_code
This is a follow up to https://github.com/aws/aws-sam-cli/pull/4485
Since after we change the hash comparison to use the correct permissions, such code syncs should not deploy the ADLs again thus shouldn't trigger Function Layer Reference sync anymore. We need to update the expected output from sync watch.
Updated the expected string
N.A.

fix: Update expected message read for ADL sync code watch integration test

---

installer/pyinstaller/hook-samcli.py

- import `cfnlint` with data files, python files and package metadata directories.
* Nightly builds for pyinstaller
* Previous change did not include the hidden imports
* validate with `--lint` now works with the appropriate imports.
* N/A

fix: `hooks` data imports for pyinstaller

---

tests/integration/sync/test_sync_watch.py

chore: remove redundant debug parameter for sync integration tests

---

installer/pyinstaller/hook-samcli.py
samcli/cli/hidden_imports.py
samcli/cli/import_module_proxy.py
samcli/cli/main.py
tests/integration/init/test_init_command.py
tests/unit/cli/test_import_module_proxy.py
tests/unit/cli/test_pyinstaller_imports.py
tests/unit/lib/observability/xray_traces/test_xray_service_graph_event_puller.py

Original PR and discussions: https://github.com/aws/aws-sam-cli/pull/4470
N/A
If dynamic imports are used but missed in pyinstaller hidden imports configuration, it will create issues with installers that is created with pyinstaller.
If `sam` is executed in development mode (`samdev`) it replaces `import_module` with a proxy method which will analyze every dynamic import and make sure that it is defined in hidden imports.
It shouldn't make any change for `sam` and `sam-nightly` executables since proxy method is only attached if it is running as `samdev` (development mode).  …

ci: validate hidden imports during unit & integration tests

---

appveyor-ubuntu.yml
appveyor-windows.yml
samcli/cli/hidden_imports.py
samcli/lib/build/app_builder.py
tests/integration/buildcmd/test_build_terraform_applications.py
tests/integration/local/start_lambda/test_start_lambda_terraform_applications.py

- Change terraform tests to `assertIn` certain text is printed.
- Run `package` tests in parallel (which speeds up 10mins per package test group [~40mins in total])
- Run `delete` tests in parallel (which speeds up 8mins per delete test group [~32mins in total])
- Add `dateparser` to hidden imports which was caught by newly added pyinstaller checks (I am in between whether we should add this as exclusion to the dynamic import validation that we added)

ci: fix canary failures

---

README.md

chore: change license badge in readme to display GH license

---

Makefile

N/A
Since we introduced `ruamel` as a dependency, running `make pr` fails every other time because of an issue in `mypy`
E.g.:
```
tests/unit/lib/sync/flows/test_rest_api_sync_flow.py:1: error: Skipping analyzing 'ruamel': found module but no type hints or library stubs
tests/unit/lib/sync/flows/test_http_api_sync_flow.py:1: error: Skipping analyzing 'ruamel': found module but no type hints or library stubs
tests/unit/lib/sync/flows/test_function_sync_flow.py:1: error: Skipping analyzing 'ruamel': found module but no type hints or library stubs
samcli/lib/sync/flows/zip_function_sync_flow.py:1: error: Skipping analyzing 'ruamel': found module but no type hints or library stubs
```
Issue in `mypy`:
- https://github.com/python/mypy/issues/12664
Apply `--no-incredental` as a workaround to …

Update make lint

---

requirements/base.txt
requirements/reproducible-linux.txt
samcli/cli/hidden_imports.py

Bumping the SamTranslator version alone will cause pip resolution conflict (see error below). We need to bump typing_extensions to 4.4.0 at the same time as the jsonschema requires that.
I examined the typing_extensions' [changelog](https://github.com/python/typing_extensions/blob/main/CHANGELOG.md). Nothing breaking except "Dropped support for Python versions 3.5 and older". 
```
ERROR: Cannot install -r requirements/base.txt (line 12) and typing_extensions==3.10.0.0 because these package versions have conflicting dependencies.
The conflict is caused by:
The user requested typing_extensions==3.10.0.0
aws-sam-translator 1.56.0 depends on typing-extensions~=4.4.0
```
By submitting this pull request, I confirm that my contribution is …

chore: Bump SamTranslator version to 1.56.0 and typing_extensions to 4.4.0

---

.github/workflows/update_app_templates_hash.yml

N/A
PR checks take around 1.25hr to finish. If the app template update job keeps running every hour, last jobs will never complete while new push will kick off new jobs.
Run it left often. Update to run every 4 hours
No

Update App Template Commit Hash Update job schedule to every 4 hour

---

samcli/commands/init/init_templates.py

This is one of the changes being made to help reduce the overall length of cloned app templates to avoid reaching the maximum path length in Windows.
Changes the folder name from `aws-sam-cli-app-templates` to `tmpl` for Windows machines.
Existing Windows installations with an `aws-sam-cli-app-templates` folder in their `%appdata%/AWS SAM` directory will have that folder remain there until it is manually deleted.

Reduced the length of the cloned app template folder name

---

tests/integration/buildcmd/build_integ_base.py
tests/integration/delete/delete_integ_base.py
tests/integration/local/generate_event/test_cli_integ.py
tests/integration/local/invoke/invoke_integ_base.py
tests/integration/local/start_api/start_api_integ_base.py
tests/integration/local/start_lambda/start_lambda_api_integ_base.py
tests/integration/package/package_integ_base.py
tests/integration/pipeline/base.py
tests/integration/pipeline/test_init_command.py
tests/integration/publish/publish_app_integ_base.py
tests/integration/root/root_integ_base.py
tests/integration/telemetry/integ_base.py
tests/integration/validate/test_validate_command.py

Remove duplicated `sam` vs `samdev` assignment in the testing code.

chore: remove duplicated samdev base_command methods in tests

---

requirements/reproducible-linux.txt

Bump wheels setuptools

---

tests/integration/validate/test_validate_command.py

* strings are immutable, assign the changes back once the windows line endings are stripped out.

tests: actually fix the integration tests for validate

---

.github/ISSUE_TEMPLATE/Bug_report.md

N/A
Main reason is for how we track bugs. We first want to validate the bug before adding the label. 
Removes the `type/bug` label that is automatically applied.
None

chore: Remove type/bug label for Bug Issue Template

---

tests/integration/testdata/buildcmd/terraform/image_based_lambda_functions_local_backend/main.tf
tests/integration/testdata/buildcmd/terraform/image_based_lambda_functions_s3_backend/main.tf

Unlocks the integration tests temporarily until https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/398 is resolved. After, this change should be reverted.

fix: Pin docker provider version to 2.x

---

appveyor-ubuntu.yml
appveyor-windows.yml
pytest.ini

N/A
To fix the issue that canary test reports are only uploaded on job succeed
Switch to use `on_finish` to upload test reports regardless job succeeds or fails
No

Fix appveyor canary job uploading test reports

---

samcli/commands/exceptions.py
tests/unit/commands/test_exceptions.py

N/A
To provide more complete info around the unhandled exception
Print all the error name and exception. Example:
```
Error: UnsupportedBuilderException("'esbuild1' does not have a supported builder")
Traceback:
File "/Volumes/workplace/gh/aws-sam-cli/.venv39/lib/python3.9/site-packages/click/core.py", line 1055, in main
.
.
.
raise UnsupportedBuilderException("'{}' does not have a supported builder".format(specified_workflow))
An unexpected error was encountered while executing "samdev build".
Search for an existing issue:
https://github.com/aws/aws-sam-cli/issues?q=is%3Aissue+is%3Aopen+Bug%3A%20samdev%20build%20-%20UnsupportedBuilderException
Or create a bug report:
https://github.com/aws/aws-sam-cli/issues/new?template=Bug_report.md&title=Bug%3A%20samdev%20build%20-%20UnsupportedBuilder …
```

Print all error name and message in UnhanledException messaging

---

samcli/commands/list/cli_common/options.py
samcli/commands/list/endpoints/command.py
samcli/commands/list/resources/command.py
tests/unit/commands/list/endpoints/test_cli.py
tests/unit/commands/list/resources/test_cli.py

Adds a warning message if a `--stack-name` option isn't provided explaining that the `sam list` command is acting only on the local template and not deployed resources. Applicable to `sam list resources` and `sam list endpoints`.

feat: Add warning about not providing stack name option

---

tests/integration/list/endpoints/endpoints_integ_base.py
tests/integration/list/endpoints/test_endpoints_command.py
tests/integration/list/list_integ_base.py
tests/integration/list/resources/resources_integ_base.py
tests/integration/list/resources/test_resources_command.py

Some `sam list` integration tests have been failing on Windows since they hard-code line endings.
Refactored the tests to not need specific strings, instead it validates JSON properties.

fix: Fix failing list tests on Windows

---

samcli/lib/list/resources/resource_mapping_producer.py
tests/unit/commands/list/resources/test_resources_context.py

N.A.
The list producer uses yaml.load() method, which should be replaced by safe yaml load.
Removes the use of yaml.load() method and use the yaml parse method already created in utilities.
Not known.

chore: Use utility's yaml parse method in list producer

---

tests/integration/sync/test_sync_adl.py

N.A.
In https://github.com/aws/aws-sam-cli/pull/4488/files an integration test is updated related to the https://github.com/aws/aws-sam-cli/pull/4485 and https://github.com/aws/aws-sam-cli/pull/4462 changes. However as the mentioned PRs got reverted, this test change was not reverted.
Updated the test to restore the test state prior to all the changes.
Not known

fix: Revert an integration test change related to permission change revert

---

samcli/commands/list/cli_common/options.py
tests/unit/commands/list/test_options.py

Since `sam list` is a command that can be used programmatically with the `json` output format, we should reserve the `stdout` stream to be exclusively the output of the command, similar to how `sam local invoke` works today. 
This PR changes the warning message to use `stderr` instead.

feat: Only stream command output to stdout

---

samcli/commands/exceptions.py
samcli/commands/validate/validate.py
tests/integration/validate/test_validate_command.py
tests/unit/commands/validate/test_cli.py

#4649
Currently, `sam validate --lint` returns a 0 return code even if lint errors occurred.
Raises an exception if any lint rules matched, which will propagate up and will exit the process with a return code of 1. 
N/A

fix: Return non-zero exit code on lint failures

---

samcli/commands/build/build_context.py

The inability to match the runtime, such as 'provided.al2' to failed builds.
So that the runtime of failed builds can be correlated by request ID
It moves the EventTracker before the build happens, so if the build fails, the EventTracker has already run
There could be something today that assumes that BuildFunctionRuntime means the build was successful, which will no longer be the case.

Move up BuildFunctionRuntime Event to track failed builds by runtime

---

samcli/commands/local/lib/swagger/parser.py
samcli/lib/providers/api_collector.py
samcli/lib/providers/cfn_base_api_provider.py
samcli/local/apigw/exceptions.py
samcli/local/apigw/local_apigw_service.py
tests/unit/commands/local/lib/swagger/test_parser.py
tests/unit/commands/local/lib/test_api_collector.py
tests/unit/commands/local/lib/test_cfn_api_provider.py
tests/unit/commands/local/lib/test_sam_api_provider.py
tests/unit/local/apigw/test_local_apigw_service.py

This change adds the basic foundation for Authorizer support for `start-api`. This PR collects and adds Lambda authorizers that are defined in the body definition for `AWS::Serverless::Api`, and AWS::Serverless::HttpApi` resources.
This change also adds linking of valid Authorizers and those found in the routes.
Adds base dataclasses for Authorizers and modifies existing Swagger route collection logic to also collect and link Authorizers.

feat: Collect Lambda authorizers in swagger definition

---

tests/integration/local/start_lambda/test_start_lambda.py
tests/integration/sync/test_sync_code.py
tests/integration/testdata/invoke/template.yml
tests/integration/testdata/sync/code/before/template-python-code-only-layer.yaml
tests/integration/testdata/sync/code/before/template-python.yaml
tests/testing_utils.py

Fixes recent issues with integration tests;
- With removal of `python3.6`, we bumped some local tests to use newer python versions but they have different output if an error happens. Updated those tests with expected error message (also verified with error message of actually deployed lambda [see below]).
```
{
"errorMessage": "Lambda is raising an exception", 
"errorType": "Exception", 
"requestId": "6698a3f0-09b6-4ae9-93cb-27882edd5046",
"stackTrace": ["  File \"/var/task/lambda_function.py\", line 4, in lambda_handler\n    raise Exception(\"Lambda is raising an exception\")\n"]
}
```
- Recently added `sam sync` tests which is related to layers, have added new functions in the test template, which broke the existing tests. Those tests have been moved to its own template and test case.
- …

chore: fix sam local and sam sync integration tests

---

samcli/lib/samlib/wrapper.py

To decouple samtranslator. It is just a simple type check, no need to import a helper function for that. 

chore: Remove unnecessary samtranslator import "IS_STR"

---

tests/integration/delete/delete_integ_base.py
tests/integration/delete/test_delete_command.py
tests/integration/deploy/deploy_integ_base.py
tests/integration/deploy/test_deploy_command.py
tests/integration/deploy/test_managed_stack_deploy.py
tests/integration/list/endpoints/test_endpoints_command.py
tests/integration/list/list_integ_base.py
tests/integration/list/resources/test_resources_command.py
tests/integration/list/stack_outputs/test_stack_outputs_command.py

- `dir_exists_ok` is added in python3.8 to `shutil.copytree` method. Replaced that with alternative approach (delete the target parent folder before starting the copy operation).
- Moved stack deletion logic into `DeployIntegBase` class so that other test classes (like `sam list` tests) can use it to cleanup stacks once tests are completed
- Removed multiple inheritance in some test classes to make implementation more straight forward.
Tested by running deploy, delete and list tests which extends from changed files below.

chore: fix canary failures which extends from deploy class

---

tests/integration/sync/test_sync_watch.py

chore: remove debug flag from sync integ tests

---

samcli/lib/init/__init__.py
samcli/lib/telemetry/metric.py
tests/integration/init/test_init_base.py
tests/integration/init/test_init_command.py
tests/unit/lib/init/test_init.py
tests/unit/lib/telemetry/test_metric.py

- Add Abort as an exit code that's no longer classified as 255
- Add OSError to the catch blocks for `sam init` such that a non existent zip location does not cause the cli to crash.
```bash
sam init --location /path/to/template.zip 
Error: An error occurred while generating this project : [Errno 2] No such file or directory: '/path/to/template.zip' 
```
Before it used to crash with a traceback.
N/A
* Change is necessary for better telemetry numbers and also allowing for tracebacks to not appear on keyboard interrupts.
* No more crashes due to interrupts
* N/A

fix: telemetry for Abort

---

samcli/lib/package/utils.py
tests/unit/lib/package/test_artifact_exporter.py

With the latest make ZIP with permission change, we improved ZIP information storage with an additional field `date_time` into the ZIP file. Without this field, the contents of the lambda package will have a default last modified date of 1980. This is the default behaviour from python's zipfile.ZipInfo library: https://docs.python.org/3/library/zipfile.html. However, adding this field is breaking our ZIP hash comparison that sync flow hashing is based upon.
With the date_time, every time we make a package ZIP for lambda functions, the ZIP will have a different hash from the previous package even if the contents of the ZIP did not change. This means the sync flow hash comparison logic for ZIP functions will not work as each time we will generate a ZIP with a new hash.
By removing the …

fix: Remove the logic that stores datetime information into packaged ZIP

---

samcli/commands/_utils/command_exception_handler.py
samcli/commands/delete/command.py
samcli/commands/deploy/command.py
samcli/commands/exceptions.py
samcli/commands/package/command.py
samcli/commands/pipeline/bootstrap/cli.py
samcli/commands/pipeline/init/cli.py
samcli/commands/publish/command.py
samcli/commands/sync/command.py
samcli/commands/validate/validate.py
tests/unit/commands/_utils/test_command_exception_handler.py

- DO NOT CRASH THE CLI on sdk errors. Showcase the error message.
* Do not crash the CLI and report a traceback on developer environment related issues/api calls related issues.
* catch and handle the exception appropriately and exit with an exit code 1. Showcase the exception message as well.
* N/A (Better UX?)
... Above is not even the full traceback. 

fix: catch all boto errors and exit gracefully

---

samcli/lib/init/default_samconfig.py
tests/unit/lib/init/test_default_samconfig.py

- sam validate will use cfn-lint by default when running the interactive init flow.
N/A
* as part of engaging the right defaults with applications initialized with sam init, the default samconfig.toml should have validate with `cfn-lint` turned on.
* turn on `lint` on `sam validate` to be True
N/A

fix: set lint on validate to be default

---

appveyor-ubuntu.yml
appveyor-windows.yml

The include filter in `aws s3 cp` commands in Windows appveyor jobs are including the json files in the tests/ directory, which is inconsistent with what we've seen in the Linux appveyor jobs.
Apply a stricter `include` filter

Update commands to upload test reports to narrow filtering

---

tests/integration/package/package_integ_base.py
tests/integration/sync/sync_integ_base.py

Earlier PR (https://github.com/aws/aws-sam-cli/pull/4788/) added default values for `self.ecr_repo_name` and `self.kms_key` in `setUp` method of the sync tests, which overrides the actual values which is set `setUpClass` in `PackageIntegBase` which runs earlier. 

chore: fix sync tests by moving default field values into package test

---

tests/end_to_end/end_to_end_base.py
tests/end_to_end/test_stages.py

E2E tests fail when the cache directory doesn't already exist since they attempt to acquire a lock with it.
Ensures directory is creating before attempting to acquire the lock.
N/A

fix: Create cache dir before attempting to lock it

---

tests/end_to_end/test_runtimes_e2e.py

N/A
E2E test for Python are failing since our environment uses Python 3.7 but generated template is for Python3.9, resulting in the build stage not working.
Changes the Python version in the test cases to 3.7 to match the environment.
N/A

fix: Use python3.7 template in E2E tests

---

samcli/commands/deploy/deploy_context.py
samcli/lib/deploy/deployer.py
tests/integration/deploy/test_deploy_command.py
tests/unit/commands/deploy/test_deploy_context.py

#4585 
`--on-failure DELETE` would set `disable-rollback` to True in the `execute-change-set` API call. However, this causes issues when you have replacement updates within your CloudFormation template. Instead, we remove setting `disable-rollback` unless that is explicitly passed in and then allow the deletion of the stack to happen based on the end status of the stack. In talking with with @lucashuy, this seems to align with the original intent.
Does what I said above.
In looking at this in depth, I removed the "UPDATE_FAILED" status to trigger a deletion. This doesn't seem like a valid end state in CloudFormation for a stack but assuming a Stack Ends up in this state, it should be recoverable from. The idea behind this was to not accidentally delete a Stack if we are not in one of the …

bug: Don't set DisableRollback with OnFailure

---

tests/integration/buildcmd/test_build_cmd.py

Revert back to disable executing the `tests/integration/buildcmd/test_build_cmd.py::TestBuildCommand_Java_With_Specified_Architecture` test cases in windows to fix the Timed Out issue in the Appveyor canaries.
https://ci.appveyor.com/project/AWSSAMCLI/aws-sam-cli-canary-windows/build/job/2c9nkyujp57la9au#L10284 

test: Disable running the Java build test cases in windows.

---

Makefile

N/A
Makes it so that developers only need to use one Makefile target to format code.
Adds target
N/A

chore: Add 'format' target to Makefile

---

samcli/lib/sync/infra_sync_executor.py
tests/unit/lib/sync/test_infra_sync_executor.py

N/A.
When the number of resources that needs a code sync exceeds a threshold value (currently 50), it's not likely that skipping infra sync and queuing up related code syncs improve the execution speed.
Add a threshold check to prevent skip infra sync if the number of required code sync resources exceed the threshold
None

feat: Add threshold to the number of code syncs that trigger skip infra sync

---

requirements/dev.txt
tests/unit/lib/sync/test_watch_manager.py

We recently updated pytest to a newer version, which seems like not working well with existing plugin versions that we have. This PR is targeting to fix it by updating those plugins to the newer versions.

chore: update pytest plugins

---

samcli/hook_packages/terraform/hooks/prepare/property_builder.py
tests/unit/hook_packages/terraform/hooks/prepare/prepare_base.py
tests/unit/hook_packages/terraform/hooks/prepare/test_hook.py

#4824 
When working with Sam CLI and the new Terraform hook, I noticed that when I create a Lambda function and specify the memory_size in the Terraform resource, this value is not passed to the Lambda function when running locally with sam local invoke. As a result, the Lambda function always runs with the default memory size of 128MB. This causes issues when testing functions that require more than 128MB, as they are killed when the memory usage exceeds that value.
To address this issue, I added the missing MemorySize field to the hook property builder. This allows the memory_size value defined in the terraform resource to be passed to the Lambda function, so I can increase the MemorySize as needed.
Not sure
By submitting this …

bug: adding missing MemorySize field to terraform hook

---

requirements/base.txt
samcli/lib/translate/sam_template_validator.py
tests/unit/commands/list/resources/test_resources_context.py
tests/unit/commands/validate/lib/test_sam_template_validator.py

#4858 
Makes use of the new SAM-T feature in version 1.61.0 to call Translator with `get_managed_policy_map` parameter and cache policies, speeding up any calls to the transform.
N/A

feat: Update translator to use new managed policy map

---

samcli/local/apigw/authorizers/lambda_authorizer.py
samcli/local/apigw/event_constructor.py
samcli/local/apigw/exceptions.py
samcli/local/apigw/local_apigw_service.py
samcli/local/apigw/service_error_responses.py
samcli/local/events/api_event.py
tests/unit/local/apigw/test_event_constructor.py
tests/unit/local/apigw/test_lambda_authorizer.py
tests/unit/local/apigw/test_local_apigw_service.py

N/A
This adds the logic required to invoke a Lambda authorizer before the route's Lambda function and passes any context from the authorizer to the route. We also validate the response from the authorizer to make sure that the request is indeed valid and allowed.
Updates our Lambda invocation to be a method so that we can reuse it for both authorizers and routes. Adds some event manipulation to append the required keys to pass along context.
None.

feat: Invoke Lambda authorizer

---

samcli/lib/deploy/deployer.py
tests/unit/lib/deploy/test_deployer.py

#4813 
Error handling was not catered for non-changeset error
re-raise the waiter exception if it doesn't contain info about the changeset. so the generic error handler will handle it as SDKError
No

Handle non changeset error while waiting for chageset

---

samcli/commands/sync/command.py
tests/integration/sync/test_sync_code.py
tests/unit/commands/sync/test_command.py

N/A
Bring back `--resource` parameter validation which was accidentally removed in https://github.com/aws/aws-sam-cli/pull/4849
Adding back the validation and also moving the tests to unit so that we can run them with PR checks.
N/A

fix: bring back validate resource parameter

---

requirements/base.txt
requirements/reproducible-linux.txt

#4844 
`sam validate --lint` does not pick up region from shell
The fix is on cfn-lint. We just need to upgrade the minimum version of cfn-lint in our requirement file 

Upgrade cfn-lint in requirement

---

samcli/commands/build/build_context.py
samcli/commands/build/utils.py
tests/integration/testdata/buildcmd/cdk_v1_synthesized_template_zip_image_functions.json
tests/unit/commands/buildcmd/test_utils.py

N/A
- `prompt_user_to_enable_mount_with_write_if_needed` errors are not handled properly
- `prompt_user_to_enable_mount_with_write_if_needed` runs for `Image` type functions which is not needed
- `TestBuildCommand_PythonFunctions_CDK_0_cdk_v1_synthesized_template_zip_image_functions_json::test_cdk_app_with_default_requirements` is failing in Windows due to timeout.
- Move `prompt_user_to_enable_mount_with_write_if_needed` into try/except block so that errors will be handled for it
- Don't prompt for the `Image` type functions, since this is only needed for `Zip` ones
- Increase `Timeout` for the function in CDK tests so that timeout will be fixed for Windows tests
N/A
By submitting this pull request, I confirm that my contribution …

fix: move mount with write into try/except block and don't prompt for Image type lambda functions

---

tests/end_to_end/end_to_end_base.py
tests/end_to_end/test_runtimes_e2e.py
tests/end_to_end/test_stages.py
tests/integration/local/invoke/invoke_cdk_templates.py
tests/integration/local/invoke/invoke_integ_base.py
tests/integration/local/invoke/runtimes/test_with_runtime_zips.py
tests/integration/local/invoke/test_integration_cli_images.py
tests/integration/local/invoke/test_integrations_cli.py
tests/integration/local/invoke/test_invoke_cdk_templates_with_function_id.py
tests/integration/local/invoke/test_invoke_terraform_applications.py
tests/integration/local/invoke/test_with_credentials.py
tests/integration/package/package_integ_base.py
tests/integration/package/test_package_command_image.py
tests/integration/package/test_package_command_zip.py

SAM CLI 1.67.0 changed the permissions of the packaged zip file which could not be invoked locally as well. Testing the cloud packaged zip file by invoking it locally to ensure it has the right permissions.
Verified sam local invoke throws permission error with SAM CLI 1.67.0 after running sam package.
The new end to end test ensures the packaged function has the correct permissions and can be invoked using sam local.
N/A

test: Add end2end test for package and local

---

samcli/commands/deploy/command.py
samcli/commands/deploy/guided_context.py
tests/unit/commands/deploy/test_command.py

https://github.com/aws/aws-sam-cli/issues/4841
* This change is necessary so that users can run `sam deploy --guided` and continue to run `sam deploy` afterwards without running into issues where `--resolve-s3` and `--s3-bucket` are both set.
* With this change, whenever a user goes through a guided flow, the resources that are required for deployment are created automatically and the config file updated with `--resolve-s3` and `--resolve-image-repos`
* Not really a side effect as this is how it used to work before as well.
`sam deploy --guided --s3-bucket <> or sam deploy --guided --image-repositories <>` will ignore the bucket or the image repositories as it is the managed flow. …

fix: respect `--resolve-s3` and `--resolve-image-repos` in a guided context.

---

samcli/commands/deploy/command.py
tests/unit/commands/deploy/test_command.py

[#4906](https://github.com/aws/aws-sam-cli/issues/4906)
The customers who use SAM CLI to deploy large templates start to face some issue during the deployment due a change in the default deploy poll delay from 5 seconds to 0.5 seconds, that makes `sam cli` exceeds the number of attempts.
Set the default poll delay to 5 seconds instead of 0.5 sec 

fix: set the deploy delay default value to 5 seconds to match the old experience.

---

samcli/local/apigw/authorizers/lambda_authorizer.py
samcli/local/apigw/local_apigw_service.py
tests/unit/local/apigw/test_lambda_authorizer.py

N/A
Adds a missing check to validate incoming headers against the validation expression property defined in the template file.
Modifies the existing header validator by overriding the parent validation method to also check the expression.
None

feat: Validate headers against validation expression property

---

samcli/local/apigw/local_apigw_service.py
tests/unit/local/apigw/test_local_apigw_service.py

N/A
APIGW payload format version `2.0` passes the context under `{authorizer: {lambda: ...context...}}` instead of `{authorizer: ...context...}`
Adds a check for the `2.0` payload format version.
None

fix: Fix APIGW V2 context passing

---

samcli/local/docker/lambda_image.py

N/A
Latest tests for image functions in app templates are failing as a result of the following bug fix: https://github.com/aws/aws-sam-cli/pull/4950. This fix moves the instantiation of `runtime_image_tag` to a broader scope to ensure it's defined before it's used, however this variable shouldn't be instantiated for image type functions.
Moves the instantiation of `runtime_image_tag` to a scope where it can be used later but isn't instantiated for image type functions.
N/A

fix: Fix failing tests for image function invoke

---

tests/integration/logs/test_logs_command.py

N/A
When running `sam logs` tests for APIGW, we make one API call and verify the logs of it. But for some cases, it doesn't fill-up the buffer therefore the logs were never delivered CW and causes the test to fail.
With this change, we are making couple of calls before checking the logs of them.
N/A

chore: fix `sam logs` APIGW tests by making more calls before pulling the logs

---

samcli/lib/init/template_modifiers/application_insights_template_modifier.py
tests/integration/init/test_init_command.py
tests/testing_utils.py
tests/unit/lib/init/test_application_insights_template_modifier.py

#4695 
After running `sam init`, the resulting template should pass `cfn-lint` by default.
- Update App Insights Template Modifier to comply with cfn-lint rules
- Update integration tests to assert with cfn lint for both app insight templates and x-ray tracing templates
No

update app insights template modifier to comply with cfn-lint rules

---

.github/workflows/build.yml

Enable GHA CI jobs to run against `develop` and `feat*` branches.

 ci: add feat* rule to run github actions

---

appveyor-ubuntu.yml
appveyor-windows.yml
tests/integration/deploy/test_managed_stack_deploy.py

- Tests in `test_managed_stack_deploy.py` clashing each other when we run them in parallel. Switched to use `--dist=loadgroup` and marked the tests with `@pytest.mark.xdist_group(name="managed_stack")` so that each test will run in the same thread sequentially.
- Updated same tests to only run in `python3.8` instead of `python3.7`
- Suppressed `rustup` output to fix issue which causes workers to stall.

fix: run managed stack tests sequentially & suppress rustup output

---

samcli/commands/local/lib/swagger/parser.py
tests/unit/commands/local/lib/swagger/test_parser.py

N/A
Previously, the "simple response only available on HTTP APIs" message was being logged to the terminal even if simple responses was never defined in the template.
Encases the `if` statement in a `None` check to only print if the property was defined. This PR also adds a typing check to the property, defaulting to `False` if an invalid type was defined.
None.

fix: Only print console message if enableSimpleResponses is defined

---

samcli/lib/providers/api_collector.py

N/A
Adds a disclaimer message to the output of `local start-api` if there are any authorizers that are being used in the template.
This change also fixes some unnecessary log output if there are no authorizers defined in the template by checking to see if a route had an authorizer set in the first place.
Adds a log statement at the end of the API collection phase and checks to the warning log for undefined authorizers.
N/A

feat: Add usage disclaimer when starting API with authorizers

---

samcli/hook_packages/terraform/hooks/prepare/property_builder.py
tests/unit/hook_packages/terraform/hooks/prepare/prepare_base.py
tests/unit/hook_packages/terraform/hooks/prepare/test_translate.py

N/A
* Support for APIGW Stage from terraform to CFN.
* Should `deployment_id` be included as well? https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_stage -> deployment_id is marked as required on the terraform docs.

feat: read and translate APIGW Stage for Terraform

---

samcli/local/docker/manager.py

#5015
to support `sam build -u` with podman
This change fully splits the image name from the tag before pulling. Podman isn't as forgiving as the official docker engine when submitting `"imagename:tag", tag="tag"` to the API
None
- [n/a] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [n/a] Write design document if needed ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [n/a] Write/update unit tests
- [n/a] Write/update integration tests
- [n/a] Write/update functional tests if needed
- [n/a] `make update-reproducible-reqs` if dependencies were changed
By submitting this pull request, I confirm …

fix: Split image name from tag before pulling

---

samcli/local/docker/manager.py
tests/unit/local/docker/test_manager.py

In #5016, we split the image_name and tag to allow for better support with other docker like systems (podman). The side affect was that, we logged the "image:tag" and asserted that it would be in the logs. Due to the change, the log was changed and caused the test to fail.
None
Failing integration tests
Fixes the integration test
None

fix: test_custom_build_image_succeeds build test was failing due log not matching

---

samcli/lib/deploy/deployer.py

N/A
We had a report that sometimes `sam deploy` can fail with a validation Error from CFN. The only path that this might be caused by is returning None if we get a ClientError from boto3. So I added additionally logging and a hard fail if we cannot determine if the Stack Exists. This ensures `sam deploy` will create the correct change set type (create or update) depending on if the stack exists.
Raises a DeployError when we cannot determine if the Stack exists
This might fail stacks more often for customers if ClientErrors are thrown. I think this is acceptable because right now we are purely guessing at if the stack exists. Returning `None` is the same as saying the stack doesn't exist which may or may  not be true.
By submitting …

fix: Hard fail deploy if can't determine if the stack exists

---

samcli/local/apigw/local_apigw_service.py
tests/unit/local/apigw/test_local_apigw_service.py

At some point, a version bump in our dependencies caused a function call (`werkzeug.urls.url_parse`) to be deprecated. This call is used within the Flask built in test mocking context that was used for one of the tests in SAM CLI, causing the CI workers to fail.
Changes the affected SAM CLI function by passing the Flask context as an argument, instead of using the global `request` variable so that it can be mocked out using `pytest`.
None

fix: Fixed flask request test mocking

---

samcli/lib/utils/preview_runtimes.py

To remove packaging warning messaging for java 17
Removes the runtime from the list of preview runtimes.
n/a

feat: remove packaging warning message for java 17

---

samcli/hook_packages/terraform/designs/resource_linking_generalized.md
samcli/hook_packages/terraform/hooks/prepare/exceptions.py
samcli/hook_packages/terraform/hooks/prepare/resource_linking.py
samcli/hook_packages/terraform/hooks/prepare/translate.py
tests/unit/hook_packages/terraform/hooks/prepare/test_resource_linking.py
tests/unit/hook_packages/terraform/hooks/prepare/test_translate.py

N/A
To make the resource linking for Terraform resources more extensible to resources beyond functions and layers. This will allow for quicker additions of linking two resources based on a given field.
Implements the resource linker generalization strategy defined in: https://github.com/aws/aws-sam-cli/pull/5039
N/A

chore: Refactor the linking algorithm to be more generic

---

samcli/cli/cli_config_file.py
tests/unit/cli/test_cli_config_file.py

#4875 
This change is necessary so that users can use a pipe with `--config-file` option.
It refactors the checks on user provided configuration file paths in order to explicitly allow pipes. 
I believe that there are no side effects.

fix: accept pipe as config file

---

samcli/lib/pipeline/bootstrap/stage_resources.yaml

`sam pipeline bootstrap` is broken because of a S3 [security change](https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/)
The default value of `ObjectOwnership` becomes `BucketOwnerEnforced` which has conflicts with `AccessControl` property. Hence the deployment will fail.
Specify `ObjectOwnership` to `ObjectWriter` so that it doesn't have conflicts with `AccessControl`

fix: Fix S3 bucket policy issue for sam pipeline

---

samcli/lib/list/resources/resource_mapping_producer.py
tests/unit/commands/list/resources/test_resources_context.py

Previously, we were using `describe_stack_resources` to get all the Resources from a Stack. However, this will only ever return the first 100 resources (per API docs). Instead, we move to using the `list_stack_resources` paginator (per API docs). This allows us to get all the resources within a stack. The response is different from `describe_stack_resources` and `list_stack_resources` but the difference is not meaningful for the current implementation.
As apart of this, I updated the unit tests. Previously, we were using another class to get a CFN Client to mock. Instead of mocking out a file that is not used within the `resource_mapping_producer.py`, I remove that and mocked out the `cfn_client` directly. This makes the tests easier to follow and removes unneeded mocking of …

fix(list): Handle Stacks with >100 resources

---

appveyor-ubuntu.yml

Setting following environment variables as it was suggested by the AppVeyor team;
```
APPVEYOR_DETAILED_SHELL_LOGGING: true
APPVEYOR_CONSOLE_DISABLE_PTY: false
```
Moved following ones into general as it is been set for every configuration;
```
PYTHON_ARCH: '64'
NOSE_PARAMETERIZED_NO_WARN: 1
```
Removed following ones as they are not used anymore (they were used once we were managing python versions there, but we are now using the ones which are provided by AppVeyor);
```
INSTALL_PY_38_PIP: 1
INSTALL_PY_39_PIP: 1
INSTALL_PY_310_PIP: 1
```
Test runs can be found;
- https://ci.appveyor.com/project/AWSSAMCLI/aws-sam-cli-canary-linux-dev/builds/46930470
- https://ci.appveyor.com/project/AWSSAMCLI/aws-sam-cli-canary-windows-dev/builds/46930475 …

chore: consolidate env vars and set the ones recommended by AppVeyor

---

tests/unit/commands/init/test_cli.py

N/A
Fix for a unit test that can fail locally if a clone directory exists on the machine.
Mocks out the call that sets this directory.
N/A

fix: Flaky Init Test

---

samcli/local/apigw/authorizers/lambda_authorizer.py
tests/unit/local/apigw/test_lambda_authorizer.py

This patch makes the lambda authorizer expect some valid statements in an IAM Policy Document that were not allowed before. Specifically, it is now allowed to use:
* single resource string instead of list; and
* action list instead of single string.
#5072, #5083
The current implementation does not allow some valid API Policy Documents as the response from the authorizer lambda. It will always lead to an authorization failure.
* Update the validator to not consider these documents to be invalid.
* Update the logic that checks the contents to handle these values properly.

fix: relax IAM Policy Document structure requirements

---

samcli/local/common/runtime_template.py
tests/unit/commands/init/test_cli.py
tests/unit/commands/init/test_non_interactive_mode.py

Complementing to: https://github.com/aws/aws-sam-cli-app-templates/pull/410
N/A
Remove dotnet5 image templates since [the language reached its EOL](https://devblogs.microsoft.com/dotnet/dotnet-5-end-of-support-update/).
AWS Lambda does not support dotnet5 as native runtime, it is only supported via Image type lambda function. This PR removes `sam local` related functionality from this code base.

remove dotnet5 support

---

appveyor-ubuntu.yml
appveyor-windows.yml
tests/integration/init/test_init_base.py
tests/integration/logs/test_logs_command.py
tests/integration/pipeline/base.py
tests/integration/telemetry/integ_base.py
tests/integration/traces/test_traces_command.py

Updates tests in `OtherTesting` group for running them in parallel with 4 threads and 4 reruns.
- Adds `xdist_group` pytest mark for following test classes so that each test in that class can run in the same thread. Otherwise they cause failures.
- `InitIntegBase` is marked as `sam_init`
- `TestLogsCommandWithRegularStack` marked as `sam_logs_regular`
- `TestLogsCommandWithNestedStack` marked as `sam_logs_nested`
- All tests that extends from `PipelineBase` marked as `sam_pipeline`
- All telemetry integration tests that extends from `IntegBase` in `tests/integration/telemetry/integ_base.py` module is marked as `sam_telemetry`
- All `sam traces` tests that extends from `TestTracesCommand` marked as `sam_traces`
- Updated AppVeyor configurations to run them in 4 threads  with 4 reruns, …

chore: run other test group in parallel

---

samcli/lib/docs/documentation_links.json

`sam docs deploy` command opens the [delete docs](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-delete.html)

fix: fix the documentation url for deploy command

---

.github/workflows/build.yml
appveyor-iac-integration-ubuntu.yml
tests/iac_integration/cdk/testdata/cdk_v1/java/src/main/java/com/myorg/JavaStack.java
tests/iac_integration/cdk/testdata/cdk_v1/python/python/python_stack.py
tests/iac_integration/cdk/testdata/cdk_v1/typescript/lib/test-stack.ts
tests/iac_integration/cdk/testdata/cdk_v2/java/src/main/java/com/myorg/JavaStack.java
tests/iac_integration/cdk/testdata/cdk_v2/python/python/python_stack.py
tests/iac_integration/cdk/testdata/cdk_v2/typescript/lib/test-stack.ts

Fix the failing CDK testing Appveyor jobs
https://ci.appveyor.com/project/AWSSAMCLI/aws-sam-cli-cdk-integration
- I fixed the Python installation to fix the failing jobs for py3.8, and py3.9.
- I added the missed runtime for some NodeJS function to fix this error
```
ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project java: An exception occured while executing the Java class. This lambda function uses a runtime that is incompatible with this layer (${Token[TOKEN.824]} is not in [nodejs14.x])
[ERROR] Error: This lambda function uses a runtime that is incompatible with this layer (${Token[TOKEN.824]} is not in [nodejs14.x])
[ERROR]     at NodejsFunction.addLayers (/tmp/jsii-kernel-yd4q3g/node_modules/aws-cdk-lib/aws-lambda/lib/function.js:1:1 …
```

fix: fix the python installation in CDK integration Appveyor

---

tests/integration/init/schemas/schemas_test_data_setup.py
tests/integration/init/schemas/test_init_with_schemas_command.py
tests/integration/init/test_init_command.py

Mark all `sam init` tests with `xdist_group` so that they will run in the same group during integration tests.
If we don't do this, different `sam init` tests might start at the same time, which causes issues during cloning step of the application templates.

chore: run all sam init tests in the same group

---

samcli/hook_packages/terraform/hooks/prepare/exceptions.py
samcli/hook_packages/terraform/hooks/prepare/resource_linking.py
samcli/hook_packages/terraform/hooks/prepare/resources/apigw.py
samcli/hook_packages/terraform/hooks/prepare/resources/resource_properties.py
samcli/hook_packages/terraform/hooks/prepare/translate.py
tests/unit/hook_packages/terraform/hooks/prepare/test_translate.py

N/A
To support `sam local start-api` for Terraform projects, AWS SAM CLI needs to be able to read the APIGW Terraform resources and then link related resources together. 
This PR adds the logic for linking all `AWS::ApiGateway::Resource` resources to their corresponding `AWS::ApiGateway::RestApi` resources linked on the `RestApiId` field.
N/A

feat: Link APIGW Resources to APIGW REST APIs

---

samcli/hook_packages/terraform/hooks/prepare/exceptions.py
samcli/hook_packages/terraform/hooks/prepare/resource_linking.py
samcli/hook_packages/terraform/hooks/prepare/resources/apigw.py
samcli/hook_packages/terraform/hooks/prepare/resources/resource_properties.py
samcli/hook_packages/terraform/hooks/prepare/translate.py
tests/unit/hook_packages/terraform/hooks/prepare/test_translate.py

N/A
To support `sam local start-api` for Terraform projects, AWS SAM CLI needs to be able to read the APIGW Terraform resources and then link related resources together.
This PR adds the logic for linking: 
- `AWS::ApiGateway::Method` resources to their corresponding `AWS::ApiGateway::Resource` resources linked on the ResourceId field.
- `AWS::ApiGateway::Stage` resources to their corresponding `AWS::ApiGateway::RestApi` resources linked on the RestApiId field.
N/A

feat: Link stages to REST APIs, methods to resources

---

samcli/cli/context.py
samcli/commands/_utils/command_exception_handler.py
samcli/commands/exceptions.py
samcli/commands/pipeline/bootstrap/guided_context.py
samcli/lib/bootstrap/bootstrap.py
samcli/lib/bootstrap/companion_stack/companion_stack_manager.py
samcli/lib/utils/managed_cloudformation_stack.py
tests/unit/commands/_utils/test_command_exception_handler.py
tests/unit/lib/bootstrap/test_bootstrap.py
tests/unit/lib/utils/test_managed_cloudformation_stack.py

- regardless of error code in exception message - DO NOT Crash.
Per https://boto3.amazonaws.com/v1/documentation/api/latest/guide/error-handling.html we should be catching all `ClientError`
* Catch all ClientError and transform them to click exceptions.
N/A

fix: catch all ClientError from Boto

---

samcli/hook_packages/terraform/hooks/prepare/property_builder.py
samcli/hook_packages/terraform/hooks/prepare/resources/internal.py
samcli/hook_packages/terraform/hooks/prepare/resources/resource_properties.py
samcli/hook_packages/terraform/hooks/prepare/translate.py
tests/unit/hook_packages/terraform/hooks/prepare/prepare_base.py
tests/unit/hook_packages/terraform/hooks/prepare/test_translate.py

N/A
To support sam local start-api for Terraform resources, we need to read in the APIGW methods and convert them to the corresponding CFN resources.
Adds a new "Internal" resource type for translating resources that exist in Terraform but not in CFN. These resources are stored temporarily to handle necessary linking and translation logic, but are not written to the metadata file.
Creates the first internal resource `Internal::ApiGateway::Method::Integration`

feat: Add support for translating and linking gateway integrations

---

samcli/commands/local/invoke/cli.py
tests/unit/commands/local/invoke/test_cli.py

fix: `sam local invoke -e` crashes on non existent file

---

samcli/hook_packages/terraform/hooks/prepare/resource_linking.py
samcli/hook_packages/terraform/hooks/prepare/resources/resource_links.py
samcli/hook_packages/terraform/hooks/prepare/translate.py
samcli/hook_packages/terraform/hooks/prepare/types.py
tests/unit/hook_packages/terraform/hooks/prepare/test_resource_linking.py
tests/unit/hook_packages/terraform/hooks/prepare/test_translate.py

N/A
Cleans up a bunch of repeated function calls with the same signature to be done by iterating over a loop of resources that need to be linked.
- Creates a dataclass for storing the source resource, destination resource and the function to link the two.
- Creates a list of the newly defined dataclass in a new module containing all of the existing supported links
- Updates the translate function to remove the repeated function calls to be handled in a separate function that iterates over the list and calls the linking function for each pair.
- Moves all relevant linking logic from the `translate.py` module to the `link_resources.py` module
- Updates unit tests accordingly
N/A …

chore: Cleanup the linking functions

---

.github/workflows/automated-updates-to-sam-cli.yml

Due to recent changes of upgrading linux installer from 3.7 to 3.11, we need to have both available in the GHA or the job will fail.
N/A
Get the `updateSAMTranslator` GHA to run properly
Installs both Python3.7 and Python3.11 in the GHA
None

fix: Install both Py3.7 and Py3.11 in GHA to upgrade SAM-T

---

samcli/hook_packages/terraform/hooks/prepare/exceptions.py
samcli/hook_packages/terraform/hooks/prepare/resource_linking.py
samcli/hook_packages/terraform/hooks/prepare/resources/apigw.py
samcli/hook_packages/terraform/hooks/prepare/resources/resource_links.py
samcli/hook_packages/terraform/hooks/prepare/translate.py
tests/unit/hook_packages/terraform/hooks/prepare/resources/test_apigw.py
tests/unit/hook_packages/terraform/hooks/prepare/test_resource_linking.py
tests/unit/hook_packages/terraform/hooks/prepare/test_translate.py

Link the internal CFN mapped integration response resources to the RestAPIs, and Gateway Resource resources, then update the Integration Method CFN resources that match these integration response resources.

feat: map gateway integration response resources to integration method resources

---

README.md

Lambda Powertools is being renamed, this updates SAM CLI to use the new name
It changes the name in the README
None

chore: update lambda powertools name

---

samcli/commands/remote_invoke/exceptions.py
samcli/commands/remote_invoke/remote_invoke_context.py
samcli/lib/utils/cloudformation.py
tests/unit/commands/remote_invoke/test_remote_invoke_context.py
tests/unit/lib/utils/test_cloudformation.py

Updates `RemoteInvokeContext` object to invoke the remote invoke executor;
- Updated `__enter__` method to find resource summary for given stack name and resource logical id
- Implemented `run` method, to instantiate remote invoke executor through its factory and run execute method on it
- Updated `get_resource_summary` in CFN utilities to return resources from nested stacks.

feat: update remote invoke context to actually invoke the executor

---

installer/pyinstaller/samcli.spec
requirements/base.txt
requirements/reproducible-linux.txt
requirements/reproducible-mac.txt
tests/integration/validate/test_validate_command.py

https://github.com/aws/aws-sam-cli/issues/5194
Upgraded cfn-lint library to the latest version to accept the latest Lambda runtimes. I also added an integration test case to validate that SAM CLI accepts the latest Lambda runtimes.
- [] Write/update unit tests

feat: upgrade cfn-lint

---

.github/dependabot.yml
.github/workflows/automated-updates-to-sam-cli.yml

Update GH action to check the latest version of aws-lambda-builders library, and to create a PR for the version bump.

Chore: update GH Action to update aws-lambda-builders dependency

---

samcli/commands/pipeline/init/interactive_init_flow.py

https://github.com/aws/aws-sam-cli/issues/5207
Removed the hardcoded number, and replaced it with the number of stages.

fix: fix the hardcoded number of stages printed in logs.

---

samcli/hook_packages/terraform/hooks/prepare/translate.py
tests/integration/local/invoke/test_invoke_terraform_applications.py
tests/integration/testdata/buildcmd/terraform/image_based_lambda_functions_local_backend/main.tf
tests/integration/testdata/buildcmd/terraform/image_based_lambda_functions_s3_backend/main.tf
tests/unit/hook_packages/terraform/hooks/prepare/test_translate.py

- Removed the `skip_get_ec2_platforms` flag from the sample Terraform testing project, AS Hashicorp pushed a new AWS Provider and removed this flag.
- Fix the resource address while accessing the module config resources
- Fix checking the experimental log integration test cases

fix: fix failing Terraform integration test cases

---

samcli/hook_packages/terraform/hooks/prepare/exceptions.py
samcli/hook_packages/terraform/hooks/prepare/resource_linking.py
samcli/hook_packages/terraform/hooks/prepare/resources/resource_links.py
tests/unit/hook_packages/terraform/hooks/prepare/test_resource_linking.py

N/A
Gateway Methods can contain a reference to a Lambda Authorizer, we'll need to resolve the link between the two.
Links the `AuthorizerId` property in the CFN resource to the right Authorizer using either a `Ref` or a existing value.
None.

feat: Added linking Gateway Method to Lambda Authorizer

---

samcli/commands/deploy/deploy_context.py
samcli/commands/deploy/guided_context.py
tests/unit/commands/deploy/test_guided_context.py

N/A
Strengthens wording on no Auth.
Updates the text
Nothing, just text update.

chore: Strengthen wording on "no Auth" during deploy

---

samcli/hook_packages/terraform/hooks/prepare/exceptions.py
samcli/hook_packages/terraform/hooks/prepare/resource_linking.py
samcli/hook_packages/terraform/hooks/prepare/resources/resource_links.py
tests/unit/hook_packages/terraform/hooks/prepare/test_resource_linking.py

N/A
Links links the Lambda Authorizer to the Rest API using the Rest API's Id.
Adds the method to call the generalized Rest API Id linking call back to link the Authorizer to the Rest API.
None.

feat: Link Lambda Authorizer to Rest API

---

requirements/dev.txt

N/A
A breaking change was introduced in `pytest-metadata` 3.0.0, resulting in empty `Environment` section in the test reports generated with `pytest-json-report`. This breaks our internal tools for test failure investigations.
Pin `pytest-metadata` to 2.0.4, which is the last version before 3.0.0.
No

pin pytest-metadata to avoid its breaking change

---

.github/workflows/automated-updates-to-sam-cli.yml

N/A
When the GHA runs and force pushes a commit, the status checks in the PR do not restart. This requires manual closing & reopening the PR to kick off new status checks.
automate closing & reopening PR if there's an existing PR
N/A

update gha to force restart of status checks

---

tests/integration/package/test_package_command_zip.py
tests/integration/testdata/package/aws-serverless-graphqlapi.yaml
tests/integration/testdata/package/sam_graphql_api/createPostItem.js
tests/integration/testdata/package/sam_graphql_api/getPost.js
tests/integration/testdata/package/sam_graphql_api/getPostFromTable.js
tests/integration/testdata/package/sam_graphql_api/schema.graphql

Integration tests for [the past PR](https://github.com/aws/aws-sam-cli/pull/5250) to support `sam package` for SAM `GraphQLApi` resource.

integration tests for graphql resource package

---

samcli/cli/cli_config_file.py
samcli/commands/_utils/custom_options/hook_name_option.py
samcli/commands/build/command.py
samcli/commands/delete/delete_context.py
samcli/commands/deploy/command.py
samcli/commands/init/command.py
samcli/commands/list/endpoints/command.py
samcli/commands/list/resources/command.py
samcli/commands/list/stack_outputs/command.py
samcli/commands/local/generate_event/event_generation.py
samcli/commands/local/invoke/cli.py
samcli/commands/local/start_api/cli.py
samcli/commands/local/start_lambda/cli.py
samcli/commands/logs/command.py
samcli/commands/package/command.py
samcli/commands/pipeline/bootstrap/cli.py
samcli/commands/pipeline/init/cli.py
samcli/commands/publish/command.py
samcli/commands/sync/command.py
samcli/commands/traces/command.py
samcli/commands/validate/validate.py
tests/unit/cli/test_cli_config_file.py
tests/unit/commands/delete/test_delete_context.py

Since `SamConfig` no longer deals solely with TOML files, the `TomlProvider` class that makes use of it has been refactored to decouple it from any mention of TOML.
The `TomlProvider` class was renamed to `ConfigProvider` in the code, and mentions of it in the codebase have been updated accordingly. In addition, since the docstrings were using an outdated format, they have been updated to the NumPy/SciPy style, and type hints have been added.
`TomlProvider` is now renamed to `ConfigProvider` in this codebase, which could impact future changes or implementations of the class. …

feat: Refactor TomlProvider

---

.github/workflows/build.yml
tests/integration/buildcmd/test_build_cmd.py

To ensure that executing AWS SAM CLI commands while Docker isn't running succeeds.
Guard against regressions.
Creates a GitHub action that runs on PRs to ensure that a build test succeeds after the Docker daemon is stopped.
N/A

test: GHA to Execute Test without Docker Running

---

samcli/lib/utils/preview_runtimes.py

Remove `ruby3.2` from preview runtimes.

fix: remove ruby3.2 from preview runtimes

---

.github/workflows/build.yml
appveyor-ubuntu.yml
appveyor-windows.yml

N/A
Some of the checks that we do in GHA is also run with Appveyor jobs and they have custom configuration rather than using the ones from `Makefile`. 
- Removing the tests/checks from Appveyor that we already run with GHA
- Cleaning up some Appveyor setup where it was repeated couple of times
N/A

chore: cleanup appveyor definitions for not running jobs which is already run with GHA & add docker info/version commands

---

samcli/cli/cli_config_file.py
samcli/commands/deploy/guided_config.py
samcli/lib/config/file_manager.py
samcli/lib/config/samconfig.py
tests/unit/commands/samconfig/test_samconfig.py
tests/unit/lib/samconfig/test_file_manager.py
tests/unit/lib/samconfig/test_samconfig.py

If users have multiple `samconfig` files of varying extensions, we want to prioritize them in a certain way. Currently that priority is set to be TOML > YAML > (YML) > JSON, according to the order of the dictionary keys in `SamConfig.FILE_MANAGER_MAPPER`, making this ordering flexible in the future.
A new method, `SamConfig._get_default_file()` has been added, which searches for whether different samconfig files exist in the project. If no files exist, it uses the default file `DEFAULT_CONFIG_FILE_NAME`. If one file exists, it is returned. If multiple files exist, the one with the higher priority is returned, and the user is given a message about which of those config files were used.
* The previous `FileManager` tests have been moved to `../lib/samconfig/test_samconfig.py` instead of …

feat: Add hierarchy for samconfig filetypes

---

.github/workflows/automated-updates-to-sam-cli.yml

NA
In GHA for updating app template commit hash, GH API sometimes returns error when trying to reopen a PR after closing it. e.g. https://github.com/aws/aws-sam-cli/actions/runs/5224495677/jobs/9432756673
```
To https://github.com/aws/aws-sam-cli
+ 22c26c1...33b0fe0 update_app_templates_hash -> update_app_templates_hash (forced update)
1
✓ Closed pull request #5314 (feat: update SAM CLI with latest App Templates commit hash)
API call failed: GraphQL: Could not open the pull request. (reopenPullRequest)
```
Successful example - https://github.com/aws/aws-sam-cli/actions/runs/5225642402/jobs/9435377828
```
To https://github.com/aws/aws-sam-cli
+ 33b0fe0...682295d update_app_templates_hash -> update_app_templates_hash (forced update)
1
✓ Closed pull request #5316 (feat: update SAM CLI with …
```

add sleep between close and reopen

---

samcli/lib/config/file_manager.py
samcli/lib/config/samconfig.py
samcli/lib/telemetry/event.py
tests/integration/telemetry/test_experimental_metric.py
tests/integration/telemetry/test_installed_metric.py
tests/integration/telemetry/test_telemetry_contract.py
tests/unit/cli/test_cli_config_file.py
tests/unit/lib/samconfig/test_samconfig.py

These changes allow us to keep track of which config file extensions users are using. As such, it will provide us insights into how many people may prefer to use one file type over another, which could aid in the potential deprecation of less-used extensions, or the potential to support newer ones.
A new `EventType` has been created for `EventName.CONFIG_FILE_EXTENSION`, which is called upon the creation of a `SamConfig` object. As such, whenever someone runs a command that reads in a config file, we will receive an Event.
In order to prevent a cyclic import, the `FILE_MANAGER_MAPPER` has been moved to `samconfig/file_manager.py` from `samconfig/samconfig.py`. This change makes sense, as the logic of pairing file extensions to `FileManager`s is encapsulated in this file anyway, and it …

feat: Track config file extension

---

.github/workflows/automated-updates-to-sam-cli.yml

Revert https://github.com/aws/aws-sam-cli/pull/5320 and https://github.com/aws/aws-sam-cli/pull/5269 because re-opening the PR often got errors after closing. (e.g. https://github.com/aws/aws-sam-cli/actions/runs/5257815634/jobs/9501166950) This behavior didn't match with local testing and testing in another GHA in my other repo. So reverting these changes for now and will find other ways to restart checks.

Revert app templates gha

---

samcli/commands/_utils/options.py
samcli/commands/remote/invoke/cli.py
samcli/commands/remote/invoke/core/command.py
samcli/commands/remote/invoke/core/formatters.py
samcli/commands/remote/invoke/core/options.py
samcli/lib/cli_validation/remote_invoke_options_validations.py
samcli/lib/remote_invoke/lambda_invoke_executors.py
samcli/lib/remote_invoke/remote_invoke_executor_factory.py
samcli/lib/remote_invoke/remote_invoke_executors.py
tests/unit/cli/test_types.py
tests/unit/commands/remote/invoke/core/test_command.py
tests/unit/commands/remote/invoke/core/test_formatter.py
tests/unit/commands/remote/invoke/core/test_options.py
tests/unit/commands/remote/invoke/test_cli.py
tests/unit/lib/cli_validation/test_remote_invoke_options_validations.py
tests/unit/lib/remote_invoke/test_lambda_invoke_executors.py
tests/unit/lib/remote_invoke/test_remote_invoke_executor_factory.py
tests/unit/lib/remote_invoke/test_remote_invoke_executors.py

N/A
Changes:
- Fixes UX when `NoRegionError` and `NoCredentialsError` errors are thrown by wrapping command with `command_exception_handler`.
- Fixes UX for error when both `--event` and `--event-file` are passed
- Improve help text for `sam remote invoke`
- Change `output-format` option to `output` with values `text/json`
- Allow remote invoke when an empty event is passed for lambda
- Read from stdin when `-` is passed for `event-file`
- Log the function name before invoking the resource
After:

feat: sam remote invoke help text and UX fixes

---

.github/workflows/build.yml

Python Setup github action has some regression issue related to the new python version 3.7.17 (https://github.com/actions/setup-python/issues/682). This Pr is a temporary fix till the github action issue got fixed.
In this PR, we pin the python version to 3.7.16 for macos.

chore: temporary pin python version to 3.7.16

---

requirements/base.txt
requirements/reproducible-linux.txt
requirements/reproducible-mac.txt

#5365
Using an older version of `cfn-lint` caused validate to not recognize `ruby3.2` as a valid runtime for Lambdas.
Bump the version of `cfn-lint` from `~=0.77.5` to `~=0.77.9`.
None.

chore: Updated cfn-lint to support ruby3.2 in validate

---

samcli/cli/cli_config_file.py
tests/integration/buildcmd/build_integ_base.py
tests/integration/buildcmd/test_build_samconfig.py
tests/integration/deploy/deploy_integ_base.py
tests/integration/deploy/test_deploy_command.py
tests/integration/testdata/buildcmd/samconfig/samconfig.json
tests/integration/testdata/buildcmd/samconfig/samconfig.toml
tests/integration/testdata/buildcmd/samconfig/samconfig.yaml
tests/integration/testdata/buildcmd/samconfig/template.yaml
tests/unit/cli/test_cli_config_file.py

To ensure the functionality of `samconfig` remains accurate given its new changes, new integration tests have been added to `buildcmd` to confirm that the config file is written to and read accurately, regardless of its extension. In addition, guided deploy integration tests previously weren't verifying that the config file was being written, so they have been fixed.
New integration tests have been added under `test_build_samconfig.py` to ensure that the config file is used regardless of extension, that parameters are overwritten correctly, and that the config files of the correct priority are selected. In addition, a new helper method has been added to `DeployIntegBase` to assert that the attributes of the `samconfig` file are set to be certain expected values.
This change adds new …

feat: Add and fix samconfig integration tests

---

tests/integration/delete/test_delete_command.py

N/A
To remove two unneeded test cases due to PR #5360 
More context: changes in PR #5360 now requires region to be specified via `--region`, env var or aws profile. As such, unit test has been updated to make sure error with right messages is thrown in case no region or no creds can be resolved by boto3. Thus there is no need to keep the two integration test cases in this PR.
Remove two test cases
no

Remove unneeded test cases

---

samcli/commands/_utils/experimental.py
samcli/commands/local/start_api/cli.py
samcli/hook_packages/terraform/hooks/prepare/translate.py
samcli/lib/providers/api_collector.py
tests/unit/hook_packages/terraform/hooks/prepare/test_translate.py

N/A
Fix the issues that came up during the Terraform `sam local start-api` bug bash.
- Fixes bug where apply warning message was not printed in the correct colour.
- Change `start-api` command to not print next command suggestions if `--hook-name` is provided.
- Fixes the random characters printed during the beta features warning.
N/A

fix: Bug Bash UX Issues

---

appveyor-ubuntu.yml

Added `--allow-releaseinfo-change` for `apt-get update` and `apt update` commands to fix recent issues.
Tested with dev canaries as it is passing these commands successfully
https://ci.appveyor.com/project/AWSSAMCLI/aws-sam-cli-canary-linux-dev/builds/47363646

chore: fix issues with appveyor ubuntu setup

---

samcli/lib/config/samconfig.py

Previously, the info message displayed when there was no config file in the given repository had implications that one would be created. This is not always the case, making the message itself misleading.
This change removes the additional sentence that a new `samconfig` file is being created, preventing confusion on the user's end.
The output message of the function is different, and less misleading.

feat: Fix message when no config file is found

---

samcli/lib/utils/osutils.py
samcli/lib/utils/stream_writer.py
samcli/local/docker/container.py
samcli/local/docker/lambda_image.py
samcli/local/docker/manager.py
tests/integration/local/invoke/test_integrations_cli.py
tests/unit/lib/utils/test_osutils.py
tests/unit/lib/utils/test_stream_writer.py
tests/unit/local/docker/test_lambda_image.py
tests/unit/local/docker/test_manager.py

Revert "fix(invoke): Write in UTF-8 string instead of bytes."

---

.github/workflows/validate_pyinstaller.yml
tests/sanity-check.sh

N/A
The script is mainly used for sanity-checking artifacts during release. It's also beneficial to use the same script in the PyInstaller Validation GHA as part PR checks.
- tests/sanity-check.sh does two things: 1/ version check against the version fetched from master branch, 2/ perform `sam init` -> `sam build` -> `sam validate` as a basic sanity check. Note that 1 is only needed during a release. It is skipped in the PyInstaller GHA, in nightly release, or in dev mode.
No

Add sanity check script and use it in pyinstaller GHA

---

samcli/cli/context.py
samcli/commands/_utils/options.py
samcli/commands/package/command.py
samcli/commands/package/core/command.py
samcli/commands/package/core/formatters.py
samcli/commands/package/core/options.py
tests/unit/cli/test_context.py
tests/unit/commands/package/core/test_command.py
tests/unit/commands/package/core/test_formatter.py
tests/unit/commands/package/core/test_options.py

* Better help text for `sam package`
* better UX
* Screenshot below
* N/A

fix: add a table for package help text.

---

samcli/lib/config/file_manager.py
tests/integration/buildcmd/test_build_samconfig.py
tests/integration/testdata/buildcmd/samconfig/samconfig.yml
tests/unit/lib/samconfig/test_file_manager.py
tests/unit/lib/samconfig/test_samconfig.py

As of now, the `SamConfig` class has already been overhauled to decouple it from TOML logic. In addition, we have already implemented YAML support. Thus, there is no reason to immediately add on several additional filetypes with these changes until we can be assured they work correctly.
Any JSON samconfig references, including the mapping and unit tests, have been either commented out or skipped. In addition, integration tests that referenced a `samconfig.json` file have been updated accordingly.
JSON config files will no longer be supported.

feat: Disable samconfig.json support

---

tests/integration/deploy/test_deploy_command.py
tests/unit/lib/samconfig/test_file_manager.py

Previously, some canary tests were failing due to samconfig changes. 
The failing deploy integration test has been updated to better reflect the new nature of samconfig. In addition, the `FileManager` tests have been updated to include checks for array-parameter support for parameters like `image-repositories`.
One of the deploy integration tests, as well as each `FileManager`'s initial read test, have been updated to better reflect new changes.

feat: Repair and refine tests

---

samcli/lib/bootstrap/companion_stack/companion_stack_manager.py
samcli/lib/deploy/deployer.py
samcli/lib/package/artifact_exporter.py
samcli/lib/package/code_signer.py
samcli/lib/package/packageable_resources.py
samcli/lib/package/s3_uploader.py
samcli/lib/package/utils.py
samcli/lib/utils/s3.py
tests/end_to_end/test_stages.py
tests/unit/lib/bootstrap/companion_stack/test_companion_stack_manager.py
tests/unit/lib/package/test_artifact_exporter.py
tests/unit/lib/utils/test_s3.py

N/A
Fixing circular dependency which happens during E2E tests;
```
E   ImportError: cannot import name 'S3Uploader' from partially initialized module 'samcli.lib.package.s3_uploader' (most likely due to a circular import) 
```
By moving `parse_s3_url` to a new module under `utils`.
N/A

fix: remove circular dependency by moving parse_s3 method to its own util file

---

.github/workflows/build.yml

This PR to revert back to use the latest Python version as this issue https://github.com/actions/setup-python/issues/682 got fixed in Python Setup github action.

chore: use latest python version

---

appveyor-windows.yml

This PR to use the amazon ecr credential helper in windows appveyor to fix the following error we received in windows canaries:
```
Logging in Public ECR 
Error saving credentials: error storing credentials - err: exit status 1, out: `error storing credentials - err: exit status 1, out: `The stub received bad data.``
```
It got tested in Dev canaries https://ci.appveyor.com/project/AWSSAMCLI/aws-sam-cli-canary-windows-dev

chore: use amazon ecr credential helper in windows appveyor

---

samcli/lib/build/bundler.py
tests/end_to_end/test_runtimes_e2e.py
tests/end_to_end/testdata/esbuild-datadog-integration/main.js
tests/end_to_end/testdata/esbuild-datadog-integration/template.yaml
tests/unit/lib/build_module/test_bundler.py

#5429
Fixes an issue where customers who wrap their Lambda function handlers with a layer using esbuild are not able to invoke their functions.
Skips updating the esbuild function handler path if it is a layer path.
N/A

fix: Handler path mapping for layer-wrapped esbuild functions

---

tests/end_to_end/end_to_end_base.py
tests/end_to_end/test_runtimes_e2e.py

N/A
Canaries are breaking because a new E2E test uses a test data directory that isn't found.
The test currently uses a relative path that doesn't work when the test is run from the root directory. This change makes the `testdata` directory relative to the test file instead of the execution directory.
N/A

fix: E2E test can't find test data directory

---

installer/pyinstaller/build-linux.sh
installer/pyinstaller/build-mac.sh

N/A
- To add an extra check to ensure no conflicts between any installed dependency after running `pip install` and before building the installer artifact. 
- To explicitly print executed commands within the build script
- run `pip check` after all `pip install` commands
- update `set -eu` to `set -eux`
N/A

add pip check after all pip install in pyinstaller scripts

---

schema/schema.py

In order for SAM CLI parameters to be read correctly in the schema, they must be parsed in a certain format.
Instead of formatting into an arbitrary dictionary, the parameters are parsed into JSON schema keywords. In addition, some other schema generation methods have been set up.
The parameters that are parsed use different keys.

feat: Parse parameters into JSON schema objects

---

samcli/commands/local/lib/swagger/parser.py
tests/unit/commands/local/lib/swagger/test_parser.py

None
Using a float as a version for the document body (eg. `swagger: 2.0`) is a valid format. Currently, the parser expects versions to be a string.
Casts the float (or any value for that matter), into a string.
None.

fix: Relax document version check for authorizers

---

samcli/commands/local/cli_common/invoke_context.py
samcli/lib/package/ecr_uploader.py
samcli/lib/utils/stream_writer.py
samcli/local/apigw/local_apigw_service.py
samcli/local/lambda_service/local_lambda_invoke_service.py
samcli/local/services/base_local_service.py
tests/unit/commands/local/cli_common/test_invoke_context.py
tests/unit/local/services/test_base_local_service.py

Related to https://github.com/aws/aws-sam-cli/pull/5427
N/A
With recently changed the way to write into stream to fix some issues related to encoding (see PR above). That changed caused some issues with ECRUpload class, due to discrepancy of the `write` method between `BytesIO` vs `StringIO`. `BytesIO` instance accepts byte array where `StringIO` accepts string.
This resolves issue by using `StringIO` stream instead of `BytesIO`. This PR also adds some typing for the inner `stream` instance of the `StreamWrapper` class to check for other usages in the code base.
Manually running `sam local` tests to validate the change. …

fix: use StringIO instead of BytesIO with StreamWriter

---

requirements/base.txt

`typing_extensions` is a dependency of many libraries and projects, notably including `aws-lambda-powertools`. The tilde syntax used as a dependency here hinders updating other packages, but limiting minor versions isn't necessary to fulfill the requirement mentioned in the pre-existing comment (about the need to support Protocol).
This allows greater versions of `typing_extensions` to be installed by users of `aws-sam-cli`.
I recommend reconsidering all tilde requirements to see if they really need to be so limited. I haven't changed them myself to keep the scope of the PR limited and hopefully let it be merged faster, as my team constantly runs into issues updating dependencies due to `aws-sam-cli` and its `typing_extensions` limitation.
No breaking changes should be introduced in minor …

Allow greater versions of typing_extensions

---

requirements/base.txt

Pin click until the linting issues are addressed on their end.
Tracking https://github.com/pallets/click/pull/2565

fix: Pin click to be < 8.1.4 temporarily

---

samcli/commands/local/cli_common/invoke_context.py
samcli/commands/remote/remote_invoke_context.py
samcli/lib/docker/log_streamer.py
samcli/lib/package/ecr_uploader.py
samcli/lib/package/s3_uploader.py
samcli/lib/utils/osutils.py
samcli/lib/utils/stream_writer.py
samcli/lib/utils/subprocess_utils.py
samcli/local/apigw/local_apigw_service.py
samcli/local/docker/container.py
samcli/local/docker/lambda_image.py
samcli/local/docker/manager.py
samcli/local/lambda_service/local_lambda_invoke_service.py
samcli/local/services/base_local_service.py
tests/integration/local/invoke/test_integrations_cli.py
tests/unit/commands/local/cli_common/test_invoke_context.py
tests/unit/lib/utils/test_osutils.py
tests/unit/lib/utils/test_stream_writer.py
tests/unit/lib/utils/test_subprocess_utils.py
tests/unit/local/docker/test_container.py
tests/unit/local/docker/test_lambda_image.py
tests/unit/local/docker/test_manager.py
tests/unit/local/services/test_base_local_service.py

None.
Windows uses a different encoding to encode their streams and will fail if a different encoding is fed into it (eg. `utf-8`).
Reverts commit #5485 and #5427.
None.

fix: Revert UTF-8 fixes #5485 and #5427

---

samcli/lib/build/bundler.py
tests/unit/lib/build_module/test_bundler.py

Windows paths contain an escape backslash (`\\`). This needs to be turned into a POSIX path before being parsed/saved into the template file.
Makes sure that the string path from the helper method is a POSIX path (`/` instead of `\\`) before parsing.
None.

fix: Convert paths to POSIX paths before checking in esbuild handling logic

---

Makefile
installer/pyinstaller/build-linux.sh
installer/pyinstaller/build-mac.sh

Related:
https://github.com/yaml/pyyaml/issues/724
https://github.com/aws/aws-sam-cli/pull/5494
https://github.com/aws/homebrew-tap/pull/491
`cython` is breaking the `PyYAML` building process when building from source.
Enforces a lower `cython` version to specifically build `PyYAML` before uninstalling `cython` and processing with the rest of the step.

fix: Pin cython to a version that is less than 3.0.0

---

samcli/lib/remote_invoke/lambda_invoke_executors.py
samcli/lib/remote_invoke/stepfunctions_invoke_executors.py

#5566 
`mypy_boto3_lambda` which is used for type checking purposes breaks the command. `boto3-stubs` is a dev dependency and not included in the prod dependencies.
Adds a condition to only import this for type checking.

fix: Add type checking on condition for mypy-boto3

---

requirements/base.txt
samcli/commands/publish/command.py
samcli/vendor/serverlessrepo/__init__.py
samcli/vendor/serverlessrepo/application_metadata.py
samcli/vendor/serverlessrepo/exceptions.py
samcli/vendor/serverlessrepo/parser.py
samcli/vendor/serverlessrepo/publish.py
tests/integration/publish/test_command_integ.py
tests/unit/commands/publish/test_command.py
tests/unit/vendor/serverlessrepo/test_application_metadata.py
tests/unit/vendor/serverlessrepo/test_parser.py
tests/unit/vendor/serverlessrepo/test_publish.py

https://github.com/aws/aws-sam-cli/issues/5569
To remove our dependency on `serverlessrepo` which is an archived project that is no longer being updated, and is causing issues because of its outdated dependencies.
Vendors the components of `serverlessrepo` that AWS SAM CLI uses.

chore: Vendor serverlessrepo to remove dependency

---

samcli/commands/local/cli_common/invoke_context.py
samcli/commands/local/invoke/cli.py
samcli/commands/local/start_api/cli.py
samcli/commands/local/start_lambda/cli.py
samcli/local/docker/container.py
samcli/local/docker/exceptions.py
tests/unit/commands/local/invoke/test_cli.py
tests/unit/commands/local/start_api/test_cli.py
tests/unit/commands/local/start_lambda/test_cli.py
tests/unit/local/docker/test_container.py

#5346 
When debugging port is provided as `-d` option and the port is already in use, `sam cli` throws a trace error.
This PR handles the above exception gracefully with the following message `Ports are not available: exposing port TCP 127.0.0.1:<port_num> -> 0.0.0.0:0: listen tcp 127.0.0.1:<port_num>: bind: address already in use.`
N/A

fix: Graceful error handling for port already in use

---

.github/labeler.yml

None.
Changes to the new schema folder are not being auto labeled due to the missing entry in the labeller workflow.
Adds a check to apply the `area/schema` label to schema related changes in the schema folder.
None.

chore: Added schema auto label to actions

---

samcli/commands/deploy/command.py
samcli/commands/package/command.py
samcli/commands/sync/command.py
samcli/lib/cli_validation/image_repository_validation.py
tests/unit/lib/cli_validation/test_image_repository_validation.py

#5424
Error messages for `sam package` and `sam sync` includes possible option `--resolve-image-repos` which is not supported for these commands.
By removing it from error messages for these commands.
N/A

fix: remove resolve-image-repos error message from the commands it is not supported

---

requirements/base.txt
requirements/dev.txt
requirements/reproducible-linux.txt
requirements/reproducible-mac.txt
samcli/__init__.py
samcli/lib/bootstrap/companion_stack/companion_stack_manager.py
samcli/lib/remote_invoke/lambda_invoke_executors.py
samcli/lib/remote_invoke/stepfunctions_invoke_executors.py

`boto3-stubs` is a dev dependency and to use the boto3 objects for type checking, they need to be imported conditionally. If the import is not conditional, it can break production installers as the testing uses dev-dependencies and this can get missed.
This PR moves `boto3-stubs` to base.txt for making the boto3 type checks more sustainable. I built a mac binary with the new changes and tested the functionality for `remote invoke` and `sam deploy` companion stack and it works as expected.
N/A

chore: Move boto3-stubs dependency from dev.txt to base.txt

---

samcli/lib/package/local_files_utils.py
tests/integration/delete/test_delete_command.py
tests/integration/testdata/package/aws-s3-with-lang-ext.yaml
tests/unit/lib/package/test_local_files_utils.py

#5254
`sam delete` command removes CFN stack, with its template which was used to deploy the stack itself. In order to find its location, `sam delete` command downloads the original template and gets its hash to calculate its S3 location (as it is done in `sam package`/`sam deploy` commands). However this creates some issues on Windows machines as writing to a temporary file and calculating its hash gets a different result, since python does some extra line ending conversion which ends up with extra lines comparing to original template.
This PR changes the way we calculate the hash of the template. Instead of writing to a temporary file and calculating its hash, this gets the hash of the contents of the template, which eliminates the behaviour above.
N/A
This code branch is only used with …

fix: calculate hash of a file with given contents without writing to a  tmp location

---

samcli/lib/utils/preview_runtimes.py

- To remove packaging warning messaging for Python3.11 
- Removes the runtime from the list of preview runtimes.
n/a

feat: remove packaging warning messaging for python3.11.

---

samcli/lib/cli_validation/image_repository_validation.py
tests/integration/package/test_package_command_image.py

fix the failing package integration test cases by updating the assert expression.

fix: update the error message in the integration testing

---

samcli/cli/types.py
schema/make_schema.py
schema/samcli.json
tests/unit/schema/test_schema_logic.py

Since the SAM CLI uses custom types without names, we had to create a constant to map the name of the parameter to its set of possible values. This creates additional overhead when creating new custom parameter types.
The `name` fields of each of these types have now been populated, and as such, they are able to be read by the schema parser. This means we can include the expected type (or types) of the parameter to be read.
The `name` field of each SAM CLI custom type has been populated instead of being an empty string (not that it was being used to begin with).

fix: Add type names to custom parameter types

---

samcli/lib/config/exceptions.py
tests/integration/buildcmd/test_build_samconfig.py

Previously, if a config file is provided without a supporting extension, a stack trace is thrown rather than just an error. This prompts the user to open an issue, which they should not do, since it is not something we can immediately address.
The `SamConfigFileReadException` class has been changed from inheriting from `Exception` to inheriting from `UserException`. That way, it is caught properly and is passed through the correct channels.
Any `SamConfigFileReadException` exceptions that are raised no longer prompt the user to open an issue about it

fix: Prevent stack trace when incorrect filetype is passed as config

---

schema/make_schema.py

While the schema was being created, it was generated in pieces to make reviewing it easier, and less prone to errors in generation. Now that the schema is fully generated and approved of, we no longer need this additional logic.
Any logic the schema previously implemented to exclude certain commands from appearing has been removed.
N/A

feat: Remove exclusionary logic from schema generation

---

.github/workflows/pr-labeler.yml

None
If the file labeller is ran after the maintainers labeller job, the file labels will replace the existing labels instead of appending them.
Requires that that the file labeling job runs before the maintainer job.
None.

fix: Require file label to run before maintainers

---

samcli/commands/local/cli_common/invoke_context.py
samcli/commands/remote/remote_invoke_context.py
samcli/lib/docker/log_streamer.py
samcli/lib/package/ecr_uploader.py
samcli/lib/package/s3_uploader.py
samcli/lib/utils/osutils.py
samcli/lib/utils/stream_writer.py
samcli/lib/utils/subprocess_utils.py
samcli/local/apigw/local_apigw_service.py
samcli/local/docker/container.py
samcli/local/docker/lambda_image.py
samcli/local/docker/manager.py
samcli/local/lambda_service/local_lambda_invoke_service.py
samcli/local/services/base_local_service.py
tests/integration/local/invoke/test_integrations_cli.py
tests/unit/commands/local/cli_common/test_invoke_context.py
tests/unit/lib/utils/test_osutils.py
tests/unit/lib/utils/test_stream_writer.py
tests/unit/lib/utils/test_subprocess_utils.py
tests/unit/local/docker/test_container.py
tests/unit/local/docker/test_lambda_image.py
tests/unit/local/docker/test_manager.py
tests/unit/local/services/test_base_local_service.py

#5229
See: https://github.com/aws/aws-sam-cli/pull/5427
t appears that we were using sys.stdout.buffer to support python2 and python3 at the same time. Switching to just write to sys.stdout allows us to write a utf-8 encoding string. When using sys.stdout.buffer, we can only write bytes and I couldn't get the correct UTF8 encoded string to print correctly.
This commit adds additional typing to help ensure things are working as expected using static analysis by mypy.
In addition, this fixes an issue found in the last revert where on windows the stream was not set to utf8 causing issues when writing a utf8 string.
Shouldn't …

fix(invoke): Write in UTF-8 string instead of bytes

---

tests/integration/local/invoke/test_integrations_cli.py

None
Forcing reading a utf8 file in utf8 which caused integration tests to fail on windows
Enforces reading the encoding correctly
Shouldn't have any.

fix(test): Force reading file with utf8 in tests for windows

---

tests/integration/local/invoke/test_integrations_cli.py

none
Occasional tests would fail with just over 20s for out max duration when timeout is set on Windows. This change adjusts that time period from 20s to 25
Updates the timeout in the test assert
None

fix(test): Increase max execution time for timeout tests

---

tests/integration/deploy/test_deploy_command.py

The integration test was failing.
Since we know the test passes if it notifies the user of the error produced when reading the config file, we can forgo trying to test for the full, exact output, and just ensure that the user is notified of the error when parsing the file.
The integration test will now pass.

fix: Repair failing integration test

---

samcli/hook_packages/terraform/hooks/prepare/resource_linking.py
samcli/hook_packages/terraform/hooks/prepare/resources/resource_links.py
tests/integration/local/start_api/test_start_api_with_terraform_application.py
tests/integration/testdata/start_api/terraform/terraform-v1-nested-apis/main.tf
tests/unit/hook_packages/terraform/hooks/prepare/test_resource_linking.py

follow up on PR https://github.com/aws/aws-sam-cli/pull/5697 to fix issue https://github.com/aws/aws-sam-cli/issues/5639
Customers are not able to run SAM CLI commands on Terraform projects that contains nested V1 APIs definition
It allowed the following resources to be linked to multiple destinations (Rest API, and Gateway Resource):
-  aws_api_gateway_method
-  aws_api_gateway_integration
- aws_api_gateway_method_response
N/A

fix: supporting nested apis for v1 method, integration, and integration response resources.

---

tests/integration/delete/test_delete_command.py

None
The integration test was stuck on Linux machines due to the process waiting for a prompt that never appears when running the `deploy` commands as a persistent command.
Uses the existing `--no-execute-changeset` flag to create a change set and exit, instead of waiting for the prompt and killing the process.
None.

fix(test): Don't execute change set instead of waiting for prompt

---

samcli/hook_packages/terraform/hooks/prepare/hook.py
samcli/lib/hook/exceptions.py
samcli/lib/utils/subprocess_utils.py
tests/unit/hook_packages/terraform/hooks/prepare/test_hook.py
tests/unit/lib/utils/test_subprocess_utils.py

N/A
Prompt users to use the Terraform Cloud workaround when they encounter the TFC error.
1. Fixes the loading dot subprocess loader to store and return data from stderr
2. Reads the stderr data, checking for the TFC error message and returns an appropriate help message if found.
N/A

feat: Prompt users to use TFC workaround

---

samcli/commands/_utils/custom_options/hook_name_option.py
samcli/commands/_utils/options.py
tests/integration/buildcmd/test_build_terraform_applications_other_cases.py
tests/integration/testdata/buildcmd/terraform/application_outside_root_directory/root_module/input_samconfig.yaml
tests/unit/commands/_utils/custom_options/test_hook_package_id_option.py

During testing I found that we ignore reading Terraform hooks parameters like (`--terraform-project-root-path` or `--terraform-plan-file`) from the sam config file.
I fixed this part to get the hook parameters from both command options, and if not in this list, we try to get it from the config file.
I also added the option `--prepare-infra` so customers can set in the default behaviour in config file to skip the infrastructure preparation, and if needed they can overwrite that behaviour by using the new option `--prepare-infra`

fix: read terraform hook parameters from samconfig file

---

appveyor-linux-binary.yml
appveyor-ubuntu.yml
appveyor-windows-binary.yml
appveyor-windows.yml

adding python 3.11 to path in appveyor jobs to fix the failing integration test case https://ci.appveyor.com/project/AWSSAMCLI/aws-sam-cli-canary-linux/build/job/x4neogmjss3hdf6k#L19679.

fix: add python 3.11 to path in appveyor jobs

---

samcli/local/docker/container.py
tests/integration/local/invoke/test_integrations_cli.py
tests/integration/testdata/invoke/main.py
tests/integration/testdata/invoke/template.yml

#5766
to allow customer test lambda functions that does not return any response.
skip parsing the container response as JSON object if there is no response.
N/A

fix: fix processing lambda container response if nothing returned

---

appveyor-linux-binary.yml
appveyor-ubuntu.yml
appveyor-windows-binary.yml
appveyor-windows.yml

fix the failing Local commands integration test cases due that terraform is missed.

fix: adding terraform to local commands integration testing job

---

samcli/local/docker/lambda_image.py

Some customers got the following exception, when they execute `sam local invoke` command
```
Error: list index out of range
Traceback:
File "click/core.py", line 1055, in main
File "click/core.py", line 1657, in invoke
File "click/core.py", line 1657, in invoke
File "click/core.py", line 1404, in invoke
File "click/core.py", line 760, in invoke
File "click/decorators.py", line 84, in new_func
File "click/core.py", line 760, in invoke
File "samcli/lib/telemetry/metric.py", line 184, in wrapped
File "samcli/lib/telemetry/metric.py", line 149, in wrapped
File "samcli/lib/utils/version_checker.py", line 42, in wrapped
File "samcli/cli/main.py", line 95, in wrapper
File "samcli/commands/local/invoke/cli.py", line 100, in cli
File "samcli/commands/local/invoke/cli.py", line 206, in do_cli
File …
```

fix: handle index error if the image info returned from docker client contains any empty list for `RepoDigests` attribute

---

samcli/local/apigw/authorizers/lambda_authorizer.py
tests/integration/local/start_api/lambda_authorizers/test_swagger_authorizer_definitions.py
tests/integration/testdata/start_api/lambda_authorizers/swagger-api.yaml
tests/unit/local/apigw/test_lambda_authorizer.py

Update the matching logic to permit a wildcard to match an empty string. This allows a wildcard resource statement to match the root URL, which mimics the real behaviour of API Gateway.
#5777 
Details on the issue
None

fix: Local lambda authorizer ARN matching

---

samcli/hook_packages/terraform/copy_terraform_built_artifacts.py
samcli/hook_packages/terraform/hooks/prepare/hook.py
samcli/lib/hook/exceptions.py
tests/integration/buildcmd/test_build_terraform_applications_other_cases.py
tests/unit/hook_packages/terraform/hooks/prepare/test_hook.py

None.
Validates that the environment variables that are passed in when running commands do not override anything we define or set.
Checks if the environment variables contain blocked arguments. If they do, exit and display a message letting the user know to omit them.
This check happens in both the Makefile script and the prepare hook logic.
None.

feat: Added environment variable validation for Terraform arguments

---

samcli/commands/remote/invoke/cli.py
tests/unit/commands/remote/invoke/test_cli.py

#5820 
`sam remote invoke` missed to honor to provided `--profile` option.
pass in provided profile into relevant boto3 client/resource providers
No

Fix sam remote invoke to take profile properly

---

samcli/lib/providers/provider.py
samcli/local/apigw/local_apigw_service.py
tests/integration/local/start_api/test_start_api.py
tests/unit/local/apigw/test_local_apigw_service.py

This PR is to add some missing logic to this PR https://github.com/aws/aws-sam-cli/pull/5619 that was merged to fix this issue https://github.com/aws/aws-sam-cli/issues/4161
The previous PR fixed the CORS handling for the HTTP API gateway where the CORS headers changes based on the request origin header. But, for REST API resources, CORS Headers will always return as defined in the ResponseParameters configuration of the method integration resource.
In this PR, I update the `cors_to_headers` method to accept the `event_type` parameter, so we can determine if this route is defined in a Http Api, or Rest Api, then we can return the CORS Headers based as expected for each type.
I also updated the integration and unit test cases to test both resource types.
**PRs will only be reviewed after …

fix: fix CORS handling for REST API.

---

samcli/commands/_utils/custom_options/hook_name_option.py
tests/unit/commands/_utils/custom_options/test_hook_package_id_option.py

N/A
There is a bug where the hook package is executed even if the customer provides a help text flag.
Add an additional condition to avoid running the hook if the help text option is provided.
N/A

fix: Don't run hook if help text option is provided

---

samcli/hook_packages/terraform/hooks/prepare/hook.py
tests/integration/local/start_lambda/test_start_lambda_terraform_applications.py

Link out to the Terraform Cloud documentation if a user runs into the Terraform Cloud exception.

feat: Add link to TF Cloud documentation

---

samcli/local/docker/container.py
tests/unit/local/docker/test_container.py

#5799 
In some rare occasion, RIE response cannot be deserialized by `json.loads`, resulting in `JSONDecodeError`
Handle `JSONDecodeError`, and update `stdout` to write response with `write_str` or `write_bytes` based on response type.
No

Fix handling of non-json-deserializable response from RIE

---

tests/integration/sync/test_sync_watch.py

None.
Testing folder and data was not being cleaned between test runs if the test were to fail and be retried.
Updates the set up and tear down methods of the test watch base class to delete the contents of the previous test run before restarting the test.
None.

fix(tests): Clean up test data folder between runs

---

samcli/commands/build/build_context.py
samcli/lib/telemetry/event.py
tests/unit/commands/buildcmd/test_build_context.py

None.
There is currently no indicators that a project used the building in source feature.
Adds a new `UsedFeature` event to track build in source usages. This is done by only sending the event if the build in source click option was passed in.
None

feat: Added event tracking for feature

---

appveyor-ubuntu.yml
appveyor-windows.yml

Change appveyor threads

---

samcli/lib/samlib/resource_metadata_normalizer.py
tests/unit/lib/samlib/test_resource_metadata_normalizer.py

#5901
When using value references in yaml file, the objects that is been created are the same instance. For that reason, changing one value from one instance will also affect the other instances.
The behaviour above causes issues when updating/normalizing resource metadata information. With that, we are adding `SamResourceId` information, but if `Metadata` information is been shared between resources, then it updates for all of them, which creates issues down the road when we are extracting functions.
This change copies metadata before starting changes, and assigns it back once it is finalized, so that it won't affect all of the references.
N/A
By submitting this pull request, I confirm that my contribution is made under the terms …

fix: copy resource metadata before normalizing the information in it

---

.github/workflows/build.yml
samcli/__init__.py
samcli/local/docker/container.py
tests/integration/buildcmd/test_build_cmd.py
tests/integration/local/invoke/test_integrations_cli.py
tests/testing_utils.py

N/A
After updating `sam local` commands to use the RIE in version 1.13.1, when a stack trace is streamed from the emulation container it contains carriage return characters that then don't get displayed by the stream writer.
Replaces the carriage return characters with the system's linesep character.
Will display addition logs when using local invoke commands that contain a stack trace.
Before:
```
Mounting C:\Users\Administrator\ws\sam-app\.aws-sam\build\HelloWorldFunction as /var/task:ro,delegated, inside runtime container
START RequestId: 06dd2e5e-af4c-47b0-b893-a9979544e244 Version: $LATEST
"body": son.dumps({y", line 38, in lambda_handler
END RequestId: 06dd2e5e-af4c-47b0-b893-a9979544e244
REPORT RequestId: 06dd2e5e-af4c-47b0-b893-a9979544e244  Init Duration: 0.15 ms  Duration: …
```

fix: Invoke stderr stream missing stack trace

---

samcli/lib/utils/git_repo.py
tests/unit/lib/utils/test_git_repo.py

https://github.com/aws/aws-sam-cli/issues/5983
When checking `git` executable, SAM CLI raises `OSError` which causes hard fail.
This replaces `OSError` with a custom one which extends from `UserError`. This will display a better warning message rather than splitting the whole exception trace.
N/A

fix: gracefully handle when git executable can't be found

---

tests/integration/remote/test_event/remote_test_event_integ_base.py
tests/integration/remote/test_event/test_remote_test_event.py

Some integration tests failed in determined circumstances 
Only "assert" for the error message. Clean up schema for test events at the beginning of the tests. 

fix: Fix integration tests for remote test events

---

tests/integration/remote/test_event/test_remote_test_event.py

Fix Win integ tests for remote test events
- Line separator in Windows is different

fix: Fix Win integ tests for remote test events

---

tests/integration/remote/test_event/remote_test_event_integ_base.py

N/A
Some `sam init` integ tests were failing as a new schema registry `lambda-testevent-schemas` was created from `sam remote test-event` command and the order of input for selecting schema changed. . This PR cleans up `lambda-testevent-schemas` registry after `remote test-event` integ tests are completed.
For reference: https://ci.appveyor.com/project/AWSSAMCLI/aws-sam-cli-canary-linux/builds/48180259/job/sc6fyg77aimxuykb?fullLog=true
As mentioned above.
No side effects.

fix: Clean up lambda-testevent-schemas registry for remote test-event integ tests

---

samcli/lib/bootstrap/companion_stack/companion_stack_manager.py
samcli/lib/utils/managed_cloudformation_stack.py

When we deploy the managed stack and SAM CLI deploys the stack, if there is no region found we state to set the AWS_REGION. Boto3 only reads the AWS_DEFAULT_REGION, causing customer confusion
None
Updates the output of an error to be accurate.
Updates the output of an error to be accurate.
None

fix: Boto3 reads AWS_DEFAULT_REGION not AWS_REGION

---

tests/integration/testdata/sync/infra/after/Ruby/function/Gemfile
tests/integration/testdata/sync/infra/after/Ruby/layer/Gemfile
tests/integration/testdata/sync/infra/before/Ruby/function/Gemfile
tests/integration/testdata/sync/infra/before/Ruby/layer/Gemfile
tests/integration/testdata/sync/infra/template-ruby-after.yaml
tests/integration/testdata/sync/infra/template-ruby-before.yaml

N/A
Update ruby version 3.2 to match with integration test environment for `sam sync` tests.

chore: fix sync integration tests with ruby

---

samcli/lib/build/app_builder.py
tests/unit/lib/build_module/test_app_builder.py

- For `build` with `--use-container` and `--build-image`
https://github.com/aws/aws-sam-cli/issues/6023
Gracefully fail and not throw a traceback

fix: gracefully exit on not finding a local image

---

requirements/base.txt
requirements/reproducible-linux.txt
requirements/reproducible-mac.txt
requirements/reproducible-win.txt

N/A
This change is necessary to add kinesis boto3 stubs which will be used for remote invoke Kinesis streams. The GitHub action that runs and validates reproducible does not run on PRs created from forked branches. This change is necessary for the PR https://github.com/aws/aws-sam-cli/pull/6063/
Adds kinesis boto3-stub dependency
N/A

chore: Add kinesis dependency to boto3-stubs in base.txt

---

tests/integration/remote/invoke/remote_invoke_integ_base.py
tests/integration/remote/invoke/test_remote_invoke.py
tests/integration/testdata/remote_invoke/template-kinesis-priority.yaml
tests/integration/testdata/remote_invoke/template-multiple-resources.yaml

N/A
This PR adds integration tests for sam remote invoke for Kinesis service. The tests have been disables until the support for the service is available.
Tests run locally:
```
tests/integration/remote/invoke/test_remote_invoke.py::TestSingleLambdaInvoke::test_invoke_asynchronous_using_boto_parameter@sam_remote_invoke_single_lambda_resource 
tests/integration/remote/invoke/test_remote_invoke.py::TestSFNPriorityInvoke::test_invoke_boto_parameters@sam_remote_invoke_sfn_resource_priority 
tests/integration/remote/invoke/test_remote_invoke.py::TestKinesisPriorityInvoke::test_invoke_boto_parameters@sam_remote_invoke_kinesis_resource_priority 
tests/integration/remote/invoke/test_remote_invoke.py::TestSQSPriorityInvoke::test_invoke_boto_parameters@sam_remote_invoke_sqs_resource_priority 
[gw1] …
```

test: Add integration tests for running remote invoke on kinesis service

---

tests/integration/buildcmd/test_build_cmd.py

Reverts tests that were temporarily skipped on GitHub actions as Lambda Builders failed to find a python3.9 executable with pip. 
Issue is resolved by https://github.com/aws/aws-lambda-builders/pull/549
This PR can be merged once the `aws_lambda_builders==1.39.0` version bump is merged into AWS SAM CLI.

chore: Revert temporarily skipped tests

---

tests/integration/buildcmd/test_build_in_source.py

None.
The build command's build in source tests were disabled back then since the Click option for build in source was not created yet.
Removes the skip decorator that skips the integration tests from running and repairs the broken template link.
None

chore(tests): Enable build tests

---

appveyor-linux-binary.yml
appveyor-ubuntu.yml
appveyor-windows-binary.yml
appveyor-windows.yml

N/A
This change re-groups some jobs to have a better time distribution of workers. Currently, some jobs take far longer than others leading to canaries taking much longer overall. This re-distribution of workers should decrease the total canary duration from ~2.5 hours to ~1.5 hours.

chore(test): Group jobs to better distribute runners

---

samcli/commands/deploy/deploy_context.py
samcli/lib/deploy/deployer.py
tests/unit/commands/deploy/test_deploy_context.py
tests/unit/lib/deploy/test_deployer.py

add some logs to deploy command to investigate issue # https://github.com/aws/aws-sam-cli/issues/5109
The problem in that issue is the WSL environment clock is not in sync with the actual time, it was 3 minutes ahead, and so the loop we use to describe the deployment events never ends, as it is not able to find any new events.
I updated the wait_for_execute method that wait for a change set to be executed, to take a time_stamp_marker as an extra parameter to use it to determine the events to be printed. The value of this marker will be the latest stack event if the stack exists, or 0 in case if the stack does not exist.  …

Chore: Use the latest stack event timestamp as a marker to get the new deployment events

---

appveyor-windows-binary.yml

N/A
This PR updates the appveyor config to run windows binary canaries on an built by me. The artifact can be found here https://github.com/hnnasit/aws-sam-cli/releases/tag/v1.99.0
Described above.

test: Update windows appveyor config to test on windows msi artifact

---

samcli/lib/build/build_graph.py
tests/unit/lib/build_module/test_build_graph.py

#6117 
The FunctionBuildDefinition currently does not compare handlers in the __eq__ method of the class which means if everything else is the same it'll consider the build definitions to be the same and result in only one handler being used for multiple functions.
compare handlers in the __eq__ method

fix: compare handlers when comparing build definitions

---

.github/workflows/build.yml

test: fail on purpose

---

tests/integration/local/invoke/test_integrations_cli.py

N/A
Fixes an integration test failure that started to occur due to line endings not matching on Windows with recent PR to write string instead of bytes.
Don't attempt to compare line endings since we really just care about the contents of the stack trace.
N/A

fix(test): Fix integration test failure on Windows

---

tests/integration/remote/invoke/test_remote_invoke.py
tests/integration/validate/test_validate_command.py

N/A
remote invoke tests for SQS are flaky due to the message being added back to the queue after consumption and the other tests picking up wrong messages.
cfn-lint does not support provided.al2023 yet and the `sam validate` integ test fails. Commenting it out for now.
Adds a WaitTimeSeconds parameter to poll longer until a message becomes available. Also deletes a message after consumption.

test: fix flaky remote invoke sqs tests

---

samcli/lib/utils/async_utils.py

None.
`asyncio.get_event_loop()` is being deprecated in the future. Deprecation warns are starting to appear, which will cause tests to fail since warnings are treated as errors.
Removes the call to `asyncio.get_event_loop()` as a default value for the tasks.
None.

fix: Update async utils to remove upcoming deprecated call

---

samcli/commands/local/cli_common/options.py
samcli/local/docker/container.py
samcli/local/docker/lambda_container.py
samcli/local/docker/utils.py
tests/unit/local/docker/test_utils.py

N/A
When finding available local port for binding AWS Runtime Interface Emulator, we first try to bind a local port to see if it is available. However that call is been made without providing any network interface that we are intended to.
With this change, when we are searching for available port, we are trying to bind a random port to specific host interface that is defined with `--container-host-interface` parameter of the `sam local` commands.

fic: check available port for specific/intended interface

---

samcli/lib/build/exceptions.py
samcli/lib/providers/sam_function_provider.py
tests/unit/commands/deploy/test_auth_utils.py
tests/unit/commands/local/lib/test_sam_function_provider.py
tests/unit/commands/sync/test_command.py
tests/unit/lib/bootstrap/nested_stack/test_nested_stack_manager.py
tests/unit/lib/build_module/test_bundler.py

#6253 
There is currently no validation on if the handler is defined within a template
Checks if the handler is defined before trying to access and assign it

fix: crashing if handler is missing

---

tests/functional/commands/validate/lib/models/api_with_swagger_authorizer_none.yaml
tests/smoke/templates/sar/alexa-skills-kit-nodejs-basic-welcome-template.yaml
tests/smoke/templates/sar/alexa-skills-kit-nodejs-premium-facts-skill-template.yaml
tests/smoke/templates/sar/amazon-cloudfront-access-logs-queries-template.yaml
tests/smoke/templates/sar/api-gateway-dev-portal-template.yaml
tests/smoke/templates/sar/sumologic-guardduty-events-processor-template.yaml

Refs: https://github.com/aws/aws-sam-cli/issues/6195
Lambda nodejs8.10 was deprecated on [Mar 6, 2020](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html)
Bumps AWS::Serverless::Function runtime nodejs8.10 to nodejs18.x
N/A

test: bump AWS::Serverless::Function runtime nodejs8.10 to nodejs18.x

---

samcli/lib/utils/tar.py
tests/unit/lib/utils/test_tar.py

None.
Non existent symlinks can happen if the symlink is suppose to reference something in the image, not the host machine.
Only dereference files when creating tarballs if the symlinked destinations exist.
None.

fix: Only dereference file paths if they all exist

---

samcli/lib/utils/tar.py
tests/unit/lib/utils/test_tar.py

None.
A previous fix did not check the contents of directories since the path list only contained the parent folders, not the individual files.
Recursively checks the children if the path is a folder.
None.

fix: Recursively call method on directory children

---

.github/workflows/pr-labeler.yml

Reverts aws/aws-sam-cli#6395
Labeler GHA has major version bump recently, which changed its configuration file.
But even with updating the configuration file as described in their documentation (see this PR https://github.com/aws/aws-sam-cli/pull/6411), it is still failing (see failure https://github.com/aws/aws-sam-cli/actions/runs/7122709971/job/19394326410 and related issue in GHA repo https://github.com/actions/labeler/issues/712).
This PR reverts version to v4 for now.

Revert "chore(deps): bump actions/labeler from 4 to 5"

---

samcli/local/docker/container.py
tests/unit/local/docker/test_container.py

#6173 
Currently there is an explicit 1 second sleep in the code to work around a race condition and ensure that everything that is printed to the cli is done in the correct order.
The original race condition occurs when the main thread finishes its execution and prints the flask response to stdout, while there are still some things from the docker container that need to be printed.
This can be reproduced currently by the following steps (after removing the sleep in dev version of sam)
```
1. sam init a hello world template (I did any version of node.js)
2. change the lambda code to just print something
3. samdev local start-lambda -t template.yaml
4. aws lambda invoke --endpoint http://localhost:3001 --function-name HelloWorldFunction out.txt (in a separate console)
5. repeat step 4 …
```

fix: remove 1 sec delay on invoke

---

.github/workflows/pr-labeler.yml

N/A
Note: The job is still failing as it looks like it picks up the scripts defined in the develop branch instead of the PR.
PR labeler GH action is failing due to missing `'` for `dependabot[bot]` maintainer. This change did not give errors when the PR to update the script was created as it used the older script to run the GH action.
Described above.

chore: Fix PR labeler GH action

---

samcli/lib/utils/preview_runtimes.py

- To remove packaging warning messaging for Python3.11
- Removes the runtime from the list of preview runtimes.
n/a

feat: remove packaging warning messaging for python3.12.

---

samcli/commands/local/lib/local_lambda_service.py

None.
`ssl_context` wasn't marked as optional, even though the doc string mentions that it is. This will cause errors since the other commands that use this service (`start lambda`) doesn't use this.
Marks it as optional by setting `=None`.
None.

fix: Mark ssl_context as optional in the service constructor

---

appveyor-linux-binary.yml
appveyor-ubuntu.yml

To update CI for it to be ready for testing dotnet8 runtimes (https://github.com/aws/aws-sam-cli/pull/6429)
Windows is not needed because it already has dotnet8 (https://www.appveyor.com/docs/windows-images-software/#net-framework)
Install dotnet8 sdk via apt-get

chore: install dotnet8 in CI (appveyor)

---

tests/end_to_end/test_runtimes_e2e.py

Yields some debug information for a flaky golang test. Hoping to run nightly canaries with this and use output to debug.
Add debug flag to the `sam local invoke` run that is currently occasionally failing.
Extra output in canaries for this test.

Add --debug to flaky test to get more information

---

samcli/local/docker/container.py
tests/unit/local/docker/test_container.py

#6516 
When the host directory does not exist and commands such as `sam build -u` or `sam local` commands tries to mount the directory, it throws a file not found error which crashes the commands.
The symlinks logic is skipped when the host directory does not exist.

fix: Add check for resolving symlinks when host_dir does not exist

---

tests/end_to_end/test_runtimes_e2e.py
tests/end_to_end/test_stages.py

Purposes of debugging the flaky golang test 
```
tests/end_to_end/test_runtimes_e2e.py::TestHelloWorldZipPackagePermissionsEndToEnd_0_go1_x::test_hello_world_workflow
```
Add logging for files pulled from S3, since this is a unique component of this test and there could be permission issues preventing the lambda from invoking properly.
Enable RIE debug environment variable to get more information
N/A

Add logging for files pulled from S3 + enable RIE debug for flaky test

---

samcli/local/docker/exceptions.py
samcli/local/docker/lambda_container.py
tests/unit/local/docker/test_lambda_container.py

#6558
Previously,  a Python `ValueError` was raised when an invalid runtime is specified in the template file a function. This causes a stack trace to be displayed, and the wrong error code to be emitted to customers.
Raises a new custom `UserException` error instead.
None.

fix: Raise UserException when an invalid runtime is specified

---

appveyor-ubuntu.yml

changing ruby version manager
appveyor no longer uses rvm in their image

fix: change rvm to rbenv

---

samcli/commands/local/invoke/cli.py
samcli/local/apigw/local_apigw_service.py
samcli/local/apigw/service_error_responses.py
samcli/local/docker/container.py
samcli/local/docker/exceptions.py
samcli/local/lambda_service/lambda_error_responses.py
samcli/local/lambda_service/local_lambda_invoke_service.py
samcli/local/lambdafn/runtime.py
tests/unit/commands/local/invoke/test_cli.py
tests/unit/local/apigw/test_local_apigw_service.py
tests/unit/local/lambda_service/test_local_lambda_invoke_service.py

#6510
To catch and handle docker container creation errors when running `sam local invoke`, `sam local start-api` and `sam local start-lambda`
Catch the error and propagate it to CLI

Handle docker container creation error

---

installer/pyinstaller/build-linux.sh
installer/pyinstaller/build-mac.sh
installer/pyinstaller/samcli-mac.spec
installer/pyinstaller/samcli.spec

None.
The version of `bzip2` used in the image that builds the Linux Pyinstaller artifacts are old. We need to update them to a newer version.
Builds `bzip2` from source, consuming the `1.0.8` version instead of the `1.0.6` in the image.
None

chore: Build bzip2 from source for Linux Pyinstaller builds

---

README.md

None.
Text correctness.
By adding a space.
None.

Update README.md: nitpick-fix (space missing before the dash)

---

.github/workflows/validate_pyinstaller.yml

Using MacOS14 leads to issues with python/pip not identifying the installed version of OpenSSL which causes errors when trying to install dependencies. This does not happen with MacOS13 so pinning the version to 13 to let the PR workflow pass 

fix: mac validate pyinstaller workflow to not use latest mac image

---

samcli/lib/build/app_builder.py
tests/unit/lib/build_module/test_app_builder.py

can be merged after https://github.com/aws/aws-lambda-builders/pull/640 is. Which will fix the issue of building rust lambda functions with an incorrect version of `GLIBC`

fix: pass unpatched runtime to lambda builder

---

.github/workflows/validate_pyinstaller.yml
installer/pyinstaller/build-mac.sh

our mac pyinstaller build does not specify the openssl directory so we are unable to install packages through pip

fix: use correct openssl when building python

---

appveyor-windows.yml
tests/integration/local/invoke/runtimes/test_with_runtime_zips.py
tests/integration/local/start_api/test_start_api.py

N/A
Fixes several flaky integration tests including:
1. Java21 (AL2023) test being run on Windows
2. SIgterm test failing re-runs due to reuse of UUID
3. Windows AppVeyor using invalid chocolatey cache
N/A

fix: Flaky integration tests

---

requirements/dev.txt
tests/integration/local/common_utils.py
tests/integration/local/start_lambda/test_start_lambda.py

N/A
Our E2E tests have been seeing errors in pytest with tests failing to start-up after the latest version update to 8.2.0, specifically on python3.8. I've tested with newer version of python and it seems to work fine.
There is an additional (or new) log statement that is printed when a duplicate error is encountered in a `sam local start...` test, handle retries for that case.

fix: Revert pytest update breaking e2e testing, catch duplicate port error

---

samcli/cli/types.py
tests/unit/cli/test_types.py

#6657
When tags are provided as list via `samconfig.toml` and certain tag values contain space, performance could be poor as tag parsing will have to do regex parsing with a complex regex pattern.
- For list input (via `samconfig.toml`), just convert the list to tuple so each tag is handled separately
No

fix: improve tag parsing performance for list input

---

Make.ps1
Makefile
pyproject.toml

N/A
Running `make lint` is giving following warning message;
```
warning: `ruff <path>` is deprecated. Use `ruff check <path>` instead.
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
- 'pylint' -> 'lint.pylint'
- 'per-file-ignores' -> 'lint.per-file-ignores'
```
Updates ruff command and its configuration accordingly
N/A

chore: update ruff params according to warning message

---

samcli/lib/utils/resource_trigger.py
tests/unit/lib/utils/test_resource_trigger.py

#7058
When watching the `template.yaml` file, file opened event gets triggered indefinitely for some cases on Linux systems, which causes high CPU usage.
We already skipping file opened event for some other file watchers for the `sam sync`, this PR also applies same fix to the template listener as well.
Since file opened event is already skipped in other places, this shouldn't have any side affects for this usage as well. 

fix: skip file opened event for template watcher

---

tests/integration/deploy/deploy_integ_base.py
tests/integration/package/package_integ_base.py

None.
For some of our integration tests, it looks we overwrite the testing data path with a new testing path. This won't work if the test failed and reran, since it'll replace the old temp folder, with a new empty temp folder, and attempt to copy the contents of the old temp folder into the new one.
The proper behaviour should be to create a new temp folder, and to copy the originally determined test data folder into this new temp folder.
Save the path of the original test data folder in it's own class variable.
None

fix(tests): Keep original test data path in its own variable to avoid overwriting

---

samcli/lib/providers/provider.py
samcli/lib/providers/sam_function_provider.py
samcli/lib/utils/path_utils.py
tests/unit/lib/utils/test_path_utils.py

[Issue](https://github.com/aws/aws-sam-cli/issues/7117)
This issues occurred when this [PR](https://github.com/aws/aws-sam-cli/pull/6930/files) got merged, it treated `imageUri` as constantly a string when in the case when the intrinsic resolver fails from some case, leaves it as not a string, resulting in a panic. 
This is a regressions because before in the event of the intrinsic resolver failing it does not crash as we had no code depending on the actual types of the resources like this
We check if the type is correct for imageUri and if it isn't we skip the code that would cause it to panic
- [ x] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [ x] Write/update unit tests …

Fix: ignore imageuri if not a path

---

samcli/cli/types.py
schema/samcli.json

https://github.com/aws/aws-sam-cli/issues/6851
The tags option can either be a string or list but the SAM CLI schema specifies the type as List right now.
Makes the type either a string or list for tags
- [x ] `make pr` passes

fix: Update the json schema type for tags option for deploy and sync commands

---

samcli/local/docker/utils.py
tests/unit/local/docker/test_manager.py

https://github.com/aws/aws-sam-cli/issues/6885
Exit gracefully when docker 
Catches the readtimeout error and exits gracefully
No side effect
- [x ] Write/update unit tests
- [ x] `make pr` passes

fix: Catch readtimeout error when docker is not reachable

---

tests/integration/local/invoke/invoke_integ_base.py
tests/integration/local/invoke/test_integration_cli_images.py
tests/integration/local/invoke/test_integrations_cli.py

None
A recent change made to the local command behaviour causes some of the integration tests to fail. This is due to the local integration tests never expecting there to be an actual valid account ID, however this is no longer the case.
Checks if the account ID looks and smells like an account ID, instead of checking for an exact value.

fix(tests): Fix local test failing for account ID checks

---

samcli/lib/iac/cdk/utils.py
tests/unit/lib/iac/cdk/test_cdk_utils.py

#6756 
To prevent unlikely error from `os.listdir(os.getcwd())` to break telemetry
In `_relevant_cdk_files_are_present`, catch the `FileNotFoundError` and return `False`
No

fix: catch error in _relevant_cdk_files_are_present

---

tests/integration/sync/test_sync_watch.py

`sam sync` Integration Test often timed-out at the `RestApi` validation step
Bump the timeout for `RestApi` validation from 20s to 40s
Test run might take longer

fix: bump timeout for waiting for restapi sync in sam sync integ test

---

.github/workflows/validate_pyinstaller.yml
installer/pyinstaller/Instruction.md

Since GitHub updated the internals of their actions to use Node.js 20, the Linux pyinstaller test started failing since the version of glibc used in the manylinux image is outdated. We will build the pyinstaller artifact in a nested container instead of directly on the runner.

chore: Bump checkout version

---

samcli/lib/sync/watch_manager.py
tests/unit/lib/sync/test_watch_manager.py

#6873 
If a Layer is set with a S3 Location, `sam sync` throws an error and stack trace when trying to add a code trigger for that layer. (Same for Lambda Function as well). This is due to the Layer/Function with a S3 Location is considered as `ResourceNotFound` from the `create_trigger`'s perspective.
In the caller (`_add_code_triggers` of `WatchManager`), catch `ResourceNotFound` and issue a warning.
example:
```
2024-07-12 09:09:07,876 | The resource AWS::Serverless::LayerVersion 'MyLayer' has specified S3 location for ContentUri. It will not be built and SAM CLI does not support invoking it locally.                                                                                                                                                  
2024-07-12 09:09:07,877 | CodeTrigger not …
```

fix: catch ResourceNotFound error when adding code trigger in sam sync

---

samcli/lib/utils/definition_validator.py
samcli/lib/utils/resource_trigger.py
tests/unit/lib/utils/test_definition_validator.py

N/A
For definition files (e.g. APIGW, SFN), a validation step is done for each FS event caught by watchdog. The validation step compares the file changes and determines if it's a valid change to sync. However, the validation step checks the file as of current but not the time when the event happened. As a result, we saw "changes" occurred and validated for a "File Opened Event", which is then ignored, and thus did not result in any sync. 
Explicitly skip File Opened Event in the validation step.
Definition files are not validated for a File Opened Event. However, this should be fine since we do not create sync flow from File Opened Event anyway.
By submitting this pull request, I confirm that my contribution is made under the terms …

Fix: sam sync defintion validator handling file opened event

---

tests/integration/testdata/sync/infra/after/Ruby/function/app.rb
tests/integration/testdata/sync/infra/before/Ruby/function/app.rb

N/A
Dependency used in `sam sync` tests for ruby runtime got updated with backward incompatible changes.
Update ruby code to align changes from the library upgrade
N/A

fix: sam sync ruby tests

---

samcli/lib/build/app_builder.py
tests/unit/lib/build_module/test_app_builder.py

#7270 
Intrinsics do not resolve properly at this stage, and we added a workaround before but missed it in this case.
https://github.com/aws/aws-sam-cli/pull/7131

fix: handle imageuri not being string

---

tests/integration/validate/test_validate_command.py

Use OS-specific line endings to fix integration test on Windows.

fix: Integration test using OS line endings

---

samcli/lib/utils/osutils.py
tests/unit/lib/utils/test_osutils.py

https://github.com/aws/aws-sam-cli/issues/6943
Note: Adding an integration test seemed like an overkill for a small change. I've added unit tests to cover these, but lmk if you feel adding one is necessary.
When the shared (within same code_uri) node_module dependencies were copied over to the other Function, the symlink files were not being copied over. However, as mentioned in the [docs](https://docs.python.org/3/library/shutil.html#shutil.copy2), copy2 does not copy symlinks on all the platforms (Windows being 1 of them). This causes OsError to be thrown crashing the command.
Catches the exception and handles it by calling `create_symlink_or_copy` function to either create a symlink or copy the target file directly.
No side effects.
**PRs will only be reviewed after checklist is …

fix: Fix copying symlink files for Windows

---

installer/pyinstaller/build-linux.sh
installer/pyinstaller/build-mac.sh

OpenSSL 1.0 is EOL and we need to upgrade to use OpenSSL 3.

chore: Upgrade to OpenSSL 3 for SAM CLI Installer

---

samcli/lib/providers/exceptions.py
samcli/lib/providers/sam_function_provider.py
samcli/local/apigw/exceptions.py
samcli/local/apigw/local_apigw_service.py
tests/unit/commands/local/lib/test_sam_function_provider.py
tests/unit/local/apigw/test_local_apigw_service.py

https://github.com/aws/aws-sam-cli/issues/7236
Avoid SAM CLI hard-crashing when it is unable to invoke a Lambda function due to an invalid function name.
Uses a custom-exception and handle it during function invocation.
N/A

fix: Avoid crashing on invalid function name

---

appveyor-linux-binary.yml
appveyor-ubuntu.yml
appveyor-windows-binary.yml
appveyor-windows.yml

chore: add back some --reruns to avoid flaky canary tests

---

tests/integration/pipeline/test_bootstrap_command.py

Error message changed from boto3 and we need to adapt the integ tests accordingly.

fix: Fix a canary failure due to an updated error messages from boto lib

---

samcli/local/layers/layer_downloader.py
tests/integration/local/start_api/test_start_api.py
tests/integration/testdata/start_api/template-warm-containers-multi-layers.yaml
tests/unit/local/layers/test_download_layers.py

Customer reports that when the SAM template contains multiple functions, some shared the same lambda layer, `local start-api` throw the exception
```
2024-08-27 09:43:43,083 | Lambda functions containers initialization failed because of [Errno 2] No such file or directory: '/Users/aguro/.aws-sam/layers-pkg/NFTUserLayer-3-ff9c237555.zip'
```
This is because there was a race condition when multiple layer_downloaders were running to build multiple functions concurrently. Some could finish downloading the file first and remove the .zip file, causing the other one failed to unzip.
The fix is to ask each downloader to download into separate zip file (by adding the thread id to the file name), but the extracted folder remains the same.
By …

fix: Race conditions with multiple downloads on the same layer

---

installer/pyinstaller/build-linux.sh
installer/pyinstaller/build-mac.sh

Because of CVE from https://www.cve.org/CVERecord?id=CVE-2024-45490, we need to bump python versions of pyinstaller to latest version

chore: bump python pysintaller versions

---

installer/pyinstaller/build-linux.sh
installer/pyinstaller/build-mac.sh

https://github.com/aws/aws-sam-cli/issues/7253
There is a new version of OpenSSL to consume.
Bumps the versions we have listed for our Mac and Linux artifacts.
None.

chore: Bump OpenSSL to 3.0.15

---

samcli/commands/exceptions.py
samcli/commands/init/interactive_init_flow.py
tests/unit/commands/init/test_cli.py

None
The current "most popular" runtime is hard coded to Python 3.9.
Dynamically checks the (Python) runtimes we support, and returns the latest one.
```
Choose an AWS Quick Start application template
1 - Hello World Example
2 - Data processing
.
.
<truncated>
.
.
Template: 1
Use the most popular runtime and package type? (python3.12 and zip) [y/N]: y
Would you like to enable X-Ray tracing on the function(s) in your application?  [y/N]: 
Would you like to enable monitoring using CloudWatch Application Insights?
For more info, please view https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch-application-insights.html [y/N]: 
Would you like to set Structured Logging in JSON format on your Lambda functions?  [y/N]: 
Project name [sam-app]: sam2
----------------------- …
```

feat: Dynamically determine latest init runtime

---

tests/integration/validate/test_validate_command.py

N/A
`python3.8` is going to be deprecated soon, for that reason `sam validate` tests are failing.
By removing `python3.8` runtime from validate tests.
N/A

chore: remove python3.8 from validate tests

---

tests/integration/validate/test_validate_command.py

Removing `go1.x` and `provided` from list of runtimes we test for `sam validate`

chore: remove go1.x & provided from validate tests

---

requirements/base.txt
requirements/reproducible-linux.txt
requirements/reproducible-mac.txt
requirements/reproducible-win.txt
tests/integration/validate/test_validate_command.py

https://github.com/aws/aws-sam-cli/issues/7673

chore: bump cfn-lint to 1.19.0 to fix sam validate for python3.13

---

DEVELOPMENT_GUIDE.md

The existing development guide states that aws-sam-cli supports Python 3.7+. However, support for python 3.7 appears to have been [removed about a year ago](https://github.com/aws/aws-sam-cli/pull/6119), and `make init` does not work with version <3.8.0.
This PR updates the development guide to indicate that the minimum supported version of Python is 3.8.

Update the development guide with the correct minimum Python version

---

appveyor-windows-al2023.yml

`Python3.13` and `nodejs22` are installed in the AppVeyor image for Al2023 Windows based project.
Don't need to install python3.13 from the embedded zip file
```
python --version
Python 3.12.3
set PATH=C:\Python313-x64;%PYTHON_HOME%;C:\Ruby33-x64\bin;C:\Ruby32-x64\bin;%PATH%;C:\Python39-x64;C:\Python310-x64;C:\Python311-x64;C:\Python312-x64;C:\Python313-x64;C:\Python313-x64\Scripts;
python --version
Python 3.13.0
pip --version
pip 24.3.1 from C:\Python312\Lib\site-packages\pip (python 3.12)
node --version
v22.6.0
```
no side effects

chore: Remove py313 install steps from the Windows Al2023 based AppVeyor project

---

samcli/cli/types.py
tests/unit/cli/test_types.py

#6657 
- Previous fix (https://github.com/aws/aws-sam-cli/pull/7049) only handle the case when `tags` are provided through `samconfig.toml`, which resulted into a list to `CfnTags`, but it doesn't fix the case when customer specify `--tags` parameter. In the later case, the provided value will be in a string, and we will face the issue with `re.findall` again, mainly due to the complex regex provided to parse `{tag}={tag}` pattern in `tags`.
- The solution is instead of parsing a full complex regex with `{tag}={tag}`, we will look for any quote strings with space in the value (e.g. "Test App"), replace the space with some replacement, and restart the parsing process.
Run `sam deploy` with `--tags tag1="value 1" tag2="value 2"` 
Customer might not be able to set tags properly during `sam …

fix: Another approach to parse tag string with spaces to avoid long running time  on regex matching.

---

samcli/commands/_utils/options.py
tests/unit/commands/samconfig/test_samconfig.py

`use-container` currently doesn't have an opposite option called `no-use-container`, user wants to use the IDE toolkit which depends on samcli to set default behaviors but still wants the flexibility of using the opposite option to carry out different operation.
Add support for `no-use-container` allow the cli to pass `use-container` = false in the samConfig file 
`no-use-container` can result to` use_container = false` in samConfig
`sam sync` 
```
Container Options:                        
-u, --use-container / --no-use-container
Build functions within an AWS Lambda-like container.
``` …

Add support for --no-use-container option 

---

.github/workflows/build.yml
tests/integration/buildcmd/test_build_cmd.py
tests/integration/buildcmd/test_build_cmd_arm64.py
tests/integration/buildcmd/test_build_cmd_python.py
tests/integration/buildcmd/test_build_samconfig.py

fix(git_action): remove python3.7 & 3.8

---

samcli/local/docker/lambda_image.py

ruby 3.3 is officially supported
#7839
The latest public.ecr.aws/lambda/ruby:3.3 is upgraded to 3.3.5 but sam local invoke still uses public.ecr.aws/lambda/ruby:3.3-preview and the version is 3.3.0 this version has some bug cause sam local invoke cannot work correctly.

chore(runtime): move ruby3.3 out of test runtime

---

samcli/lib/build/app_builder.py
samcli/local/docker/container.py
samcli/local/docker/manager.py
samcli/local/lambdafn/runtime.py
tests/unit/lib/build_module/test_app_builder.py
tests/unit/local/docker/test_container.py
tests/unit/local/docker/test_manager.py
tests/unit/local/lambdafn/test_runtime.py

SAM CLI shouldn't be mounting symlinks by default when building in a container
Symbolic links are used in SAM CLI to achieve faster build times with `build-in-source`. The build process creates symlinks for dependencies, that then can be used when running `sam local invoke`. These symlinks don't need to be mounted during `sam build`.
We add a new context property for the container to make a different decision depending on the context.
If SAM CLI users were relying on this behavior during builds, their workflow might get broken. Please create an issue if you're affected by this change, and we'll prioritize to add a new property to allow mounting symlinks in any case.
By submitting this pull request, I confirm that my contribution is …

fix: Resolve symlinks on local invoke only

---

tests/integration/testdata/delete/companion-ecr/hello_world/Dockerfile

It was a missing place when we removed python3.8 tests. This test was using python3.8 image still, but trying to use python3.9 executable. 

test: Change python3.8 image to python3.9

---

tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_local_backend/expected.template.yaml

Remove double "python3.9"
Integration tests with Terraform were failing with an error when removing python3.8

test: Fix Terraform tests

---

appveyor-ubuntu.yml
appveyor-windows-al2023.yml
appveyor-windows.yml

Previous jump from Python3.8 to 3.11 might have caused some issues, so we're returning only to Python3.9
Previous change in #7857

test: Set Python3.9 for AppVeyor tests

---

tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_local_backend_container_windows/expected.template.yaml
tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_local_backend_windows/expected.template.yaml
tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_s3_backend/expected.template.yaml
tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_s3_backend_container_windows/expected.template.yaml
tests/integration/testdata/buildcmd/terraform/zip_based_lambda_functions_s3_backend_windows/expected.template.yaml
tests/integration/testdata/sync/infra/cdk/cdk_v1_synthesized_template_level3_nested_zip_functions.json
tests/integration/testdata/sync/infra/cdk/cdk_v1_synthesized_template_level3_nested_zip_functions_after.json
tests/integration/testdata/sync/infra/cdk/cdk_v1_synthesized_template_zip_functions.json
tests/integration/testdata/sync/infra/cdk/cdk_v1_synthesized_template_zip_functions_after.json

Misses during the removal of python3.8. This makes some tests fail.

test: remove double runtime in compatible layers

---

tests/integration/testdata/buildcmd/terraform/build_image_docker/Dockerfile

Terraform Docker container was trying to use python3.9 on AL2, which doesn't exist. Migrate to AL2023, which already has python3.9 installed (so we don't even need to install it)

test: Fix Terraform Docker container

---

tests/integration/local/start_api/lambda_authorizers/test_cfn_authorizer_definitions.py
tests/integration/local/start_api/lambda_authorizers/test_sfn_props_lambda_authorizers.py
tests/integration/local/start_api/lambda_authorizers/test_swagger_authorizer_definitions.py

The start-api tests take longer on Windows, so we increase the timeout so they don't fail.
Failure on integration tests. 
Tests were failing just because of a timeout and not because of real problems in the tests. This were all "invalid template" tests, that had a very small timeout, but it depends on the machine where these tests are run.
Increasing the timeout
If the test were to get stuck forever, it will take longer for the overall test infrastructure to stop this particular test.

test: Increase start-api tests timeouts

---

tests/integration/validate/test_validate_command.py

`cfn-lint` changed their message when a Lambda runtime is deprecated [1]
From `Check if EOL Lambda Function Runtimes are used`
To `Validate if lambda runtime is deprecated`
And also using nodejs16.x changed from a warning (W2531) to an error (E2531)
Also, removed some extra escape characters that were not required.
[1]: https://github.com/aws-cloudformation/cfn-lint/commit/31783cadb0b1faaa7d8ec4dc1389dfe5fc2f4fd7#diff-3e96ba21727bba3d7bfb0c5c235a0cbc45eca97819429104d7ff9fbec8aa05b2

test: fix error message in 'validate'

---

requirements/base.txt
requirements/reproducible-linux.txt
requirements/reproducible-mac.txt
requirements/reproducible-win.txt

- This new version of `cfn-lint` recognizes Ruby 3.4 as a valid runtime
(This replaces #7951 . The `update-reproducible-requirements` action seems to be failing when updating dependencies from a branch from an external fork)

chore: update cfn-lint to 1.32.0

---

tests/integration/validate/test_validate_command.py

`cfn-lint` changed their message (again) when a Lambda runtime is deprecated.
From `Validate if lambda runtime is deprecated`
Back to `Check if EOL Lambda Function Runtimes are used`
This PR reverts https://github.com/aws/aws-sam-cli/pull/7920
This 

test: fix validate error message

---

samcli/commands/_utils/experimental.py
samcli/lib/package/artifact_exporter.py
samcli/lib/package/packageable_resources.py
samcli/lib/package/utils.py
tests/unit/commands/_utils/test_experimental.py
tests/unit/lib/package/test_artifact_exporter.py

#4053
`sam package` (and `deploy`) can take an extremely long time.
This happens because the command zips every lambda resource in a template, even if all the lambdas point to the same local path. For instance, with NodeJS lambdas, there are many files involved due to the nature of npm/node, and that puts a serious dent on the disk (especially so in CI environments where SSD is not guarenteed).
Normally, `sam build` will create a separate directory for each lambda resource in the template. However, there is an experimental flag -- `SAM_CLI_BETA_BUILD_PERFORMANCE` -- which creates only one shared directory for all the lambdas. This boosts `sam build` performance tremendously, and it works because in most cases, all lambdas in a project share the same code (just a different handler …

Experimental flag to boost 'package' command performance

---

tests/end_to_end/test_runtimes_e2e.py

Make failure with following error when using python 3.12+
```
tests/end_to_end/test_runtimes_e2e.py:1: error: Cannot find implementation or library stub for module named "distutils.dir_util"  [import-not-found]
tests/end_to_end/test_runtimes_e2e.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```
Make pr failure.
The distutils module was deprecated in Python 3.10 and removed in Python 3.12. Therefore, distutils.dir_util is no longer available in Python 3.12 or later versions.
The recommended replacement for distutils.dir_util is the shutil module, which provides similar functionality and is still actively maintained in Python.
The error was in the `tests/end_to_end/test_runtimes_e2e.py` file. The `mypy` type checker was failing because it couldn't …

fix: make pr failure for python 3.12+

---

samcli/commands/deploy/command.py
samcli/commands/deploy/guided_context.py
samcli/commands/package/command.py
samcli/lib/bootstrap/bootstrap.py
samcli/lib/package/s3_uploader.py

* Set the right indentation across `package`, `deploy`, `package/deploy --resolve-s3` & `deploy --guided`
* Set the right indentation on `Skipping upload` to S3.
No explicit issue against this.
The indentation was not aligned.
BEFORE:
AFTER:
* More consistent UX and pleasing to the eye.
* Should be none, these are UX changes.

refactor: remove duplicate code and fix indentation

---

samcli/lib/utils/async_utils.py

Not sure if there was an issue for this.
Something I noticed while running the tests.
The event loops closed and I don't see the warning anymore on running the unit tests.
There should'nt be any.

fix: close event loops for async tasks

---

Makefile

Reproducible workflow failing since pip auto upgraded to 25.1, forcing it to use 24.0 until pip tools supported pip 25.1

chore(workflow): fix pip, pip-tools version

---

.github/dependabot.yml

`aws/serverless-application-experience-sbt` are still being added as reviewers to dependabot PRs.

chore: remove SBT from dependabot reviewers

---

appveyor-linux-binary.yml
appveyor-ubuntu.yml
appveyor-windows-al2023.yml
appveyor-windows-binary.yml
appveyor-windows.yml

Modify the end of the canary to call Lambda function instead of sending a task action directly to Step Functions
Also update Maven to 3.9.11 (Maven 3.9.10 is not available in that location anymore)
Updated some indentation in some Windows files.
- As part of a canary infrastructure update, the new credentials used to run the canary can no longer make a call to StepFunctions directly, so we added a new Lambda function to wrap the account reset action. This Lambda function calls Step Functions internally so the outcome is the same.
- Changing a direct Step Functions call with a Lambda function call.
- The output of the function is put into a file, and then we print that file (that's how Lambda gives you the result of a function call) …

test(canary): Call Lambda function to reset test account instead of making StepFunctions api call

---

samcli/lib/build/app_builder.py
tests/integration/buildcmd/test_build_cmd_python.py
tests/integration/testdata/buildcmd/PythonParentPackages/src/fnone/main.py
tests/integration/testdata/buildcmd/PythonParentPackages/src/fnone/requirements.txt
tests/integration/testdata/buildcmd/PythonParentPackages/src/fntwo/main.py
tests/integration/testdata/buildcmd/PythonParentPackages/src/fntwo/requirements.txt
tests/integration/testdata/buildcmd/template_with_metadata_python.yaml
tests/unit/lib/build_module/test_app_builder.py

I added [documentation](https://github.com/aws/aws-lambda-builders/blob/43953af0a862ae2c98dd4d5895c504c1f1a5ecf4/aws_lambda_builders/workflows/python_pip/DESIGN.md#parent_python_packages) to aws-lambda-builders for its API. I was unable to find the existing BuildProperties documentation to update.
#6593
Python allows ambiguous relative imports so importing `uuid` is usually from the standard library but could also be a file `uuid.py` adjacent to the handler module. [PEP 8](https://peps.python.org/pep-0008/#imports) advises absolute imports or explicit relative imports, and the [Google Python Style Guide](https://google.github.io/styleguide/pyguide.html#23-packages) provides examples of the pitfalls.
This change integrates with a [change](https://github.com/aws/aws-lambda-builders/pull/765) …

feat: add python option for creating parent packages during copy

---

samcli/cli/hidden_imports.py

I'm seeing unit tests fail locally when running `make pr`:
```
samcli.cli.import_module_proxy.MissingDynamicImportError: Dynamic import not allowed for name: jaraco.text package: None
```
I looked into the issue and it's due to a hidden import that gets brought in by recent versions of `setuptools` for `jaraco.text`. This is only happening on the test when running `pkg_resources.py2_warn` - which gets included in the test parameterization since it was added to this list of hidden imports to test.
I looked into it further and found that PyInstaller removed support for pkg_resources.py2_warn in version 5.3 (July 2022) in [issue #6952](https://github.com/pyinstaller/pyinstaller/issues/6952). We depend on PyInstaller 6.15.0, so this dependency isn't being brought in transitively anymore …

fix: remove unnecessary hidden import for pkg_resources
